### PR TITLE
Fix migration validation issue

### LINKED ISSUE #6151: Upgrade fails from 0.28.1-alpha to 0.29.18.alpha
## Environment
- **Airbyte version**: 0.28.1-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: High
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
After following the upgrade steps described at https://docs.airbyte.io/operator-guides/upgrading-airbyte (`docker-compose down`, then `git pull`, then `docker-compose up`), attempting to load the Airbyte dashboard just shows a blank page.  In the Dev Tools console, we see the error message:

```
Error: Version mismatch between 0.29.18-alpha and 0.28.1-alpha.
Please upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/operator-guides/upgrading-airbyte
```

## Expected Behavior
After version 0.27.0 was released, Airbyte migrated its internal configuration automatically when upgrading.  It usually runs the migration automatically and then starts up without incident.

## Logs
Based on the logs, it looks like it did actually try to run a migration, but failed due to a JSON validation problem.
```
2021-09-16 18:45:26 ERROR i.a.s.ServerApp(runAutomaticMigration):284 - {workspace_app_root=/tmp/workspace/server/logs} - Automatic Migration failed 
java.lang.IllegalArgumentException: Input data schema does not match declared input schema ATTEMPTS.
	at io.airbyte.migrate.Migrate.lambda$runMigration$1(Migrate.java:140) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at io.airbyte.migrate.migrations.MigrationV0_29_0.migrate(MigrationV0_29_0.java:110) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at io.airbyte.migrate.MigrateWithMetadata.migrate(MigrateWithMetadata.java:52) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at io.airbyte.migrate.Migrate.runMigration(Migrate.java:150) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at io.airbyte.migrate.Migrate.run(Migrate.java:113) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:76) ~[io.airbyte-airbyte-migration-0.29.18-alpha.jar:?]
	at io.airbyte.server.RunMigration.run(RunMigration.java:79) ~[io.airbyte-airbyte-server-0.29.18-alpha.jar:?]
	at io.airbyte.server.ServerApp.runAutomaticMigration(ServerApp.java:282) [io.airbyte-airbyte-server-0.29.18-alpha.jar:?]
	at io.airbyte.server.ServerApp.getServer(ServerApp.java:234) [io.airbyte-airbyte-server-0.29.18-alpha.jar:?]
	at io.airbyte.server.ServerApp.main(ServerApp.java:263) [io.airbyte-airbyte-server-0.29.18-alpha.jar:?]
Caused by: io.airbyte.validation.json.JsonValidationException: json schema validation failed. 
errors: $.temporal_workflow_id: is not defined in the schema and the schema does not allow additional properties 
schema: 
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "title" : "Attempts",
  "description" : "representation of a attempts record as created in schema.sql",
  "type" : "object",
  "required" : [ "id", "job_id", "attempt_number", "log_path", "status", "created_at", "updated_at" ],
  "additionalProperties" : false,
  "properties" : {
    "id" : {
      "type" : "number"
    },
    "job_id" : {
      "type" : "number"
    },
    "attempt_number" : {
      "type" : "number"
    },
    "log_path" : {
      "type" : "string"
    },
    "output" : {
      "type" : [ "null", "object" ]
    },
    "status" : {
      "type" : "string"
    },
    "created_at" : {
      "type" : "string",
      "description" : "Integration specific blob. Must be a valid JSON string."
    },
    "updated_at" : {
      "type" : "string"
    },
    "ended_at" : {
      "type" : [ "null", "string" ]
    }
  }
} 
object: 
{
  "id" : 1,
  "job_id" : 1,
  "attempt_number" : 0,
  "log_path" : "/tmp/workspace/1/0/logs.log",
  "output" : null,
  "status" : "running",
  "created_at" : "2021-07-27T17:31:55.394428Z",
  "updated_at" : "2021-07-27T17:31:55.394428Z",
  "ended_at" : null,
  "temporal_workflow_id" : null
}
```

## Steps to Reproduce
```
docker-compose down
git pull
docker-compose up
```

### PR DESCRIPTION
**Pull request by tuliren**
- The `temporal_workflow_id` added in the Flyway migration (#5850) is not visible to the file-based migration system. So the migration will fail whenever a user tries to upgrades the server from an old version.
- This is a temporary fix to mark the `Attempts` schema forward compatible so that the migration can run.
- We are actually working on deprecating the file-based migration system. Once it is done, we can revert this change.

### CODE REVIEW

File: airbyte-db/lib/src/main/java/io/airbyte/db/instance/jobs/migrations/V0_29_15_001__Add_temporalWorkflowId_col_to_Attempts.java [hunk 1]
```diff
@@ -38,7 +38,8 @@ public void migrate(Context context) throws Exception {
     // As database schema changes, the generated jOOQ code can be deprecated. So
     // old migration may not compile if there is any generated code.
     DSLContext ctx = DSL.using(context.getConnection());
-    ctx.alterTable("attempts").addColumn(DSL.field("temporal_workflow_id", SQLDataType.VARCHAR(256).nullable(true)))
+    ctx.alterTable("attempts")
+        .addColumnIfNotExists(DSL.field("temporal_workflow_id", SQLDataType.VARCHAR(256).nullable(true)))
```
Comment (tuliren) [inline airbyte-db/lib/src/main/java/io/airbyte/db/instance/jobs/migrations/V0_29_15_001__Add_temporalWorkflowId_col_to_Attempts.java:42]: This is not necessary. But I feel that we should be extra cautious. This change makes the migration idempotent. Even if the user's database is in a weird state (e.g. this column is manually added), it will work.

File: airbyte-db/lib/src/main/resources/jobs_database/Attempts.yaml [hunk 2]
```diff
@@ -11,7 +11,7 @@ required:
   - status
   - created_at
   - updated_at
-additionalProperties: false
+additionalProperties: true
```
Comment (tuliren) [inline airbyte-db/lib/src/main/resources/jobs_database/Attempts.yaml:14]: Make the attempts schema forward compatible before the file-based migration system is removed.

File: airbyte-db/lib/src/main/resources/jobs_database/Attempts.yaml [hunk 3]
```diff
@@ -25,8 +25,6 @@ properties:
     type: ["null", object]
   status:
     type: string
-  temporal_workflow_id:
-    type: ["null", string]
```
Comment (tuliren) [inline airbyte-db/lib/src/main/resources/jobs_database/Attempts.yaml:29]: This schema is used for validation in the file-based migration system, which does not know the existence of this property.
