### PR TITLE
🪟 🐛 Fix trailing whitespace and ending with a forward slash transformation GitHub URL issue

### LINKED ISSUE #16638: Transformation View should clean up github repo URLs
It looks like trailing whitespace and ending with a forward slash will both make airbyte fail to find a transformation repo.

We should either validate or clean for this.

### PR DESCRIPTION
**Pull request by dizel852**
## What
Closes https://github.com/airbytehq/airbyte/issues/16638

## How
Add regex matcher for entered GitHub URL:
- no trailing space
- no  forward slash at the end

https://www.loom.com/share/98d55365c1994c7885d2eb320f05859f

### CODE REVIEW

File: airbyte-webapp/src/views/Connection/TransformationForm/TransformationForm.tsx [hunk 1]
```diff
@@ -32,7 +32,10 @@ const validationSchema = yup.object({
   name: yup.string().required("form.empty.error"),
   operatorConfiguration: yup.object({
     dbt: yup.object({
-      gitRepoUrl: yup.string().required("form.empty.error"),
+      gitRepoUrl: yup
+        .string()
+        .required("form.empty.error")
+        .matches(/((http(s)?)|(git@[\w.]+))(:(\/\/)?)([\w.@:/\-~]+)(\.git)$/, "form.repositoryUrl.invalidUrl"),
```
Comment (josephkmh) [inline airbyte-webapp/src/views/Connection/TransformationForm/TransformationForm.tsx:38]: Regex looks good to me, but IMO would be a good place for a unit test. Since the backend apparently fails without this, it would be good to defend against a regression. Maybe `validationSchema` could be exported and tested explicitly with `validationSchema.validate( ... )`?

**Review by joeykmh — CHANGES_REQUESTED** [review]

File: airbyte-webapp/src/views/Connection/TransformationForm/TransformationForm.tsx (hunk 1 above)
Comment (dizel852) [reply airbyte-webapp/src/views/Connection/TransformationForm/TransformationForm.tsx:38]: Yeah, sounds reasonable. 
Will add tests for `validationSchema`

**Review by joeykmh — APPROVED** [review]
Looks great, thanks for adding tests! 🔥
