### PR TITLE
fix issue with oneOf with sub schemas with same key but different type

### LINKED ISSUE #5907: Saving changes not working when changing destination output format-format type from Avro to Parquet
## Enviroment
- **Airbyte version**:  0.29.13-alpha
- **OS Version / Instance**:  Ubuntu 21.04 VM 
- **Deployment**: Kubernetes 
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3)  S3
- **Severity**: Low 
- **Step where error happened**:  Update connector

## Current Behavior
*Tell us what happens.*
When changing S3 destination output format/format type from Avro to parquet, saving doesn't actually do anything, format type still remains Avro and instead of connection being tested, you're automatically taken to the destinations view, but when you change from Avro to e.g. CSV the change is applied correctly.
## Expected Behavior
*Tell us what should happen.*
When changing S3 destination output format/format type from Avro to parquet, clicking "Save changes and test" button should result in connection being tested and change applied.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Create a new Destination and use S3 as the Destination type, fill out all the remaining fields including choosing Avro as the output format as well as the format type and click Set up destination when done.
2. Check that the destination you just created has Avro as its output format, change this to Parquet and change format type to Parquet too,  set compression codec to GZIP and leave everything else as it is.
3. Click "Save changes and test button" and check if this destination now has Parquet as its output format

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by cgardens**
closes https://github.com/airbytehq/airbyte/issues/5907

the issue is described in-line and in the new test case.

@lmossman and I debugged this one together. brutal.

### CODE REVIEW

**Review by lmossman — APPROVED** [review]
LGTM (paired with Charles on this)

File: airbyte-config/persistence/src/test/java/io/airbyte/config/persistence/split_secrets/JsonSecretsProcessorTest.java [hunk 1]
```diff
@@ -62,6 +62,97 @@
           + "    }\n"
           + "  }");
 
+  private static final JsonNode ONE_OF_WITH_SAME_KEY_IN_SUB_SCHEMAS = Jsons.deserialize(
```
Comment (jrhizor) [inline airbyte-config/persistence/src/test/java/io/airbyte/config/persistence/split_secrets/JsonSecretsProcessorTest.java:65]:
```suggestion
  private static final JsonNode ONE_OF_WITH_SAME_KEY_IN_SUB_SCHEMAS = Jsons.deserialize(
```

Generally we prefer to stick json files like this for testing in a resource so it's easier to read and edit compared to the escaped Java string.

**Review by jrhizor — APPROVED** [review]

**Comment by jrhizor** [comment]
It would also be pretty useful to add a test case for this in `SecretsHelpersTest` to make sure that the non-oauth secrets parsing won't break on it as well.
