### PR TITLE
🐛 Source CockroachDB: fix connector replication failure due to multiple open portals error

### LINKED ISSUE #7933: CockroachdB error with https://go.crdb.dev/issue-v/40195/v21.1
## Enviroment
- **Airbyte version**:  0.30.36-alpha
- **OS Version / Instance**: Ubuntu on EC2
- **Deployment**: Docker
- **Source Connector and version**: Cockroachdb 0.1.3 (connected to Cockroachdb v21.1.10)
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

It throws an error

## Expected Behavior
It doesn't throw an error

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:55)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:48)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:18)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:119)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachDbSource.main(CockroachDbSource.java:87)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:509)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSetMetaData.getPGType(PgResultSetMetaData.java:407)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSetMetaData.getColumnTypeName(PgResultSetMetaData.java:325)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.putCockroachSpecialDataType(CockroachJdbcSourceOperations.java:54)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.rowToJson(CockroachJdbcSourceOperations.java:47)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcSourceOperations$1.tryAdvance(JdbcSourceOperations.java:52)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	... 31 more
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - Caused by: org.postgresql.util.PSQLException: ERROR: unimplemented: multiple active portals not supported
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 -   Hint: You have attempted to use a feature that is not yet implemented.
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - See: https://go.crdb.dev/issue-v/40195/v21.1
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:509)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.initSqlType(PgResultSet.java:2993)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.getSQLType(PgResultSet.java:2982)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:187)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2843)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:733)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.cockroachdb.CockroachJdbcSourceOperations.rowToJson(CockroachJdbcSourceOperations.java:42)
[34msource[0m - 2021-11-12 20:18:04 ERROR () LineGobbler(voidCall):82 - 	... 32 more

```

</details>

## Steps to Reproduce
1. Create a CockroachDB (v21.1.10) source
2. Use incremental | Deduped
3. Failures occur

## Are you willing to submit a PR?

I'm not a huge java person, but I guess I could try.

### PR DESCRIPTION
**Pull request by lshrinivas**
## What
This PR fixes issue: https://github.com/airbytehq/airbyte/issues/7933. CockroachDB does not implement the multiple active portals from PostgreSQL wire protocol, so any time a JDBC client satisfied the following conditions, CockroachDB throws an error:
- Uses a prepared statement.
- Sets the fetchSize of the statement to a positive number.
- After running the statement, the database returns more rows than the fetchSize.
- The client runs some other query before calling close() on the ResultSet.
See https://github.com/cockroachdb/cockroach/issues/40195?version=v21.2#issuecomment-870570351 for detailed analysis of the issue. 
As such, due to the above limitation, the CockroachDB airbyte connector fails to replicate any tables that have > 1000 rows (the fetch size set in the connector). 

## How
In this PR, I created a subclass of `JdbcDatabase` specific to CockroachDB that uses `bufferedResultSetQuery` instead of the default streaming method. By using `bufferedResultSetQuery`, we ensure that all rows are fetched and the result set is closed (which makes the CockroachDB server close the server-side session aka portal). This does mean that the results need to fit in memory, but until CockroachDB implements multiple active portals, I don't know of any other way to get around this limitation.

## Recommended reading order
1. `CockroachDbSource.java`
2. `CockroachJdbcDatabase.java`

## 🚨 User Impact 🚨
The main user impact would be memory usage by the connector - for large tables, the connector container could potentially run out of memory, resulting in sync failure. With the status quo, sync fails anyway for tables with > 1000 rows, so not sure this is a major issue. 

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
thanks @lshrinivas the team will review this contribution early next week.

File: airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSource.java [hunk 1]
```diff
@@ -110,12 +110,29 @@ protected boolean isNotInternalSchema(JsonNode jsonNode, Set<String> internalSch
...
+    return new CockroachJdbcDatabase(database, sourceOperations);
+  }
+  
   private CheckedFunction<Connection, PreparedStatement, SQLException> getPrivileges(JdbcDatabase database) {
     return connection -> {
       final PreparedStatement ps = connection.prepareStatement(
           "SELECT DISTINCT table_catalog, table_schema, table_name, privilege_type\n"
               + "FROM   information_schema.table_privileges\n"
-              + "WHERE  grantee = ? AND privilege_type in ('SELECT', 'ALL')");
+              + "WHERE  (grantee  = ? AND privilege_type in ('SELECT', 'ALL')) OR (table_schema = 'public')");
```
Comment (lshrinivas) [inline airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSource.java:135]: This change is unrelated to the bug, but without this, tables in the `public` schema are not visible in the Airbyte UI (which feels odd, since tables in the `public` schema in CockroachDB are visible to all users regardless of explicit grants). Feel free to undo this if this isn't a change you'd like to incorporate in the connector

**Review by marcosmarxm — APPROVED** [review]
thanks @lshrinivas sorry the long delay to review your contribution
