### PR TITLE
🐛Destination S3 and GCS  - Fixed connector's bug that prevent writing streams with more than 50GB

### LINKED ISSUE #5720: S3 and GCS writes are limited to 50GB
## Enviroment
- **Airbyte version**:  0.29.12-alpha
- **Environent:** Debian 10, GCP
- **Deployment**: Docker
- **Source Connector and version**: mssql 0.3.4
- **Destination Connector and version**: gcs 0.1.0
- **Step where error happened**: Sync job

## Current Behavior
When syncing our MSSQL database to Google Cloud Storage, after reading few million rows, the job stops with an `java.lang.IndexOutOfBoundsException`. 

Note that the job doesn't **fail**, it just stops and never continues.

## Expected Behavior
The syncing just works™

## Logs
```
2021-08-26 19:33:48 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256184000
2021-08-26 19:33:48 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256185000
2021-08-26 19:33:49 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256186000
2021-08-26 19:33:49 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256187000
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'Andr'...
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-08-26 19:33:49 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256188000
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to mimo_airbyte_sync/production/Andr/2021_08_26_1629985551451_0.avro with id ABPnzm7-I...9-fC_bQ0Y]: Aborted
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'AndrPro' aborted.
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'Chap...
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-08-26 19:33:49 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 256189000
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to mimo_airbyte_sync/production/Chap/2021_08_26_1629985551451_0.avro with id ABPnzm6nq...ivdTH52Xc]: Aborted
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'Chap' aborted.
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'AndRec'...
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to mimo_airbyte_sync/production/AndrRec/2021_08_26_1629985551451_0.avro with id ABPnzm5DW...aOZGkIUaE]: Aborted
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):127 - {} - Upload of stream 'AndrRec' aborted.
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [33mWARN[m i.a.i.d.g.w.BaseGcsWriter(close):125 - {} - Failure detected. Aborting upload of stream 'LessPro'...
2021-08-26 19:33:49 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-26 19:33:49 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.checkSize(MultiPartOutputStream.java:110)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at alex.mojaki.s3upload.MultiPartOutputStream.write(MultiPartOutputStream.java:143)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.file.DataFileWriter$BufferedFileOutputStream$PositionFilter.write(DataFileWriter.java:476)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.io.BufferedBinaryEncoder$OutputStreamSink.innerWrite(BufferedBinaryEncoder.java:227)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.io.BufferedBinaryEncoder.writeFixed(BufferedBinaryEncoder.java:157)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.file.DataFileStream$DataBlock.writeBlockTo(DataFileStream.java:394)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.file.DataFileWriter.writeBlock(DataFileWriter.java:408)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.file.DataFileWriter.writeIfBlockFull(DataFileWriter.java:351)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:320)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.avro.GcsAvroWriter.write(GcsAvroWriter.java:90)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsConsumer.acceptTracked(GcsConsumer.java:105)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:136)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	at io.airbyte.integrations.destination.gcs.GcsDestination.main(GcsDestination.java:48)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 	Suppressed: java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at alex.mojaki.s3upload.MultiPartOutputStream.close(MultiPartOutputStream.java:164)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at org.apache.avro.file.DataFileWriter.close(DataFileWriter.java:461)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at io.airbyte.integrations.destination.gcs.avro.GcsAvroWriter.closeWhenFail(GcsAvroWriter.java:102)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at io.airbyte.integrations.destination.gcs.writer.BaseGcsWriter.close(BaseGcsWriter.java:126)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at io.airbyte.integrations.destination.gcs.GcsConsumer.close(GcsConsumer.java:111)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:130)
2021-08-26 19:33:49 ERROR () LineGobbler(voidCall):85 - 		... 2 more
```

## Steps to Reproduce
1. Sync a lot of rows to GCS?

## Are you willing to submit a PR?
Unlikely, except if it's a very obvious fix 😄

### PR DESCRIPTION
**Pull request by etsybaev**
## What
Currently, we can't write to S3 and GCS objects with more than 50GB of each

## How
The reason is that servers allow 10,000 blocks max and currently we have block size hardcoded as 5MB. but servers allow to have it up to 5GB each.
To fix the described issue - added a new arg that allows to configure it. Basically, to reach the max object limit of 5TB - the max block's size of 525 (MB) is enough. The new arg supports size from 5MB (min for server) to 525MB.

https://cloud.google.com/storage/quotas
https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

Tested locally:
Selection_002
Selection_001
Selection_003
Selection_004

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+  @Test
+  public void testParseCodecConfigSnappy() {
+    JsonNode snappyConfig = Jsons.deserialize("{ \"codec\": \"snappy\" }");
+    CodecFactory codecFactory = S3AvroFormatConfig.parseCodecConfig(snappyConfig);
+    assertEquals(DataFileConstants.SNAPPY_CODEC, codecFactory.toString());
+  }
+
+  @Test
+  public void testParseCodecConfigInvalid() {
+    try {
```
Comment (alexandr-shegeda) [inline airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java:115]: it's better to use `Assertions.assertThrows(IllegalArgumentException.class, () -> {....} ` instead of `try-catch` block

File: airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+    S3FormatConfig formatConfig = gcsDestinationConfig.getFormatConfig();
+    assertEquals("AVRO", formatConfig.getFormat().name());
+    assertEquals(6, formatConfig.getPartSize());
+    // Assert that is set properly in config
+    StreamTransferManager streamTransferManager = S3StreamTransferManagerHelper.getDefault(
+        gcsDestinationConfig.getBucketName(), "objectKey", null,
+        gcsDestinationConfig.getFormatConfig().getPartSize());
+
+    Integer partSizeBytes = (Integer) FieldUtils.readField(streamTransferManager, "partSize", true);
+    assertEquals(6291456, partSizeBytes);
```
Comment (alexandr-shegeda) [inline airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java:145]: could you possibly create a constant or local variable that explains this "magic number"?

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java [hunk 3]
```diff
@@ -26,19 +26,61 @@
...
   public static final int DEFAULT_PART_SIZE_MB = 5;
+  // MAX object size for AWS and GCS is 5TB (max allowed 10,000 parts*525mb)
+  // (https://aws.amazon.com/s3/faqs/, https://cloud.google.com/storage/quotas)
+  public static final int MAX_ALLOWED_PART_SIZE_MB = 525;
   public static final int DEFAULT_NUM_STREAMS = 1;
 
-  public static StreamTransferManager getDefault(String bucketName, String objectKey, AmazonS3 s3Client) {
+  public static StreamTransferManager getDefault(String bucketName, String objectKey, AmazonS3 s3Client, Long partSize) {
+    if (partSize == null) {
+      LOGGER.warn(String.format("Part side for StreamTransferManager is not set explicitly. Will use the default one = %sMB. "
```
Comment (alexandr-shegeda) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java:50]: it looks like a mistyped `side` instead of `size`

File: airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java (hunk 1 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java]: updated, thanks

File: airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java (hunk 2 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/test/java/io/airbyte/integrations/destination/gcs/avro/GcsAvroFormatConfigTest.java]: updated, thanks

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java (hunk 3 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java]: updated, thanks

**Comment by alexandr-shegeda** [comment]
LGTM

**Review by alexandr-shegeda — APPROVED** [review]

File: airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json [hunk 4]
```diff
@@ -229,6 +229,13 @@
                     }
                   }
                 ]
+              },
```
Comment (davinchia) [inline airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json:232]: Instead of having this appear multiple times in each format option, what if this was a field at the top level?

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java [hunk 5]
```diff
@@ -26,19 +26,61 @@
...
+  // (https://aws.amazon.com/s3/faqs/, https://cloud.google.com/storage/quotas)
+  public static final int MAX_ALLOWED_PART_SIZE_MB = 525;
   public static final int DEFAULT_NUM_STREAMS = 1;
 
-  public static StreamTransferManager getDefault(String bucketName, String objectKey, AmazonS3 s3Client) {
+  public static StreamTransferManager getDefault(String bucketName, String objectKey, AmazonS3 s3Client, Long partSize) {
+    if (partSize == null) {
+      LOGGER.warn(String.format("Part size for StreamTransferManager is not set explicitly. Will use the default one = %sMB. "
+          + "Please note server allows up to 10,000 parts to be uploaded for a single object, i.e. 50GB for stream. "
+          + "Fell free to increase partSize arg, but make sure you have enough memory resources allocated", DEFAULT_PART_SIZE_MB));
```
Comment (davinchia) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java:52]:
```suggestion
          + "Feel free to increase partSize arg, but make sure you have enough memory resources allocated", DEFAULT_PART_SIZE_MB));
```

**Review by davinchia — APPROVED** [review]
Great stuff! Appreciate the screen shots. Appreciate all the test you added.

Small feedback from me - it would have been easier to review if the PR was split into the base S3 changes, and a follow up PR for GCS changes. 

Please also go through the updating connector checklist in the future so it's easy for me to know what is/what is not done.

Thanks!

File: airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json (hunk 4 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json:232]: Hi @davinchia. The is a Parquet option where this param is not applicable, so I had to add it several times for other applicable options (to avoid users confusion)

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java (hunk 5 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/util/S3StreamTransferManagerHelper.java]: fixed, thanks!

File: airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json (hunk 4 above)
Comment (davinchia) [reply airbyte-integrations/connectors/destination-gcs/src/main/resources/spec.json:232]: I realised that after I typed this. This is fine.

**Comment by etsybaev** [comment]
Released new S3 connector, but can't release GCS due to other blocking bug

**Comment by etsybaev** [comment]
Merging the latest master with a fix didn't help. It seems like we've got new issues in master that prevent merging. So still can't publish GCS and merge this

**Comment by PS-istarostenko** [comment]
@etsybaev can we please get the same fix, but for BigQuery and Snowflake when using GCS and S3 as a staging loading method?
https://github.com/airbytehq/airbyte/issues/5720
