### PR TITLE
Destination mysql: fix tests + upgrade to latest CDK

### LINKED ISSUE #33383: Upgrade destination-mysql to use latest java cdk
* Decide:
  * Verify that it's using the async framework (albeit in a slightly weird way)
  * Move the file-writing logic to use the async framework in the intended way

### LINKED ISSUE #33465: Fix destination-mysql tests
we've been failing for a Long Time https://connectors.airbyte.com/files/generated_reports/test_summary/destination-mysql/index.html

get back to green so we can make DV2-related changes with confidence. Or start nuking tests from orbit, since we're releasing this as a breaking change.

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/33465; closes https://github.com/airbytehq/airbyte/issues/33383

rebased on https://github.com/airbytehq/airbyte/pull/33506

The CDK changelog isn't quite as detailed as I might like... but I think the only relevant change is in 0.6.0, with the switch to the async framework. I haven't run any manual syncs, but we're at least passing DATs. I think that's sufficient for a community connector.

### CODE REVIEW

File: airbyte-integrations/connectors/destination-mysql/src/test-integration/java/io/airbyte/integrations/destination/mysql/MySQLDestinationAcceptanceTest.java [hunk 1]
```diff
@@ -260,58 +271,76 @@ protected void assertSameValue(final JsonNode expectedValue, final JsonNode actu
...
+  /**
+   * Legacy mysql normalization is broken, and uses the FLOAT type for numbers. This rounds off e.g.
+   * 12345.678 to 12345.7. We can fix this in DV2, but will not fix legacy normalization. As such,
+   * disabling the test case.
+   */
+  @Override
+  @Disabled
+  @ParameterizedTest
+  @ArgumentsSource(DataTypeTestArgumentProvider.class)
+  public void testDataTypeTestWithNormalization(final String messagesFilename,
```
Comment (gisripa) [inline airbyte-integrations/connectors/destination-mysql/src/test-integration/java/io/airbyte/integrations/destination/mysql/MySQLDestinationAcceptanceTest.java:341]: See Stephane's suggestion in #33507

**Review by gisripa — APPROVED** [review]
lgtm.

File: airbyte-integrations/connectors/destination-mysql-strict-encrypt/build.gradle [hunk 2]
```diff
@@ -28,6 +28,16 @@ dependencies {
...
+
     integrationTestJavaImplementation project(':airbyte-integrations:connectors:destination-mysql')
     integrationTestJavaImplementation libs.testcontainers.mysql
 }
+
+configurations.all {
+    resolutionStrategy {
+        force libs.jooq
+    }
+}
```
Comment (gisripa) [inline airbyte-integrations/connectors/destination-mysql-strict-encrypt/build.gradle:43]: We need to somehow pull it into some base module and fix the dependency chain instead of forcing in all destinations

Comment (edgao) [reply airbyte-integrations/connectors/destination-mysql-strict-encrypt/build.gradle:43]: yeah. I forget _why_ we need this, tbh. isn't the point that we use the version in deps.toml everywhere already?

File: airbyte-integrations/connectors/destination-mysql/src/test-integration/java/io/airbyte/integrations/destination/mysql/MySQLDestinationAcceptanceTest.java (hunk 1 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-mysql/src/test-integration/java/io/airbyte/integrations/destination/mysql/MySQLDestinationAcceptanceTest.java:339]: done in https://github.com/airbytehq/airbyte/pull/33468/commits/43c5d27eb6b47cc1accaf5bb1b4e0b59ac2cdca1
