### PR TITLE
🎉Source Postgres: 13608, 12026, 14590 - Align regular and CDC integration tests and data mappers; improve BCE date handling

### LINKED ISSUE #12026: Postgres CDC source should not lose milliseconds precision when a timestamp/datetime is converted to string
This is a followup to https://github.com/airbytehq/airbyte/issues/9157

Exit criteria:
 - acceptance test that verifies that we are carrying over millisecond precision in Postgres CDC connector during initial sync of a table configured for incremental syncs
 - acceptance test for subsequent incremental sync

Size estimate: medium (2-3 days)

### LINKED ISSUE #13608: Source-postgres: align regular and CDC integration tests and data mappers
Currently, we have 2 different classes for integration datatype tests  CdcPostgresSourceDatatypeTest and PostgresSourceDatatypeTest.

1. Merge them. Implement timezone-aware data types instead of strings for schema type. Make a base class and add the possibility to run it using different configurations (ex. by subclasses where you add config). See SSH (key or login]pass) as an example
2. update data mappers. Most probably that in some tests for common and CDC sync will have a different expected result. So additional work would be required to alignn it.

### LINKED ISSUE #14590: Source Postgres (CDC): debezium does not handle era indicators (AD | BC) for 'DATE' type
## Current Behavior
Source-postgres in cdc mode omits era indicator. For example, the values  `1991-02-10 BC` and `1991-02-10` have the same output

## Expected Behavior
Dates with the current era (AD) and before the current era (BC) should have different outputs and era indicators should not be omitted

## Steps to Reproduce
1. Insert 2 date rows to Postgres table with the same value but different eras (e.g `1991-02-10 BC`, `1991-02-10`)
2. Run sync or datatype test
3. The output values are the same

### PR DESCRIPTION
**Pull request by yurii-bidiuk**
## What
Fixes airbytehq/airbyte#13608 airbytehq/airbyte#12026, https://github.com/airbytehq/airbyte/issues/14628
Currently, we have 2 different classes for integration datatype tests CdcMssqlSourceDatatypeTest and MssqlSourceDatatypeTest. They have the same input args, but differ "expected result" for some types.
CDC source loses milliseconds precision when a timestamp/datetime is converted to string

## How
Updated data mappers for CDC and regular sync modes. 
Added mappers for datetime datatypes to save millisecond and make datetime/date/time formats the same as for regular sync

## Recommended reading order
1. `PostgresConverter.java`
2. `PostgresSourceOperations.java`
3. `DateTimeConverter.java`
4. `AbstractPostgresSourceDatatypeTest.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by etsybaev — APPROVED** [review]

**Review by sashaNeshcheret — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]

**Comment by grishick** [comment]
I added @subodh1810 and @edgao as reviewers, because they are (have been recently) working on this code

**Review by subodh1810 — COMMENTED** [review]
@edgao am curious what do you think about this? How would this overlap with the work that you would be doing/are doing as part of this [issue](https://github.com/airbytehq/airbyte/issues/14628)

**Comment by edgao** [comment]
@subodh1810 I've only skimmed this PR (and basically haven't looked into that issue at all), but I think they should be aligned? https://github.com/airbytehq/airbyte/issues/14628 is probably easier if we have unified tests, and hopefully updating these tests to assert the correct values will be sufficient to verify that the issue is done?

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 1]
```diff
@@ -0,0 +1,526 @@
...
+
+    addDataTypeTestData(
+        TestDataHolder.builder()
+            .sourceType("circle")
+            .airbyteType(JsonSchemaType.STRING)
+            .addInsertValues("'(5,7),10'", "'(0,0),0'", "'(-10,-4),10'", "null")
+            .addExpectedValues("<(5.0,7.0),10.0>", "<(0.0,0.0),0.0>", "<(-10.0,-4.0),10.0>", null)
+            .build());
+
+    // Debezium does not handle era indicators (AD nd BC)
```
[the remark this answers is not in the document]
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:177]: @subodh1810  Debezium returns `'1991-02-10'`. Value stored in DB is `'1991-02-10 BC'`

[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:177]: that seems pretty problematic... Is there any way for us to bypass debezium's conversion (i.e. retrieve the raw DB value)? b/c otherwise that sounds like we currently can't resolve https://github.com/airbytehq/airbyte/issues/14590, right?

(I didn't see an obvious solution since debezium just throws an actual Date object at us, but really hoping I just missed something)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java [hunk 2]
```diff
@@ -84,11 +138,7 @@ private void registerMoney(final RelationalColumn field, final ConverterRegistra
         return DebeziumConverterUtils.convertDefaultValue(field);
       } else if (x instanceof Double) {
         final BigDecimal result = BigDecimal.valueOf((Double) x);
-        if (result.compareTo(new BigDecimal("999999999999999")) == 1
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:87]: is this no longer needed? I saw some comments in the deleted code about money values being rounded (somehow related to https://github.com/airbytehq/airbyte/issues/7338)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+import java.time.ZoneOffset;
+import java.time.format.DateTimeFormatter;
+
+public class DateTimeConverter {
+
+  public static final DateTimeFormatter TIME_WITH_TIMEZONE_FORMATTER = DateTimeFormatter.ofPattern(
+      "HH:mm:ss[.][SSSSSSSSS][SSSSSSS][SSSSSS][SSSSS][SSSS][SSS][SS][S][''][XXX][XX][X]");
+
+  public static String convertToTimeWithTimezone(Object time) {
+    OffsetTime timetz = OffsetTime.parse(time.toString(), TIME_WITH_TIMEZONE_FORMATTER);
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:30]: nonblocking, somewhat nitpicky; @subodh1810 I'd be interested in your opinion here: this toString -> parse -> format makes me a little nervous - it seems weird to take an object that might already be a Timestamp (or Date/Datetime/whatever) and convert it back-and-forth.

But also, checking a bunch of `instanceof` would be really gross :/ so I'm pretty conflicted about which option is less bad

Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:30]: less nitpicky, are we guaranteed that debezium will give us an object with the exact correct timestamp format?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+    return resolveEra(localDate, localDate.toString());
+  }
+
+  public static String convertToTime(Object time) {
+    LocalTime localTime = LocalTime.parse(time.toString());
+    return localTime.format(TIME_FORMATTER);
+  }
+
+  public static String resolveEra(LocalDate date, String value) {
+    return isBCE(date) ? value.substring(1) + " BC" : value;
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:63]: checking my understanding: `isBCE` is currently always false, because debezium just drops the BCE era indicator?

and the `substring(1)` is because `value` will be negative, i.e. `-2000-01-23` should become `2000-01-23 BC`?

(adding those answers as comments would be useful)

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 5]
```diff
@@ -261,6 +278,26 @@ protected void putBoolean(final ObjectNode node, final String columnName, final
     node.put(columnName, resultSet.getString(index).equalsIgnoreCase("t"));
   }
 
+  protected void putFloat8(final ObjectNode node, final String columnName, final ResultSet resultSet, final int index)
+      throws SQLException {
+    final BigDecimal bigDecimal = DataTypeUtils.returnNullIfInvalid(() -> resultSet.getBigDecimal(index));
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:283]: why does this need to be BigDecimal, if the column is just an 8-byte float? Is that not equivalent to a java `double`?

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 6]
```diff
@@ -0,0 +1,526 @@
...
+            .airbyteType(JsonSchemaType.STRING)
+            .addInsertValues("'198.24.10.0/24'", "'198.24.10.0'", "'198.10/8'", "null")
+            .addExpectedValues("198.24.10.0/24", "198.24.10.0", "198.10.0.0/8", null)
+            .build());
+
+    for (final String type : Set.of("integer", "int", "int4")) {
+      addDataTypeTestData(
+          TestDataHolder.builder()
+              .sourceType(type)
+              .airbyteType(JsonSchemaType.NUMBER)
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:213]: fyi there are some merge conflicts after https://github.com/airbytehq/airbyte/pull/14362 - ints now generate `JsonSchemaType.INTEGER` (same comment for smallint, etc)

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 7]
```diff
@@ -0,0 +1,526 @@
...
+
+    // timestamp without time zone
+    for (final String fullSourceType : Set.of("timestamp", "timestamp without time zone")) {
+      addDataTypeTestData(
+          TestDataHolder.builder()
+              .sourceType("timestamp")
+              .fullSourceDataType(fullSourceType)
+              .airbyteType(JsonSchemaType.STRING_TIMESTAMP_WITHOUT_TIMEZONE)
+              .addInsertValues("TIMESTAMP '2004-10-19 10:23:00'", "TIMESTAMP '2004-10-19 10:23:54.123456'", "null")
+              .addExpectedValues("2004-10-19T10:23:00.000000", "2004-10-19T10:23:54.123456", null)
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:422]: nice! making my life easier for https://github.com/airbytehq/airbyte/issues/14628 :D

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:177]: also, we should keep the other test cases uncommented (i.e. the non-BC date, and the null entry).

Not sure if the linter will accept this, but `.addInsertValues("'1999-01-08'", /* "'1991-02-10 BC'" */, "null")` seems reasonable

**Review by edgao — COMMENTED** [review]
nice! Added some comments, but I think this change looks really solid. I mostly just want to make sure I understand everything happening here.

**Comment by edgao** [comment]
actually: for https://github.com/airbytehq/airbyte/issues/14628, doesn't this PR resolve most of it?
* mysql / other DB sources still need to be fixed, but they can be based on this PR
* postgres BCE handling is still broken, but that's maybe a debezium limitation

**Comment by edgao** [comment]
merged in master + fixed conflicts + enabled catalog assert for the CDC tests (these were already passing, at least on my laptop!)

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:177]: added some log statements into PostgresConverter and ran this test case; apparently we're getting a Date object with no era indicator :/ Doing some research into whether there's some other interface that would give us the raw query output

Screen Shot 2022-07-27 at 3 02 54 PM

[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:177]: saving state before I take a long weekend:
* `java.sql.Date` does actually (kind of) support eras: if you have `Date d`, then `d.before(Date.valueOf("0001-01-01"))` is basically equivalent. (note that we use year 1 CE because there's no such thing as year 0)
    * The problem is mostly that the exact date 0001-01-01 is ambiguous (leap years, etc weren't applied consistently). But that's probably fine, since we don't really need that much precision for dates around that time?

I tried running a test case with `.addInsertValues("'0001-12-31 BC'", "'0001-01-01'")`, and was able to detect the first one as a BC date using the `.before` logic. But I dont know if the other types (Timestamp, etc) have an equivalent problem/solution.

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 8]
```diff
@@ -0,0 +1,526 @@
...
+              .addExpectedValues(null, "1001", "-2147483648", "2147483647")
+              .build());
+    }
+
+    addDataTypeTestData(
+        TestDataHolder.builder()
+            .sourceType("interval")
+            .airbyteType(JsonSchemaType.STRING)
+            .addInsertValues("null", "'P1Y2M3DT4H5M6S'", "'-178000000'", "'178000000'")
+            .addExpectedValues(null, "1 year 2 mons 3 days 04:05:06", "-49444:26:40", "49444:26:40")
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:224]: is it expected that the input format also affects the output format (i.e. `HHHHHHHHH:MM:SS` vs `x years y mons etc`)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java (hunk 2 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java]: Yes, you're right. Currently, this code is needed until #7338 will be fixed, so I reverted it. I tried to fix that in the scope of this ticket, but it requires more time than I expected

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java (hunk 4 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:70]: Yes, you're right. Added comment

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 5 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: Fixed. Now it's `double`

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java (hunk 3 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:30]: Hello @subodh1810. Could you please share your opinion about that?

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 9]
```diff
@@ -0,0 +1,528 @@
...
+    }
+
+    // timestamp without time zone
+    for (final String fullSourceType : Set.of("timestamp", "timestamp without time zone")) {
+      addDataTypeTestData(
+          TestDataHolder.builder()
+              .sourceType("timestamp")
+              .fullSourceDataType(fullSourceType)
+              .airbyteType(JsonSchemaType.STRING_TIMESTAMP_WITHOUT_TIMEZONE)
+              .addInsertValues("TIMESTAMP '2004-10-19 10:23:00'", "TIMESTAMP '2004-10-19 10:23:54.123456'", "null")
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:423]: let's add a BC timestamp to the timestamp and timestamptz test cases, e.g. `"TIMESTAMP '3001-10-19 10:23:54.123456 BC'"`

**Review by edgao — APPROVED** [review]
there's a couple open conversations but I feel comfortable merging this as-is. @subodh1810 any concerns?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java [hunk 10]
```diff
@@ -57,14 +102,23 @@ private void registerText(final RelationalColumn field, final ConverterRegistrat
...
       }
+      return switch (fieldType.toUpperCase(Locale.ROOT)) {
+        case "TIMETZ" -> DateTimeConverter.convertToTimeWithTimezone(x);
+        case "TIMESTAMPTZ" -> DateTimeConverter.convertToTimestampWithTimezone(x);
+        case "TIMESTAMP" -> DateTimeConverter.convertToTimestamp(x);
+        // Debezium doesn't handle era indicators
+        // https://github.com/airbytehq/airbyte/issues/14590
+        case "DATE" -> DateTimeConverter.convertToDate(x);
+        case "TIME" -> DateTimeConverter.convertToTime(x);
+        case "INTERVAL" -> convertInterval((PGInterval) x);
```
Comment (subodh1810) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:119]: We have a debezium property which we can specify so that debezium can handle interval data type differently Please take a look at this and let me know what you think of it. https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-interval-handling-mode

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java [hunk 11]
```diff
@@ -39,9 +43,50 @@ public void converterFor(final RelationalColumn field, final ConverterRegistrati
...
+      // one.
+      // The code below strips trailing zeros for integer numbers and represents number with exponent
+      // if this number has decimals point.
+      final double doubleValue = Double.parseDouble(x.toString());
+      var valueWithTruncatedZero = BigDecimal.valueOf(doubleValue).stripTrailingZeros().toString();
+      return valueWithTruncatedZero.contains(".") ? String.valueOf(doubleValue) : valueWithTruncatedZero;
+    });
+  }
+
+  private void registerBytea(final RelationalColumn field, final ConverterRegistration<SchemaBuilder> registration) {
```
Comment (subodh1810) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:81]: There is a property [binary.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-binary-handling-mode) that we can use 

```
Specifies how binary (bytea) columns should be represented in change events:

bytes represents binary data as byte array.

base64 represents binary data as base64-encoded strings.

hex represents binary data as hex-encoded (base16) strings.
```

**Review by subodh1810 — CHANGES_REQUESTED** [review]
There are a bunch of data type handling modes that we should look into the debezium's doc. Using the right mode may enable us to not build our own custom implementation. 
[time.precision.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-time-precision-mode)

[decimal.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-decimal-handling-mode)

[hstore.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-hstore-handling-mode)

[interval.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-interval-handling-mode)

[binary.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-binary-handling-mode)

Also look into the data type handling of [debezium](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-data-types) to understand how it works

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java (hunk 9 above)
Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:423]: I actually did this locally and had to make this change to get source-postgres to pass the tests https://github.com/airbytehq/airbyte/pull/14534/commits/fb9d301af86d9bdebcf62e0acca22f18c7134629

Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:423]: (also, took the opportunity to reuse the existing method in AbstractJdbcCompatibleSourceOperations)

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java [hunk 12]
```diff
@@ -0,0 +1,528 @@
...
+            .build());
+
+    // Debezium does not handle era indicators (AD nd BC)
+    // https://github.com/airbytehq/airbyte/issues/14590
+     addDataTypeTestData(
+     TestDataHolder.builder()
+     .sourceType("date")
+     .airbyteType(JsonSchemaType.STRING_DATE)
+     .addInsertValues("'1999-01-08'", /* "'1991-02-10 BC'",*/ "null")
+     .addExpectedValues("1999-01-08", /* "1990-02-10 BC", */ null)
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractPostgresSourceDatatypeTest.java:184]:
```suggestion
     .addExpectedValues("1999-01-08", /* "1991-02-10 BC", */ null)
```
(unless that's intentional?)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java (hunk 3 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DateTimeConverter.java:30]: The format could be different by milliseconds or timezone, so I added different variants to `TIME_WITH_TIMEZONE_FORMATTER` to handle it

**Comment by subodh1810** [comment]
My review should not be a blocker, I just wanted to highlight that might be a mechanism to handle few data types via the data type handling mode flag and if testing the modes is taking a lot of time, feel free to go ahead and merge this and create a separate issue to experiment with the debezium data type handling mode flags

**Comment by yurii-bidiuk** [comment]
Hi @subodh1810 
I made some research on the properties that you provided. A brief result for some of them:

- [binary.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-binary-handling-mode) - This could be used instead of our implementation because it could represent `bytea` as a hex. But there will be a small difference with non-CDC mode because non-CDC mode represents `bytea` with leading `\x` (e.g. \x123), and CDC mode with binary.handling.mode: hex represents `bytea` without `\x` (e.g. 123). I'm not sure which format is better for us.

- [hstore.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-hstore-handling-mode) - According to [#11953](https://github.com/airbytehq/airbyte/issues/11953) `hstore` should be written as json, so now it works well for CDC.

- [interval.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-interval-handling-mode) - The same result as for binary.handling.mode: we could use this property but the represented value would be different from the value in the non-CDC mode.

**Comment by edgao** [comment]
thanks for the analysis! In that case, I think we should publish+merge this PR as-is.

File: docs/integrations/sources/postgres.md [hunk 13]
```diff
@@ -354,7 +354,8 @@ Possible solutions include:
 
 | Version | Date       | Pull Request                                             | Subject                                                                                                           |
 |:--------|:-----------|:---------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------|
-| 0.5.0   | 2022-07-26 | [14362](https://github.com/airbytehq/airbyte/pull/14362) | Integral columns are now discovered as int64 fields. |
```
Comment (edgao) [inline docs/integrations/sources/postgres.md:357]: this version was published as 0.4.38, so needed to fix the changelog.

**Comment by edgao** [comment]
can't publish until https://github.com/airbytehq/airbyte/pull/14801 is merged

**Comment by edgao** [comment]
@yurii-bidiuk I'll take over publishing here.

Will merge https://github.com/airbytehq/airbyte/pull/15187/ into this one, get https://github.com/airbytehq/airbyte/pull/14801 merged to master, and update this PR's version numbers/changelog accordingly.
