### PR TITLE
Handle SQLSTATE Exception (08006) when reading records

### LINKED ISSUE #12962: Gracefully handle SQLSTATE(08006) in Postgres Source
## Environment
- **Airbyte version**:  0.38.4-alpha
- **OS Version / Instance**: Ubuntu 20.04.4 LTS on AWS EC2 m5a.xlarge (2 core, 16GB) and c5a.2xlarge (8 core, 16GB)
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.16
- **Destination Connector and version**: S3 0.3.5 (jsonl.gz)
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
I want Airbyte to do a full load of a PostgreSQL replica node. The PostgreSQL node is configured to have a `max_standby_archive_delay` set to `14400000` (4 hours) and `max_standby_streaming_delay` set to `14400000` (4 hours) aswell.

Unfortunately the job seems to run into that 4 hour limit causing Airbyte to fail. In the log I can see the Java stack trace mentioning a fatal error but the job history lists this very job as `Succeeded`.

## Expected Behavior
I expect Airbyte to mark the failed run as `Failed` instead of `Succeeded`

## Logs
Lines in log mentioning errors + successful sync summary:

1. `Connection org.postgresql.jdbc.PgConnection@2adddc06 marked as broken because of SQLSTATE(08006), ErrorCode(0)`
1. `org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.`
1. `AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.`
1. `FATAL: terminating connection due to conflict with recovery`
1. `sync summary: io.airbyte.config.ReplicationAttemptSummary@299d029[status=completed,`

<details>
<summary>LOG</summary> 

```

...
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77076000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77077000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77078000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77079000 (104 GB)
2022-05-18 12:47:38 [44msource[0m > 2022-05-18 12:47:38 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):256 - Reading stream table_a. Records read: 34990000
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77080000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77081000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77082000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77083000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77084000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77085000 (104 GB)
2022-05-18 12:47:38 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77086000 (104 GB)
2022-05-18 12:47:39 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77087000 (104 GB)
2022-05-18 12:47:39 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77088000 (104 GB)
2022-05-18 12:47:39 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):331 - Records read: 77089000 (104 GB)
2022-05-18 12:47:39 [44msource[0m > 2022-05-18 12:47:38 [32mINFO[m i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):256 - Reading stream table_a. Records read: 35000000
2022-05-18 12:47:39 [44msource[0m > 2022-05-18 12:47:38 [33mWARN[m c.z.h.p.ProxyConnection(checkException):177 - HikariPool-2 - Connection org.postgresql.jdbc.PgConnection@2adddc06 marked as broken because of SQLSTATE(08006), ErrorCode(0)
2022-05-18 12:47:39 [44msource[0m > org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2566) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:2143) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:91) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$2(IntegrationRunner.java:176) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:232) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:175) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:156) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:156) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:410) [io.airbyte.airbyte-integrations.connectors-source-postgres-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > Caused by: java.io.EOFException
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.PGStream.receiveChar(PGStream.java:455) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2119) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2561) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	... 37 more
2022-05-18 12:47:39 [44msource[0m > 2022-05-18 12:47:38 [1;31mERROR[m i.a.c.u.CompositeIterator(close):93 - exception while closing
2022-05-18 12:47:39 [44msource[0m > java.lang.RuntimeException: java.sql.SQLException: Connection is closed
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:71) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:52) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.java:91) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) [io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) [io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) [io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:410) [io.airbyte.airbyte-integrations.connectors-source-postgres-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > Caused by: java.sql.SQLException: Connection is closed
2022-05-18 12:47:39 [44msource[0m > 	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at jdk.proxy3.$Proxy38.setAutoCommit(Unknown Source) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:68) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	... 18 more
2022-05-18 12:47:39 [44msource[0m > 2022-05-18 12:47:38 [1;31mERROR[m i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2022-05-18 12:47:39 [44msource[0m > java.lang.RuntimeException: org.postgresql.util.PSQLException: FATAL: terminating connection due to conflict with recovery
2022-05-18 12:47:39 [44msource[0m >   Detail: User query might have needed to see row versions that must be removed.
2022-05-18 12:47:39 [44msource[0m >   Hint: In a moment you should be able to reconnect to the database and repeat your command.
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:100) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$2(IntegrationRunner.java:176) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:232) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:175) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:156) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:156) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:410) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	Suppressed: java.lang.RuntimeException: java.sql.SQLException: Connection is closed
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:71) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:52) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.java:91) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.AutoCloseableIterators.lambda$appendOnClose$0(AutoCloseableIterators.java:88) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:49) ~[io.airbyte-airbyte-commons-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) ~[io.airbyte.airbyte-integrations.bases-base-java-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:410) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	Caused by: java.sql.SQLException: Connection is closed
2022-05-18 12:47:39 [44msource[0m > 		at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at jdk.proxy3.$Proxy38.setAutoCommit(Unknown Source) ~[?:?]
2022-05-18 12:47:39 [44msource[0m > 		at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:68) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 		... 18 more
2022-05-18 12:47:39 [44msource[0m > Caused by: org.postgresql.util.PSQLException: FATAL: terminating connection due to conflict with recovery
2022-05-18 12:47:39 [44msource[0m >   Detail: User query might have needed to see row versions that must be removed.
2022-05-18 12:47:39 [44msource[0m >   Hint: In a moment you should be able to reconnect to the database and repeat your command.
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2561) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:2143) ~[postgresql-42.3.4.jar:42.3.4]
2022-05-18 12:47:39 [44msource[0m > 	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java) ~[HikariCP-5.0.1.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	at io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:91) ~[io.airbyte.airbyte-db-lib-0.38.3-alpha.jar:?]
2022-05-18 12:47:39 [44msource[0m > 	... 34 more
2022-05-18 12:47:39 [32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$6):342 - Total records read: 77089792 (104 GB)
2022-05-18 12:47:39 [33mWARN[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):345 - 42775 schema validation errors found for stream public-table_b. Error message: Record schema validation failed for public-table_b. Expected schema: {"foo":"bar"}
2022-05-18 12:47:39 [33mWARN[m i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):345 - 42046983 schema validation errors found for stream public-table_c. Error message: Record schema validation failed for public-table_c. Expected schema: {"foo":"bar"}
2022-05-18 12:47:39 [32mINFO[m i.a.w.DefaultReplicationWorker(run):168 - One of source or destination thread complete. Waiting on the other.
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [33mWARN[m i.a.i.d.b.BufferedStreamConsumer(acceptTracked):141 - Unexpected message: TRACE
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):170 - executing on success close procedure.
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(flushAll):92 - Flushing all 3 current buffers (288 MB in total)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$flushAll$2):95 - Flushing buffer of stream full_database_table_b (4 MB)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.s.S3ConsumerFactory(lambda$flushBufferFunction$3):129 - Flushing buffer for stream full_database_table_b (4 MB) to storage
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):131 - Wrapping up compression and write GZIP trailer data.
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):138 - Finished writing data to 2add8d3b-16e5-4bf5-9265-842e392d0e122192105942002136712.jsonl.gz (4 MB)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.s.u.StreamTransferManagerHelper(getDefault):60 - PartSize arg is set to 525 MB
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to airbyte-ingestion-dev/raw/datasrc/full_database_table_b/partition_year=2022/partition_month=05/partition_day=18/full_database_table_b-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz with full ID PQFoPmb9Qgrb9FANK4jBwpF_exJLzBugrFXcl6S7XHvQHNBinGm_TbWY_fp.iqkEptiMky1CkF._aGTHXJ9egjWI_TELTq.G8PaXxAv7S71nOc.8h0dznPoKqIRdRI3M
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_b/partition_year=2022/partition_month=05/partition_day=18/full_database_table_b-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz with id PQFoPmb9Q...KqIRdRI3M]: Uploading leftover stream [Part number 1 containing 4.67 MB]
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_b/partition_year=2022/partition_month=05/partition_day=18/full_database_table_b-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz with id PQFoPmb9Q...KqIRdRI3M]: Finished uploading [Part number 1 containing 4.67 MB]
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_b/partition_year=2022/partition_month=05/partition_day=18/full_database_table_b-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz with id PQFoPmb9Q...KqIRdRI3M]: Completed
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.s.S3StorageOperations(loadDataIntoBucket):176 - Uploaded buffer file to storage: 2add8d3b-16e5-4bf5-9265-842e392d0e122192105942002136712.jsonl.gz -> raw/datasrc/full_database_table_b/partition_year=2022/partition_month=05/partition_day=18/full_database_table_e-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz (filename: full_database_table_e-1-2022-05-18-08-46-33-c16b92c8-3226-4d4f-abd3-37c7ee3e762a_0.jsonl.gz)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.FileBuffer(deleteFile):81 - Deleting tempFile data 2add8d3b-16e5-4bf5-9265-842e392d0e122192105942002136712.jsonl.gz
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$flushAll$2):95 - Flushing buffer of stream full_database_table_c (96 MB)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.s.S3ConsumerFactory(lambda$flushBufferFunction$3):129 - Flushing buffer for stream full_database_table_c (96 MB) to storage
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):131 - Wrapping up compression and write GZIP trailer data.
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):138 - Finished writing data to caf6417a-5174-4899-a42b-950b5adf1b9a684925404377952484.jsonl.gz (96 MB)
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m i.a.i.d.s.u.StreamTransferManagerHelper(getDefault):60 - PartSize arg is set to 525 MB
2022-05-18 12:47:39 [43mdestination[0m > 2022-05-18 12:47:39 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to airbyte-ingestion-dev/raw/datasrc/full_database_table_c/partition_year=2022/partition_month=05/partition_day=18/full_database_table_c-1-2022-05-18-08-46-33-6f32d3fd-79ab-4ff2-a9d1-e63fafd475e6_71.jsonl.gz with full ID OtQEDhAiNsIpTJXmqcQcKdOerO7x5e0iOe39uCdqSw.0PKt57mtbF253XkbpRv.n4C.DGHRlxKMN3_sTyxANS5WRVb5u1lLUkRgYo1eMXljP5V25spLmO6Jm6cL.yjdu
2022-05-18 12:47:40 [43mdestination[0m > 2022-05-18 12:47:40 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_c/partition_year=2022/partition_month=05/partition_day=18/full_database_table_c-1-2022-05-18-08-46-33-6f32d3fd-79ab-4ff2-a9d1-e63fafd475e6_71.jsonl.gz with id OtQEDhAiN...m6cL.yjdu]: Finished uploading [Part number 1 containing 96.07 MB]
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_c/partition_year=2022/partition_month=05/partition_day=18/full_database_table_c-1-2022-05-18-08-46-33-6f32d3fd-79ab-4ff2-a9d1-e63fafd475e6_71.jsonl.gz with id OtQEDhAiN...m6cL.yjdu]: Completed
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.s.S3StorageOperations(loadDataIntoBucket):176 - Uploaded buffer file to storage: caf6417a-5174-4899-a42b-950b5adf1b9a684925404377952484.jsonl.gz -> raw/datasrc/full_database_table_c/partition_year=2022/partition_month=05/partition_day=18/full_database_table_c-1-2022-05-18-08-46-33-6f32d3fd-79ab-4ff2-a9d1-e63fafd475e6_71.jsonl.gz (filename: full_database_table_c-1-2022-05-18-08-46-33-6f32d3fd-79ab-4ff2-a9d1-e63fafd475e6_71.jsonl.gz)
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.r.FileBuffer(deleteFile):81 - Deleting tempFile data caf6417a-5174-4899-a42b-950b5adf1b9a684925404377952484.jsonl.gz
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$flushAll$2):95 - Flushing buffer of stream full_database_table_a (188 MB)
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.s.S3ConsumerFactory(lambda$flushBufferFunction$3):129 - Flushing buffer for stream full_database_table_a (188 MB) to storage
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):131 - Wrapping up compression and write GZIP trailer data.
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.r.BaseSerializedBuffer(flush):138 - Finished writing data to 8b0f542c-7004-4cdb-9729-33bc8344f66017938745840088194705.jsonl.gz (188 MB)
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m i.a.i.d.s.u.StreamTransferManagerHelper(getDefault):60 - PartSize arg is set to 525 MB
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to airbyte-ingestion-dev/raw/datasrc/full_database_table_a/partition_year=2022/partition_month=05/partition_day=18/full_database_table_a-1-2022-05-18-08-46-33-2e558d15-8842-4481-96e4-206975d061f2_12.jsonl.gz with full ID bembgt6RNd2oKVAmsRwSK4w8LhCEQ34ZFwva7aaiO.2JhoSbC3U4Lnw8hxvXZfJPoaEeKWqEAWt7g6ft3csgFIv.NiQGRA9.eWI5XIg3INuXhKEFRnXnxaYhzsH6MRaF
2022-05-18 12:47:41 [43mdestination[0m > 2022-05-18 12:47:41 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_a/partition_year=2022/partition_month=05/partition_day=18/full_database_table_a-1-2022-05-18-08-46-33-2e558d15-8842-4481-96e4-206975d061f2_12.jsonl.gz with id bembgt6RN...hzsH6MRaF]: Finished uploading [Part number 1 containing 188.20 MB]
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - [Manager uploading to airbyte-ingestion-dev/raw/datasrc/full_database_table_a/partition_year=2022/partition_month=05/partition_day=18/full_database_table_a-1-2022-05-18-08-46-33-2e558d15-8842-4481-96e4-206975d061f2_12.jsonl.gz with id bembgt6RN...hzsH6MRaF]: Completed
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.d.s.S3StorageOperations(loadDataIntoBucket):176 - Uploaded buffer file to storage: 8b0f542c-7004-4cdb-9729-33bc8344f66017938745840088194705.jsonl.gz -> raw/datasrc/full_database_table_a/partition_year=2022/partition_month=05/partition_day=18/full_database_table_a-1-2022-05-18-08-46-33-2e558d15-8842-4481-96e4-206975d061f2_12.jsonl.gz (filename: full_database_table_a-1-2022-05-18-08-46-33-2e558d15-8842-4481-96e4-206975d061f2_12.jsonl.gz)
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.d.r.FileBuffer(deleteFile):81 - Deleting tempFile data 8b0f542c-7004-4cdb-9729-33bc8344f66017938745840088194705.jsonl.gz
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(close):119 - Closing buffer for stream full_database_table_e
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(close):119 - Closing buffer for stream full_database_table_c
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(close):119 - Closing buffer for stream full_database_table_a
2022-05-18 12:47:43 [43mdestination[0m > 2022-05-18 12:47:43 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.destination.s3.S3Destination
2022-05-18 12:47:43 [32mINFO[m i.a.w.DefaultReplicationWorker(run):170 - Source and destination threads complete.
2022-05-18 12:47:43 [32mINFO[m i.a.w.DefaultReplicationWorker(run):233 - sync summary: io.airbyte.config.ReplicationAttemptSummary@299d029[status=completed,recordsSynced=77089791,bytesSynced=112089518910,startTime=1652863591877,endTime=1652878063505,totalStats=io.airbyte.config.SyncStats@7637a765[recordsEmitted=77089791,bytesEmitted=112089518910,stateMessagesEmitted=0,recordsCommitted=77089791],streamStats=[io.airbyte.config.StreamSyncStats@2b109f6e[streamName=full_database_table_e,stats=io.airbyte.config.SyncStats@5124716a[recordsEmitted=42798,bytesEmitted=14435399,stateMessagesEmitted=<null>,recordsCommitted=42798]], io.airbyte.config.StreamSyncStats@1d70ebff[streamName=full_database_table_a,stats=io.airbyte.config.SyncStats@56b77bbb[recordsEmitted=35000010,bytesEmitted=6930004003,stateMessagesEmitted=<null>,recordsCommitted=35000010]], io.airbyte.config.StreamSyncStats@79f375ec[streamName=full_database_table_c,stats=io.airbyte.config.SyncStats@baee499[recordsEmitted=42046983,bytesEmitted=105145079508,stateMessagesEmitted=<null>,recordsCommitted=42046983]]]]
2022-05-18 12:47:43 [32mINFO[m i.a.w.DefaultReplicationWorker(run):262 - Source did not output any state messages
2022-05-18 12:47:43 [33mWARN[m i.a.w.DefaultReplicationWorker(run):270 - State capture: No new state, falling back on input state: io.airbyte.config.State@62d4f120[state={}]
2022-05-18 12:47:43 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
2022-05-18 12:47:43 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):157 - sync summary: io.airbyte.config.StandardSyncOutput@2e56b438[standardSyncSummary=io.airbyte.config.StandardSyncSummary@fdaa227[status=completed,recordsSynced=77089791,bytesSynced=112089518910,startTime=1652863591877,endTime=1652878063505,totalStats=io.airbyte.config.SyncStats@7637a765[recordsEmitted=77089791,bytesEmitted=112089518910,stateMessagesEmitted=0,recordsCommitted=77089791],streamStats=[io.airbyte.config.StreamSyncStats@2b109f6e[streamName=full_database_table_e,stats=io.airbyte.config.SyncStats@5124716a[recordsEmitted=42798,bytesEmitted=14435399,stateMessagesEmitted=<null>,recordsCommitted=42798]], io.airbyte.config.StreamSyncStats@1d70ebff[streamName=full_database_table_a,stats=io.airbyte.config.SyncStats@56b77bbb[recordsEmitted=35000010,bytesEmitted=6930004003,stateMessagesEmitted=<null>,recordsCommitted=35000010]], io.airbyte.config.StreamSyncStats@79f375ec[streamName=full_database_table_c,stats=io.airbyte.config.SyncStats@baee499[recordsEmitted=42046983,bytesEmitted=105145079508,stateMessagesEmitted=<null>,recordsCommitted=42046983]]]],normalizationSummary=<null>,state=io.airbyte.config.State@62d4f120[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@18aa7f22[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@31f4eba5[stream=io.airbyte.protocol.models.AirbyteStream@2a186ed7[name=full_database_table_e,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@70893a29[stream=io.airbyte.protocol.models.AirbyteStream@3b110875[name=full_database_table_c,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@2d2e7571[stream=io.airbyte.protocol.models.AirbyteStream@44a9c8d5[name=full_database_table_a,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@7dc8fa1b[stream=io.airbyte.protocol.models.AirbyteStream@4ea91777[name=full_database_table_f,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[installed_rank]],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[installed_rank]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1072762e[stream=io.airbyte.protocol.models.AirbyteStream@1a17eb95[name=full_database_table_d,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@20b5d2ee[stream=io.airbyte.protocol.models.AirbyteStream@26217b20[name=full_database_table_d_bck,jsonSchema={"foo":"bar"},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=datasrc,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@25e1bacc[failureOrigin=source,failureType=system_error,internalMessage=java.lang.RuntimeException: org.postgresql.util.PSQLException: FATAL: terminating connection due to conflict with recovery
  Detail: User query might have needed to see row versions that must be removed.
  Hint: In a moment you should be able to reconnect to the database and repeat your command.,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@fb6a6[additionalProperties={attemptNumber=0, jobId=174, from_trace_message=true}],stacktrace=[io.airbyte.db.jdbc.StreamingJdbcDatabase$1.tryAdvance(StreamingJdbcDatabase.java:100), java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:42), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), java.base/java.util.Iterator.forEachRemaining(Iterator.java:132), io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$2(IntegrationRunner.java:176), io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:232), io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:175), io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:156), io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54), io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38), io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:156), io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107), io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:410)],retryable=<null>,timestamp=1652878058831]]]
2022-05-18 12:47:43 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):236 - Stopping temporal heartbeating...
2022-05-18 12:47:43 [32mINFO[m i.a.c.p.ConfigRepository(updateConnectionState):774 - Updating connection 022ca685-8f31-431e-9f6b-4fb3914bf5a3 state: io.airbyte.config.State@83d6959[state={}]
2022-05-18 12:47:43 [33mWARN[m i.a.s.p.JobNotifier(notifyJob):116 - Failed to successfully notify success: io.airbyte.config.Notification@54eb9d16[notificationType=slack,sendOnSuccess=true,sendOnFailure=true,slackConfiguration=io.airbyte.config.SlackNotificationConfiguration@5f980121[webhook=],customerioConfiguration=<null>,additionalProperties={}]
2022-05-18 12:47:43 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.compression_codec: is missing but it is required, $.format_type: does not have a value in the enumeration [Avro]
2022-05-18 12:47:43 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.flattening: is missing but it is required, $.format_type: does not have a value in the enumeration [CSV]
2022-05-18 12:47:43 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.compression_type: does not have a value in the enumeration [No Compression]

```

</details>

## Steps to Reproduce
1. Set the following PostgreSQL options to less milliseconds than an usual Airbyte job would take
    1. max_standby_archive_delay
    1. max_standby_streaming_delay
1. Configure Airbyte job to do a full load of that source
1. Let Airbyte run into that limit

## Are you willing to submit a PR?

Would love to contribute but I'm not familiar with Java.

### PR DESCRIPTION
**Pull request by ryankfu**
## What
Adds logic to emit most recent "ready" state when a SQLException is thrown. In particular this logic also tests for SQLSTATE with error code `08006` which the beginning two digits `08` indicate a connection failure. Closes [Github Issue](https://github.com/airbytehq/airbyte/issues/12962)

## How
Updates `StateDecoratingIterator` control flow to catch `Exceptions` while splitting logic handling between `SQLExceptions` and general `RuntimeExceptions`

## Recommended reading order
1. `StateDecoratingIterator.java`
2. `StateDecoratingIteratorTest.java`
3. `IncrementalUtils.java`
4. `AbstractDbSource.java`
5. `StreamingJdbcDatabase.java`
6. `test_streams.py` is generated from running `./gradlew format`

NOTE: `StreamingJdbcDatabase` logging is mainly because this is where the `SQLException` is wrapped by the a `RuntimeException` and as such is the closest location to where the user was originally experiencing the `PSQLException` causing a failure within the messageIterator

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

No user impact, this will prevent users from experiencing issues when their sync to a replication server takes longer than their primary server allocates and kills the connection for Airbyte to retrieve records from their source connection

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java [hunk 1]
```diff
@@ -147,6 +173,48 @@ void testCursorFieldIsEmpty() {
...
+        RECORD_VALUE_1,
+        JsonSchemaPrimitive.STRING,
+        0);
+    assertEquals(RECORD_MESSAGE_1, iterator.next());
+    assertEquals(RECORD_MESSAGE_2, iterator.next());
+    assertEquals(RECORD_MESSAGE_2, iterator.next());
+    assertEquals(RECORD_MESSAGE_3, iterator.next());
+    // since stateEmission is not set to emit frequently, this will catch the error but not emit state message since it wasn't in a ready state
+    // of having a frequency > 0 but will prevent an exception from causing the iterator to fail by marking iterator as endOfData()
+    assertFalse(iterator.hasNext());
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java:215]: Quick note: this may not be ideal since the cursor isn't updated when the `stateEmissionFrequency = 0` but ideally by having all connections use at least `1` or greater for `stateEmissionFrequency` this will emit state more frequently. The note here is that while this does not emit a state message, it does at least catch the exception and log that the messageIterator failed to read the next record

**Comment by ryankfu** [comment]
These two integration tests are failing on `master` and confirmed the failures are the exact same as the ones ran on this branch which it seems unrelated to the changes here:
* [source-scaffold-java-jdbc](https://github.com/airbytehq/airbyte/actions/runs/2928946320)
* [source-bigquery](https://github.com/airbytehq/airbyte/actions/runs/2929003911)

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java [hunk 2]
```diff
@@ -66,42 +73,98 @@ private String getCursorCandidate(final AirbyteMessage message) {
...
-            // because the last state message will be taken care of in a different branch.
-            intermediateStateMessage = createStateMessage(false);
+      // Use try-catch to catch Exception that could occur when connection to the database fails
+      try {
+        final AirbyteMessage message = messageIterator.next();
+        if (message.getRecord().getData().hasNonNull(cursorField)) {
+          final String cursorCandidate = getCursorCandidate(message);
+          if (IncrementalUtils.compareCursors(maxCursor, cursorCandidate, cursorType) < 0) {
+            if (stateEmissionFrequency > 0 && !Objects.equals(maxCursor, initialCursor) && messageIterator.hasNext()) {
+              // Only emit an intermediate state when it is not the first or last record message,
```
Comment (grishick) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:113]: - why not emit intermediate state if this is the first record message?
 - where is the last state message taken care of?

**Review by grishick — APPROVED** [review]
LGTM, I had two questions that I added in a comment, but these are more for my own education

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java (hunk 2 above)
Comment (ryankfu) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:113]: * it does not emit state since after reading the first record it is not clear if there's records with the same `cursorField`, once a cursor has been updated it will emit the state on the next iteration. This example is explained a little further in [this comment](https://github.com/airbytehq/airbyte/pull/15496#discussion_r942590918) and in `StateDecoratingIteratorTest#testStateEmissionForRecordsSharingSameCursorValue`
* the last state message is _only_ emitted when it reaches a "ready" state. In this case the last state message is taken care of within the `StateDecoratingIterator#createStateMessage`. To the best of my knowledge there is also still work that Liren is completing with regards to the last state message in [this PR](https://github.com/airbytehq/airbyte/pull/15535/files)
