### PR TITLE
Fix settings link in the connection row

### LINKED ISSUE #9637: Click on settings icon in connection list brings you to default page
Currently (present on master) when clicking the Settings icon in the connection row it will bring you to the default page. If you click the row besides that icon it will correctly bring you to the connection page.

Peek 2022-01-20 10-15

This is something a lot of users (~10%) are running into.

### PR DESCRIPTION
**Pull request by juliachvyrova**
## What
Fix Settings link in the connection row in Connections Page.

Closes #9637

### CODE REVIEW

**Review by jamakase — APPROVED** [review]

File: airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx [hunk 1]
```diff
@@ -3,9 +3,9 @@ import styled from "styled-components";
 import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
 import { faCog } from "@fortawesome/free-solid-svg-icons";
 
-import useRouter from "hooks/useRouter";
 import { RoutePaths } from "pages/routes";
 import { useCurrentWorkspace } from "hooks/services/useWorkspace";
+import Link from "components/Link";
```
Comment (Jamakase) [inline airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx:8]: I believe this could be imported as 

`import { Link } from "components"` instead

**Review by jrhizor — APPROVED** [review]
