### PR TITLE
🐛 Destination snowflake: support concurrent syncs with identical stream name but different namespace

### LINKED ISSUE #30492: Destination snowflake (and maybe bigquery?): Create staging area with namespace
snowflake's `create stage` query is doing roughly `create stage airbyte_internal.<stream_name>`. If there are multiple streams with the same name but different namespace, they will clobber each other. We should give the stage name the same name as the raw table, i.e. `create stage airbyte_internal.<namespace>_raw__stream_<name>`.

Check if bigquery has a similar problem for its GCS files.

Errors look like:

```
ERROR i.a.i.d.s.SnowflakeInternalStagingSqlOperations(uploadRecordsToStage):85 Failed to upload records into stage 2023/09/14/14/720F6F38-07B5-48A6-A757-D348B352174A/ net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Stage 'XXX."airbyte_internal"."sales"' does not exist or not authorized.
```

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/30492

review order:
* first commit (https://github.com/airbytehq/airbyte/pull/30599/commits/eadaa97700de0cbd8054d325cd3be83710e57cdd) makes the `incrementalDedupIdenticalName` test use different messages for each stream. It doesn't actually catch the bug, but seems like good improvement anyway :shrug:
* Review the [rest of the diff](https://github.com/airbytehq/airbyte/pull/30599/files/eadaa97700de0cbd8054d325cd3be83710e57cdd..05cdd1566b0b6de99cb4ff86238268f17c3811d4):
  * Add a `identicalNameSimultaneousSync` test case, which _does_ catch the bug. It passes for destination-bigquery on master, but fails for destination-snowflake.
    * Arguably, this should actually be a base DAT test case :shrug: but we have DATs disabled for bq+snowflake right now, so that would be tricky
    * This test takes about 2 minutes locally for bigquery, which I think is acceptable for an acceptance test. It takes <1 minute for snowflake, so I think once bigquery is asyncified, it'll get a lot better.
    * empirically, CI ran the entire integration test suite in 5.5 minutes for snowflake + 3.5 minutes for bigquery, so I feel OK here.
    * I didn't do any tuning; it's possible that 100K iterations is overkill.
  * Switch the async framework to use the raw table name as the stage name, instead of just the stream name.
  * Add a comment to destination-redshift saying that we should do the same thing, eventually. (presumably, if we forget, the new test will catch it.)

### CODE REVIEW

File: airbyte-integrations/bases/base-typing-deduping-test/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/BaseTypingDedupingTest.java [hunk 1]
```diff
@@ -617,31 +694,36 @@ private static List<AirbyteMessage> readMessages(final String filename, final St
    * make edits here, you probably want to also edit there.
    */
 
-  // These contain some state, so they are instanced per test (i.e. cannot be static)
-  private Path jobRoot;
-  private ProcessFactory processFactory;
```
Comment (edgao) [inline airbyte-integrations/bases/base-typing-deduping-test/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/BaseTypingDedupingTest.java:622]: these didn't need to actually be fields, and in fact need to be isolated per-process to avoid clobbering the destination connector inputs (i.e. catalog/config). I moved these declarations into the methods, so each process now gets its  own jobRoot + processFactory.

(possibly the processfactory can be shared? but I didn't bother testing that, and I don't think it really matters)

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`bde700388f`](https://github.com/airbytehq/airbyte/pull/30599/commits/bde700388f81bef9710c990fb716fdd905555bed)) - ❌

⏲️  Total pipeline duration: 02mn28s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ❌        |
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695415350/bde700388f81bef9710c990fb716fdd905555bed/destination-redshift/0.6.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bde700388f81bef9710c990fb716fdd905555bed)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`bde700388f`](https://github.com/airbytehq/airbyte/pull/30599/commits/bde700388f81bef9710c990fb716fdd905555bed)) - ✅

⏲️  Total pipeline duration: 09mn14s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Build connector tar                                                          | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                    | ✅        |
| Java Connector Integration Tests                                             | ✅        |
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695415350/bde700388f81bef9710c990fb716fdd905555bed/destination-snowflake/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bde700388f81bef9710c990fb716fdd905555bed)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`bde700388f`](https://github.com/airbytehq/airbyte/pull/30599/commits/bde700388f81bef9710c990fb716fdd905555bed)) - ✅

⏲️  Total pipeline duration: 06mn25s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695415350/bde700388f81bef9710c990fb716fdd905555bed/destination-bigquery/2.0.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bde700388f81bef9710c990fb716fdd905555bed)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`6cdd43e835`](https://github.com/airbytehq/airbyte/pull/30599/commits/6cdd43e83527e81646e37d59cf5809093f94ac83)) - ❌

⏲️  Total pipeline duration: 02mn26s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ❌        |
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695659612/6cdd43e83527e81646e37d59cf5809093f94ac83/destination-redshift/0.6.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6cdd43e83527e81646e37d59cf5809093f94ac83)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`b9f267bb41`](https://github.com/airbytehq/airbyte/pull/30599/commits/b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d)) - ❌

⏲️  Total pipeline duration: 09mn34s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Build connector tar                                                          | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                    | ✅        |
| Java Connector Integration Tests                                             | ❌        |
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695660004/b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d/destination-snowflake/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`b9f267bb41`](https://github.com/airbytehq/airbyte/pull/30599/commits/b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d)) - ✅

⏲️  Total pipeline duration: 06mn34s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695660004/b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d/destination-bigquery/2.0.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b9f267bb41f9f79a5c332712b6cb19c7bc2ab64d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`96ece09cf8`](https://github.com/airbytehq/airbyte/pull/30599/commits/96ece09cf8952695a3c4e0e3ec97512ee591a5a9)) - ❌

⏲️  Total pipeline duration: 01mn17s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ❌        |
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695842110/96ece09cf8952695a3c4e0e3ec97512ee591a5a9/destination-redshift/0.6.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:96ece09cf8952695a3c4e0e3ec97512ee591a5a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`96ece09cf8`](https://github.com/airbytehq/airbyte/pull/30599/commits/96ece09cf8952695a3c4e0e3ec97512ee591a5a9)) - ✅

⏲️  Total pipeline duration: 07mn14s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695843336/96ece09cf8952695a3c4e0e3ec97512ee591a5a9/destination-bigquery/2.0.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:96ece09cf8952695a3c4e0e3ec97512ee591a5a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`96ece09cf8`](https://github.com/airbytehq/airbyte/pull/30599/commits/96ece09cf8952695a3c4e0e3ec97512ee591a5a9)) - ❌

⏲️  Total pipeline duration: 09mn14s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Build connector tar                                                          | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                    | ✅        |
| Java Connector Integration Tests                                             | ❌        |
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695843336/96ece09cf8952695a3c4e0e3ec97512ee591a5a9/destination-snowflake/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:96ece09cf8952695a3c4e0e3ec97512ee591a5a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`96ece09cf8`](https://github.com/airbytehq/airbyte/pull/30599/commits/96ece09cf8952695a3c4e0e3ec97512ee591a5a9)) - ❌

⏲️  Total pipeline duration: 01mn46s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ❌        |
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695843336/96ece09cf8952695a3c4e0e3ec97512ee591a5a9/destination-redshift/0.6.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:96ece09cf8952695a3c4e0e3ec97512ee591a5a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`1176a24a0a`](https://github.com/airbytehq/airbyte/pull/30599/commits/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)) - ✅

⏲️  Total pipeline duration: 11mn34s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Build connector tar                                                          | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                    | ✅        |
| Java Connector Integration Tests                                             | ✅        |
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695846920/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e/destination-snowflake/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`1176a24a0a`](https://github.com/airbytehq/airbyte/pull/30599/commits/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)) - ✅

⏲️  Total pipeline duration: 03mn57s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695846920/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e/destination-bigquery/2.0.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`1176a24a0a`](https://github.com/airbytehq/airbyte/pull/30599/commits/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)) - ❌

⏲️  Total pipeline duration: 01mn45s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ❌        |
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dv2_identicalnamehandling/1695846920/1176a24a0ae9eb5ef9be575d8cd7abeb4030456e/destination-redshift/0.6.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1176a24a0ae9eb5ef9be575d8cd7abeb4030456e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]
