### PR TITLE
force job submitter to only submit jobs if no other job with same scope is active

### LINKED ISSUE #1342: JobSubmitter does not respect scope
## Expected Behavior
* JobSubmitter should not allow sync jobs that have the same scope. Otherwise we can have two syncs jobs for the same connection at once.

## Current Behavior
* If you click sync now it starts a new job regardless of what's running. This creates bad behavior if something is already running 1) undefined what data gets replicated 2) the state machine around job status exhibits undefined behavior.

## Steps to Reproduce
1. hit sync now a bunch of times

### PR DESCRIPTION
**Pull request by cgardens**
Closes https://github.com/airbytehq/airbyte/issues/1342

## What
* JobSubmitter is submitting job when another job of that scope is either already running or awaiting retry. In both of these cases, we do not want to allow the job to be submitted.

## How
* Fixed the query. Added tests.

### CODE REVIEW

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java [hunk 1]
```diff
@@ -143,6 +143,6 @@
    */
   Optional<State> getCurrentState(UUID connectionId) throws IOException;
 
-  Optional<Job> getOldestPendingJob() throws IOException;
+  Optional<Job> getNextJob() throws IOException;
```
Comment (cgardens) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java:146]: changing name to so that you have to go read what the rules of the method.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java [hunk 2]
```diff
@@ -287,9 +287,14 @@ private Job getJob(DSLContext ctx, long jobId) {
   }
 
   @Override
-  public Optional<Job> getOldestPendingJob() throws IOException {
+  public Optional<Job> getNextJob() throws IOException {
+    // rules:
```
Comment (cgardens) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:291]: a little unclear if 2 and 3 should apply for jobs that are not sync jobs. e.g. there's no reason why two spec queries need to wait on each other. i'm inclined to say it doesn't matter, but if we do run into a performance issue here we can changes it so rules 2 and 3 _only_ apply to sync jobs. inclined to keep it simpler until we need to though.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java [hunk 3]
```diff
@@ -75,7 +75,7 @@ public void run() {
     try {
       LOGGER.info("Running job-submitter...");
 
-      final Optional<Job> oldestPendingJob = persistence.getOldestPendingJob();
+      final Optional<Job> oldestPendingJob = persistence.getNextJob();
```
Comment (michel-tricot) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java:78]: you should rename the variable as well.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java [hunk 4]
```diff
@@ -287,9 +287,14 @@ private Job getJob(DSLContext ctx, long jobId) {
   }
 
   @Override
-  public Optional<Job> getOldestPendingJob() throws IOException {
+  public Optional<Job> getNextJob() throws IOException {
```
Comment (michel-tricot) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:290]: This interface looks better.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java (hunk 2 above)
Comment (michel-tricot) [reply airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:291]: I agree with you that we might want to always resolve jobs that are not syncs. 

The question is: in what scenario can we have two sync jobs for the same config in a non terminal state? That doesn't seem right.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java (hunk 1 above)
Comment (michel-tricot) [reply airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java:146]: yep good name.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java (hunk 2 above)
Comment (michel-tricot) [reply airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:291]: Actually read through the issue. 

Why did you chose this option instead of having a conditional add when someone asks for a manual sync? and not do it if there is a sync running?

**Review by sherifnada — APPROVED** [review]

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java (hunk 2 above)
Comment (cgardens) [reply airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:291]: It is definitely important to enforce this inside the job submitter so we don't have undefined behavior. I want this invariant to be bullet proof at the core level.

Currently the only case this comes up is if the user hits the sync now button a bunch of times. I have no problem adding logic there as well that if something is already running, now job is added if we want to prevent queuing multiple jobs. I think there's some complexity there. If a user clicks "sync now" while a reset is running do we want to prevent them from queueing the job? It is not obvious to me that we do. 

Either the behavior is that every time you hit the "sync now" or "reset job" button we queue a job or when you hit those buttons we queue a job if it is allowed and provide an error message. no strong preference.

**Review by michel-tricot — APPROVED** [review]
