### PR TITLE
🐛 Fix bucket path for destination s3

### LINKED ISSUE #11482: S3 Destination ignoring s3_path_format argument
## Environment
- **Airbyte version**:  example is 0.35.59-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Destination Connector and version**: s3-destination 0.2.12
- **Severity**: medium
- **Step where error happened**: Sync job

## Current Behavior
After upgrading s3 destination connector from 0.2.10 to 0.2.12, the output ignoring argument `s3_bucket_path ` in s3 path.
```
S3 Bucket Name = bucket-example
s3_bucket_path = foo
ouput_path will be s3://bucket-example/${SOUCE_NAMESPACE}/${STREAM_NAME}
```

## Expected Behavior
output_path should be `s3://bucket-example/foo/${SOUCE_NAMESPACE}/${STREAM_NAME}`

## Steps to Reproduce
1. create a source
2. create destination and keep empty the field `s3_path_format`
3. create a connection and sync

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes https://github.com/airbytehq/airbyte/issues/11482

## How
Use s3_bucket_path when constructing the object path

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3ConsumerFactory.java [hunk 1]
```diff
@@ -80,26 +80,19 @@ public AirbyteMessageConsumer create(final Consumer<AirbyteMessage> outputRecord
       final AirbyteStream abStream = stream.getStream();
       final String namespace = abStream.getNamespace();
       final String streamName = abStream.getName();
-      final String outputNamespace = getOutputNamespace(abStream, config.get(BUCKET_PATH_FIELD).asText(), namingResolver);
-      final String customOutputFormat =
-          config.has(PATH_FORMAT_FIELD) && !config.get(PATH_FORMAT_FIELD).asText().isBlank() ? config.get(PATH_FORMAT_FIELD).asText()
-              : S3DestinationConstants.DEFAULT_PATH_FORMAT;
-      final String outputBucketPath = storageOperations.getBucketObjectPath(outputNamespace, streamName, SYNC_DATETIME, customOutputFormat);
+      final String bucketPath = config.get(BUCKET_PATH_FIELD).asText();
+      final String customOutputFormat = String.join("/",
```
Comment (Phlair) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3ConsumerFactory.java:84]: does `customOutputFormat` still make sense as the name here when we're including bucketPath?

**Review by Phlair — APPROVED** [review]
lgtm, just left a comment on var name

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3ConsumerFactory.java (hunk 1 above)
Comment (ChristopheDuong) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3ConsumerFactory.java:84]: you can still customize the end part of the bucket path

it just always starts with the bucketPath now
