### PR TITLE
`destination-redshift` should fail syncs if records or properties are too large, rather than silently skipping records and succeeding

### LINKED ISSUE #19990: Redshift reports successful sync after ignoring some of the records
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: ubuntu EC2
- **Deployment**: docker on a single instance but with RDS datastore
- **Source Connector and version**: airbyte/source-postgres 1.0.22
- **Destination Connector and version**: airbyte/destination-redshift 0.3.51
- **Step where error happened**: Sync job

## Current Behavior
I run a sync and when it completes I get the message
`Sync Succeeded 10,000,000 emitted records | 10,000,000 committed records`
However when I check the database I only have 9,986,326 rows.
When I check the log there's a message 
`A total of 13674 record(s) of data from stream AirbyteStreamNameNamespacePair{name='events_196', namespace='analytics_raw'} were invalid and were ignored.`

## Expected Behavior
I would expect the UI to tell me it was only a partial success! 
The UI should tell me how many rows were actually inserted to the destination (and ideally a way to retrieve the id's of the failures)

## Logs
The logs are attached in the [slack thread about this issue](https://airbytehq.slack.com/archives/C021JANJ6TY/p1668518421758359)

## Steps to Reproduce
1. create a postgres (or any?) source that contains a jsonb column that has more than 65535 characters stored in it
2. Run a sync (mine was raw not normalised)

## Root Cause
I did some digging and the root cause of the issue is that the SUPER column in Redshift can only store 65535 characters of data, so it overflows (more pronounced as the json from the source gets escaped which further increases its character count and all columns are combined into the _airbyte_data column).
The root cause (in this case) looks like it'll be fixed by a Redshift update [https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-redshift-sql-capabilities-speed-data-warehouse-migrations-preview/](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-redshift-sql-capabilities-speed-data-warehouse-migrations-preview/) 

I'm still raising the issue as it's the UI reporting of what happened that's the actual issue.

## Are you willing to submit a PR?
erm... I've never looked at the Airbyte source, it says Java and Python... If it's in a Python bit I _might_ be able to have a go if someone can point me in the right direction... but it might take a long while.

### PR DESCRIPTION
**Pull request by evantahler**
Closes https://github.com/airbytehq/airbyte/issues/19990, albiet in a less-than-ideal way.  At least now, users will be notified when source data won't fit in the destination.  From there, a view or other filtering mechanism on the source can be used to adjust the incoming records to fix within Redshift.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`116f297c83`](https://github.com/airbytehq/airbyte/pull/27993/commits/116f297c83cc41a6c844c9f016981bed9cafb94c)) - ❌

⏲️  Total pipeline duration: 30mn19s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688599944/116f297c83cc41a6c844c9f016981bed9cafb94c/destination-redshift/0.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`8398de38f4`](https://github.com/airbytehq/airbyte/pull/27993/commits/8398de38f4d889b5ab61eb1fb0b8ad47dd0d6905)) - ❌

⏲️  Total pipeline duration: 28mn55s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688629060/8398de38f4d889b5ab61eb1fb0b8ad47dd0d6905/destination-redshift/0.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Review by edgao — APPROVED** [review]
what do you think of keeping this behavior available as a config option? I'm nervous about sources that don't have the ability to do that sort of filtering

if not: We can also delete `implementsRecordSizeLimitChecks` and `testSyncVeryBigRecords` from DestinationAcceptanceTest / RedshiftStagingS3DestinationAcceptanceTest

either way - this diff lgtm

**Comment by evantahler** [comment]
Thanks for the review @edgao!

> what do you think of keeping this behavior available as a config option? I'm nervous about sources that don't have the ability to do that sort of filtering

Give the choice between the two options, I didn't want to go with a config option, because whenever possible I want the behavior of our destinations to match.  Snowflake and BQ have the same problem today, and one day we should holistically tackle this problem, rather than a piecemeal per-destination solution.

For example, once we get one-stream-one-table released (https://github.com/airbytehq/airbyte/issues/26028), we could add a feature to every destination that handles per-field and per-record size limitations.  We could just write the PK and cursor for the record, and then include an `_airbyte_medata.error = ['data for column "foo" too large']`.  This would work for every destination, and not require any config settings.  1s1t solves every problem ;)

**Comment by octavia-squidington-iii** [comment]
##  destination-oracle-strict-encrypt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 12mn27s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-oracle-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-oracle-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle-strict-encrypt test
```

File: airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java [hunk 1]
```diff
@@ -848,10 +840,6 @@ public void testIncrementalDedupeSync() throws Exception {
    */
   @Test
   void testSyncVeryBigRecords() throws Exception {
```
Comment (edgao) [inline airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java:842]: I think you need to delete this method entirely - previously all destinations except redshift were skipping it (and now we also want redshift to skip it)

**Comment by edgao** [comment]
sgtm :shipit:

**Comment by octavia-squidington-iii** [comment]
##  destination-pubsub test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 06mn46s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-pubsub/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-pubsub docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-pubsub:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-pubsub/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pubsub test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-vertica test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 01mn31s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-vertica/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-vertica/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-vertica test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mqtt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 07mn44s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mqtt/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-mqtt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mqtt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-mqtt/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mqtt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-azure-blob-storage test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 06mn30s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-azure-blob-storage/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build destination-azure-blob-storage docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-azure-blob-storage:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-azure-blob-storage/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-azure-blob-storage test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-keen test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 04mn47s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-keen/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-keen docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-keen:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-keen/0.2.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-keen test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-starburst-galaxy test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 12mn02s 

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-starburst-galaxy/metadata.yaml     | ✅        |
| Connector version semver check                                                          | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build destination-starburst-galaxy docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-starburst-galaxy:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-starburst-galaxy/0.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-starburst-galaxy test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-yugabytedb test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 11mn28s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-yugabytedb/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-yugabytedb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-yugabytedb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-yugabytedb/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-yugabytedb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-exasol test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 06mn57s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-exasol/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ❌        |
| Build connector tar                                                           | ✅        |
| Build destination-exasol docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-exasol:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-exasol/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-exasol test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-dev-null test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 03mn33s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dev-null/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dev-null docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dev-null:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-dev-null/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dev-null test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-snowflake test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 12mn38s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ❌        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-snowflake:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-snowflake:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-snowflake/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kafka test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 05mn28s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kafka/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-kafka docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kafka:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-kafka/0.1.10/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kafka test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kinesis test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 02mn29s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kinesis/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Build connector tar                                                            | ✅        |
| Build destination-kinesis docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kinesis:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-kinesis/0.1.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kinesis test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-elasticsearch-strict-encrypt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 05mn33s 

| Step                                                                                                | Result   |
|:----------------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-elasticsearch-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                                      | ✅        |
| QA checks                                                                                           | ✅        |
| Build connector tar                                                                                 | ✅        |
| Build destination-elasticsearch-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-elasticsearch-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-elasticsearch-strict-encrypt/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-elasticsearch-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 13mn27s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-databricks test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 07mn29s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-databricks/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-databricks docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-databricks:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-databricks/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-databricks test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-r2 test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 05mn01s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-r2/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build destination-r2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-r2:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-r2/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-r2 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-local-json test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 03mn58s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-local-json/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-local-json docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-local-json:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-local-json/0.2.11/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-local-json test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 10mn21s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-tidb test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 10mn11s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-tidb docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-tidb:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-tidb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-tidb/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-tidb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-clickhouse-strict-encrypt test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 08mn20s 

| Step                                                                                             | Result   |
|:-------------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-clickhouse-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                                   | ✅        |
| QA checks                                                                                        | ✅        |
| Build connector tar                                                                              | ✅        |
| Build destination-clickhouse-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-clickhouse:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-clickhouse-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-clickhouse-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-clickhouse-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-teradata test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 16mn17s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-teradata/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-teradata docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-teradata:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-teradata/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-teradata test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-scylla test report (commit [`8e65341d0e`](https://github.com/airbytehq/airbyte/pull/27993/commits/8e65341d0e088ca35b00482de4307241d153d545)) - ❌

⏲️  Total pipeline duration: 05mn01s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-scylla/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-scylla docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-scylla:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688668944/8e65341d0e088ca35b00482de4307241d153d545/destination-scylla/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-scylla test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ❌

⏲️  Total pipeline duration: 22mn24s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-selectdb test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ❌

⏲️  Total pipeline duration: 18mn57s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-selectdb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ❌        |
| Build connector tar                                                             | ✅        |
| Build destination-selectdb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-selectdb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-selectdb/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-selectdb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-dynamodb test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ✅

⏲️  Total pipeline duration: 15mn11s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-dynamodb/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-local-json test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ✅

⏲️  Total pipeline duration: 04mn28s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-local-json/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-local-json docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-local-json:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-local-json/0.2.11/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-local-json test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-vertica test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ❌

⏲️  Total pipeline duration: 01mn25s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-vertica/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-vertica/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-vertica test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-cassandra test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ❌

⏲️  Total pipeline duration: 07mn33s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-cassandra/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ✅        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-cassandra docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-cassandra:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-cassandra/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-cassandra test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-s3 test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ✅

⏲️  Total pipeline duration: 08mn46s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-s3/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build destination-s3 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-s3:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-s3/0.5.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-pubsub test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ✅

⏲️  Total pipeline duration: 14mn22s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-pubsub/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-pubsub docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-pubsub:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-pubsub/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pubsub test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redis test report (commit [`58f607f417`](https://github.com/airbytehq/airbyte/pull/27993/commits/58f607f417ee5a42197abf98769db00df43081a1)) - ❌

⏲️  Total pipeline duration: 04mn44s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redis/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-redis docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redis:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1688757893/58f607f417ee5a42197abf98769db00df43081a1/destination-redis/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redis test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-pulsar test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 16mn57s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-pulsar/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-pulsar docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-pulsar:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-pulsar/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pulsar test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 01mn33s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-redshift/0.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-doris test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 04mn14s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-doris/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ❌        |
| Build connector tar                                                          | ✅        |
| Build destination-doris docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-doris:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-doris/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-doris test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-dynamodb test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 16mn00s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-dynamodb/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 09mn16s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build destination-gcs docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-gcs:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-gcs/0.4.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-r2 test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 06mn01s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-r2/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build destination-r2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-r2:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-r2/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-r2 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-azure-blob-storage test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 08mn43s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-azure-blob-storage/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build destination-azure-blob-storage docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-azure-blob-storage:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-azure-blob-storage/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-azure-blob-storage test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-s3-glue test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 08mn58s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-s3-glue/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Build connector tar                                                            | ✅        |
| Build destination-s3-glue docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-s3-glue:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-s3-glue/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-s3-glue test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 41mn14s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-mysql/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redpanda test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 08mn40s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redpanda/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redpanda docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redpanda:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-redpanda/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redpanda test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-iceberg test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 533mn08s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-iceberg/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ❌        |
| Build connector tar                                                            | ✅        |
| Build destination-iceberg docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-iceberg:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-iceberg/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-iceberg test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 27mn31s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-bigquery/1.5.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-snowflake test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 38mn46s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ✅        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-snowflake:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-snowflake:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-snowflake/1.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kinesis test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 09mn37s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kinesis/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Build connector tar                                                            | ✅        |
| Build destination-kinesis docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kinesis:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-kinesis/0.1.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kinesis test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-csv test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ✅

⏲️  Total pipeline duration: 05mn33s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-csv/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build destination-csv docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-csv:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-csv/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-csv test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kafka test report (commit [`c6b4ef0732`](https://github.com/airbytehq/airbyte/pull/27993/commits/c6b4ef0732d3bcced8984e74453eb62098ac7ad8)) - ❌

⏲️  Total pipeline duration: 09mn46s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kafka/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-kafka docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kafka:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_redshift-fails-on-big-data/1689288781/c6b4ef0732d3bcced8984e74453eb62098ac7ad8/destination-kafka/0.1.10/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kafka test
```

**Comment by evantahler** [comment]
Enough of the tests for other connectors are passing, and the builds all seem to be OK... so... Merging!

**Comment by octavia-approvington** [comment]
It's time <br/> fine lets go

**Review by octavia-approvington — APPROVED** [review]

**Comment by alexnikitchuk** [comment]
> 



> Thanks for the review @edgao!
> 
> > what do you think of keeping this behavior available as a config option? I'm nervous about sources that don't have the ability to do that sort of filtering
> 
> Give the choice, I didn't want to go with a config option, because whenever possible I want the behavior of our destinations to match. Snowflake and BQ have the same problem today, and one day we should holistically tackle this problem, rather than a piecemeal per-destination solution.
> 
> For example, once we get one-stream-one-table released (#26028), we could add a feature to every destination that handles per-field and per-record size limitations. We could just write the PK and cursor for the record, and then include an `_airbyte_medata.error = ['data for column "foo" too large']`. This would work for every destination, and not require any config settings. 1s1t solves every problem ;)

This looks like a breaking change. IMO better to have the option to switch back to the old behavior.

**Comment by jablonskijakub** [comment]
thanks @evantahler for your PR. tbh I was not aware of the issue with Redshift's limits on SUPER type until I upgraded my connector to your version.
Unfortunately it is not quite a solution I would prefer as I need to load all rows from a source db and I was wondering if it would be possible to allow for copying if a row is < 1mb but varchar fields exceed the limit and blocking normalisation so that the data remains in the raw format? what could be a solution here otherwise?

**Comment by evantahler** [comment]
We've got a feature on the roadmap to use our new features in Destinations V2 (https://github.com/airbytehq/airbyte/issues/26028) to have a work around!  We'll import the columns we can, and include an error message, per-record, for any column which has a filed that is too large for the destination.

Would you prefer the too-large field with the error to have NULL or a truncated value?

**Comment by jablonskijakub** [comment]
sounds great! personally I would prefer to have it as NULL as then it would indicate that given field was too big for a destination and with a truncated value I suspect it might sl without being noticed.

If I understood you correctly Destinations V2 would be used instead on the normalisation step which is being used atm. I believe my issue is slightly different as my payload field is in a jsonb format and being read as a single string value (please correct me if I'm wrong) thus exceeding 65535 bytes for a single value within a SUPER data type.
