### PR TITLE
fix(iceberg): map NumberType to DecimalType to support deduplication

### LINKED ISSUE #63359: S3 Data Lake destination failing on several tables when deduping
### Connector Name

S3 Data Lake

### Connector Version

0.3.34

### What step the error happened?

During the sync

### Relevant information

Title: S3 Data Lake Destination - Equality-Delete Writer Fails with Perfect Primary Key Data, This does not happen on all streams in my source, just some of them.

Component: S3 Data Lake Destination (version 0.3.34)
Severity: High (Breaks core deduplication functionality)

Description:
The equality-delete writer consistently fails with "Equality field ids shouldn't be null or empty" error, even with perfect primary key data.

Evidence:
- Data Quality: 52,071 records, 52,071 unique "Entry_No" (number) pkey values, 0 nulls, 0 duplicates
- Fresh stream test: Same error with completely new stream
- Workaround: Only Full Refresh Overwrite works
- Impact: All deduplication modes fail for some tables but not others

Expected: Deduplication should work with unique, non-null primary keys
Actual: Equality-delete writer fails regardless of data quality

Workaround: Use Full Refresh Overwrite mode, however this is not an option for tables that i need to do incremental deduping (3+ million records)

### Relevant log output

```shell
2025-07-17 14:19:05 info APPLY Stage: BUILD — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info APPLY Stage: CLAIM — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info Claimed: true for 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check via API for 5d2222c2-b60a-4e89-96c3-f0d2bdc79704
2025-07-17 14:19:05 info APPLY Stage: LOAD_SHED — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info APPLY Stage: CHECK_STATUS — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info No pod found running for workload 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check
2025-07-17 14:19:05 info APPLY Stage: MUTEX — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info No mutex key specified for workload: 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check. Continuing...
2025-07-17 14:19:05 info APPLY Stage: ARCHITECTURE — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info APPLY Stage: LAUNCH — (workloadId=83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check)
2025-07-17 14:19:05 info [initContainer] image: airbyte/workload-init-container:1.7.1 resources: ResourceRequirements(claims=[], limits={}, requests={}, additionalProperties={})
2025-07-17 14:19:14 info Attempting to update workload: 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check to LAUNCHED.
2025-07-17 14:19:14 info Pipeline completed for workload: 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check.
2025-07-17 14:19:18 info 
2025-07-17 14:19:18 info ----- START CHECK -----
2025-07-17 14:19:18 info 
2025-07-17 14:19:21 info Connector exited, processing output
2025-07-17 14:19:21 info Output file jobOutput.json found
2025-07-17 14:19:21 info Connector exited with exit code 0
2025-07-17 14:19:21 info Reading messages from protocol version 0.2.0
2025-07-17 14:19:21 info Check succeeded
2025-07-17 14:19:21 info Checking for optional control message...
2025-07-17 14:19:21 info Writing output of 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check to the doc store
2025-07-17 14:19:21 info Marking workload 83b6fdcf-2574-440f-af64-5e96d65da3b4_796_0_check as successful
2025-07-17 14:19:21 info 
2025-07-17 14:19:21 info Deliberately exiting process with code 0.
2025-07-17 14:19:21 info ----- END CHECK -----
2025-07-17 14:19:21 info 
2025-07-17 14:19:23 info APPLY Stage: BUILD — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info APPLY Stage: CLAIM — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info Claimed: true for 716ca874-520b-4902-9f80-9fad66754b89_796_0_check via API for 5d2222c2-b60a-4e89-96c3-f0d2bdc79704
2025-07-17 14:19:23 info APPLY Stage: LOAD_SHED — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info APPLY Stage: CHECK_STATUS — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info No pod found running for workload 716ca874-520b-4902-9f80-9fad66754b89_796_0_check
2025-07-17 14:19:23 info APPLY Stage: MUTEX — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info No mutex key specified for workload: 716ca874-520b-4902-9f80-9fad66754b89_796_0_check. Continuing...
2025-07-17 14:19:23 info APPLY Stage: ARCHITECTURE — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info APPLY Stage: LAUNCH — (workloadId=716ca874-520b-4902-9f80-9fad66754b89_796_0_check)
2025-07-17 14:19:23 info [initContainer] image: airbyte/workload-init-container:1.7.1 resources: ResourceRequirements(claims=[], limits={}, requests={}, additionalProperties={})
2025-07-17 14:19:31 info Attempting to update workload: 716ca874-520b-4902-9f80-9fad66754b89_796_0_check to LAUNCHED.
2025-07-17 14:19:31 info Pipeline completed for workload: 716ca874-520b-4902-9f80-9fad66754b89_796_0_check.
2025-07-17 14:19:36 info 
2025-07-17 14:19:36 info ----- START CHECK -----
2025-07-17 14:19:36 info 
2025-07-17 14:19:37 info Connector exited, processing output
2025-07-17 14:19:37 info Output file jobOutput.json found
2025-07-17 14:19:37 info Connector exited with exit code 0
2025-07-17 14:19:37 info Reading messages from protocol version 0.2.0
2025-07-17 14:19:38 info INFO main i.m.c.e.DefaultEnvironment(<init>):168 Established active environments: [k8s, cloud, cli, destination, aws, connector]
2025-07-17 14:19:38 info INFO main i.a.c.AirbyteConnectorRunnable(run):33 Executing class io.airbyte.cdk.load.check.CheckOperation operation.
2025-07-17 14:19:38 info INFO main i.a.c.l.t.i.p.i.IcebergUtil(createTable):139 Creating Iceberg table 'airbyte_test_namespace.airbyte_test_table'....
2025-07-17 14:19:38 info INFO main o.a.i.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder(tableDefaultProperties):266 Table properties set at catalog level through catalog properties: {}
2025-07-17 14:19:38 info INFO main o.a.i.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder(tableOverrideProperties):280 Table properties enforced at catalog level through catalog properties: {}
2025-07-17 14:19:38 info INFO main o.a.i.BaseMetastoreTableOperations(commit):129 Successfully committed to table airbyte.airbyte_test_namespace.airbyte_test_table in 514 ms
2025-07-17 14:19:38 info INFO main o.a.i.BaseMetastoreTableOperations(refreshFromMetadataLocation):189 Refreshing table metadata from new version: s3://datahalla/bronze/airbyte_test_table/metadata/00000-5d5b97b3-1764-473e-88a5-2a40497fecf0.metadata.json
2025-07-17 14:19:38 info INFO main o.a.i.BaseMetastoreTableOperations(refreshFromMetadataLocation):189 Refreshing table metadata from new version: s3://datahalla/bronze/airbyte_test_table/metadata/00000-5d5b97b3-1764-473e-88a5-2a40497fecf0.metadata.json
2025-07-17 14:19:38 info INFO main o.a.i.a.g.GlueCatalog(dropTable):357 Successfully dropped table airbyte_test_namespace.airbyte_test_table from Glue
2025-07-17 14:19:38 info INFO main o.a.i.CatalogUtil(dropTableData):109 Manifests to delete: 
2025-07-17 14:19:38 info INFO main o.a.i.a.g.GlueCatalog(dropTable):360 Glue table airbyte_test_namespace.airbyte_test_table data purged
2025-07-17 14:19:38 info INFO main o.a.i.a.g.GlueCatalog(dropTable):362 Dropped table: airbyte_test_namespace.airbyte_test_table
2025-07-17 14:19:38 info INFO main i.a.c.AirbyteConnectorRunnable(run):46 Flushing output consumer prior to shutdown.
2025-07-17 14:19:38 info INFO main i.a.c.AirbyteConnectorRunnable(run):48 Completed integration: airbyte/destination-s3-data-lake.
2025-07-17 14:19:38 info Checking for optional control message...
2025-07-17 14:19:38 info Writing output of 716ca874-520b-4902-9f80-9fad66754b89_796_0_check to the doc store
2025-07-17 14:19:38 info Marking workload 716ca874-520b-4902-9f80-9fad66754b89_796_0_check as successful
2025-07-17 14:19:38 info 
2025-07-17 14:19:38 info Deliberately exiting process with code 0.
2025-07-17 14:19:38 info ----- END CHECK -----
2025-07-17 14:19:38 info 
2025-07-17 14:19:41 info Starting async replication
2025-07-17 14:19:41 info Creating workload 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync
2025-07-17 14:19:42 info APPLY Stage: BUILD — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info APPLY Stage: CLAIM — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info Claimed: true for 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync via API for 5d2222c2-b60a-4e89-96c3-f0d2bdc79704
2025-07-17 14:19:42 info APPLY Stage: LOAD_SHED — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info APPLY Stage: CHECK_STATUS — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info No pod found running for workload 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync
2025-07-17 14:19:42 info APPLY Stage: MUTEX — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info Mutex key: 5476131c-c4a0-463c-b665-1d475c5d4504 specified for workload: 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync. Attempting to delete existing pods...
2025-07-17 14:19:42 info Existing pods for mutex key: 5476131c-c4a0-463c-b665-1d475c5d4504 deleted.
2025-07-17 14:19:42 info APPLY Stage: ARCHITECTURE — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info APPLY Stage: LAUNCH — (workloadId=5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync)
2025-07-17 14:19:42 info [initContainer] image: airbyte/workload-init-container:1.7.1 resources: ResourceRequirements(claims=[], limits={memory=8Gi, cpu=4}, requests={memory=4Gi, cpu=2}, additionalProperties={})
2025-07-17 14:19:42 info Launching replication pod: replication-job-796-attempt-0 (selectors = {eks.amazonaws.com/compute-type=auto}) with containers:
2025-07-17 14:19:42 info [source] image: airbyte/source-declarative-manifest:6.59.1 resources: ResourceRequirements(claims=[], limits={memory=8Gi, cpu=4}, requests={memory=4Gi, cpu=2}, additionalProperties={})
2025-07-17 14:19:42 info [destination] image: airbyte/destination-s3-data-lake:0.3.34 resources: ResourceRequirements(claims=[], limits={memory=8Gi, cpu=4}, requests={memory=4Gi, cpu=2}, additionalProperties={})
2025-07-17 14:19:42 info [orchestrator] image: airbyte/container-orchestrator:1.7.1 resources: ResourceRequirements(claims=[], limits={memory=8Gi, cpu=4}, requests={memory=4Gi, cpu=2}, additionalProperties={})
2025-07-17 14:19:51 info Attempting to update workload: 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync to LAUNCHED.
2025-07-17 14:19:51 info Pipeline completed for workload: 5476131c-c4a0-463c-b665-1d475c5d4504_796_0_sync.
2025-07-17 14:19:57 info Running replication worker...
2025-07-17 14:19:58 info Starting replication worker. job id: 796 attempt: 0
2025-07-17 14:19:58 info 
2025-07-17 14:19:58 info ----- START REPLICATION -----
2025-07-17 14:19:58 info 
2025-07-17 14:19:58 info Running destination...
2025-07-17 14:19:58 info Writing messages to protocol version 0.2.0
2025-07-17 14:19:58 info Reading messages from protocol version 0.2.0
2025-07-17 14:19:58 info Reading messages from protocol version 0.2.0
2025-07-17 14:19:58 info Starting workload heartbeat
2025-07-17 14:19:58 info SourceReader started.
2025-07-17 14:19:58 info DestinationWriter started.
2025-07-17 14:19:58 info MessageProcessor started.
2025-07-17 14:19:58 info DestinationReader started.
2025-07-17 14:19:58 info INFO main i.m.c.e.DefaultEnvironment(<init>):168 Established active environments: [k8s, cloud, cli, destination, aws, connector]
2025-07-17 14:19:59 warn WARN main c.k.j.j.JsonSchemaGenerator$MyJsonFormatVisitorWrapper(expectAnyFormat):725 Not able to generate jsonSchema-info for type: [simple type, class com.fasterxml.jackson.databind.JsonNode] - probably using custom serializer which does not override acceptJsonFormatVisitor
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DataChannelBeanFactory(dataChannelMedium):60 Using data channel medium STDIO
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DataChannelBeanFactory(namespaceMapper):310 Going to use the given source value: SOURCE for namespace
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DestinationCatalog(<init>):49 Destination catalog initialized: [DestinationStream(unmappedNamespace=null, unmappedName=CustomerAttrValueQuery_Schema_Edit, importType=Dedupe(primaryKey=[[ID]], cursor=[]), schema=ObjectType(properties={ID=FieldType(type=NumberType, nullable=true), Value=FieldType(type=StringType, nullable=true), Blocked=FieldType(type=BooleanType, nullable=true), SystemId=FieldType(type=StringType, nullable=true), DateValue=FieldType(type=StringType, nullable=true), AttributeID=FieldType(type=NumberType, nullable=true), NumericValue=FieldType(type=NumberType, nullable=true), AttributeName=FieldType(type=StringType, nullable=true)}, additionalProperties=true, required=[]), generationId=3, minimumGenerationId=3, syncId=796, isFileBased=false, includeFiles=false, destinationObjectName=null, matchingKey=null, namespaceMapper=io.airbyte.cdk.load.command.NamespaceMapper@71b8e428)]
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DataChannelBeanFactory(logPerNRecords):137 Logging every 100000 records
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DataChannelBeanFactory(dataChannelSocketPaths):69 Using socket paths []
2025-07-17 14:19:59 info INFO main i.a.c.l.s.PipelineEventBookkeepingRouter(<init>):75 Creating bookkeeping router for 1 data channels
2025-07-17 14:19:59 info INFO main i.a.c.l.c.DataChannelBeanFactory(dataChannelFormat):79 Using data channel format JSONL
2025-07-17 14:19:59 info INFO main i.a.c.AirbyteConnectorRunnable(run):33 Executing class io.airbyte.cdk.load.write.WriteOperation operation.
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):158 Starting input consumer task
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):163 Starting startup task
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-1 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.internal.InputConsumerTask@31f72a10)
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.implementor.SetupTask@1498d333)
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):167 Launching open stream task 0
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):171 Setting up load pipeline
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-1 i.a.c.l.t.i.InputConsumerTask(execute):84 Starting consuming messages from the input flow
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-2 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.implementor.OpenStreamTask@2e505d83)
2025-07-17 14:19:59 info INFO main i.a.c.l.p.DirectLoadPipelineStep(taskForPartition):40 Creating DirectLoad pipeline step task for partition 0
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-1 i.a.c.l.t.i.ReservingDeserializingInputFlow(collect):32 Reserved 2457mb memory for input processing
2025-07-17 14:19:59 info INFO main i.a.c.l.p.DirectLoadPipelineStep(taskForPartition):40 Creating DirectLoad pipeline step task for partition 1
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-5 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(LoadPipelineStepTask(DirectLoadRecordAccumulator, part=0))
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):173 Launching update batch task
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):176 Launching heartbeat task
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-8 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.internal.UpdateBatchStateTask@e25aac5)
2025-07-17 14:19:59 info INFO main i.a.c.l.t.DestinationTaskLauncher(run):185 Starting checkpoint update task
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-2 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.internal.HeartbeatTask@5ae021bd)
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-4 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(LoadPipelineStepTask(DirectLoadRecordAccumulator, part=1))
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-6 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.internal.UpdateCheckpointsTask@1a98d203)
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-6 i.a.c.l.t.i.UpdateCheckpointsTask(execute):33 Starting to consume checkpoint messages (state) for updating
2025-07-17 14:19:59 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(io.airbyte.cdk.load.task.implementor.SetupTask@1498d333) completed
2025-07-17 14:20:03 info Starting syncing
2025-07-17 14:20:03 info Marking stream CustomerAttrValueQuery_Schema_Edit as STARTED
2025-07-17 14:20:03 info Syncing stream: CustomerAttrValueQuery_Schema_Edit 
2025-07-17 14:20:03 info Marking stream CustomerAttrValueQuery_Schema_Edit as RUNNING
2025-07-17 14:20:03 info Stream status TRACE received of status: STARTED for stream CustomerAttrValueQuery_Schema_Edit
2025-07-17 14:20:03 info Sending update for CustomerAttrValueQuery_Schema_Edit - null -> RUNNING
2025-07-17 14:20:03 info Stream Status Update Received: CustomerAttrValueQuery_Schema_Edit - RUNNING
2025-07-17 14:20:03 info Creating status: CustomerAttrValueQuery_Schema_Edit - RUNNING
2025-07-17 14:20:03 info Read 38 records from CustomerAttrValueQuery_Schema_Edit stream
2025-07-17 14:20:03 info Marking stream CustomerAttrValueQuery_Schema_Edit as STOPPED
2025-07-17 14:20:03 info Finished syncing CustomerAttrValueQuery_Schema_Edit
2025-07-17 14:20:03 info Finished syncing
2025-07-17 14:20:03 info Stream status TRACE received of status: RUNNING for stream CustomerAttrValueQuery_Schema_Edit
2025-07-17 14:20:03 info Stream status TRACE received of status: COMPLETE for stream CustomerAttrValueQuery_Schema_Edit
2025-07-17 14:20:03 info Total records read: (6 KB)
2025-07-17 14:20:03 info Schema validation was performed to a max of 10 records with errors per stream.
2025-07-17 14:20:03 info SourceReader finished.
2025-07-17 14:20:03 info MessageProcessor finished.
2025-07-17 14:20:03 info DestinationWriter finished.
2025-07-17 14:20:03 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(handleStreamMessage):85 Saw first record for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit); awaiting setup complete
2025-07-17 14:20:03 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(handleStreamMessage):89 Setup complete, starting stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 o.a.i.BaseMetastoreTableOperations(refreshFromMetadataLocation):189 Refreshing table metadata from new version: s3://datahalla/bronze/bc/customerattrvaluequery_schema_edit/metadata/00001-10a7313e-87d3-480a-a0b4-daf72d97cab3.metadata.json
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 o.a.i.BaseMetastoreCatalog(loadTable):69 Table loaded by catalog: airbyte.bc.customerattrvaluequery_schema_edit
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.i.p.i.IcebergUtil(createTable):147 Loading Iceberg table bc.customerattrvaluequery_schema_edit ...
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 o.a.i.BaseMetastoreTableOperations(refreshFromMetadataLocation):189 Refreshing table metadata from new version: s3://datahalla/bronze/bc/customerattrvaluequery_schema_edit/metadata/00001-10a7313e-87d3-480a-a0b4-daf72d97cab3.metadata.json
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 o.a.i.BaseMetastoreCatalog(loadTable):69 Table loaded by catalog: airbyte.bc.customerattrvaluequery_schema_edit
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 i.a.i.d.s.S3DataLakeStreamLoader(start):75 maybe creating branch airbyte_staging for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 i.a.i.d.s.S3DataLakeStreamLoader(start):80 branch airbyte_staging already exists for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(handleStreamMessage):92 Initialization for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit) complete
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-9 i.a.i.d.s.S3DataLakeDirectLoaderFactory(create):39 Creating direct loader for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 i.a.i.d.s.S3DataLakeDirectLoaderFactory(create):39 Creating direct loader for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(handleStreamMessage):113 Read COMPLETE for stream Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.t.i.ReservingDeserializingInputFlow(collect):55 Finished processing input
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-2 i.a.c.l.t.i.UpdateCheckpointsTask$execute$3(emit):38 Updating stream checkpoint Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit):CheckpointKey(checkpointIndex=CheckpointIndex(value=1), checkpointId=CheckpointId(value=1)):Stats(recordCount=38, rejectedRecordCount=0)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(close):225 Maybe closing bookkeeping router 1
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.s.PipelineEventBookkeepingRouter(close):244 Closing internal control channels
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-2 i.a.c.l.s.CheckpointManager(addStreamCheckpoint):111 Added checkpoint for stream: Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit) at index: CheckpointKey(checkpointIndex=CheckpointIndex(value=1), checkpointId=CheckpointId(value=1))
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.m.MultiProducerChannel(close):26 Closing producer fileMessageQueue (active count=0, initialized count: 1)
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.m.MultiProducerChannel(close):30 Closing underlying queue
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-2 i.a.c.l.t.i.UpdateCheckpointsTask(execute):60 All checkpoints (state) updated
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-6 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(io.airbyte.cdk.load.task.implementor.OpenStreamTask@2e505d83) completed
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-1 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(io.airbyte.cdk.load.task.internal.InputConsumerTask@31f72a10) completed
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-2 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(io.airbyte.cdk.load.task.internal.UpdateCheckpointsTask@1a98d203) completed
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-9 o.a.h.i.c.CodecPool(getCompressor):153 Got brand-new compressor [.zstd]
2025-07-17 14:20:05 info INFO DefaultDispatcher-worker-3 o.a.h.i.c.CodecPool(getCompressor):153 Got brand-new compressor [.zstd]
2025-07-17 14:20:06 error ERROR DefaultDispatcher-worker-9 i.a.c.l.t.DestinationTaskLauncher$WrappedTask(execute):129 Caught exception in task LoadPipelineStepTask(DirectLoadRecordAccumulator, part=1) java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[iceberg-bundled-guava-1.7.0.jar:?]
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148) ~[iceberg-data-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120) ~[iceberg-core-1.7.0.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30) ~[bulk-cdk-core-load-0.537.jar:?]
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217) ~[bulk-cdk-core-load-0.537.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-2.1.10.jar:2.1.10-release-473]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]

Stack Trace: java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513)
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23)
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30)
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

2025-07-17 14:20:06 error ERROR DefaultDispatcher-worker-3 i.a.c.l.t.DestinationTaskLauncher$WrappedTask(execute):129 Caught exception in task LoadPipelineStepTask(DirectLoadRecordAccumulator, part=0) java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[iceberg-bundled-guava-1.7.0.jar:?]
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148) ~[iceberg-data-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120) ~[iceberg-core-1.7.0.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30) ~[bulk-cdk-core-load-0.537.jar:?]
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217) ~[bulk-cdk-core-load-0.537.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-2.1.10.jar:2.1.10-release-473]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704) [kotlinx-coroutines-core-jvm-1.10.2.jar:?]

Stack Trace: java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513)
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23)
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30)
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.DestinationTaskLauncher$WrappedTask(execute):133 Skipping exception handling, because it has already run.
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(LoadPipelineStepTask(DirectLoadRecordAccumulator, part=0)) completed
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-9 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(LoadPipelineStepTask(DirectLoadRecordAccumulator, part=1)) completed
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching io.airbyte.cdk.load.task.implementor.FailStreamTask@4fd4f42b
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-9 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):34 Launching TaskWrapper(io.airbyte.cdk.load.task.implementor.FailSyncTask@49a4f54d)
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task io.airbyte.cdk.load.task.implementor.FailStreamTask@4fd4f42b completed
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-9 i.a.c.l.t.i.FailSyncTask(execute):37 Calling teardown with failure result DestinationFailure(cause=java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer, streamResults={Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)=StreamProcessingFailed(streamException=java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer)})
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-9 i.a.c.l.t.TaskScopeProvider$launch$job$1(invokeSuspend):36 Task TaskWrapper(io.airbyte.cdk.load.task.implementor.FailSyncTask@49a4f54d) completed
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider(kill):59 Failing, killing input tasks and canceling long-running tasks
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-3 i.a.c.l.t.DestinationTaskLauncher$WrappedTask(execute):126 Task io.airbyte.cdk.load.task.internal.HeartbeatTask@5ae021bd was cancelled.
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider(kill):64 Cancelled killable tasks, waiting 600000ms for remaining tasks to complete
2025-07-17 14:20:06 info INFO DefaultDispatcher-worker-9 i.a.c.l.t.DestinationTaskLauncher$WrappedTask(execute):126 Task io.airbyte.cdk.load.task.internal.UpdateBatchStateTask@e25aac5 was cancelled.
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):69 Waiting for TaskWrapper(io.airbyte.cdk.load.task.implementor.OpenStreamTask@2e505d83) to complete
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):71 Task completed
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):69 Waiting for TaskWrapper(io.airbyte.cdk.load.task.implementor.FailSyncTask@49a4f54d) to complete
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):71 Task completed
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):69 Waiting for io.airbyte.cdk.load.task.implementor.FailStreamTask@4fd4f42b to complete
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):71 Task completed
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):69 Waiting for TaskWrapper(io.airbyte.cdk.load.task.implementor.SetupTask@1498d333) to complete
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):71 Task completed
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):69 Waiting for TaskWrapper(io.airbyte.cdk.load.task.internal.UpdateCheckpointsTask@1a98d203) to complete
2025-07-17 14:20:06 info INFO main i.a.c.l.t.TaskScopeProvider$kill$6(invokeSuspend):71 Task completed
2025-07-17 14:20:06 info INFO main i.a.c.l.w.WriteOperation$execute$1(invokeSuspend):68 Destination failed with stream results {Descriptor(namespace=null, name=CustomerAttrValueQuery_Schema_Edit)=StreamProcessingFailed(streamException=java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer)}
2025-07-17 14:20:06 error ERROR main i.a.c.AirbyteConnectorRunnable(run):36 Failed class io.airbyte.cdk.load.write.WriteOperation operation execution. java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[iceberg-bundled-guava-1.7.0.jar:?]
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148) ~[iceberg-data-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134) ~[iceberg-core-1.7.0.jar:?]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120) ~[iceberg-core-1.7.0.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83) ~[bulk-cdk-toolkit-load-iceberg-parquet-0.537.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-data-lake.jar:?]
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30) ~[bulk-cdk-core-load-0.537.jar:?]
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217) ~[bulk-cdk-core-load-0.537.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-2.1.10.jar:2.1.10-release-473]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704) ~[kotlinx-coroutines-core-jvm-1.10.2.jar:?]

Stack Trace: java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513)
	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165)
	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44)
	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23)
	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30)
	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

2025-07-17 14:20:06 info INFO main i.a.c.AirbyteConnectorRunnable(run):46 Flushing output consumer prior to shutdown.
2025-07-17 14:20:06 info INFO main i.a.c.AirbyteConnectorRunnable(run):48 Completed integration: airbyte/destination-s3-data-lake.
2025-07-17 14:20:06 error java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer
2025-07-17 14:20:06 error 	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513)
2025-07-17 14:20:06 error 	at org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134)
2025-07-17 14:20:06 error 	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83)
2025-07-17 14:20:06 error 	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44)
2025-07-17 14:20:06 error 	at io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30)
2025-07-17 14:20:06 error 	at io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
2025-07-17 14:20:06 error 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
2025-07-17 14:20:06 error 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
2025-07-17 14:20:06 error DestinationReader error: 
2025-07-17 14:20:06 info DestinationReader finished.
2025-07-17 14:20:06 error runJobs failed; recording failure but continuing to finish.
2025-07-17 14:20:06 info Closing StateCheckSumCountEventHandler
2025-07-17 14:20:06 info Sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1752779996808,
  "endTime" : 1752780006449,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 6840,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1752779998061,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 38,
    "recordsCommitted" : 0,
    "recordsFilteredOut" : 0,
    "bytesFilteredOut" : 0,
    "replicationEndTime" : 1752780006446,
    "replicationStartTime" : 1752779996808,
    "sourceReadEndTime" : 1752780003459,
    "sourceReadStartTime" : 1752779998062,
    "sourceStateMessagesEmitted" : 1
  },
  "streamStats" : [ {
    "streamName" : "CustomerAttrValueQuery_Schema_Edit",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 6840,
      "recordsEmitted" : 38,
      "recordsCommitted" : 0,
      "recordsFilteredOut" : 0,
      "bytesFilteredOut" : 0
    }
  } ],
  "performanceMetrics" : { }
}
2025-07-17 14:20:06 info Failures: [ {
  "failureOrigin" : "destination",
  "failureType" : "system_error",
  "internalMessage" : "java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer",
  "externalMessage" : "Equality field ids shouldn't be null or empty when creating equality-delete writer",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 796,
    "from_trace_message" : true,
    "connector_command" : "write"
  },
  "stacktrace" : "java.lang.IllegalStateException: Equality field ids shouldn't be null or empty when creating equality-delete writer\n\tat org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:513)\n\tat org.apache.iceberg.data.GenericAppenderFactory.newEqDeleteWriter(GenericAppenderFactory.java:148)\n\tat org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:408)\n\tat org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.newWriter(BaseTaskWriter.java:401)\n\tat org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.openCurrent(BaseTaskWriter.java:333)\n\tat org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.<init>(BaseTaskWriter.java:295)\n\tat org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.<init>(BaseTaskWriter.java:403)\n\tat org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:134)\n\tat org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.<init>(BaseTaskWriter.java:120)\n\tat io.airbyte.cdk.load.toolkits.iceberg.parquet.io.BaseDeltaTaskWriter$RowDataDeltaWriter.<init>(BaseDeltaTaskWriter.java:114)\n\tat io.airbyte.cdk.load.toolkits.iceberg.parquet.io.UnpartitionedDeltaWriter.<init>(UnpartitionedWriters.kt:44)\n\tat io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.newDeltaWriter(IcebergTableWriterFactory.kt:165)\n\tat io.airbyte.cdk.load.toolkits.iceberg.parquet.io.IcebergTableWriterFactory.create(IcebergTableWriterFactory.kt:83)\n\tat io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:44)\n\tat io.airbyte.integrations.destination.s3_data_lake.S3DataLakeDirectLoaderFactory.create(S3DataLakeDirectLoader.kt:23)\n\tat io.airbyte.cdk.load.pipeline.DirectLoadRecordAccumulator.start(DirectLoadRecordAccumulator.kt:30)\n\tat io.airbyte.cdk.load.task.internal.LoadPipelineStepTask$execute$$inlined$fold$1.emit(Reduce.kt:217)\n\tat kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)\n\tat kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)\n\tat kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)\n\tat kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)\n\tat kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)\n",
  "timestamp" : 1752780006281
}, {
  "failureOrigin" : "destination",
  "internalMessage" : "Destination process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the destination connector",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 796,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1\n\tat io.airbyte.container.orchestrator.worker.DestinationReader.run(ReplicationTask.kt:54)\n\tat io.airbyte.container.orchestrator.worker.DestinationReader$run$1.invokeSuspend(ReplicationTask.kt)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1752780006446
} ]
2025-07-17 14:20:06 info Closing io.micronaut.context.propagation.instrument.execution.ExecutorServiceInstrumenter$2@14b5752f
2025-07-17 14:20:06 info Closing io.airbyte.container.orchestrator.worker.io.LocalContainerAirbyteDestination@b94703b
2025-07-17 14:20:06 info 
2025-07-17 14:20:06 info ----- END REPLICATION -----
2025-07-17 14:20:06 info 
2025-07-17 14:20:06 error Error closing resource io.airbyte.container.orchestrator.worker.io.LocalContainerAirbyteDestination@b94703b; recording failure but continuing.
2025-07-17 14:20:06 info Closing io.airbyte.container.orchestrator.worker.io.LocalContainerAirbyteSource@34f23816
2025-07-17 14:20:06 info Closing io.airbyte.container.orchestrator.worker.RecordSchemaValidator@6736f40f
2025-07-17 14:20:06 info Closing io.airbyte.container.orchestrator.persistence.SyncPersistenceImpl@12f9f896
2025-07-17 14:20:06 info Returning output...
2025-07-17 14:20:07 info 
----- START POST REPLICATION OPERATIONS -----


2025-07-17 14:20:07 info No post-replication operation(s) to perform.
2025-07-17 14:20:07 info 
----- END POST REPLICATION OPERATIONS -----


2025-07-17 14:20:08 info Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, successivePartialFailureLimit=1000, totalCompleteFailureLimit=10, totalPartialFailureLimit=20, successiveCompleteFailures=1, successivePartialFailures=0, totalCompleteFailures=1, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
```

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by lleadbet**
## What

Maps Airbyte `NumberType` to Iceberg `DecimalType(38, 18)` instead of `DoubleType` for **all fields**. This fixes [#63359](https://github.com/airbytehq/airbyte/issues/63359), where S3/GCS Data Lake destinations fail with `Equality field ids shouldn't be null or empty` when all primary keys are `NumberType`.

**Root cause:** Iceberg disallows `DoubleType`/`FloatType` as identifier fields (floating-point equality is unreliable). The CDK silently excluded these from identifier fields, causing an empty identifier set when all PKs were `NumberType` → `DoubleType`.

**This is a breaking change** — all `NumberType` columns change from `DoubleType` to `DecimalType(38, 18)` on next sync. `DecimalType` preserves numeric semantics (SUM, AVG, ORDER BY, comparisons work natively) and is allowed as an Iceberg identifier field per [the spec](https://iceberg.apache.org/spec/).

Requested by: @lleadbet
[Devin session](https://app.devin.ai/sessions/5a4d676a65fe4fc39167721d2a487be4)

Closes: https://github.com/airbytehq/airbyte/issues/63359

## How

1. **`AirbyteTypeToIcebergSchema.kt`** — `convert()` now maps `NumberType` → `Types.DecimalType.of(38, 18)` universally (was `DoubleType`).
2. **`AirbyteValueToIcebergRecord.kt`** — `NumberValue` conversion checks the target Iceberg type: if `DECIMAL`, returns the raw `BigDecimal` value directly; otherwise falls back to `toDouble()`.
3. **`IcebergSuperTypeFinder.kt`** — Removed `DECIMAL` from `unsupportedTypeIds`. Added decimal precision widening logic (Iceberg allows widening precision with same scale).
4. **`IcebergTypesComparator.kt`** — Added `DECIMAL` case to `typesAreEqual()` that compares precision and scale.
5. **`IcebergWriteTest.kt`** — Fixed pre-existing flaky `testAppendSchemaEvolution` by using distinct `extractedAt` values for deterministic sort order.
6. **Tests** — Added tests verifying NumberType → DecimalType mapping, decimal equality, precision widening, and different scale/precision comparisons.

> **Note:** This PR contains only CDK changes. The GCS Data Lake connector (`GcsDataLakeAggregate.kt`) also needs a corresponding update, but must be done in a separate connector PR per CI policy.

### Updates since last revision
- **Applied DecimalType universally** per @benmoriceau and @subodh1810 consensus. Initially scoped to PK fields only per @tryangul feedback, then expanded to universal per reviewer alignment.
- Previous revision: **Switched from StringType to DecimalType** per @subodh1810's review feedback.
- Previous revision: **Added Decimal support to schema evolution utilities**: `IcebergSuperTypeFinder` and `IcebergTypesComparator` now handle `DecimalType` properly.

## Review guide

1. `AirbyteTypeToIcebergSchema.kt` — Universal NumberType → DecimalType(38, 18) mapping in `convert()` (~1 line change)
2. `AirbyteValueToIcebergRecord.kt` — Type-aware NumberValue → BigDecimal conversion (~5 lines)
3. `IcebergSuperTypeFinder.kt` — Remove DECIMAL from unsupported, add precision widening (~15 lines)
4. `IcebergTypesComparator.kt` — Add DECIMAL equality check (~8 lines)
5. `IcebergWriteTest.kt` — Flaky test fix using distinct extractedAt values (~2 lines)
6. Test files — All NumberType expectations updated to DecimalType(38, 18)

**⚠️ Items for reviewer attention:**

- **Schema evolution from DoubleType → DecimalType for ALL NumberType columns:** Iceberg's `TypeUtil.isPromotionAllowed` likely does NOT allow `Double` → `Decimal` promotion. Existing tables with ANY `NumberType` columns (currently `DoubleType`) will need full refresh or manual column migration. This affects ALL connections using NumberType fields, not just those with NumberType PKs.
- **Decimal precision/scale limits:** `Decimal(38, 18)` provides 20 integer digits and 18 fractional digits. Max value: ~10^20. Is this sufficient for all use cases? Airbyte `NumberType` is backed by `BigDecimal` which has arbitrary precision. Values exceeding this range will be truncated or rejected.
- **BigDecimal → Iceberg Decimal conversion:** The code passes raw `BigDecimal` to Iceberg's `GenericRecord`. Verify this works correctly — does Iceberg accept raw `BigDecimal` for `DecimalType` fields, or does it need conversion to `org.apache.iceberg.types.Decimal`?
- **GCS Data Lake follow-up required:** This PR does NOT include the corresponding `GcsDataLakeAggregate.kt` change (CI requires CDK and connector changes in separate PRs). A follow-up connector PR is needed.
- **Decimal precision widening logic:** `IcebergSuperTypeFinder` handles same-scale precision widening, but different-scale decimals fall through to `isPromotionAllowed` which may reject them. Is this correct behavior?
- **Missing breaking change metadata:** This PR doesn't include:
  - `metadata.yaml` updates with `breakingChanges` entry
  - Migration guide at `docs/integrations/destinations/s3-data-lake-migrations.md`
  - Connector version bumps
  
  Should these be added now or in a follow-up?

## User Impact

**Positive:**
- Dedup sync mode now works for streams where all/some primary keys are `NumberType` (previously failed with "equality field ids shouldn't be null or empty" error).
- Numeric semantics preserved: SUM(), AVG(), ORDER BY, numeric comparisons, and sorting work natively without explicit casting (vs. StringType approach which would have required casting).

**Breaking:**
- **ALL `NumberType` columns** change from `DoubleType` to `DecimalType(38, 18)` on next sync.
- Existing tables with ANY `NumberType` columns require schema migration (likely full refresh) — Iceberg does not support `Double` → `Decimal` promotion.
- Downstream queries/dashboards referencing `NumberType` columns as `DOUBLE` type will see type mismatches.
- Numbers in ANY `NumberType` column exceeding `Decimal(38, 18)` range (>10^20 or >18 fractional digits) will be truncated or rejected.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [x] NO ❌

**Rationale:** Once merged, tables with ANY `NumberType` columns will be migrated to the new schema (DoubleType → DecimalType). Reverting would require manual table schema migration back to DoubleType, and any data synced with the new version would need re-ingestion. The blast radius affects ALL connections using `NumberType` fields (not just those with NumberType PKs).

### CODE REVIEW

**Review by subodh1810 — DISMISSED** [review]
Mapping NumberType to StringType loses numeric semantics - queries like SUM(), AVG(), numeric comparisons, and sorting won't work correctly without explicit casting. This creates a poor user experience for analytics workloads.                                                                                                                                                                                
                                                                                                                                                                                                      Proposed alternative: Use DecimalType instead                                                                                                                                                            
                                                                                                                                                                                                           
According to the https://iceberg.apache.org/spec/, only float, double, and optional fields are prohibited as identifier fields. DecimalType is allowed and preserves numeric semantics.                  
                                                                                                                                                                                                           
The fix should:                                                                                                                                                                                          
1. Map NumberType → DecimalType (e.g., Types.DecimalType.of(38, 18)) instead of StringType                                                                                                               
    - DECIMAL(38, 18) provides sufficient precision for virtually all use cases                                                                                                                            
    - Airbyte's NumberType is backed by BigDecimal, so conversion is straightforward                                                                                                                       
2. Add Decimal support to IcebergSuperTypeFinder                                                                                                                                                         
    - Remove DECIMAL from unsupportedTypeIds                                                                                                                                                               
    - Handle precision widening for schema evolution (Iceberg allows widening precision but not changing scale)                                                                                            
3. Update IcebergTypesComparator if needed for Decimal type equality checks                                                                                                                              
                                                                                                                                                                                                           
  This approach:                                                                                                                                                                                           
  - ✅ Allows NumberType fields as identifier fields (fixes the original issue)                                                                                                                            
  - ✅ Preserves numeric semantics (SUM, AVG, ORDER BY, comparisons)                                                                                                                                       
  - ✅ Works naturally with downstream BI/analytics tools                                                                                                                                                  
  - ✅ No casting required in queries                                                                                                                                                                      
                                                                                                                                                                                                           
Let me know if you have questions about this approach. Also this would still be a breaking change. So please follow our breaking change protocol (update the connector metadata).

**Review by subodh1810 — COMMENTED** [review]
Is it possible to test this once against s3 data lake connector locally before merging (by setting the cdk version to local and then running integration tests). If the tests pass, I can approve

File: airbyte-cdk/bulk/toolkits/load-iceberg-parquet/src/main/kotlin/io/airbyte/cdk/load/data/iceberg/parquet/AirbyteTypeToIcebergSchema.kt [hunk 1]
```diff
@@ -67,7 +67,7 @@ class AirbyteTypeToIcebergSchema {
             is BooleanType -> Types.BooleanType.get()
             is DateType -> Types.DateType.get()
             is IntegerType -> Types.LongType.get()
-            is NumberType -> Types.DoubleType.get()
+            is NumberType -> Types.DecimalType.of(38, 18)
```
Comment (benmoriceau) [inline airbyte-cdk/bulk/toolkits/load-iceberg-parquet/src/main/kotlin/io/airbyte/cdk/load/data/iceberg/parquet/AirbyteTypeToIcebergSchema.kt:70]: We still need to limit that to the PKs. We want to limit the impact on this change for the connection which don't need it.

Comment (subodh1810) [reply airbyte-cdk/bulk/toolkits/load-iceberg-parquet/src/main/kotlin/io/airbyte/cdk/load/data/iceberg/parquet/AirbyteTypeToIcebergSchema.kt:70]: I think its fine. NumberType->DecimalType is correct. As long as mark the new version as a breaking change, we should be good.

Comment (benmoriceau) [reply airbyte-cdk/bulk/toolkits/load-iceberg-parquet/src/main/kotlin/io/airbyte/cdk/load/data/iceberg/parquet/AirbyteTypeToIcebergSchema.kt:70]: Go with the universal approach

**Review by benmoriceau — APPROVED** [review]
