### PR TITLE
🎉  MySQL Source : Expose serverTimezone debezium option via MySQL Source spec for CDC

### LINKED ISSUE #6573: Expose serverTimezone debezium option via MySQL Source spec for CDC
Hello all,

A full refresh works, as it is using the JDBC connection params defined in the UI, but the incremental update seems to ignore the configured jdbc parameters and fails.

## Enviroment
- **Airbyte version**:  0.30.1-alpha
- **OS Version / Instance**: Windows 100 /Docker WSL2
- **Deployment**:  Docker 
- **Source Connector and version**:  MySQL | airbyte/source-mysql | 0.4.5
- **Destination Connector and version**:  snowflake | airbyte/destination-snowflake | 0.3.14
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
Fails to sync due MySQL errors, which are happening because the jdbc params are not applied in incemental mode (binlog)

## Expected Behavior
Should use the JDBC params defined in the source settings and sync.

## Logs

<details>
<summary>LOG</summary> 

```

2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:152)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:99)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.computeNext(DebeziumRecordIterator.java:52)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:83)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:83)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:58)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:139)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:251)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - Caused by: java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.debezium.internals.DebeziumRecordPublisher.close(DebeziumRecordPublisher.java:137)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:35)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.airbyte.integrations.debezium.internals.DebeziumRecordIterator.requestClose(DebeziumRecordIterator.java:149)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	... 23 more
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - Caused by: org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:342)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlJdbcContext.readMySqlSystemVariables(MySqlJdbcContext.java:321)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:79)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:52)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:346)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:142)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:758)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.lang.Thread.run(Thread.java:832)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - Caused by: java.sql.SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:230)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:871)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:866)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:412)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:328)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	... 11 more
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:134)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2186)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2209)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1318)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
2021-09-30 12:03:28 ERROR () LineGobbler(voidCall):65 - 	... 19 more

```

```

</details>

## Steps to Reproduce
1. Use a MySQL database with the timezone  set to 'CEST' as a Source
2. Use JDBC connection param to Change it to e.g. serverTimezone=Europe/Berlin
3. Try to sync Data from the database to any target with BINLOG (CDC) and Incremental mode, which fails and switch to full refresh and it will work

### PR DESCRIPTION
**Pull request by akashkulk**
## What
Closes [#6573](https://github.com/airbytehq/airbyte/issues/6573)

Currently, CDC mode does not work when when the source MySQL db is set up with a server timezone that is not recognized by the ZoneID Java library (e.g. CEST, PDT). 

The fix here is to expose an server timezone option in the CDC replication methods UI and add it to the debezium serverTimezone property while reading from MySQL in CDC mode. 

## 🚨 User Impact 🚨
User will see a new option to add server timezone, with messaging that this is an 'advanced' option - only to be used when the server timezone is not IANNA compliant. 

https://www.loom.com/i/2c1d080ab76541419782d508a22ab98b

### CODE REVIEW

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java [hunk 1]
```diff
@@ -74,6 +76,33 @@ public static Optional<Integer> getFirstRecordWaitSeconds(final JsonNode config)
     return Optional.empty();
   }
 
+  public static Optional<String> getCdcServerTimezone(final JsonNode config) {
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java:79]: this can be private

**Review by subodh1810 — APPROVED** [review]
This makes sense. I am just curious if it would be possible to add a test case with a docker instance that you used to reproduce the error

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java]: Done

**Comment by akashkulk** [comment]
> 

Seems like the test library we use for containers supports creating images on the fly, but we'd have to duplicate a lot of the code that is currently in the MySQL test container.

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlCdcProperties.java [hunk 2]
```diff
@@ -17,6 +17,8 @@
 import java.net.URI;
 import java.nio.file.Path;
 import java.util.Properties;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlCdcProperties.java:21]: Curious, is this used somewhere? I don't see any references to these imports

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java [hunk 3]
```diff
@@ -74,6 +76,33 @@ public static Optional<Integer> getFirstRecordWaitSeconds(final JsonNode config)
...
+    return Optional.empty();
+  }
+
+  public static void checkCdcReplicationMethodConfig(final JsonNode config) {
+    checkFirstRecordWaitTime(config);
+    checkServerTimeZoneConfig(config);
+  }
+
+  @VisibleForTesting
+  public static void checkServerTimeZoneConfig(final JsonNode config) {
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java:94]: If this method is `public`, would the need for @VisibleForTesting still be necessary? Unless my understanding is off, this usually for the usage of `default` or `protected` access modifiers, no? 

That said, I like the link out to the IANA website for customers to reference

**Review by ryankfu — APPROVED** [review]
LGTM, minor comments but otherwise not blocking

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlCdcProperties.java (hunk 2 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlCdcProperties.java:21]: Removing - I was trying to log something to debug

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java (hunk 3 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java:94]: Removing the @VisibleForTesting

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false
