### PR TITLE
increase spec and discover worker timeouts to 30 minutes

### LINKED ISSUE #1664: A long discovery request causes a timeout in the UI
## Description
Salesforce catalogs can be quite large and discovery can take a long time (>2m) to complete, which causes a timeout in the UI. When catalogs will take a long time to discover, we need a way to get around this. 

## Steps to Reproduce
1. TODO -- need to figure out how big is "big enough" to cause this timeout

## Severity of the bug for you
High -- it prevents using the connector for users with many resources in Salesforce

### PR DESCRIPTION
**Pull request by sherifnada**
## What
This will help with issues like #1664 #1669 and #1462 by not failing the worker in cases where the underlying operation fundamentally takes more time

### CODE REVIEW

File: airbyte-workers/src/main/java/io/airbyte/workers/DefaultGetSpecWorker.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ public DefaultGetSpecWorker(final IntegrationLauncher integrationLauncher) {
         // this.
         // retrieving spec should generally be instantaneous, but since docker images might not be pulled
         // it could take a while longer depending on internet conditions as well.
-        WorkerUtils.gentleClose(process, 2, TimeUnit.MINUTES);
+        WorkerUtils.gentleClose(process, 10, TimeUnit.MINUTES);
```
Comment (cgardens) [inline airbyte-workers/src/main/java/io/airbyte/workers/DefaultGetSpecWorker.java:80]: what's the longest time we've heard someone take? i thought we said 30 min? 10 is fine if we think this covers all the cases we've seen.

**Review by cgardens — APPROVED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/DefaultGetSpecWorker.java (hunk 1 above)
Comment (sherifnada) [reply airbyte-workers/src/main/java/io/airbyte/workers/DefaultGetSpecWorker.java:80]: 10m was finger-to-the-wind estimate, I don't see an issue with increasing the timeout to 30m. Updated.
