### PR TITLE
🐛  fix issue where jobs retried forever

### LINKED ISSUE #2452: Failed syncs endlessly loop in 0.17.0-alpha
## Expected Behavior
Should stop trying to sync if the sync fails at least 3 times like in previous versions

## Current Behavior
Failed syncs keep happening and never stop

## Steps to Reproduce
1. pull 0.17.0-alpha and launch a sync with a known failure

## Severity of the bug for you
Medium

## Airbyte Version
0.17.0-alpha

## Connector Version (if applicable)
GitHub | airbyte/source-github-singer | 0.2.0

### LINKED ISSUE #2495: Scheduler can't run new jobs after it crashes
## Expected Behavior

Scheduler should run new jobs (e.g: discover schema)

## Current Behavior
It can run new jobs until a SYNC job crashes.

## Logs
```
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.b.FailureTrackingConsumer(close):64 - {} - hasFailed: true.
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 ERROR i.a.i.d.b.BufferedStreamConsumer(close):158 - {} - executing on failed close procedure.
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):153 - {} - Cleaning tmp tables in destination started for 0 streams
airbyte-scheduler   | 2021-03-17 02:03:40 INFO i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 2021-03-17 02:03:40 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):162 - {} - Cleaning tmp tables in destination completed.
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - catalog: {"streams":[]} ,
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - message: {"type":"RECORD","record":{"stream":"sf733bec714344f80971f113d4a3063c5exchange_rate","data":{"CAD":1.299830251,"HKD":7.790851425,"ISK":122.3085857232,"PHP":50.7683373537,"DKK":6.6755114804,"HUF":294.8092557849,"CZK":22.7025819709,"GBP":0.7578665237,"RON":4.2730277852,"SEK":9.356562137,"IDR":13884.4992405968,"INR":71.3897078531,"BRL":4.0087554722,"RUB":61.8147949611,"HRK":6.6510318949,"JPY":108.7733404807,"THB":30.1447333155,"CHF":0.9706959707,"EUR":0.8934155276,"MYR":4.0886268203,"BGN":1.7473420888,"TRY":5.9589922273,"CNY":6.9638166711,"NOK":8.7919235236,"NZD":1.493612079,"ZAR":14.0709371929,"USD":1.0,"MXN":18.8852854463,"SGD":1.3476279818,"AUD":1.4300008934,"ILS":3.4566246761,"KRW":1159.8677745019,"PLN":3.8009470205,"date":"2020-01-02T00:00:00Z"},"emitted_at":1615946618000}}
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:147)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:75)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.FailureTrackingConsumer.accept(FailureTrackingConsumer.java:53)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:131)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:115)
airbyte-scheduler   | 2021-03-17 02:03:40 ERROR i.a.c.i.LineGobbler(voidCall):69 - {ActivityId=43e53145-bc8d-3136-8abf-e81896e417aa, ActivityType=Run, Namespace=default, RunId=1167c082-f000-485b-b8c6-006d514f9335, TaskQueue=SYNC, WorkflowId=1ff3624d-c7b0-43f4-a174-cdb49d4cbe8b, job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/0} - 	at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:69)
```

## Steps to Reproduce
1. Create a connection with an empty syncCatalog
1. Run a discover schema command and see it return ok
1. Wait until the scheduler crashes when running a SYNC for the connection
2. Run discover schema command and see it fail

## Severity of the bug for you
Pretty High

## Airbyte Version
0.17.1-alpha

## Connector Version (if applicable)
I'm using exchange rates API (the version is the one bundled with 0.17.1)

## Additional context
Debian 10.8 using Linux 4.19 on x64

### PR DESCRIPTION
**Pull request by cgardens**
closes: https://github.com/airbytehq/airbyte/issues/2452
closes: https://github.com/airbytehq/airbyte/issues/2495

## What
Bug where when a worker field, temporal would keep retrying it indefinitely. This was due to a misconfiguration in how we set up temporal. 

## How
* Set temporal to not retry
* Catch the correct temporal exception

### CODE REVIEW

**Review by jrhizor — APPROVED** [review]

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/worker_run/TemporalWorkerRunFactory.java [hunk 1]
```diff
@@ -122,7 +123,11 @@ private static TemporalJobType toTemporalJobType(ConfigType jobType) {
   private OutputAndStatus<JobOutput> toOutputAndStatus(CheckedSupplier<JobOutput, TemporalJobException> supplier) {
     try {
       return new OutputAndStatus<>(JobStatus.SUCCEEDED, supplier.get());
-    } catch (TemporalJobException e) {
+    } catch (TemporalJobException | TemporalException e) {
+      // while from within the temporal activity we throw TemporalJobException, Temporal wraps any
+      // exception thrown by an activity in an ApplicationFailure exception, which gets wrapped in
+      // ActivityFailure exception which get wrapped in a WorkflowFailedException. We will need to unwrap
+      // these later, but for now we just catch the parent.
```
Comment (sherifnada) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/worker_run/TemporalWorkerRunFactory.java:130]: should we create an issue for this?

**Review by sherifnada — APPROVED** [review]

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/worker_run/TemporalWorkerRunFactory.java (hunk 1 above)
Comment (cgardens) [reply airbyte-scheduler/src/main/java/io/airbyte/scheduler/worker_run/TemporalWorkerRunFactory.java:130]: normally i would say yes, but i plan to just handle this in this open PR https://github.com/airbytehq/airbyte/pull/2385
