### PR TITLE
Destinations BigQuery and Snowflake - Move SAFE/TRY casting to seperate transaction

### LINKED ISSUE #30418: Destinations V2: Only use SAFE_CAST if we have to
I have a suspicion that our usage of SAFE_CAST is the most expensive.  I'd rather start investigating ways to maybe try a T&D without it first, and if it fails, try again with SAFE_CAST.  that might save a bunch of compute

This is a story in 2 parts:
1. Analyze if SAFE_CAST is expensive - run a (big) sync with and without it and get some data (BQ is good at logging cost information)
2. If it is effective, change our T&D code to try first without SAFE_CAST, and then only if there is a failure, try a second time with SAFE_CAST

```java
doTandD() {
  try {
    TandDUnsafely();
  } catch (BQException) {
    log(BQException);
    TandDWithSafeCast(); // what we have now
  }
}
```

### PR DESCRIPTION
**Pull request by jbfbell**
- add try catch to cdk
- move try catch to java

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java [hunk 1]
```diff
@@ -239,6 +236,29 @@ public CompletableFuture<Optional<Exception>> typeAndDedupeTask(final StreamConf
...
+   */
+  private void typeAndDedupeTransactions(final StreamConfig streamConfig) throws Exception {
+    final String suffix = getFinalTableSuffix(streamConfig.id());
+    try {
+      LOGGER.info("Attempting typing and deduping for {}.{}", streamConfig.id().originalNamespace(), streamConfig.id().originalName());
+      final String unsafeSql = sqlGenerator.updateTable(streamConfig, suffix, minExtractedAtByStream.get(streamConfig.id()), false);
+      destinationHandler.execute(unsafeSql);
+      // TODO determine which Exceptions should not be retried even with safer sql
+    } catch (Exception e) {
+      LOGGER.error("Encountered Exception on unsafe SQL for stream %s %s, attempting with error handling"
```
Comment (evantahler) [inline airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java:255]: Nice logging

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java [hunk 2]
```diff
@@ -382,7 +382,7 @@ public void incrementalDedupSameNameNamespace() throws Exception {
             }
             """)));
 
-    final String sql = generator.updateTable(stream, "", Optional.empty());
+    final String sql = generator.updateTable(stream, "", Optional.empty(), true);
```
Comment (evantahler) [inline airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java:385]: Seems like there are no tests for the `false` case... should there be?

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java [hunk 3]
```diff
@@ -374,7 +374,7 @@ public String softReset(final StreamConfig stream) {
     final String clearLoadedAt = clearLoadedAt(stream.id());
     // We just unset loaded_at on all raw records, so we need to process all of them (i.e. should not
     // filter on extracted_at)
-    final String rebuildInTempTable = updateTable(stream, SOFT_RESET_SUFFIX, Optional.empty());
+    final String rebuildInTempTable = updateTable(stream, SOFT_RESET_SUFFIX, Optional.empty(), true);
```
Comment (evantahler) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java:377]: Why do soft-resets always use the more expensive version? Shouldn't this also be the try/catch?

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java [hunk 4]
```diff
@@ -586,7 +561,7 @@ public String overwriteFinalTable(final StreamId stream, final String finalSuffi
   public String softReset(final StreamConfig stream) {
     final String createTempTable = createTable(stream, SOFT_RESET_SUFFIX.toUpperCase(), true);
     final String clearLoadedAt = clearLoadedAt(stream.id());
-    final String rebuildInTempTable = updateTable(stream, SOFT_RESET_SUFFIX.toUpperCase(), Optional.empty());
+    final String rebuildInTempTable = updateTable(stream, SOFT_RESET_SUFFIX.toUpperCase(), Optional.empty(), true);
     final String overwriteFinalTable = overwriteFinalTable(stream.id(), SOFT_RESET_SUFFIX.toUpperCase());
```
Comment (evantahler) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java:565]: Same comment as BQ - why are soft resets always the SAFE way?

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java (hunk 1 above)
Comment (jbfbell) [reply airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java:255]: 🪵

Comment (edgao) [reply airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java:255]: fyi the logger has built-in string formatting, e.g. `LOGGER.error("foo {} bar {}", "first param", "second param")`

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java (hunk 3 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java:377]: we might need to refactor the softReset method to live in the TyperDeduper, and promote the `clearLoadedAt` method to a public method on SqlGenerator. I.e. in DefaultTyperDeduper:

```java
private void softReset(StreamConfig stream) {
  // This method doesn't currently exist in the SqlGenerator interface, it's a private method in BigQuerySqlGenerator
  execute(generator.clearLoadedAt(stream));
  execute(generator.createTable(stream, "_soft_reset"));
  try {
    execute(generator.updateTable(stream, "_soft_reset", false));
  } catch (Exception e) {
    execute(generator.updateTable(stream, "_soft_reset", true));
  }
  execute(generator.overwriteFinalTable(stream, "_soft_reset"));
}
````

this try-catch can't live inside the sqlgenerator b/c sqlgenerator is side-effect free. i.e. it can't actually execute sql

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java [hunk 5]
```diff
@@ -178,45 +180,16 @@ public String updateTable(final StreamConfig stream, final String finalSuffix, f
...
-   * END;';
-   * }
-   * </pre>
-   * <p>
-   * This method is a workaround for this behavior. We switch to using the {@code get} method to
-   * extract JSON values, and avoid the `${` sequence by using string concatenation. This generates a
-   * sql statement like {@code SELECT TRY_CAST((get("_airbyte_data", '$' + '{foo}')::text) as INTEGER)
-   * FROM ...}.
-   */
-  private String extractAndCastInsideScript(final ColumnId column, final AirbyteType airbyteType) {
```
[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java:203]: kill it. it's a private method so I trust intellij

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java (hunk 3 above)
Comment (jbfbell) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java:377]: +1 to ed's comment - I think its ok to leave it out for now, soft resets are erring on the side of being the expensive but reliable query but we should probably extract it

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java (hunk 1 above)
Comment (jbfbell) [reply airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java:255]: :doh: I for some reason thought that the override with variable inputs and auto-formatting would format the exception weirdly but it works fine

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java (hunk 2 above)
Comment (jbfbell) [reply airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java]: looked into this - added both options where appropriate, the sql generator tests also sometimes assume that casting errors will be caught but this is probably a misplaced test, these tests should probably be in in the `DefaultTyperDeduperTest` to avoid duplicating this logic for testing purposes.

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java (hunk 3 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java:377]: I actually just realized - we probably should do this refactor before releasing this pr? Otherwise this will be a regression in bigquery soft reset performance

Comment (edgao) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java:377]: open to discussion though. maybe that's worth the improvement for query length

Comment (jbfbell) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java]: fair enough! refactored

File: airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java [hunk 6]
```diff
@@ -102,4 +91,11 @@ default ColumnId buildColumnId(final String name) {
    */
   String migrateFromV1toV2(StreamId streamId, String namespace, String tableName);
 
+  /**
+   * Typically we need to create a soft reset temporary table and clear loaded at values
+   *
+   * @return
+   */
+  String prepareTablesForSoftReset(final StreamConfig stream);
```
Comment (edgao) [inline airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java:99]: nit: I'd mildly prefer to have the caller do a createTable call instead of making that implicit in this method (or at least have this method explicitly accept the table name suffix)

**Review by edgao — APPROVED** [review]
lgtm - one nit but I wouldn't block over it, feel free to merge as-is
