### PR TITLE
Fix password reset

### LINKED ISSUE #6674: "Forgot my password" does not work.
I get the email to reset my password, but when I click on the link, I end up in the wrong place (just on the login screen). Unclear if this is just a firebase setting that needs to change or a UI bug.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Fixes #6674.

## How
- Previously password reset did not work because the route was wrong. React router expected a `/confirm-password-reset` path for the password confirmation page. However, in Firebase, all links in the emails have the same "action URL", which is set to `/verify-email`.
- Different firebase actions can be matched by the `mode` parameter.

## Screenshots

| Scenario | Screenshot |
| --- | --- |
| Request password reset | Screen Shot 2021-10-05 at 00 10 53 |
| Invalid link | Screen Shot 2021-10-05 at 00 10 12 |
| Password reset complete | Screen Shot 2021-10-05 at 00 10 38 |

### CODE REVIEW

File: airbyte-webapp/src/packages/cloud/routes.tsx [hunk 1]
```diff
@@ -72,9 +72,18 @@ export enum Routes {
   Signup = "/signup",
   Login = "/login",
   ResetPassword = "/reset-password",
-  ConfirmPasswordReset = "/confirm-password-reset",
-  VerifyEmail = "/verify-email",
   ConfirmVerifyEmail = "/confirm-verify-email",
+
+  // Firebase action routes
```
Comment (cgardens) [inline airbyte-webapp/src/packages/cloud/routes.tsx:77]: weird. thanks for putting such a clear comment about this.

**Review by jamakase — APPROVED** [review]

**Review by cgardens — APPROVED** [review]
amazing 🎉
