### PR TITLE
🐛 Destination Snowflake - support reserved column names

### LINKED ISSUE #30190: Either Quote, mangle, or directly prevent column names with reserved words (SNOWFLAKE)
Related to this [page](https://airbytehq.sentry.io/issues/4398228154/?project=6527718), [sync](https://cloud.airbyte.com/workspaces/c67963ed-2c60-4fde-a83b-72dc7de2c245/connections/bdbad1c8-f484-40ef-b1cb-666c4e838db6/job-history#4473759::4), and [slack thread](https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1693986349800509):

```
Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: JavaScript execution error: Uncaught Execution of multiple statements failed on statement "CREATE OR REPLACE TABLE "(truncated)" (at line 3, position 0).
SQL compilation error: error line 17 at position 1
.invalid column definition name 'CURRENT_DATE' (ANSI reserved) in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace: 
SYSTEM$MULTISTMT line: 10
```

We either need to:
* Figure out how to allow columns with these reserved words, possibly by quoting them
   * `create or replace table RESERVED_COLS (ID NUMBER, "CURRENT_DATE" TIMESTAMP);` (with quotes) still fails.  Is there another way to quote this column?
   * `create or replace table RESERVED_COLS (ID NUMBER, "current_date" TIMESTAMP);` (lower case was OK)
   * Why did this stream use to be OK in v1/normalization?  [This](https://github.com/airbytehq/airbyte/blob/evan/reomve-bigquery-denormalized/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/destination_name_transformer.py#L171), which is called when `is_reserved_keyword() ==True` implies with the right amount of quoting, reserved column names would be OK... 
* Mangle the name of the columns to be valid, e.g. `CURRENT_DATE` could become `_CURRENT_DATE`
* Fail the syncs early with a clear error message (e.g. `column CREATED_AT is not allowed`)

Snowflake clearly lists it's reserved words here: https://docs.snowflake.com/en/sql-reference/reserved-keywords

### PR DESCRIPTION
**Pull request by cynthiaxyin**
closes #30190 + the test portion of #30366 

User-side changes:
- Snowflake: reserved column names are now prefixed by `_` so the sync doesn't crash
  - The behavior for other keywords (ex: `WHERE`) doesn't change; this was already working before
- BigQuery: column names with reserved keywords work as-is

Code changes:
- Prefix logic in `SnowflakeSqlGenerator.java`
- Second `buildColumnId` constructor for `SqlGenerator` classes that takes in a suffix
  - This is to be able to parse the reserved keyword separately from the suffix `_#` that gets added for column name collisions in `CatalogParser`.
  - Example: `CURRENT_DATE` and `current_date` in the raw data will get converted to `_CURRENT_DATE` and `_CURRENT_DATE_1` (rather than `CURRENT_DATE_1`).
- Integration test in `BaseSqlGeneratorIntegrationTest.java`

I also ran a sync from local Postgres to Snowflake and verified the [raw](https://app.snowflake.com/xdaabwo/gz45853/#/data/databases/INTEGRATION_TEST_DESTINATION/schemas/airbyte_internal/table/cynthia_keywords_raw__stream_cynthia_keywords_keywords/data-preview) + [final](https://app.snowflake.com/xdaabwo/gz45853/#/data/databases/INTEGRATION_TEST_DESTINATION/schemas/CYNTHIA_KEYWORDS/table/CYNTHIA_KEYWORDS_KEYWORDS/data-preview) table records.

### CODE REVIEW

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryReservedKeywords.java [hunk 1]
```diff
@@ -0,0 +1,109 @@
+package io.airbyte.integrations.destination.bigquery;
+
+import com.google.common.collect.ImmutableList;
+import java.util.List;
+
+public class BigQueryReservedKeywords {
+
+  // https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved_keywords
+  public static final List<String> RESERVED_KEYWORDS = ImmutableList.of(
```
Comment (cynthiaxyin) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryReservedKeywords.java:9]: This class is not being used, but I created it for completeness.

Both this and the `SnowflakeReservedKeywords` file were copied from normalization: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/reserved_keywords.py

File: airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sqlgenerator/reservedkeywords_inputrecords_raw.jsonl [hunk 2]
```diff
@@ -0,0 +1,2 @@
+// A column name that is a reserved keyword should be added for each typing & deduping destination.
+{"_airbyte_raw_id": "b2e0efc4-38a8-47ba-970c-8103f09f08d5", "_airbyte_extracted_at": "2023-01-01T00:00:00Z", "_airbyte_data": {"current_date":  "foo"}}
```
Comment (evantahler) [inline airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sqlgenerator/reservedkeywords_inputrecords_raw.jsonl:2]: nit: add {"JOIN": "foo"} as well.  If this meant to be a tested on all destinations, a reserved word `JOIN` is more common across SQL dialects than `current_date`

Comment (edgao) [reply airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sqlgenerator/reservedkeywords_inputrecords_raw.jsonl:2]: no harm in having multiple fields, but current_date is actually a pretty common reserved word according to wikipedia https://en.wikipedia.org/wiki/List_of_SQL_reserved_words

image

(at the very least, the sql standard defines it as a reserved word)

File: airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java [hunk 3]
```diff
@@ -12,6 +12,8 @@ public interface SqlGenerator<DialectTableDefinition> {
 
   ColumnId buildColumnId(String name);
```
Comment (edgao) [inline airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java:13]: nit: why not just delete this overload entirely? or at least define a default implementation
```suggestion
  default ColumnId buildColumnId(String name) {
    return buildColumnId(name, "");
  }
```

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java [hunk 4]
```diff
@@ -48,8 +49,16 @@ public StreamId buildStreamId(final String namespace, final String name, final S
...
   public ColumnId buildColumnId(final String name) {
+    return buildColumnId(name, "");
+  }
+
+  @Override
+  public ColumnId buildColumnId(final String name, final String suffix) {
     // No escaping needed, as far as I can tell. We quote all our identifier names.
-    return new ColumnId(escapeSqlIdentifier(name).toUpperCase(), name, name.toUpperCase());
+    final String nameWithSuffix = name + suffix;
+    return new ColumnId(prefixReservedKeyword(escapeSqlIdentifier(name).toUpperCase()) + suffix,
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java:59]: I think this will be a breaking change - some column names that were previously working  (e.g. `WHERE`) will now be prefixed with `_`. I don't think we need an explicit migration, since we'll auto soft reset, but this should be a major version bump, probably. Unless we think the impact is really small? :shrug:

Or... we can track down which words are only reserved as column names? and define a `RESERVED_COLUMN_NAME_LIST` for them specifically. Then it would be a patch bump (since we were crashing on those column names, so there was no previous behavior)

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java [hunk 5]
```diff
@@ -577,6 +586,11 @@ public static String escapeSqlIdentifier(String identifier) {
     return escapeJsonIdentifier(identifier);
   }
 
+  private static String prefixReservedKeyword(final String columnName) {
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java:589]: nit: this is only doing column names, rename to something like `prefixReservedColumnName`

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryReservedKeywords.java (hunk 1 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryReservedKeywords.java:9]: this is a useful comment to put in the code directly! Otherwise I can see a future developer deleting this class for being unused.

(you would probably want to link to the commit tree directly, since we're planning to nuke normalization from master. I.e. https://github.com/airbytehq/airbyte/blob/f226503bd1d4cd9c7412b04d47de584523988443/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/reserved_keywords.py)

File: airbyte-integrations/connectors/destination-snowflake/src/test-integration/resources/sqlgenerator/reservedkeywords_expectedrecords_final.jsonl [hunk 6]
```diff
@@ -0,0 +1 @@
+{"_airbyte_raw_id":"b2e0efc4-38a8-47ba-970c-8103f09f08d5","_airbyte_extracted_at":"2023-01-01T00:00:00.000000000Z","_airbyte_meta":{"errors":[]}, "_CURRENT_DATE": "foo"}
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/test-integration/resources/sqlgenerator/reservedkeywords_expectedrecords_final.jsonl:1]: comments! :D 
```suggestion
// Note that we prefix `current_date` with an underscore (to `_CURRENT_DATE`). This is because even if you quote `CURRENT_DATE`, snowflake rejects it as a column name.
{"_airbyte_raw_id":"b2e0efc4-38a8-47ba-970c-8103f09f08d5","_airbyte_extracted_at":"2023-01-01T00:00:00.000000000Z","_airbyte_meta":{"errors":[]}, "_CURRENT_DATE": "foo"}
```

**Review by edgao — APPROVED** [review]
calling out that this is probably a breaking change as-is. I had a thought for how to avoid that, but your call on whether that's a better approach.

Otherwise had a few nits; lgtm once those are resolved + you switch to a major version bump / figure out the reserved column names thing.

File: airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sqlgenerator/reservedkeywords_inputrecords_raw.jsonl (hunk 2 above)
Comment (cynthiaxyin) [reply airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sqlgenerator/reservedkeywords_inputrecords_raw.jsonl:2]: Thanks for the suggestion! I was trying to find a good one to use.

File: airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java (hunk 3 above)
Comment (cynthiaxyin) [reply airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/SqlGenerator.java:13]: >why not just delete this overload entirely
There's a bunch of test usages that I didn't want to update (and I don't want tests to have to specify "" as the second parameter every time).

>a default implementation
TIL :)

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java (hunk 4 above)
Comment (cynthiaxyin) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java]: Thanks for calling this out. Going with the second approach to not introduce another breaking change unnecessarily. The list of reserved column names is also relatively small.
