### PR TITLE
🎉Destination-bigquery-denorm: fixed emittedAt timestamp

### LINKED ISSUE #11067: Wrong Timestamp while using BigQuery(Denormalized) Destination
## Environment
- **Airbyte version**:  0.35.36-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Postgres 12.7
- **Destination Connector and version**: BigQuery(denormalized)
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
- Timestamp at Bigquery Denormalized destination is wrong. It is showing something like `54155-07-08 16:40:49 UTC`

## Expected Behavior
- Timestamp should be correct

## Steps to Reproduce
1. Using Postgres Source and Bigquery Denormalized destination set up a connection in full refresh append mode.
2. Run a sync on a Table.
3. On destination side you will see wrong Timestamp in `_airbyte_emitted_at` column.

## Are you willing to submit a PR?

No.

### PR DESCRIPTION
**Pull request by etsybaev**
## What
Currently, datetime in the emittedAt field is incorrect

## How
Fixed date and checked locally, see captures below

*Describe the solution*
Selection_105
Selection_106
Selection_107

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/util/TestBigQueryDenormalizedRecordFormatter.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+  public TestBigQueryDenormalizedRecordFormatter(
+                                                 JsonNode jsonSchema,
+                                                 StandardNameTransformer namingResolver) {
+    super(jsonSchema, namingResolver);
+  }
+
+  @Override
+  public void addAirbyteColumns(ObjectNode data,
+                                AirbyteRecordMessage recordMessage) {
+    super.addAirbyteColumns(data, recordMessage);
```
Comment (mkhokh-33) [inline airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/util/TestBigQueryDenormalizedRecordFormatter.java:25]: why do we created this class if overwritten method only call super implementation?

File: airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/BigQueryDenormalizedUtilsTest.java [hunk 2]
```diff
@@ -206,6 +211,24 @@ void testSchemaWithNestedDatetimeInsideNullObject() {
 
   }
 
+  @Test
+  public void testEmittedAtTimeConversion() {
+    // in this test we don't care about json schema and naming resolver, so leave it as a null
+    final JsonNode jsonNodeSchema = getSchema();
```
Comment (mkhokh-33) [inline airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/BigQueryDenormalizedUtilsTest.java:217]: could we consider to use mock instead of instance?

**Review by mkhokh-33 — CHANGES_REQUESTED** [review]

File: airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/BigQueryDenormalizedUtilsTest.java (hunk 2 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/BigQueryDenormalizedUtilsTest.java:217]: Just forgot to remove the comment, it's not applicable for now.
Record formatted requires a valid schema for now.
Removed obsolete comment. Thanks

File: airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/util/TestBigQueryDenormalizedRecordFormatter.java (hunk 1 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery-denormalized/src/test/java/io/airbyte/integrations/destination/bigquery/util/TestBigQueryDenormalizedRecordFormatter.java:25]: This is a test class is located in the test package and exposes a protected method from the main package.
@VisibleForTesting annotation doesn't work here, I didn't want to use reflection to keep code more readable.

**Review by mkhokh-33 — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with merging and publishing without airbyte review

**Comment by etsybaev** [comment]
/publish connector=connectors/destination-bigquery-denormalized
