### PR TITLE
Deprecate Legacy Migration System

### LINKED ISSUE #6917: Remove legacy migration system
## Tell us about the problem you're trying to solve
Before @tuliren implemented migrations with Flyway we used a file based migration system. Keeping the system around is painful because it adds a lot of complexity to the start up sequence of the server app. It generally makes it difficult or blocks making that app HA.

## Plan
What we want to do is change the contract on our migrations. We theoretically allow a user to migrate from any old version of Airbyte to any new version, right now. Instead we propose having a user run two upgrades if they are migrating a great distance. For example, imagine we have Airbyte versions 1-10. We would say that if you are on a version below 5 (say 2) and you want to upgrade to version 10, you must first upgrade from 2 to 5. Then once your migration to 5 is complete, you can upgrade again to version 10.

What this allows us to do is to remove the legacy migration system after version 5. The trade off is that the user has to do an extra upgrade if they are upgrading from a really ancient version.

## Tasks
- [x] - Make sure that if a user is trying to upgrade past the transition version that we throw an exception with clear instructions on what they want to do
- [x] - Document the two step upgrade
- [ ] - After whatever version we do this on, delete the legacy migration system (this includes removing file system persistence and file migration)

### PR DESCRIPTION
**Pull request by cgardens**
closes https://github.com/airbytehq/airbyte/issues/6917

## What
* Now that the we are passed the faux major version bump, we can remove the legacy migration system. This PR just removes there is called. It will focus on the least change path to remove it from the production code path. Subsequently all of the underlying code will be removed, but for now just focused on stopping it from being run and making sure tests are happy.

## How
* Remove where it is called in `ServerApp.java`

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/ServerApp.java [hunk 1]
```diff
@@ -221,20 +221,11 @@ public static ServerRunnable getServer(final ServerFactory apiFactory, final Con
     final SynchronousSchedulerClient bucketSpecCacheSchedulerClient =
         new BucketSpecCacheSchedulerClient(syncSchedulerClient, configs.getSpecCacheBucket());
     final SpecCachingSynchronousSchedulerClient cachingSchedulerClient = new SpecCachingSynchronousSchedulerClient(bucketSpecCacheSchedulerClient);
-    final SpecFetcher specFetcher = new SpecFetcher(cachingSchedulerClient);
-
-    // todo (cgardens) - this method is deprecated. new migrations are not run using this code path. it
-    // is scheduled to be removed.
-    final Optional<AirbyteVersion> airbyteDatabaseVersion = runFileMigration(
```
Comment (benmoriceau) [inline airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: Nit, we can remove `runFileMigration` as well.

**Review by benmoriceau — CHANGES_REQUESTED** [review]
One small cleanup comment

File: airbyte-server/src/main/java/io/airbyte/server/ServerApp.java (hunk 1 above)
Comment (lmossman) [reply airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: According to the description, this PR is trying to just remove the least amount of code possible to stop the migration from being run, so `runFileMigration()` will be removed in a future PR

**Review by lmossman — APPROVED** [review]
LGTM for a minimal change to remove the file migration call

**Comment by lmossman** [comment]
My only concern is that it according to [this slack message](https://airbytehq.slack.com/archives/C01A4CAP81L/p1637235955119900?thread_ts=1637193620.114600&cid=C01A4CAP81L), it sounds like a user was able to upgrade from <0.32.0, straight to v0.32.1, which may indicate that the logic to prevent this is not working correctly? If so, we probably should not merge this change until that is fixed

File: airbyte-server/src/main/java/io/airbyte/server/ServerApp.java (hunk 1 above)
Comment (benmoriceau) [reply airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: I see, I forgot the description. I checked it in IntelliJ and it is thew only place where it got called, I believe that we can remove this dead code in this review safely. IMO since it is the only place this method is call we should remove it in the same review.

Comment (benmoriceau) [reply airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: Please don't consider it as a blocker.

Comment (cgardens) [reply airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: @benmoriceau yeah. it is intentional. in case we've made a mistake and need to bring it back by removing just the call point the chance of having a complex merge conflict on revert is lower, which is why i have taken this approach. if you're okay with that can you switch your review so that gh won't block the PR?

**Comment by cgardens** [comment]
looking into the issue that @lmossman raised before merging it.

File: airbyte-server/src/main/java/io/airbyte/server/ServerApp.java (hunk 1 above)
Comment (benmoriceau) [reply airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:228]: I am ok, I just hope that doing that will lead to a lot of dead code If we do it too often. As far as we make sure it is clean up, that's fine.

**Review by benmoriceau — APPROVED** [review]

**Comment by cgardens** [comment]
confirmed that this looked good after doing a test minor version bump [here](https://github.com/airbytehq/airbyte/pull/8327).
