### PR TITLE
249/user cannot change email

### LINKED ISSUE #6335: Cloud password reset not working
https://github.com/airbytehq/airbyte-cloud/issues/228

### PR DESCRIPTION
**Pull request by isalikov**
## What
- Users can change email
image

### CODE REVIEW

File: airbyte-webapp/src/packages/cloud/lib/auth/GoogleAuthService.ts [hunk 1]
```diff
@@ -89,6 +92,15 @@ export class GoogleAuthService implements AuthService {
     return updateEmail(user, email);
   }
 
+  async changePassword(passwd: string, newPassword: string): Promise<void> {
+    const user = await this.getCurrentUser()!;
+
+    const credential = EmailAuthProvider.credential(user.email!, passwd);
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/lib/auth/GoogleAuthService.ts:98]: We try to avoid `!` even though we have it in some places.

Is it possible for this email to be empty? if yes - lets check it for null and through error otherwise. Credential should always be a email, right?

File: airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection.tsx [hunk 2]
```diff
@@ -1,17 +1,44 @@
...
+  const auth = useAuth();
+  const authService = useMemo(() => new GoogleAuthService(() => auth), []);
+
+  const { isLoading: isChangingPassword, mutate: changePassword } = useMutation<
+    void,
+    Error,
+    { currentPassword: string; password: string }
+  >(
+    async ({ password, currentPassword }) => {
+      return authService.changePassword(currentPassword, password);
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection.tsx:35]: this should call `services/auth` service. We do not want this logic to spread everywhere. I suppose you need to add proxy to this method in AuthContext

File: airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection.tsx [hunk 3]
```diff
@@ -1,17 +1,44 @@
...
 import { Field, FieldProps, Form, Formik } from "formik";
+import styled from "styled-components";
 
 import {
   Content,
   SettingsCard,
 } from "pages/SettingsPage/pages/SettingsComponents";
 import { FieldItem } from "packages/cloud/views/auth/components/FormComponents";
 import { LabeledInput } from "components/LabeledInput";
+import { Button } from "../../../../../../components/base/Button";
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection.tsx:12]: Small style comment: let's order lib import ( `react-query` ) above our imports. And get rig of `../../../`

File: airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/EmailSection.tsx [hunk 4]
```diff
@@ -51,17 +51,23 @@ export const EmailSection: React.FC = () => {
...
-    await authService.changeEmail(email, passwd);
-    return userService.changeEmail(email);
-  });
+  >(
+    async ({ email, passwd }) => {
+      await authService.changeEmail(email, passwd);
+      await userService.changeEmail(email);
+    },
+    {
+      onSuccess: () => window.location.reload(),
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/EmailSection.tsx:60]: Why do we need to reload page?

File: airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/EmailSection.tsx [hunk 5]
```diff
@@ -51,17 +51,23 @@ export const EmailSection: React.FC = () => {
     void,
     Error,
     { email: string; passwd: string }
-  >(async ({ email, passwd }) => {
-    await authService.changeEmail(email, passwd);
-    return userService.changeEmail(email);
-  });
+  >(
+    async ({ email, passwd }) => {
+      await authService.changeEmail(email, passwd);
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/EmailSection.tsx:56]: Logic leak here. Let's place it into `AuthService` just how all other auth services handle it. It already has access to authService and userService, so you won't need to do any initial initialization

**Review by jamakase — CHANGES_REQUESTED** [review]
Good job!

Few comments about the implementation + I suppose only 1 thing is missed - I do not see error handling. What if reauthenticateWithCredential fails? Or password will be too weak? Firebase doc includes list of possible errors

**Review by jamakase — APPROVED** [review]

File: airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection/typings.d.ts [hunk 6]
```diff
@@ -0,0 +1,5 @@
+export type FormValues = {
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/users/AccountSettingsView/components/PasswordSection/typings.d.ts:1]: No need to use d.ts extensions here as .d.ts is bridge between ts and js. We use just simple ts.

File: airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx [hunk 7]
```diff
@@ -32,84 +34,100 @@ const Buttons = styled.div`
...
+                        />
+                      )}
+                    </Field>
+                    <Buttons>
+                      <Button
+                        secondary
+                        disabled={!dirty}
+                        onClick={() => resetForm()}
+                      >
+                        cancel
```
Comment (Jamakase) [inline airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx:98]: Hmmm, looks like we forgot to add it into locale. Let's add it.

**Review by jamakase — APPROVED** [review]
