### PR TITLE
sync data from beginning if lsn is no longer valid in postgres cdc 

### LINKED ISSUE #12821: Postgres Incremental sync skips rows after failure
## Environment
- **Airbyte version**:  0.36.6-alpha
- **OS Version / Instance**: AWS Linux
- **Deployment**: kubernetes
- **Source Connector and version**: postgres 0.4.14
- **Destination Connector and version**: Redshift 0.3.32
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
Sync attempt 0 failures.
Sync retry 1 succeeds.
Sync attempt 0 advanced the incremental cursor.
Sync attempt 1 skipped rows for incremental tables and was marked successful.

## Expected Behavior
Incremental syncs should not be advanced for failures. If they cannot be recovered automatically, then the sync itself should fail in a way that indicates to the user that the source needs to be reset to recover.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

Failed attempt: [logs-2048.txt](https://github.com/airbytehq/airbyte/files/8682302/logs-2048.txt)
Successful retry: [logs-2048 (1).txt](https://github.com/airbytehq/airbyte/files/8682303/logs-2048.1.txt)

## Steps to Reproduce
1. Start a sync job that uses postgres logical replication
2. Force a failure (not sure if type/timing matters)
3. Observe that recently added rows are skipped on the retry

## Are you willing to submit a PR?
This one is probably out of my depth...

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/airbyte/issues/12821
In this PR we are going to parse the debezium state and then compare the saved lsn from state with the replication slot's confirmed_flush_lsn . In a scenario where the source acknowledged the lsn on postgres server but airbyte sync failed cause of the destination or any other issue and we were not able to save the state in our DB, when the next sync starts, we will start from an older state and compare the older state with the replication slot's lsn. If replication slots lsn is ahead of our state then we would sync data from scratch.

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by subodh1810** [comment]
I have identified few more test cases that I would like to add to the PR but feel free to go ahead and review the implementation

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumPropertiesManager.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+
+  protected Properties getDebeziumProperties() {
+    final Properties props = new Properties();
+    props.putAll(properties);
+
+    // debezium engine configuration
+    props.setProperty("name", "engine");
+    props.setProperty("offset.storage", "org.apache.kafka.connect.storage.FileOffsetBackingStore");
+    props.setProperty("offset.storage.file.filename", offsetManager.getOffsetFilePath().toString());
+    props.setProperty("offset.flush.interval.ms", "1000"); // todo: make this longer
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumPropertiesManager.java:46]: should this be configurable? / what's preventing it from being longer right now?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+        Optional.empty());
+    final Properties debeziumProperties = debeziumPropertiesManager.getDebeziumProperties();
+    final OptionalLong savedOffset = parseSavedOffset(debeziumProperties);
+
+    if (savedOffset.isPresent()) {
+      if (replicationSlot.has("confirmed_flush_lsn")) {
+        final long confirmedFlushLsnOnServerSide = Lsn.valueOf(replicationSlot.get("confirmed_flush_lsn").asText()).asLong();
+        LOGGER.info("Replication slot confirmed_flush_lsn : " + confirmedFlushLsnOnServerSide + " Saved offset LSN : " + savedOffset.getAsLong());
+        return savedOffset.getAsLong() >= confirmedFlushLsnOnServerSide;
+      } else if (replicationSlot.has("restart_lsn")) {
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:60]: is restart_lsn actually sufficient? my understanding (from <30 seconds of google) is that this is some sort of extra info that's needed to read the wal log; is it always possible to read from exactly this position?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+  }
+
+  /**
+   *
+   * @param properties Properties should contain the relevant properties like path to the debezium
+   *        state file, etc. It's assumed that the state file is already initialised with the saved
+   *        state
+   * @return Returns the LSN that Airbyte has acknowledged in the source database server
+   */
+  private OptionalLong parseSavedOffset(final Properties properties) {
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:77]: I think the approach here makes sense, but it looks like we're depending on debezium internal behaviors. Are we putting ourselves at risk of really complicated debezium version upgrades? (I don't think it's avoidable, just want to check that we're OK with it)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+
+    FileOffsetBackingStore fileOffsetBackingStore = null;
+    OffsetStorageReaderImpl offsetStorageReader = null;
+    try {
+      fileOffsetBackingStore = new FileOffsetBackingStore();
+      final Map<String, String> propertiesMap = Configuration.from(properties).asMap();
+      propertiesMap.put(WorkerConfig.KEY_CONVERTER_CLASS_CONFIG, JsonConverter.class.getName());
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:84]: > `.class.getName()`

nice, this is much better than hardcoding the FQCN as a string

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+      propertiesMap.put(WorkerConfig.VALUE_CONVERTER_CLASS_CONFIG, JsonConverter.class.getName());
+      fileOffsetBackingStore.configure(new StandaloneConfig(propertiesMap));
+      fileOffsetBackingStore.start();
+
+      final JsonConverter keyConverter = new JsonConverter();
+      keyConverter.configure(Configuration.from(properties).subset("internal.key.converter" + ".", true).asMap(), true);
+      final JsonConverter valueConverter = new JsonConverter();
+      // Make sure that the JSON converter is configured to NOT enable schemas ...
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:92]: why is this necessary? (would be nice to have that as part of the comment)

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+      LOGGER.info("No previous offsets found");
+      return OptionalLong.empty();
+    }
+
+    final Offsets<Partition, PostgresOffsetContext> of = Offsets.of(offsets);
+    final PostgresOffsetContext previousOffset = of.getTheOnlyOffset();
+
+    final Map<String, ?> offset = previousOffset.getOffset();
+
+    if (offset.containsKey(LAST_COMMIT_LSN_KEY)) {
```
Comment (edgao) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:142]: do these different keys have different semantics? Or are they just connector-specific?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java (hunk 3 above)
Comment (subodh1810) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:77]: As long as debezium doesnt introduce a breaking change in the structure of the state, we should be fine. We upgraded from 1.4 to 1.9 and there was no breaking change in the structure of the state that debezium stores so this logic would have stayed the same in that upgrade.

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java (hunk 2 above)
Comment (subodh1810) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:60]: We should always rely on `confirmed_flush_lsn` cause its the point which debezium acknowledged on the postgres source server has read and processed wal logs. In some versions of postgres DB `confirmed_flush_lsn` might not be present. In that case we rely on `restart_lsn`. `restart_lsn` is basically the oldest available wal position.

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumPropertiesManager.java (hunk 1 above)
Comment (subodh1810) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumPropertiesManager.java:46]: I wouldnt want users to configure this. Its basically how often we want debezium to flush the state in the file. Debezium may or may not flush it though. It will try to but its based on other factors as well. The lower the value the lower the performance in wal processing. We never got back to finalising the right value. Also it would be out of scope for this PR

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java (hunk 6 above)
Comment (subodh1810) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:142]: So debezium state can differ in structure based on when the state is being generated. For instance here is the state that's generated after debezium is done with initial snapshot
```
{"last_snapshot_record":true,"lsn":23897640,"txId":505,"ts_usec":1658821300732000,"snapshot":true}
```
as you can see it doesnt have `lsn_commit` attribute, it only has `lsn` 

But here is the state when debezium switches to wal log processing
```
{"transaction_id":null,"lsn_proc":23906656,"lsn_commit":23904168,"lsn":23906656,"txId":528,"ts_usec":1658824891856537}
```
In this case you can see `lsn_commit` is present. So depending on the state structure we determine which attribute should we rely on.

**Review by edgao — APPROVED** [review]
chatted offline, LGTM pending code comments

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java (hunk 6 above)
Comment (tuliren) [reply airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:142]: By the way, what does `lsn` in the second state mean? I cannot find any documentation about this one.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java [hunk 7]
```diff
@@ -284,17 +293,34 @@ public List<AutoCloseableIterator<AirbyteMessage>> getIncrementalIterators(final
...
+        LOGGER.warn("Saved offset is before Replication slot's confirmed_flush_lsn, Airbyte will trigger sync from scratch");
+      }
+
       final AirbyteDebeziumHandler handler = new AirbyteDebeziumHandler(sourceConfig,
           PostgresCdcTargetPosition.targetPosition(database), false, firstRecordWaitTime);
       final PostgresCdcStateHandler postgresCdcStateHandler = new PostgresCdcStateHandler(stateManager);
       final List<ConfiguredAirbyteStream> streamsToSnapshot = identifyStreamsToSnapshot(catalog, stateManager);
       final Supplier<AutoCloseableIterator<AirbyteMessage>> incrementalIteratorSupplier = () -> handler.getIncrementalIterators(catalog,
-          new PostgresCdcSavedInfoFetcher(stateManager.getCdcStateManager().getCdcState()),
+          new PostgresCdcSavedInfoFetcher(savedOffsetAfterReplicationSlotLSN ? stateManager.getCdcStateManager().getCdcState() : null),
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java:318]: When `savedOffsetAfterReplicationSlotLSN` is `false`, the data should be synced from scratch. However, it is not obvious to me which line of code is triggering this behavior. We are not creating new snapshot iterators when `savedOffsetAfterReplicationSlotLSN` is `false`.

Is that the incremental iterator constructed here will sync everything when the offset does not exist?

File: airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+        LOGGER.info("Replication slot confirmed_flush_lsn : " + confirmedFlushLsnOnServerSide + " Saved offset LSN : " + savedOffset.getAsLong());
+        return savedOffset.getAsLong() >= confirmedFlushLsnOnServerSide;
+      } else if (replicationSlot.has("restart_lsn")) {
+        final long restartLsn = Lsn.valueOf(replicationSlot.get("restart_lsn").asText()).asLong();
+        LOGGER.info("Replication slot restart_lsn : " + restartLsn + " Saved offset LSN : " + savedOffset.getAsLong());
+        return savedOffset.getAsLong() >= restartLsn;
+      }
+    }
+
+    return true;
```
Comment (tuliren) [inline airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/PostgresDebeziumStateUtil.java:67]: Can you add a comment why it is safe to return `true` when the offset does not exist?

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java [hunk 9]
```diff
@@ -514,4 +516,59 @@ public void newTableSnapshotTest() throws Exception {
...
+    final JsonNode state = Jsons.jsonNode(stateAfterFirstBatch);
+    final AutoCloseableIterator<AirbyteMessage> secondBatchIterator = getSource()
+        .read(getConfig(), CONFIGURED_CATALOG, state);
+    final List<AirbyteMessage> dataFromSecondBatch = AutoCloseableIterators
+        .toListAndClose(secondBatchIterator);
+    final List<AirbyteStateMessage> stateAfterSecondBatch = extractStateMessages(dataFromSecondBatch);
+
+    final Set<AirbyteRecordMessage> recordsFromSecondBatch = extractRecordMessages(
+        dataFromSecondBatch);
+    final JsonNode stateAfterSecond = Jsons.jsonNode(stateAfterSecondBatch);
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java:550]: `stateAfterSecond`, `recordsFromSecondBatch`, and `stateAfterSecondBatch` are not used in any assertion. If no assertion is needed, these variables can be deleted.

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java [hunk 10]
```diff
@@ -514,4 +516,59 @@ public void newTableSnapshotTest() throws Exception {
...
+    }
+
+    // Triggering sync with the first sync's state only which would mimic a scenario that the second sync failed on destination end and we didn't save state
+    final AutoCloseableIterator<AirbyteMessage> thirdBatchIterator = getSource()
+        .read(getConfig(), CONFIGURED_CATALOG, state);
+
+    final List<AirbyteMessage> dataFromThirdBatch = AutoCloseableIterators
+        .toListAndClose(thirdBatchIterator);
+
+    final List<AirbyteStateMessage> stateAfterThirdBatch = extractStateMessages(dataFromThirdBatch);
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java:567]: `stateAfterThirdBatch` is not used in any assertion. Maybe adding an assertion that the state message should be the same as the one after the first sync?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java (hunk 7 above)
Comment (subodh1810) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java:318]: Yup. The incremental iterator will sync everything from scratch cause debezium will look at the state and see it's null

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java (hunk 10 above)
Comment (subodh1810) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java:567]: It wouldn't be the same since the lsn value in the state would be ahead cause a bunch of records have been written in the database after the first sync
