### PR TITLE
7198: SSH Tunnel: allow using OPENSSH key format

### LINKED ISSUE #7198: SSH Tunnel: allow using OPENSSH key format
## Enviroment
- **Airbyte version**:  Cloud
- **Source Connector and version**: postgres
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Create a Source

## Current Behavior
Airbyte uses BouncyCastle to validate the SSH key. Some users want to use the OPENSSH format and its not supported.

## Expected Behavior
I want to use OPENSSH keys when trying to connect using SSH tunnels.

## Logs
```
2021-10-19 21:56:09 INFO  2021-10-19 21:56:09 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - {} - Starting connection with method: SSH_KEY_AUTH
2021-10-19 21:56:17 ERROR Exception in thread "main" java.lang.RuntimeException: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:286)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.<init>(SshTunnel.java:134)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getInstance(SshTunnel.java:185)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:204)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:37)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.check(SpecModifyingSource.java:38)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.source.postgres.PostgresSourceStrictEncrypt.main(PostgresSourceStrictEncrypt.java:34)
2021-10-19 21:56:17 ERROR Caused by: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getPrivateKeyPair(SshTunnel.java:234)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:267)
2021-10-19 21:56:17 ERROR 	... 7 more
```
## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by kimerinn**
## What
This closes #7198 .
Allows to use nonencrypted OPENSSH keys for SSH tunneling

## How
Use sshlib library to deal with OPENSSH keys
[github.com/connectbot/sshlib](https://github.com/connectbot/sshlib)

## Recommended reading order
1. airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/ssh/SshTunnel.java

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by grishick** [comment]
asking @rodireich to review this together with https://github.com/airbytehq/airbyte/pull/15635 and https://github.com/airbytehq/airbyte/issues/15529 in order to avoid these PRs breaking each other

**Comment by rodireich** [comment]
This can be done with BouncyCastle I think. 
See [OpenSSHPrivateKeyUtil.parsePrivateKeyBlob](https://javadoc.io/static/org.bouncycastle/bcprov-jdk14/1.67/org/bouncycastle/crypto/util/OpenSSHPrivateKeyUtil.html)

**Comment by alexandr-shegeda** [comment]
@rodireich can you take a look at the comment from @kimerinn?
cc @grishick

**Comment by rodireich** [comment]
The following code will turn an SSH-Ed25519 pairkey into java security's KeyPair using Bouncycastle:
```final byte[] keyContent = pemObject.getContent();
final byte[] keyContent = pemObject.getContent();
final var pkp = OpenSSHPrivateKeyUtil.parsePrivateKeyBlob(keyContent);
if (pkp instanceof Ed25519PrivateKeyParameters) {
            final Ed25519PublicKeyParameters pubKeyParam = ((Ed25519PrivateKeyParameters) pkp).generatePublicKey();
            final AsymmetricCipherKeyPair ackp = new AsymmetricCipherKeyPair(pubKeyParam, pkp);
            final byte[] pkcs8Encoded = PrivateKeyInfoFactory.createPrivateKeyInfo(ackp.getPrivate()).getEncoded();
            final PKCS8EncodedKeySpec pkcs8EncodedKeySpec = new PKCS8EncodedKeySpec(pkcs8Encoded);
            final byte[] spkiEncoded = SubjectPublicKeyInfoFactory.createSubjectPublicKeyInfo(ackp.getPublic()).getEncoded();
            final X509EncodedKeySpec spkiKeySpec = new X509EncodedKeySpec(spkiEncoded);
            final KeyFactory keyFac = KeyFactory.getInstance("Ed25519", "BC");
            return new KeyPair(keyFac.generatePublic(spkiKeySpec), keyFac.generatePrivate(pkcs8EncodedKeySpec));
}```
However we need support other subtypes of OPENSSH keys - mainly the legacy format SSH-RSA.

I'm assigning it to myself to complete implementation if that's OK @kimerinn , @alexandr-shegeda

**Comment by rodireich** [comment]
@kimerinn I'm not sure why it doesn't let me add you as a reviewer

File: airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java [hunk 1]
```diff
@@ -4,18 +4,96 @@
...
+import java.util.Arrays;
 import org.apache.sshd.common.util.security.SecurityUtils;
 import org.apache.sshd.common.util.security.eddsa.EdDSASecurityProviderRegistrar;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.ValueSource;
 
 class SshTunnelTest {
 
+  private static final String SSH_ED25519_PRIVATE_KEY = "-----BEGIN OPENSSH PRIVATE KEY-----\\n"
```
Comment (ryankfu) [inline airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java:26]: Should this information be placed into a separate file? The gut feeling is that maybe this shouldn't just be openly visible in a test file. There are private keys stored in separate files: https://github.com/airbytehq/airbyte/blob/7aa7a373db6d9072d2642b57dbdb42ef47f92234/tools/integrations-test-ssl/mssql.key

File: airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/ssh/SshTunnel.java [hunk 2]
```diff
@@ -231,13 +229,12 @@ public void close() {
...
    * the keys from the key info, and return the key pair for use in authentication.
    */
-  private KeyPair getPrivateKeyPair() throws IOException {
-    final PEMParser pemParser = new PEMParser(new StringReader(validateKey()));
-    final PEMKeyPair keypair = (PEMKeyPair) pemParser.readObject();
-    final JcaPEMKeyConverter converter = new JcaPEMKeyConverter();
-    return new KeyPair(
-        converter.getPublicKey(SubjectPublicKeyInfo.getInstance(keypair.getPublicKeyInfo())),
-        converter.getPrivateKey(keypair.getPrivateKeyInfo()));
+  KeyPair getPrivateKeyPair() throws IOException, GeneralSecurityException {
```
Comment (ryankfu) [inline airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/ssh/SshTunnel.java:232]: Is there a reason this is no longer `private` and if so how come? 

Minor nit: not a fan of using `kp` as a variable name since it's not abundantly clear what that means. I presume it means `keypair`

**Review by ryankfu — APPROVED** [review]
Left some minor comments to address but overall looks good

File: airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/ssh/SshTunnel.java (hunk 2 above)
Comment (rodireich) [reply airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/ssh/SshTunnel.java:235]: This is required for testing. Reduced visibility to package private, and changed name.
thanks!

File: airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java (hunk 1 above)
Comment (rodireich) [reply airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java:28]: These are all random keys created with `ssh-keygen -t rsa` and `ssh-keygen -t ed25519`. 
No actual secrets.

Comment (rodireich) [reply airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java:28]: Added link do doc
