### PR TITLE
🪟 🧹 Display returned error messages on replication view

### LINKED ISSUE #16244: Replication settings show "Invalid fields" message when a 403 error is returned after trying to save updates
This may impact cloud scenarios, but the wording is not correct.  When this endpoint is called `/api/v1/web_backend/connections/update` (the one used to save the connection,) we see:

image

But the actual error is a 403, not a validation error. This may also happen with other error codes, but only checked with the 403.

https://github.com/airbytehq/airbyte/blob/c2c276d1a44d8e208aa0fe0897e8edb88053479e/airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx#L359

## Steps to reproduce

1. Go to a connection replication settings
2. Disable some streams
3. Save

### PR DESCRIPTION
**Pull request by teallarson**
## What
closes https://github.com/airbytehq/airbyte/issues/16244

Previously, we would always display a generic "Form is invalid" error for all error messages on Replication View due to bad ternary logic.

Now, we return whatever we get back _or_ the standard validation error.

Success message unchanged:
Screen Shot 2022-09-07 at 6 33 54 PM

Validation message unchanged:
Screen Shot 2022-09-07 at 6 31 07 PM

Now show whatever was returned as the error message, including truncating it with CSS if it is excessively long:
Screen Shot 2022-09-07 at 6 31 41 PM

## How
- Fixed the bad ternary
- Also migrated the ConnectionForm EditControls to scss modules and using our variables, Text component, etc.

## Recommended reading order
1. `ConnectionForm.tsx`
2. others

### CODE REVIEW

File: airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx [hunk 1]
```diff
@@ -376,7 +378,11 @@ export const ConnectionForm: React.FC<ConnectionFormProps> = ({
                 isSubmitting={isSubmitting}
                 isValid={isValid && !editingTransformation}
                 errorMessage={
-                  errorMessage || !isValid ? formatMessage({ id: "connectionForm.validation.error" }) : null
+                  errorMessage
+                    ? errorMessage
+                    : !isValid
+                    ? formatMessage({ id: "connectionForm.validation.error" })
+                    : null
```
Comment (krishnaglick) [inline airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx:385]: I feel like, since this is repeated, you can just do an:
`const displayedErrorMessage = errorMessage ?? !isValid ? formatMessage({ id: "connectionForm.validation.error" }) : null;`
and use that in both places

Comment (lmossman) [reply airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx:385]: +1

**Review by krishnaglick — APPROVED** [review]
Tested locally, LGTM. Merge on green!

File: airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.module.scss [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+.controlButton {
+  margin-left: variables.$spacing-md;
+}
+
+// currently only implemented on transformation view form card, margins are specific to that implementation
+// todo: standardize the margin sizes here
+.line {
+  min-width: 100%;
+  height: variables.$border-thin;
+  background: colors.$grey;
```
Comment (edmundito) [inline airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.module.scss:23]: This should be `$grey-100`.
