### PR TITLE
🎉 Source Postgres: support all Postgres 14 types

### LINKED ISSUE #4071: Source Postres: Connector provides wrong values for some datatypes
Found by comprehensive tests #3562

## Expected Behavior
A connector should transform source data into an Airbyte datatype without value/meaning losses.

## Current Behavior
General source implementation:
- [x] `bit`. Returns values `true`, `false` instead of `1`, `0`. Also can't handle values like this "B'101'"
- [ ] #8903
- [ ] #8902
- [x] 'money'. The Money type fails when amount is > 1,000. at the JdbcUtils-> rowToJson -> r.getObject(i); with the reason "Bad value for type double : 1,000.01". The reason is that in jdbc implementation money type is tried to get as Double (jdbc internal  implementation for rs.getObject(). JDBC driver also returns Double for getObjectType(), but "Money" in "getMetaData()" ). Meanwhile  Max values for Money type in Postres : "-92233720368547758.08", "92233720368547758.07"
- [x] 'numeric', 'decomal'. Numeric and decimal types in Postres may contain 'Nan' type, but in JdbcUtils-> rowToJson we currently try to map it like this, so it fails
"case NUMERIC, DECIMAL -> o.put(columnName, nullIfInvalid(() -> r.getBigDecimal(i)));"
- [x] 'time', 'timetz'. Time only (ex. 04:05:06) would be represented like "1970-01-01T04:05:06Z" which is incorrect. This causes as  JdbcUtils-> DATE_FORMAT is set as ""yyyy-MM-dd'T'HH:mm:ss'Z'"" for both Date and Time types.

## Steps to Reproduce
Short way:
1. Checkout master branch
2. Go to `CdcPostgresSourceComprehensiveTest.java` and "PostresSourceComprehensiveTest.java" and find test with appropriate types. Use example values from comment to insert to addInsertValues and addExpectedValues
4. Run the test.
5. :bomb: 
NOTES: To REMEMBER while fixing this bug: Most of the cases would need to be corrected at JdbcUtils, but this is based class that is used by all others JDBC DBs, i.e. all other JDBC DBs will be affected

## Severity of the bug for you
High

## Airbyte Version
0.24.7-alpha

## Connector Version
0.3.3

### LINKED ISSUE #7727: Support all types in PostgreSQL source
Double check that we support and have unit tests for every data types for PostgreSQL 14:

https://www.postgresql.org/docs/14/datatype.html

### LINKED ISSUE #7871: Source Postgres: DB values '-Infinity', 'Infinity', 'Nan' are parsed as null
## Current Behavior
**float8,  double precision, float, numeric, decimal, real**: Values '-Infinity', 'Infinity', 'Nan' will not be parsed correctly. Parsed values for all of them are `null`.
Please see:
`case NUMERIC, DECIMAL -> o.put(columnName, nullIfInvalid(() -> r.getBigDecimal(i)));`

## Expected Behavior
Values '-Infinity', 'Infinity', 'Nan' should not be parsed as `null`

### LINKED ISSUE #7905: Source Postgres: parsed value for type 'bytea' is encoded by Base64
## Current Behavior
The value stored in DB is 4, parsed value in Airbyte is ‘EjQ=’
The represented value is encoded by Base64

## Expected Behavior
The represented value should be the same as in DB 

## Steps to Reproduce
1. Go to PostresSourceDatatypeTest.class:
2. Add insert values and verify them in DB
3. Add expected values the same as in DB
4. Run tests

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Support all Postgres types.
- Except two remaining issues that we need to confirm on the destination side if the solution works:
  - https://github.com/airbytehq/airbyte/issues/8903
  - https://github.com/airbytehq/airbyte-internal-issues/issues/358

## How
- Postgres does not have a public type enum. So the MySQL approach won't work for Postgres.
- We use `JDBCType` for most of the types. For corner cases, we check the column type name returned from JDBC, and treat them differently.

## Recommended reading order
1. `PostgresSourceDatatypeTest.java`
2. `PostgresSourceOperations.java`

## 🚨 User Impact 🚨
- This PR changes some of the Postgres data types. It is published with a minor version bump.

### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java [hunk 1]
```diff
@@ -221,48 +224,43 @@ protected void initTests() {
...
         TestDataHolder.builder()
-            .sourceType("double_precision")
-            .fullSourceDataType("double precision")
-            .airbyteType(JsonSchemaPrimitive.NUMBER)
-            .addInsertValues("'123'", "'1234567890.1234567'", "null")
-            .addExpectedValues("123.0", "1.2345678901234567E9", null)
+            .sourceType("date")
+            .airbyteType(JsonSchemaPrimitive.STRING)
+            .addInsertValues("'1999-01-08'", "null")
+            .addExpectedValues("1999-01-08T00:00:00Z", null)
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java:242]: I reverted the change that returns a pure date (without the time portion), because I have not verified that this is a safe change.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 2]
```diff
@@ -49,12 +70,106 @@ public JsonNode rowToJson(final ResultSet queryContext) throws SQLException {
...
+
+    // ResultSet#getBigDecimal cannot handle Infinity, -Infinity, or NaN, and will throw exception,
+    // which becomes null. So we need to check these special values as string.
+    final String value = resultSet.getString(index);
+    if (value.equalsIgnoreCase("infinity")) {
+      node.put(columnName, Double.POSITIVE_INFINITY);
+    } else if (value.equalsIgnoreCase("-infinity")) {
+      node.put(columnName, Double.NEGATIVE_INFINITY);
+    } else if (value.equalsIgnoreCase("nan")) {
+      node.put(columnName, Double.NaN);
```
Comment (sherifnada) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:161]: does json have a concept of infinity and Nan? how are these represented when output from the connector itself?

**Review by sherifnada — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 2 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:163]: Good catch. Actually Json numbers do not support `NaN` or infinity. To support these three special values, we need to make sure that the destination can handle them. Otherwise, the destination will fail. Too bad, I need to revert this.

Comment (ChristopheDuong) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: like how we currently handle dates, you can output them in a string type with a format hint.

Then have normalization handle the special format hint for these special numbers accordingly for the destination

Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: @ChristopheDuong, nice.

Where the code that handles this? I'd like to see what the format hint looks like.

Comment (ChristopheDuong) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: In the json, it's "string" type.

Then, on normalization, if we find a format hint, we know it's actually a date not a string:
https://github.com/airbytehq/airbyte/blob/c5fc568061f00b99dac9ec3f0f1573e3a30c096a/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/utils.py#L33

Comment (ChristopheDuong) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: Example of catalog.json with date:
https://github.com/airbytehq/airbyte/blob/c5fc568061f00b99dac9ec3f0f1573e3a30c096a/airbyte-integrations/bases/base-normalization/integration_tests/resources/test_simple_streams/data_input/catalog.json#L17

so you can have a special string-float type instead of using json's number in order to encode special float values:

```
"db_float_column": {
  "type": "string",
  "format": "airbyte-float"
}
```
