### PR TITLE
Fix connection settings changing randomly

### LINKED ISSUE #14726: Name field should get a default value when creating a connection
## Environment
- **Airbyte version**:  0.39.34-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: OSS
- **Step where error happened**: Setup new connection

## Steps to Reproduce
1. Go to Connections -> Setup source -> Setup destination
2. Check the 'Name' field

## Current Behavior
The name field's value isn't pre-filled-out. Also isn't marked as mandatory.

## Expected Behavior
The name field's value is pre-filled-out and marked as mandatory.

image

### LINKED ISSUE #14844: Connection creation UI resets replication settings anytime there's any text input/edited
## Environment
- **Airbyte version**:  Cloud
- **Step where error happened**: Connection creation

## Current Behavior
Replication settings reset after adding or editing inputs or drop-downs above the `Activate the streams you want to sync` settings.

## Expected Behavior
replication settings to stay as the user intends after updating anything

## Logs

[Loom 1](https://www.loom.com/share/1895d7de050f48bbb3adc79a8e45563d)
[Loom 2](https://www.loom.com/share/85395c6c735d471a89de020647fe4c9e)

## Steps to Reproduce
1. Create new connection
2. Change tables and settings
3. Edit any input.

## Are you willing to submit a PR?

Possibly

### PR DESCRIPTION
**Pull request by timroes**
## What

Fixes #14844 
Fixes #14726

When trying to investigate #14844 with @tealjulia we found that the problems were caused by our logic that informs the parent components of `ConnectionForm` about the form values. Those were then calculated into a new `connection` property which was passed back to `ConnectionForm` and causing in there a reinitialization of the form. For that the `useInitialValues` hook was called and since it deteced that those values were now changed it recalculated a new sync catalog causing basically the whole catalog to reset on every change in any field.

We brainstormed for some time about a solution, and we believe the long term solution is to actually move the Formik handling one component up the tree (into the `CreateConnectionContent` and `ReplicationView` component respectively). Since this is a larger refactoring and we try to resolve the bug for now, we decided to revert the changes from https://github.com/airbytehq/airbyte/pull/13895. Those would reintroduce the previous behavior that refreshing the source schema while having a dirty form will reset all those changes in the form. We can't easily mitigate that given the current code structure, thus we decided to instead add a modal warning the user when they try to "Refresh Source Schema" while they still have a dirty form, that all their changes will get lost unless they save them beforehand.

screenshot-20220804-221006

Reverting the change also happened to fix #14726. Further issues for the refactoring will be created as part of #14174

### CODE REVIEW

File: airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx [hunk 1]
```diff
@@ -189,11 +181,33 @@ export const ReplicationView: React.FC<ReplicationViewProps> = ({ onAfterSaveSch
...
+    }
+  };
+
   const onCancelConnectionFormEdit = () => {
     setSaved(false);
     setActiveUpdatingSchemaMode(false);
   };
 
+  const onDirtyChanges = useCallback((dirty: boolean) => {
+    connectionFormDirtyRef.current = dirty;
```
Comment (timroes) [inline airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx:208]: :information_source: We track the dirty state in this component in a ref not state, since we don't require any rerendering of this component if this changes.

File: airbyte-webapp/src/locales/en.json [hunk 2]
```diff
@@ -330,6 +330,9 @@
   "connection.sourceTestAgain": "Test source connection again",
   "connection.resetData": "Reset your data",
   "connection.updateSchema": "Refresh source schema",
+  "connection.updateSchema.formChanged.title": "Unsaved changes",
+  "connection.updateSchema.formChanged.text": "Your replication settings have unsaved changes. Those will be lost when refreshing the source schema. Save your changes before refreshing the source schema to not lose them.",
+  "connection.updateSchema.formChanged.confirm": "Proceed anyway",
```
Comment (andyjih) [inline airbyte-webapp/src/locales/en.json:335]:
```suggestion
  "connection.updateSchema.formChanged.confirm": "Discard changes and confirm reset",
```

**Review by teallarson — APPROVED** [review]
Works as described.

I see a modal warning me that my changes will be overwritten when I go to refresh.

This is another reason it would be a great idea to move the Formik context up a level!
