### PR TITLE
Fix copy link to logs functionality

### LINKED ISSUE #15320: [webapp] Connection sync log link does not land on log component
## Environment
- **Airbyte version**:  v0.39.41-alpha
- **Step where error happened**: Connection Status Page

## Current Behavior
When opening the connection log link, the page does not scroll down to the log nor expands it

## Expected Behavior
When opening the connection log link, the page scrolls down to the log and expands it

## Steps to Reproduce
1. Open the airbyte webapp
2. Navigate to a connection with multiple syncs completed
3. Scroll to the last sync job, expand and click the copy link button
4. On a new browser tab or window, paste the link and go

### PR DESCRIPTION
**Pull request by timroes**
## What

Fixes #15320

This fixes the problem that linking to an individual log did not open that log or scroll to it anymore. The issue was that we tried to compare a string to a number, which typescript didn't see due to us casting in the `getJobId` method and therefore destroying the typesafteyness.

I've also removed the unused `shortInfo` property. I checked if we forgot to remove it when we didn't use that feature anymore, but it seems it got introduced in https://github.com/airbytehq/airbyte/pull/9585/files and simply was never used.

Since I got into some confusion around the StatusIcon component, I also made sure that `error` can be an explicitly passed in state now, to clarify what happens when you'd prior just use `<StatusIcon />` (this is slightly unrelated to the rest and if someone has an issue with having that in the same PR, I can separate it into two. Since both changes were really small, I had them in one for now.)

### CODE REVIEW

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 1]
```diff
@@ -32,28 +32,28 @@ const LoadLogs = styled.div`
...
 const didJobSucceed = (job: SynchronousJobReadWithStatus | JobsWithJobs) => {
   return getJobStatus(job) !== "failed";
 };
 
-export const getJobStatus: (job: SynchronousJobReadWithStatus | JobsWithJobs) => JobStatus = (job) => {
-  return (job as JobsWithJobs).job?.status ?? (job as SynchronousJobReadWithStatus).status;
+export const getJobStatus: (
+  job: SynchronousJobReadWithStatus | JobsWithJobs
+) => JobStatus | CheckConnectionReadStatus = (job) => {
+  return "status" in job ? job.status : job.job.status;
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:45]: :information_source: The casting also caused TypeScript to lose the real return type here, so changed this as well.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 2]
```diff
@@ -32,28 +32,28 @@ const LoadLogs = styled.div`
...
 
-export const getJobId = (job: SynchronousJobReadWithStatus | JobsWithJobs) =>
-  (job as SynchronousJobReadWithStatus).id ?? (job as JobsWithJobs).job.id;
+export const getJobId = (job: SynchronousJobReadWithStatus | JobsWithJobs) => ("id" in job ? job.id : job.job.id);
 
-export const JobItem: React.FC<JobItemProps> = ({ shortInfo, job }) => {
+export const JobItem: React.FC<JobItemProps> = ({ job }) => {
   const { jobId: linkedJobId } = useAttemptLink();
-  const [isOpen, setIsOpen] = useState(linkedJobId === getJobId(job));
+  const [isOpen, setIsOpen] = useState(linkedJobId === String(getJobId(job)));
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:56]: :information_source: This is the actual fix, that restores that behavior.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 3]
```diff
@@ -32,28 +32,28 @@ const LoadLogs = styled.div`
 `;
 
 interface JobItemProps {
-  shortInfo?: boolean;
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:35]: :information_source: This was never passed into this component, so removed it.

File: airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx [hunk 4]
```diff
@@ -20,20 +20,22 @@ interface StatusIconProps {
 
 const getBadgeWidth = (props: StatusIconProps) => (props.big ? (props.value ? 57 : 40) : props.value ? 37 : 20);
 
-const _iconByStatus: Partial<Record<StatusIconStatus, IconDefinition | undefined>> = {
+const _iconByStatus = {
```
Comment (timroes) [inline airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx:23]: :information_source: By changing this just to a `as const`, TypeScript understands which keys exactly exist in this, unless beforehand where it always suspected accessing something in here could also be `undefined`.

File: airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx [hunk 5]
```diff
@@ -44,8 +46,8 @@ const Container = styled.div<StatusIconProps>`
   vertical-align: middle;
 `;
 
-const Badge = styled(Container)<StatusIconProps>`
-  background: ${(props) => props.theme[(props.status && _themeByStatus[props.status]) || "dangerColor"]};
+const Badge = styled(Container)<{ status: Exclude<StatusIconStatus, "loading"> }>`
```
Comment (timroes) [inline airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx:49]: :information_source: Just require the properties that are actually used here (and in the `Pick` above), can simplify that code, since it understands that `theme[...]` cannot be undefined anymore.

File: airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx [hunk 6]
```diff
@@ -66,7 +68,7 @@ const Value = styled.span`
   padding-left: 3px;
 `;
 
-const StatusIcon: React.FC<StatusIconProps> = ({ title, status, ...props }) => {
+const StatusIcon: React.FC<StatusIconProps> = ({ title, status = "error", ...props }) => {
```
Comment (timroes) [inline airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx:71]: :information_source: Make `error` the default status, to not need to adjust all places this was used without a status.

**Review by edmundito — COMMENTED** [review]
Tested it locally and the job expands but for some reason it doesn't scroll as implemented in
https://github.com/airbytehq/airbyte/blob/4d84bdb8828f0fe03a9d51f699c723376bda64df/airbyte-webapp/src/components/JobItem/JobItem.tsx#L65-L72

**Comment by timroes** [comment]
@edmundito thanks for finding this. There was one small issue within the `if`, but the problem also is, that this doesn't work calling this without any timout, since the page hasn't finished rendering. I've played a bit around with timeouts and you need unfortunately to get up to a second to delay to make this work somewhat reliable. So I added a second delay before scrolling to the element. Alternatively if we consider this solution to be too hacky, we could remove the scrolling code altogether.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 7]
```diff
@@ -32,28 +32,28 @@ const LoadLogs = styled.div`
...
+  return "status" in job ? job.status : job.job.status;
 };
 
 export const getJobAttemps: (job: SynchronousJobReadWithStatus | JobsWithJobs) => AttemptRead[] | undefined = (job) => {
   return "attempts" in job ? job.attempts : undefined;
 };
 
-export const getJobId = (job: SynchronousJobReadWithStatus | JobsWithJobs) =>
-  (job as SynchronousJobReadWithStatus).id ?? (job as JobsWithJobs).job.id;
+export const getJobId = (job: SynchronousJobReadWithStatus | JobsWithJobs) => ("id" in job ? job.id : job.job.id);
```
[the remark this answers is not in the document]
Comment (krishnaglick) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:52]: When I was initially going through here I thought there was a bug. But no, we unfortunately get back both from the backend :/

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 8]
```diff
@@ -63,24 +63,25 @@ export const JobItem: React.FC<JobItemProps> = ({ shortInfo, job }) => {
...
+        scrollAnchor.current?.scrollIntoView({
+          behavior: "smooth",
+          block: "start",
+        });
+      }, 1000);
+      return () => {
+        window.clearTimeout(timeout);
+      };
     }
+    return undefined;
```
Comment (krishnaglick) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:79]: https://reactjs.org/docs/hooks-reference.html#uselayouteffect
?

Comment (timroes) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:79]: This unfortunately doesn't help (I barely ever had a case where useLayoutEffect actually helped :D). This will just cause it to slip into the execution slot after the next rendering, which unfortunately isn't enough in this case. There is just too much (async) rendering still ongoing, that even setting a timeout of like 300ms isn't enough to get this work. Tested also with `useLayoutEffect` and it does neither scroll (without the high timeout).

Comment (edmundito) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:79]: @krishnaglick https://eslint.org/docs/latest/rules/consistent-return but sometimes it's tricky with use effect calls. Alternative I do:

```ts
if (linkedJobId !== String(getJobId(job))) {
  return;
}

// ...The actual code that returns a function here...

return () => ...
```

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 9]
```diff
@@ -63,24 +63,25 @@ export const JobItem: React.FC<JobItemProps> = ({ shortInfo, job }) => {
   };
 
   useEffectOnce(() => {
-    if (linkedJobId) {
-      scrollAnchor.current?.scrollIntoView({
-        behavior: "smooth",
-        block: "start",
-      });
+    if (linkedJobId === String(getJobId(job))) {
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:66]: Alternatively, I make this a negative check and return, then the rest of the code that returns the function.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 10]
```diff
@@ -63,24 +63,25 @@ export const JobItem: React.FC<JobItemProps> = ({ shortInfo, job }) => {
...
+      // We need to wait here a bit, so the page has a chance to finish rendering, before starting to scroll
+      // since otherwise this scroll won't really do anything.
+      const timeout = window.setTimeout(() => {
+        scrollAnchor.current?.scrollIntoView({
+          behavior: "smooth",
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:71]: Nit: Not a huge fan of smooth behavior because it feels like my page is being scrolled by a ghost!

File: airbyte-webapp/src/components/JobItem/JobItem.tsx (hunk 8 above)
Comment (krishnaglick) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:79]: I don't think it's a _better_ idea, but could do a `setInterval(() => {}, 100)` that runs until it's loaded.

Comment (timroes) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:79]: We unfortunately also don't have a way to determine whether it's loaded in that sense. The DOM reference IS there from thebeginning and mounted, so there is no clear way to determine that the browser is done with rendering everything around it.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx (hunk 10 above)
Comment (timroes) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx:71]: Happy to remove it. Thought especially with the delay it might not suddenly jump, but I don't have any strong feelings in either direction :)

File: airbyte-webapp/src/components/JobItem/JobItem.tsx (hunk 8 above)
Comment (krishnaglick) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx]: We do!
Screen Shot 2022-08-08 at 4 17 11 PM
Screen Shot 2022-08-08 at 4 17 29 PM

Can fiddle with exact implementation, but I think this is a nice solution no?

Comment (timroes) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx]: Oh good call. Yeah we def can use the animationComplete there to trigger the scroll to. Will change this tomorrow.

Comment (krishnaglick) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx]: I can push this if you'd like

Comment (krishnaglick) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx]: Pushed to `kc/fix-link-to-logs`

**Review by edmundito — APPROVED** [review]
Tested locally.

File: airbyte-webapp/src/components/JobItem/JobItem.tsx (hunk 8 above)
Comment (timroes) [reply airbyte-webapp/src/components/JobItem/JobItem.tsx]: Added this to this PR, as discussed offline this won't work in Chrome (on Linux) apparently, but since it'll work in Firefox stable, we'll still keep this code in.
