### PR TITLE
Handle correctly full refresh streams.

### LINKED ISSUE #28363: ctid with cursor: Sync containing both incremental and full refresh streams will fail to sync
Configuring a catalog containing both full refresh and incremental streams results in the following error when attempting to run sync:
```
2023-07-17 15:59:17 source > INFO i.a.i.s.p.PostgresQueryUtils(lambda$getCursorBasedSyncStatusForStreams$4):153 Querying max cursor value for public.snowflake_1tb
2023-07-17 15:59:17 source > ERROR i.a.i.b.s.SshWrappedSource(read):76 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:39) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:100) ~[guava-31.1-jre.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresQueryUtils.lambda$getCursorBasedSyncStatusForStreams$4(PostgresQueryUtils.java:168) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.airbyte.integrations.source.postgres.PostgresQueryUtils.getCursorBasedSyncStatusForStreams(PostgresQueryUtils.java:143) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresSource.getIncrementalIterators(PostgresSource.java:591) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresSource.getIncrementalIterators(PostgresSource.java:127) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:161) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.50.7.jar:?]
	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:74) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.7.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:139) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.7.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.7.jar:?]
	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:698) ~[io.airbyte.airbyte-integrations.connectors-source-postgres-0.50.7.jar:?]
Stack Trace: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:39)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:100)
```

Analysis: the full refresh stream is incorrectly classified as a ctid stream and causes a failure since there's no cursor defined.

### PR DESCRIPTION
**Pull request by rodireich**
Handle full refresh (currently blocked in ui). remove unnecessary debug logs.
Closes #28363

### CODE REVIEW

**Comment by rodireich** [comment]
@akashkulk and @nguyenaiden please take a look
I'm adding tests

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`2e81703e58`](https://github.com/airbytehq/airbyte/pull/28369/commits/2e81703e5891fe7b40a136b76f8da2a7b89c1860)) - ❌

⏲️  Total pipeline duration: 17mn38s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689621254/2e81703e5891fe7b40a136b76f8da2a7b89c1860/source-postgres/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`2e81703e58`](https://github.com/airbytehq/airbyte/pull/28369/commits/2e81703e5891fe7b40a136b76f8da2a7b89c1860)) - ❌

⏲️  Total pipeline duration: 06mn43s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689621254/2e81703e5891fe7b40a136b76f8da2a7b89c1860/source-alloydb/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`2e81703e58`](https://github.com/airbytehq/airbyte/pull/28369/commits/2e81703e5891fe7b40a136b76f8da2a7b89c1860)) - ❌

⏲️  Total pipeline duration: 06mn33s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build source-alloydb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689621254/2e81703e5891fe7b40a136b76f8da2a7b89c1860/source-alloydb-strict-encrypt/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`2e81703e58`](https://github.com/airbytehq/airbyte/pull/28369/commits/2e81703e5891fe7b40a136b76f8da2a7b89c1860)) - ❌

⏲️  Total pipeline duration: 08mn46s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689621254/2e81703e5891fe7b40a136b76f8da2a7b89c1860/source-postgres-strict-encrypt/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`a428f71b9f`](https://github.com/airbytehq/airbyte/pull/28369/commits/a428f71b9f646a635608a047ec1d4e43f5913a8e)) - ❌

⏲️  Total pipeline duration: 06mn14s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689623760/a428f71b9f646a635608a047ec1d4e43f5913a8e/source-postgres-strict-encrypt/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`a428f71b9f`](https://github.com/airbytehq/airbyte/pull/28369/commits/a428f71b9f646a635608a047ec1d4e43f5913a8e)) - ❌

⏲️  Total pipeline duration: 04mn20s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build source-alloydb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689623760/a428f71b9f646a635608a047ec1d4e43f5913a8e/source-alloydb-strict-encrypt/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`a428f71b9f`](https://github.com/airbytehq/airbyte/pull/28369/commits/a428f71b9f646a635608a047ec1d4e43f5913a8e)) - ❌

⏲️  Total pipeline duration: 04mn38s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689623760/a428f71b9f646a635608a047ec1d4e43f5913a8e/source-alloydb/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Review by nguyenaiden — APPROVED** [review]
+1. Looks good. Non-blocking: we should add an e2e test to verify this behavior as well, but the unit stream categorization tests gives me enough confidence for us to roll this out.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java [hunk 1]
```diff
@@ -80,12 +81,18 @@ public static StreamsCategorised<CursorBasedStreams> categoriseStreams(final Sta
 
     final List<ConfiguredAirbyteStream> newlyAddedStreams = identifyNewlyAddedStreams(fullCatalog, alreadySeenStreamPairs);
     final List<ConfiguredAirbyteStream> streamsForCtidSync = getStreamsFromStreamPairs(fullCatalog, stillInCtidStreamPairs);
-    streamsForCtidSync.addAll(newlyAddedStreams);
-
-    final List<ConfiguredAirbyteStream> streamsForCursorBasedSync = getStreamsFromStreamPairs(fullCatalog, cursorBasedSyncStreamPairs);
+    final List<ConfiguredAirbyteStream> streamsForCursorBasedOrFullRefreshSync = getStreamsFromStreamPairs(fullCatalog, cursorBasedSyncStreamPairs);
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: Can we just modify streams from stream pairs to return streams that are only in incremental mode?

IIUC the issue here is that a full refresh mode follows a different path and full refresh is handled by another path, so I'm think we don't need to specifically care about those streams here. `AbstractDbSource.getFullRefreshIterators` and we are not filtering out the full refresh streams here?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java [hunk 2]
```diff
@@ -84,14 +85,15 @@ public static StreamsCategorised<XminStreams> categoriseStreams(final StateManag
         .map(Jsons::clone)
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java:85]: Can we modify CtidUtils.identifyNewlyAddedStreams to filter for incremental streams?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java (hunk 1 above)
Comment (nguyenaiden) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: The FullRefresh path is actually handled when the stream is passed to `super.getIncrementalIterators`. So we would need to know which stream from `newlyAddedStreams` is FullRefresh or not.

**Review by akashkulk — CHANGES_REQUESTED** [review]
Do the same changes apply to CDC mode?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: That's not quite correct. We have a seperate codepath in AbstractDbSource which explicitly handles streams in full refresh. getIncrementalIterators should only handle incremental streams and filter out all full refresh. https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java#L164

Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: I see what you're saying.
the code in `AbstractDBSource.read()` only expects us to only return iterators that are incremental. 
Full refresh is handled afterwards
```
    final List<AutoCloseableIterator<AirbyteMessage>> incrementalIterators =
        getIncrementalIterators(database, catalog, fullyQualifiedTableNameToInfo, stateManager,
            emittedAt);
    final List<AutoCloseableIterator<AirbyteMessage>> fullRefreshIterators =
        getFullRefreshIterators(database, catalog, fullyQualifiedTableNameToInfo, stateManager,
            emittedAt);
```

**Comment by rodireich** [comment]
The behavior in CDC not fully clear to me.
Even today configuring a CDC sync with full refresh is not blocked in UI or fully hashed out.
CDC is still locked behind a feature flag at this time.

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`385aab9229`](https://github.com/airbytehq/airbyte/pull/28369/commits/385aab922995d37730bfeb15a6bc91f920dbbdff)) - ❌

⏲️  Total pipeline duration: 12mn13s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689633362/385aab922995d37730bfeb15a6bc91f920dbbdff/source-postgres-strict-encrypt/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: I think we want to apply the same filter to getStreamsFromStreamPairs too, correct? And I think we still shouldn't care about full refresh here (and in the XminCtidUtils) right? `streamsForCursorBasedOrFullRefreshSync`

Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java]: Added

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java (hunk 2 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java:85]: done

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`385aab9229`](https://github.com/airbytehq/airbyte/pull/28369/commits/385aab922995d37730bfeb15a6bc91f920dbbdff)) - ✅

⏲️  Total pipeline duration: 16mn58s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689633362/385aab922995d37730bfeb15a6bc91f920dbbdff/source-postgres/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java [hunk 3]
```diff
@@ -78,14 +79,13 @@ public static StreamsCategorised<CursorBasedStreams> categoriseStreams(final Sta
...
     }
 
-    final List<ConfiguredAirbyteStream> newlyAddedStreams = identifyNewlyAddedStreams(fullCatalog, alreadySeenStreamPairs);
-    final List<ConfiguredAirbyteStream> streamsForCtidSync = getStreamsFromStreamPairs(fullCatalog, stillInCtidStreamPairs);
-    streamsForCtidSync.addAll(newlyAddedStreams);
-
-    final List<ConfiguredAirbyteStream> streamsForCursorBasedSync = getStreamsFromStreamPairs(fullCatalog, cursorBasedSyncStreamPairs);
+    final List<ConfiguredAirbyteStream> newlyAddedIncrementalStreams = identifyNewlyAddedStreams(fullCatalog, alreadySeenStreamPairs, SyncMode.INCREMENTAL);
+    final List<ConfiguredAirbyteStream> streamsForCtidSync = getStreamsFromStreamPairs(fullCatalog, stillInCtidStreamPairs, SyncMode.INCREMENTAL);
+    final List<ConfiguredAirbyteStream> streamsForCursorBasedOrFullRefreshSync = getStreamsFromStreamPairs(fullCatalog, cursorBasedSyncStreamPairs, SyncMode.INCREMENTAL);
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: nit : Can we rename this to streamsForCursorBasedSync (since seems like we are filtering out full refresh streams)

Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cursor_based/CursorBasedCtidUtils.java:84]: on it

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java [hunk 4]
```diff
@@ -77,21 +78,22 @@ public static StreamsCategorised<XminStreams> categoriseStreams(final StateManag
...
     fullCatalog.getStreams().stream()
         .filter(stream -> streamsStillInCtidSync.contains(AirbyteStreamNameNamespacePair.fromAirbyteStream(stream.getStream())))
         .map(Jsons::clone)
         .forEach(streamsForCtidSync::add);
 
-    streamsForCtidSync.addAll(newlyAddedStreams);
+    streamsForCtidSync.addAll(newlyAddedIncrementalStreams);
 
-    final List<ConfiguredAirbyteStream> streamsForXminSync = fullCatalog.getStreams().stream()
+    final List<ConfiguredAirbyteStream> streamsForXminOrFullRefreshSync = fullCatalog.getStreams().stream()
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/xmin/XminCtidUtils.java:90]: Same here : can we rename streamsForXminOrFullRefreshSync -> streamsForXmin

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`385aab9229`](https://github.com/airbytehq/airbyte/pull/28369/commits/385aab922995d37730bfeb15a6bc91f920dbbdff)) - ❌

⏲️  Total pipeline duration: 07mn47s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689633362/385aab922995d37730bfeb15a6bc91f920dbbdff/source-alloydb/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`385aab9229`](https://github.com/airbytehq/airbyte/pull/28369/commits/385aab922995d37730bfeb15a6bc91f920dbbdff)) - ❌

⏲️  Total pipeline duration: 06mn25s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build source-alloydb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689633362/385aab922995d37730bfeb15a6bc91f920dbbdff/source-alloydb-strict-encrypt/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Review by akashkulk — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`3713b02282`](https://github.com/airbytehq/airbyte/pull/28369/commits/3713b0228286985d3ecb9d924965a73390f1869e)) - ❌

⏲️  Total pipeline duration: 08mn51s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689636123/3713b0228286985d3ecb9d924965a73390f1869e/source-postgres-strict-encrypt/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`3713b02282`](https://github.com/airbytehq/airbyte/pull/28369/commits/3713b0228286985d3ecb9d924965a73390f1869e)) - ❌

⏲️  Total pipeline duration: 5.14s 

| Step                                                                                 | Result   |
|:-------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                       | ✅        |
| QA checks                                                                            | ✅        |
| Build connector tar                                                                  | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689636123/3713b0228286985d3ecb9d924965a73390f1869e/source-alloydb-strict-encrypt/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`3713b02282`](https://github.com/airbytehq/airbyte/pull/28369/commits/3713b0228286985d3ecb9d924965a73390f1869e)) - ❌

⏲️  Total pipeline duration: 7.87s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689636123/3713b0228286985d3ecb9d924965a73390f1869e/source-postgres/3.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`3713b02282`](https://github.com/airbytehq/airbyte/pull/28369/commits/3713b0228286985d3ecb9d924965a73390f1869e)) - ❌

⏲️  Total pipeline duration: 5.31s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Build connector tar                                                   | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28363-ctid-with-cursor-sync-containing-both-incremental-and-full-refresh-streams-will-fail-to-sync/1689636123/3713b0228286985d3ecb9d924965a73390f1869e/source-alloydb/2.0.28/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```
