### PR TITLE
🐛 Fix data type tests in CdcPostgresSourceDatatypeTest

### LINKED ISSUE #5382: Fix data type tests in CdcPostgresSourceComprehensiveTest
The test written in CdcPostgresSourceComprehensiveTest were not going through CDC flow. As part of the PR https://github.com/airbytehq/airbyte/pull/5370 I fixed it and the tests started running against the CDC flow. After that I realised that there are few data types which are not being correctly handled. I commented out those tests so that the build can pass. As part of this issue we need to fix the commented out data types in the class CdcPostgresSourceComprehensiveTest

### PR DESCRIPTION
**Pull request by sashaNeshcheret**
## What
Fix data type tests in CdcPostgresSourceDataTypeTest

## How
Created custom PostgressConvertet that implements CustomConverter

## Recommended reading order
1. `x.java`
2. `y.yaml`
3. `z.json`
4. `k.md`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by DoNotPanicUA — DISMISSED** [review]

**Review by sherifnada — COMMENTED** [review]
Very exciting!

I have one potentially blocking question about whether setting the DB timezone to UTC in test potentially does not match DBs in production. If the answer is "no it does not mask issues in prod" then you are free to merge. 

also @sashaNeshcheret reminder to fill out the full PR template e.g: reading order I know it seems pedantic, but it's very helpful for the reviewer at times

**Review by sherifnada — APPROVED** [review]

File: airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java [hunk 1]
```diff
@@ -13,12 +13,18 @@
...
 
 public class DataTypeUtils {
 
   public static final String DATE_FORMAT_PATTERN = "yyyy-MM-dd'T'HH:mm:ss'Z'";
   public static final DateFormat DATE_FORMAT = new SimpleDateFormat(DATE_FORMAT_PATTERN); // Quoted "Z" to indicate UTC, no timezone offset
+  public static final DateFormat DATE_FORMAT_UTC = new SimpleDateFormat(DATE_FORMAT_PATTERN);
+
+  static {
+    DATE_FORMAT_UTC.setTimeZone(TimeZone.getTimeZone("UTC"));
+  }
```
Comment (sashaNeshcheret) [inline airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:27]: @sherifnada, please, take a look for it. We figured out that cases with converting duration and milliseconds to date format depends on time zone, but in general we don't know time zone for incoming parameters, as far as described in debezium docs, it returns milliseconds in UTC time zone, so we update date type utils regarding it.

Comment (sherifnada) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:27]: @sashaNeshcheret Can you clarify what you mean? If we don't know the time zone for incoming records, why are we assuming they are UTC? Couldn't that lead to data corruption?

Comment (sashaNeshcheret) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:27]: @sherifnada We don't know time zone for incoming parameters in general cases, so we can not make any assumption and change existing DATE_FORMAT that used in a lot of places, so I've created DATE_FORMAT_UTC and set it to UTC time zone specially for debezium. In debezium docs I found that timestamps converted to milliseconds that are in UTC to avoid any affecting, so i assumed that all numbers in dates files are following this approach and expect number in UTC format.
If it is not right assumption and we still don't have info about time zone, we can convert it to String as is.

Comment (sherifnada) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:27]: @sashaNeshcheret ok so if we know 100% that the places where we use this format are going to be in UTC, then this is okay. My only concern is assuming timetsamps are UTC if they are not.

Comment (sashaNeshcheret) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java]: I reverted changes with UTC date format, because in documentation we are not 100% sure that number and Duration can be in another format.
