### PR TITLE
🐛  fix error message for postgres standby error

### LINKED ISSUE #31357: Update Postgres standby error message to point towards correct link
Context : https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1697069687329289

We have an error message which reads : Failure reason: We're having issues syncing from a Postgres replica that is configured as a hot standby server. Please see https://docs.airbyte.com/integrations/sources/postgres/#sync-data-from-postgres-hot-standby-server for options and workarounds

However, this link is now stale. We should update it to point to : https://docs.airbyte.com/integrations/sources/postgres/postgres-troubleshooting#sync-data-from-postgres-hot-standby-server

Better yet : We can change links for source connectors from https://docs.airbyte.com/ to a short-url with Airbyte domain. I am checking on bitly credentials

### PR DESCRIPTION
**Pull request by stephane-airbyte**
## What
fixes #31357 (1 of 2) 
simply changing the error message with the correct bitly
I took the opportunity to cleanup the CDK code a bit.
Finally, all postgres connectors should use this new CDK version so that they all have the new error message. That will be done in another PR

## 🚨 User Impact 🚨
no breaking change

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

File: airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/util/ConnectorExceptionUtil.java [hunk 1]
```diff
@@ -88,22 +85,22 @@ public static <T extends Throwable> void logAllAndThrowFirst(final String initia
     }
   }
 
-  private static Predicate<Throwable> getConfigErrorPredicate() {
-    return e -> e instanceof ConfigErrorException;
+  private static boolean isConfigErrorException(Throwable e) {
+    return e instanceof ConfigErrorException;
```
Comment (postamar) [inline airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/util/ConnectorExceptionUtil.java:89]: Thanks for this change and others like it. There's really no point in declaring static variables containing Function<> and friends over declaring a method.

File: airbyte-cdk/java/airbyte-cdk/build.gradle [hunk 2]
```diff
@@ -30,8 +30,8 @@ subprojects { subproject ->
         }
         repositories {
             maven {
-                name 'airbyte-public-jars'
-                url 'https://airbyte.mycloudrepo.io/repositories/airbyte-public-jars/'
+                name 'airbyte-repo'
+                url 'https://airbyte.mycloudrepo.io/repositories/airbyte-public-jars/' //This is only used to publish.
```
Comment (postamar) [inline airbyte-cdk/java/airbyte-cdk/build.gradle:34]: nit, regarding commentary: I had in mind also a comment which mentioned that this URL was different than that in the repositories { } block in settings.gradle.

**Review by postamar — COMMENTED** [review]
LGTM

File: airbyte-cdk/java/airbyte-cdk/build.gradle (hunk 2 above)
Comment (stephane-airbyte) [reply airbyte-cdk/java/airbyte-cdk/build.gradle]: @postamar ack and changed

File: airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/util/ConnectorExceptionUtil.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/util/ConnectorExceptionUtil.java:89]: +1

**Review by akashkulk — APPROVED** [review]
Fine to do in a seperate PR (or after the new CDK is published), but you will seperately have to 
1. Update the CDK dependency for source-postgres in it's corresponding build.gradle file
2. Bump version + changelog for source-postgres
