### PR TITLE
Fix flaky tests

### LINKED ISSUE #19398: BasicAcceptanceTests.testIncrementalSync is flaky
## What

We may start a new sync in the tests while the reset is still terminating.
Test is [here](https://github.com/airbytehq/airbyte/blob/64b50adfdd847cd610b058074620f93e42dbef36/airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java#L651)

Example of failed run: https://github.com/airbytehq/airbyte/runs/9485866616

### PR DESCRIPTION
**Pull request by gosusnp**
## What

Tests involving resets can be flaky. It is due to the fact that we currently track job state in two different ways, one is in the jobs table, the other one is WorkflowState from the connection manager. Following a reset, we update part of the WorkflowState state, update the jobs db, clear resets from the reset table, then update the state.

One option could be to rewrite the state logic to have workers have the main source of truth in the DB rather than split. This is an issue that is likely to happen in the tests, however, due to scheduling and timing less likely to happen under real conditions.

This PR introduce a workaround to be able to wait on both states. The other solution should be discussed/prioritized later.

Closes airbytehq/airbyte#19398 

## How
* Expose `WorkflowState.running` in the `JobsDebugInfo` API.
* Add a condition on the tests involving a reset to wait for the `WorkflowState.running` flag to flip as well as the jobs status.

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java [hunk 1]
```diff
@@ -122,7 +143,15 @@ public JobDebugInfoRead getJobDebugInfo(final JobIdRequestBody jobIdRequestBody)
     final Job job = jobPersistence.getJob(jobIdRequestBody.getId());
     final JobInfoRead jobinfoRead = jobConverter.getJobInfoRead(job);
 
-    return buildJobDebugInfoRead(jobinfoRead);
+    final JobDebugInfoRead jobDebugInfoRead = buildJobDebugInfoRead(jobinfoRead);
+    if (temporalClient != null) {
```
Comment (benmoriceau) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java:147]: Do we want to have that check or do the migration in cloud directly?

**Review by benmoriceau — APPROVED** [review]

File: airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java [hunk 2]
```diff
@@ -641,6 +642,11 @@ void testIncrementalSync() throws Exception {
     final JobInfoRead jobInfoRead = apiClient.getConnectionApi().resetConnection(new ConnectionIdRequestBody().connectionId(connectionId));
     waitWhileJobHasStatus(apiClient.getJobsApi(), jobInfoRead.getJob(),
         Sets.newHashSet(JobStatus.PENDING, JobStatus.RUNNING, JobStatus.INCOMPLETE, JobStatus.FAILED));
+    // This is a band-aid to prevent some race conditions where the job status was updated but we may
+    // still be cleaning up some data in the reset table. This would be an argument for reworking the
+    // source of truth of the replication workflow state to be in DB rather than in Memory and
+    // serialized automagically by temporal
+    waitWhileJobIsRunning(apiClient.getJobsApi(), jobInfoRead.getJob(), Duration.ofMinutes(1));
```
Comment (cgardens) [inline airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java:649]: @gosusnp - do we need this line at all? now that you've updated the handler won't `waitWhileJobHasStatus` (2 lines above) also get the correct source of truth? it seems redundant.

Comment (gosusnp) [reply airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java:649]: I believe those tests were flaky until this PR got merged.
Those two checks are different, the first one is looking at the DB state, this one is looking at temporal state. Until we fix the actual endpoint (either change how we handle clean up after a reset or have a single source of truth for state), yes, I think we still need this check.

Comment (cgardens) [reply airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java:649]: ah. i see. they are using different endpoints. can you make sure we have an issue to follow up on this, please? it's pretty spooky.

Comment (gosusnp) [reply airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/BasicAcceptanceTests.java:649]: Captured in https://github.com/airbytehq/airbyte/issues/19854

File: airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java [hunk 3]
```diff
@@ -122,7 +143,15 @@ public JobDebugInfoRead getJobDebugInfo(final JobIdRequestBody jobIdRequestBody)
...
+      final UUID connectionId = UUID.fromString(job.getScope());
+      temporalClient.getWorkflowState(connectionId)
```
Comment (cgardens) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java:149]: @gosusnp will this break if the _next_ job has started? basically for connection X:
* job 1 happens and completes. 
* then job 2 starts. 
* while job 2 is running i look up the debug info for job 1. won't it say running (because this `getWorkflowState` is keyed only by connection id), but i would expect it to not be running.

Comment (gosusnp) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java:149]: It think what you described is correct since workflowState is per connection id and has no history.

The other option that was considered was to have a different API endpoint, I think this felt like a smaller lift at that time to remove some noise from the tests.

Comment (cgardens) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java:149]: got it. we should at least have a todo or warning in the code then. that's going to catch someone by surprise. i didn't figure it out until i was in the shower a couple hours later. 😅
