### PR TITLE
Fix migrations to 0.18.0

### LINKED ISSUE #2665: Migration from 0.17.1-alpha to 0.18.0-alpha fails
## Expected Behavior
Running migration from `0.16.X-alpha` to `0.18.0-alpha` works.
Running migration from `0.17.3-alpha` to `0.18.0-alpha` fails with an exception.

This seems to be due to the `tombstone` field added to Standard Workspace https://github.com/airbytehq/airbyte/pull/2325/ (in 0.17.1?) which isn't expected while migrating since the expected JSON Schema for that object does not contain any references to that field:
https://github.com/airbytehq/airbyte/blob/master/airbyte-migration/src/main/resources/migrations/migrationV0_14_0/airbyte_config/StandardWorkspace.yaml

This is failing even though, 0.18.0 does not relate to StandardWorkspace objects at all.

## Current Behavior
Upgrade tarball successfully

## Logs

```
2021-03-30 10:45:19 INFO i.a.m.MigrationRunner(parse):78 - {} - args: [--input, /config/3d4e8c96-75c3-48b2-ab5e-69e267acafc4.tar.gz, --output, /config/18.tar.gz]
2021-03-30 10:45:19 INFO i.a.m.MigrationRunner(run):50 - {} - Unpacking tarball
2021-03-30 10:45:19 INFO i.a.m.MigrationRunner(run):67 - {} - Running migrations...
2021-03-30 10:45:19 INFO i.a.m.MigrationRunner(run):68 - {} - MigrateConfig{inputPath=/tmp/airbyte_migrate12711066458087605762/uncompressed, outputPath=/tmp/airbyte_migrate12711066458087605762/output, targetVersion='null'}
2021-03-30 10:45:19 INFO i.a.m.Migrate(run):88 - {} - Starting migrations. Current version: 0.17.3-alpha, Target version: null
2021-03-30 10:45:19 INFO i.a.m.Migrate(run):112 - {} - Migrating from version: 0.17.0-alpha to version 0.18.0-alpha.
2021-03-30 10:45:20 WARN c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword existingJavaType - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
Exception in thread "main" java.lang.IllegalArgumentException: Input data schema does not match declared input schema.
	at io.airbyte.migrate.Migrate.lambda$runMigration$1(Migrate.java:139)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.airbyte.migrate.migrations.MigrationV0_18_0.migrate(MigrationV0_18_0.java:81)
	at io.airbyte.migrate.MigrateWithMetadata.migrate(MigrateWithMetadata.java:52)
	at io.airbyte.migrate.Migrate.runMigration(Migrate.java:149)
	at io.airbyte.migrate.Migrate.run(Migrate.java:113)
	at io.airbyte.migrate.MigrationRunner.run(MigrationRunner.java:70)
	at io.airbyte.migrate.MigrationRunner.main(MigrationRunner.java:108)
Caused by: io.airbyte.validation.json.JsonValidationException: json schema validation failed. 
errors: $.tombstone: is not defined in the schema and the schema does not allow additional properties 
```

## Steps to Reproduce
1. Setup an airbyte instance in 0.17.1 or later
1. export
1. migrate to 0.18.0

## Severity of the bug for you
High 

## Airbyte Version
0.18.1-alpha

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes #2665 

## How
Handle `tombstone` field in `StandardWorkspace.yaml` introduced recently

### CODE REVIEW

File: airbyte-migration/src/main/java/io/airbyte/migrate/migrations/MigrationV0_18_0.java [hunk 1]
```diff
@@ -68,9 +72,21 @@ public String getVersion() {
     return MIGRATION_VERSION;
   }
 
+  @Override
```
Comment (davinchia) [inline airbyte-migration/src/main/java/io/airbyte/migrate/migrations/MigrationV0_18_0.java:75]: nit: can we update the class comments to include adding in the tombstone?

**Review by cgardens — APPROVED** [review]

**Review by sherifnada — APPROVED** [review]
