### PR TITLE
Switch logging logs to DEBUG. Add job id label to Kube workers.

### LINKED ISSUE #5868: Job Sync logs keep printing `Setting docker job mdc`
## Enviroment
- **Airbyte version**:  0.29.15-alpha
- **OS Version / Instance**: ~
- **Deployment**: Docker
- **Source Connector and version**: Harvest 0.1.0
- **Destination Connector and version**: Postgres
- **Severity**: Very Low / **Low** / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
https://github.com/airbytehq/airbyte/blob/fe38f692764a6b8851684e8cc5178bfd91cd931f/airbyte-config/models/src/main/java/io/airbyte/config/helpers/LogClientSingleton.java#L144-L152

Screenshot from 2021-09-06 16-39-13

@davinchia this is expected to happen?

## Expected Behavior
Logs should be cleaner and easy to understand. The logs keep printing a non relevant message to users.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-09-06 19:33:18 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.15-alpha
2021-09-06 19:33:18 INFO () TemporalAttemptExecution(get):111 - Executing worker wrapper. Airbyte version: 0.29.15-alpha
2021-09-06 19:33:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:33:18 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 5 attempt id: 0
2021-09-06 19:33:18 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.company=full_refresh - overwrite, null.estimates=full_refresh - overwrite, null.expenses=full_refresh - overwrite, null.expenses_clients=full_refresh - overwrite, null.expenses_team=full_refresh - overwrite, null.invoice_messages=full_refresh - overwrite, null.project_budget=full_refresh - overwrite, null.time_tasks=full_refresh - overwrite, null.invoice_item_categories=full_refresh - overwrite, null.time_team=full_refresh - overwrite, null.clients=full_refresh - overwrite, null.time_clients=full_refresh - overwrite, null.invoices=full_refresh - overwrite, null.tasks=full_refresh - overwrite, null.expense_categories=full_refresh - overwrite, null.estimate_messages=full_refresh - overwrite, null.expenses_projects=full_refresh - overwrite, null.invoice_payments=full_refresh - overwrite, null.task_assignments=full_refresh - overwrite, null.uninvoiced=full_refresh - overwrite, null.project_assignments=full_refresh - overwrite, null.estimate_item_categories=full_refresh - overwrite, null.user_assignments=full_refresh - overwrite, null.contacts=full_refresh - overwrite, null.projects=full_refresh - overwrite, null.roles=full_refresh - overwrite, null.expenses_categories=full_refresh - overwrite, null.cost_rates=full_refresh - overwrite, null.users=full_refresh - overwrite, null.billable_rates=full_refresh - overwrite, null.time_entries=full_refresh - overwrite, null.time_projects=full_refresh - overwrite}
2021-09-06 19:33:18 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-09-06 19:33:18 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-postgres:0.3.10 exists...
2021-09-06 19:33:18 INFO () LineGobbler(voidCall):85 - airbyte/destination-postgres:0.3.10 was found locally.
2021-09-06 19:33:18 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/5/0 --network host --log-driver none airbyte/destination-postgres:0.3.10 write --config destination_config.json --catalog destination_catalog.json
2021-09-06 19:33:18 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-harvest:dev exists...
2021-09-06 19:33:18 INFO () LineGobbler(voidCall):85 - airbyte/source-harvest:dev was found locally.
2021-09-06 19:33:18 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/5/0 --network host --log-driver none airbyte/source-harvest:dev read --config source_config.json --catalog source_catalog.json
2021-09-06 19:33:18 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-09-06 19:33:18 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-09-06 19:33:18 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.p.PostgresDestination(main):82 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):96 - {} - Running integration: io.airbyte.integrations.destination.postgres.PostgresDestination
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):100 - {} - Command: WRITE
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.b.IntegrationRunner(run):101 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=billable_rates, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_rdk_billable_rates, outputTableName=_airbyte_raw_billable_rates, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=clients, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ljt_clients, outputTableName=_airbyte_raw_clients, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=company, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_kdd_company, outputTableName=_airbyte_raw_company, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=contacts, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pma_contacts, outputTableName=_airbyte_raw_contacts, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=cost_rates, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_yrf_cost_rates, outputTableName=_airbyte_raw_cost_rates, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=estimate_item_categories, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_vam_estimate_item_categories, outputTableName=_airbyte_raw_estimate_item_categories, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=estimate_messages, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_xri_estimate_messages, outputTableName=_airbyte_raw_estimate_messages, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=estimates, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_oiv_estimates, outputTableName=_airbyte_raw_estimates, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expense_categories, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_htp_expense_categories, outputTableName=_airbyte_raw_expense_categories, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expenses, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_jts_expenses, outputTableName=_airbyte_raw_expenses, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expenses_categories, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_nyf_expenses_categories, outputTableName=_airbyte_raw_expenses_categories, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expenses_clients, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pow_expenses_clients, outputTableName=_airbyte_raw_expenses_clients, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expenses_projects, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_iay_expenses_projects, outputTableName=_airbyte_raw_expenses_projects, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=expenses_team, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_tsh_expenses_team, outputTableName=_airbyte_raw_expenses_team, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=invoice_item_categories, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_krm_invoice_item_categories, outputTableName=_airbyte_raw_invoice_item_categories, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=invoice_messages, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ahy_invoice_messages, outputTableName=_airbyte_raw_invoice_messages, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=invoice_payments, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_jfm_invoice_payments, outputTableName=_airbyte_raw_invoice_payments, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=invoices, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_qyv_invoices, outputTableName=_airbyte_raw_invoices, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=project_assignments, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_yjh_project_assignments, outputTableName=_airbyte_raw_project_assignments, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=project_budget, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ldn_project_budget, outputTableName=_airbyte_raw_project_budget, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=projects, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ozh_projects, outputTableName=_airbyte_raw_projects, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=roles, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_uzz_roles, outputTableName=_airbyte_raw_roles, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=task_assignments, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_wuo_task_assignments, outputTableName=_airbyte_raw_task_assignments, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=tasks, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_ojg_tasks, outputTableName=_airbyte_raw_tasks, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=time_clients, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_gft_time_clients, outputTableName=_airbyte_raw_time_clients, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=time_entries, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_pln_time_entries, outputTableName=_airbyte_raw_time_entries, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=time_projects, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_vgb_time_projects, outputTableName=_airbyte_raw_time_projects, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=time_tasks, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_jhy_time_tasks, outputTableName=_airbyte_raw_time_tasks, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=time_team, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_mwj_time_team, outputTableName=_airbyte_raw_time_team, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=uninvoiced, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_prc_uninvoiced, outputTableName=_airbyte_raw_uninvoiced, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=user_assignments, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_jum_user_assignments, outputTableName=_airbyte_raw_user_assignments, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):116 - {} - Write config: WriteConfig{streamName=users, namespace=null, outputSchemaName=public, tmpTableName=_airbyte_tmp_xfw_users, outputTableName=_airbyte_raw_users, syncMode=overwrite}
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):143 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):139 - {} - Preparing tmp tables in destination started for 32 streams
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream billable_rates. schema: public, tmp table name: _airbyte_tmp_rdk_billable_rates
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream clients. schema: public, tmp table name: _airbyte_tmp_ljt_clients
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream company. schema: public, tmp table name: _airbyte_tmp_kdd_company
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream contacts. schema: public, tmp table name: _airbyte_tmp_pma_contacts
2021-09-06 19:33:23 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:23 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream cost_rates. schema: public, tmp table name: _airbyte_tmp_yrf_cost_rates
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream estimate_item_categories. schema: public, tmp table name: _airbyte_tmp_vam_estimate_item_categories
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream estimate_messages. schema: public, tmp table name: _airbyte_tmp_xri_estimate_messages
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream estimates. schema: public, tmp table name: _airbyte_tmp_oiv_estimates
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expense_categories. schema: public, tmp table name: _airbyte_tmp_htp_expense_categories
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expenses. schema: public, tmp table name: _airbyte_tmp_jts_expenses
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expenses_categories. schema: public, tmp table name: _airbyte_tmp_nyf_expenses_categories
2021-09-06 19:33:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:24 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expenses_clients. schema: public, tmp table name: _airbyte_tmp_pow_expenses_clients
2021-09-06 19:33:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:25 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expenses_projects. schema: public, tmp table name: _airbyte_tmp_iay_expenses_projects
2021-09-06 19:33:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:25 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream expenses_team. schema: public, tmp table name: _airbyte_tmp_tsh_expenses_team
2021-09-06 19:33:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:25 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream invoice_item_categories. schema: public, tmp table name: _airbyte_tmp_krm_invoice_item_categories
2021-09-06 19:33:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:25 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream invoice_messages. schema: public, tmp table name: _airbyte_tmp_ahy_invoice_messages
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream invoice_payments. schema: public, tmp table name: _airbyte_tmp_jfm_invoice_payments
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream invoices. schema: public, tmp table name: _airbyte_tmp_qyv_invoices
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream project_assignments. schema: public, tmp table name: _airbyte_tmp_yjh_project_assignments
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream project_budget. schema: public, tmp table name: _airbyte_tmp_ldn_project_budget
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream projects. schema: public, tmp table name: _airbyte_tmp_ozh_projects
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream roles. schema: public, tmp table name: _airbyte_tmp_uzz_roles
2021-09-06 19:33:26 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:26 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream task_assignments. schema: public, tmp table name: _airbyte_tmp_wuo_task_assignments
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream tasks. schema: public, tmp table name: _airbyte_tmp_ojg_tasks
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream time_clients. schema: public, tmp table name: _airbyte_tmp_gft_time_clients
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream time_entries. schema: public, tmp table name: _airbyte_tmp_pln_time_entries
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream time_projects. schema: public, tmp table name: _airbyte_tmp_vgb_time_projects
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream time_tasks. schema: public, tmp table name: _airbyte_tmp_jhy_time_tasks
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream time_team. schema: public, tmp table name: _airbyte_tmp_mwj_time_team
2021-09-06 19:33:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:27 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream uninvoiced. schema: public, tmp table name: _airbyte_tmp_prc_uninvoiced
2021-09-06 19:33:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:28 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream user_assignments. schema: public, tmp table name: _airbyte_tmp_jum_user_assignments
2021-09-06 19:33:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:28 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):143 - {} - Preparing tmp table in destination started for stream users. schema: public, tmp table name: _airbyte_tmp_xfw_users
2021-09-06 19:33:28 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-06 19:33:28 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):149 - {} - Preparing tables in destination completed.
2021-09-06 19:33:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:33:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:33:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:33:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:34:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:35:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:36:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:37:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:38:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:39:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:40:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:18 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:28 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:38 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:48 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:41:58 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc
2021-09-06 19:42:08 INFO () LogClientSingleton(setJobMdc):146 - Setting docker job mdc

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by davinchia**
## What
As title.

- Closes #5868.
- Label is for us to track pod costs.

## Recommended reading order
1. `LogClientSingleton.java`
2. `KubePodProcess.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
nice!

File: airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java [hunk 1]
```diff
@@ -45,6 +45,7 @@
   private static final Logger LOGGER = LoggerFactory.getLogger(KubeProcessFactory.class);
 
   private static final Pattern ALPHABETIC = Pattern.compile("[a-zA-Z]+");;
+  private static final String JOB_LABEL_KEY = "jobid";
```
Comment (jrhizor) [inline airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java:48]: super nit: Does the formatting of this matter? Can it be `job_id`?

**Comment by cgardens** [comment]
@davinchia and i talked offline. realized we should probably be tracking by attempt level and not just job level.

File: airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java [hunk 2]
```diff
@@ -370,11 +371,13 @@ public KubePodProcess(String processRunnerHost,
     List<Container> containers = usesStdin ? List.of(main, remoteStdin, relayStdout, relayStderr, callHeartbeatServer)
         : List.of(main, relayStdout, relayStderr, callHeartbeatServer);
 
+    Map<String, String> podLabels = labels.addAll(AIRBYTE_POD_LABELS);
```
Comment (marcosmarxm) [inline airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java:374]: @davinchia Map<String, String> doesnt have the method `addAll` can you validate this?

**Review by marcosmarxm — CHANGES_REQUESTED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java (hunk 1 above)
Comment (davinchia) [reply airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java:48]: yes!

File: airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java (hunk 2 above)
Comment (davinchia) [reply airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java]: oof, typed too fast.

I changed the structure so this no longer applies.
