### PR TITLE
Validate protocol version on connector update

### LINKED ISSUE #15462: Prevent upgrade of a connector if its protocol version is out of range
## What

When updating to a new version of a connector, the platform will fail the update if the connector is using a version of the protocol that is ahead of the platform and notify the user at the same time

## How

* Check the protocol version we read from the Connector SPEC. If it is out of range, fail with an explicit message

### PR DESCRIPTION
**Pull request by gosusnp**
## What
Prevent connector definition modification if the protocol version of the connector is not supported by the platform.

Closes #15462 

## How
Check ProtocolVersion before create/update of source/dest definitions.

### CODE REVIEW

File: airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
+/*
+ * Copyright (c) 2022 Airbyte, Inc., all rights reserved.
+ */
+
+package io.airbyte.commons.version;
+
+public class AirbyteProtocolVersionRange {
```
[the remark this answers is not in the document]
Comment (colesnodgrass) [reply airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java:7]: Also the `Version` class itself already has methods that handle comparison to other `Version` objects (`compatibleVersionCompareTo`, `greaterThan`, `lessThan`, etc.), should we be using one of those method here?

File: airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java [hunk 2]
```diff
@@ -179,6 +187,10 @@ public DestinationDefinitionRead createPrivateDestinationDefinition(final Destin
     final StandardDestinationDefinition destinationDefinition = destinationDefinitionFromCreate(destinationDefCreate)
         .withPublic(false)
         .withCustom(false);
+    if (!protocolVersionRange.isSupported(new Version(destinationDefinition.getProtocolVersion()))) {
+      throw new RuntimeException(String.format("Airbyte Protocol Version %s is not supported. (Must be within [%s:%s])",
```
Comment (colesnodgrass) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java:191]: Should this be replaced with a specific exception?  Similar to the `IdNotFoundKnownException` exception thrown above?  It should made this code a little less verbose as the exception itself could take the version objects here and generate the message within itself.

  (This question applies to all the `RuntimeException`s being thrown in this PR.)

File: airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (gosusnp) [reply airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java:7]: Not feeling super strong either way about using a record.

About the `Version` comparison, none of the current behaviors matches which is what led me to add this `AirbyteProtocolVersionRange` in the first place.
* `compatibleVersionCompareTo` is closer to an exact compare that check if the major, minor matches and ignores the patch.
* `greaterThan` is doing a Major.minor check, in the protocol version version case, we are only concerned about major because minors should be backward compatible within a major by design.

File: airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java (hunk 2 above)
Comment (gosusnp) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java]: Good point. Also discovered that `KnownException` comes with the logic to define the error code.
Updated.

File: airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (gosusnp) [reply airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteProtocolVersionRange.java]: Rewrote the class as a record.

**Review by colesnodgrass — APPROVED** [review]

File: airbyte-server/src/main/java/io/airbyte/server/errors/UnsupportedProtocolVersion.java [hunk 3]
```diff
@@ -0,0 +1,25 @@
+/*
+ * Copyright (c) 2022 Airbyte, Inc., all rights reserved.
+ */
+
+package io.airbyte.server.errors;
+
+import io.airbyte.commons.version.Version;
+
+public class UnsupportedProtocolVersion extends KnownException {
```
Comment (jdpgrailsdev) [inline airbyte-server/src/main/java/io/airbyte/server/errors/UnsupportedProtocolVersion.java:9]: Nit:  Should this have `Exception` in the class name to make it clear that it represents an exception?

Comment (gosusnp) [reply airbyte-server/src/main/java/io/airbyte/server/errors/UnsupportedProtocolVersion.java]: done
