### PR TITLE
[Source-postgres] : Compare each record’s lsn_commit value instead of lsn_proc.

### LINKED ISSUE #35963: [Source-postgres] : Compare each record’s lsn_commit value instead of lsn_proc.
TLDR is we are comparing the lsn_proc from the event instead of the lsn_commit

If lsn_proc(record) > lsn_commit(state_file) AND lsn_commit(record) < lsn_comit(state_file) AND we emit state + fail
Can explain certain data loss situations, since we emit state that corresponds to records we may not have processed yet. We also ack this LSN and clear the WAL, so these records are forever lost. 

References : 
- https://docs.google.com/document/d/1yVW3QJjOZiCTHU4m-P-FdIm5yiJLzmomrFol9_7oPxc/edit
- https://debezium.zulipchat.com/#narrow/stream/348249-community-postgresql/topic/Different.20LSN.20values.20in.20Debezium.20state

### PR DESCRIPTION
**Pull request by akashkulk**
Closes https://github.com/airbytehq/airbyte/issues/35963

### CODE REVIEW

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java [hunk 1]
```diff
@@ -105,10 +109,27 @@ public boolean isEventAheadOffset(final Map<String, String> offset, final Change
...
-    final String offset_lsn =
-        offsetJson.get("lsn_commit") != null ? String.valueOf(offsetJson.get("lsn_commit")) : String.valueOf(offsetJson.get("lsn"));
-    final String event_lsn = String.valueOf(event.eventValueAsJson().get("source").get("lsn"));
-    return Long.parseLong(event_lsn) > Long.parseLong(offset_lsn);
+    final String stateOffsetLsnCommit = offsetJson.get("lsn_commit") != null ? String.valueOf(offsetJson.get("lsn_commit")) : null;
+    if (stateOffsetLsnCommit == null) {
+      return false;
+    }
+
+    try {
```
Comment (rodireich) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:117]: Can you add a comment with a typical structure of the event you're parsing. To make it easier to uderstand

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java [hunk 2]
```diff
@@ -105,10 +109,27 @@ public boolean isEventAheadOffset(final Map<String, String> offset, final Change
...
+      ObjectMapper objectMapper = new ObjectMapper();
+      TypeReference<List<String>> listType = new TypeReference<>() {};
+      final JsonNode lsnSequenceNode = event.eventValueAsJson().get("source").get("sequence");
```
Comment (rodireich) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:120]: Is there a case sequence isn't going to be there?

Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:120]: I don't think so. It's been there since at least 2.2, possibly longer : https://debezium.io/documentation/reference/2.2/connectors/postgresql.html#postgresql-create-events

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java (hunk 1 above)
Comment (stephane-airbyte) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:117]: NIT:
```
if (offsetJson.get("lsn_commit") == null) {
  return false;
}
final stateOffsetLsnCommit =String.valueOf(offsetJson.get("lsn_commit")); 
```

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java [hunk 3]
```diff
@@ -912,9 +912,9 @@ protected void verifyCheckpointStatesBySeconds() throws Exception {
 
     assertEquals(recordsToCreate, extractRecordMessages(dataFromSecondBatch).size());
     final List<AirbyteStateMessage> stateMessagesCDC = extractStateMessages(dataFromSecondBatch);
-    if (!isOnLegacyPostgres()) {
-      assertTrue(stateMessagesCDC.size() > 1, "Generated only the final state.");
-    }
+    // We expect only one cdc state message, as all the records are inserted in a single transaction. Since
```
Comment (stephane-airbyte) [inline airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java]: thank you for the additional comment. Does that mean that somehow, your change is also fixing legacy postgres?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java (hunk 2 above)
Comment (stephane-airbyte) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:127]: looks like autoformat kicked in. Let's disable it, as your formatting was way more readable

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java (hunk 3 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java]: Not quite. For legacy postgres, only one state message was expected (not sure why). 

So this change just streamlines the test to check for just one state message instead of multiple (which I'm not sure was a good test to begin with)

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java [hunk 4]
```diff
@@ -871,9 +871,10 @@ protected void verifyCheckpointStatesByRecords() throws Exception {
         .toListAndClose(secondBatchIterator);
     assertEquals(recordsToCreate, extractRecordMessages(dataFromSecondBatch).size());
     final List<AirbyteStateMessage> stateMessagesCDC = extractStateMessages(dataFromSecondBatch);
-    if (!isOnLegacyPostgres()) {
-      assertTrue(stateMessagesCDC.size() > 1, "Generated only the final state.");
-    }
+    // We expect only one cdc state message, as all the records are inserted in a single transaction.
+    // Since
+    // lsn_commit only increases with a new transaction, we expect only one state message.
```
Comment (xiaohansong) [inline airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java:876]: are we not expecting a checkpoint state message (after the transaction) and a final state message in this case?

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java (hunk 3 above)
Comment (stephane-airbyte) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java]: we NEVER are on legacy postgres... Let's remove that method altogether, no?

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java (hunk 4 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdcPostgresSourceTest.java:876]: The one state message we expect is after the dbz engine is shut down. In this case, there is just one transaction so only one state message is expected. (that's the change we're trying to test by comparing against `lsn_commit` and not `lsn_proc`)

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java (hunk 2 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/cdc/PostgresCdcTargetPosition.java:139]: Nice seems like that did the trick

**Review by stephane-airbyte — APPROVED** [review]

**Review by rodireich — APPROVED** [review]

**Review by xiaohansong — APPROVED** [review]
