### PR TITLE
Auth Button now shows re-authenticate when it has been authenticated once

### LINKED ISSUE #14226: After OAuth in connector and switching to a different auth method and back, user is asked to OAuth again
## Environment
- **Airbyte version**:  0.39.28-alpha
- **Step where error happened**: Setup new source or destination

## Current Behavior
OAuth button reads "Authenticate your ___ account" when it should read "Re-authenticate...". User can save connection at this point because credentials have been stored in form state.

## Expected Behavior
Button on OAuth confirms that user is already authorized or user has to auth from the start, depending on desired UX.

## Steps to Reproduce
1. Create a new Snowflake Source
2. Set the `Host`
3. Select Authorization method as "OAuth 2.0"
4. Click on "Authenticate your Snowflake account"
5. Select "Username and Password" Authorization method
6. Select "OAuth 2.0" Authorization method again

### PR DESCRIPTION
**Pull request by krishnaglick**
Resolves #14226

### CODE REVIEW

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx [hunk 1]
```diff
@@ -38,13 +41,16 @@ function useFormikOauthAdapter(connector: ConnectorDefinitionSpecification): {
     }
 
     setValues(newValues);
+    setHasRun(true);
   };
 
   const { run, loading, done } = useRunOauthFlow(connector, onDone);
+  const connectionObjectEmpty = !!Object.keys((values?.connectionConfiguration as object) ?? {}).length;
```
Comment (timroes) [inline airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx:48]: Wouldn't that simply check if there is any configuration parameter set, i.e. this could be also any other parameter of the form being set?

Comment (krishnaglick) [reply airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx:48]: Screen Shot 2022-08-12 at 1 37 59 PM
The oauth interfaces that I interacted with were all like this, so it seemed a safe call. If that's not the case than this may be a good bit more complicated.

**Comment by timroes** [comment]
I think the original issue talks about the text on the button not the success message? The Authentication button at the moment states "Reauthenticate ..." when you already authenticated. This doesn't seem to be addressed by this PR.

**Comment by krishnaglick** [comment]
> I think the original issue talks about the text on the button not the success message? The Authentication button at the moment states "Reauthenticate ..." when you already authenticated. This doesn't seem to be addressed by this PR.

Previously it would always show `Authenticate your {connector} account` even if you were authenticated. This is the correct behavior based on my reading of the ticket.

**Comment by timroes** [comment]
@edmundito maybe you could clarify here since you wrote the issue?

**Comment by edmundito** [comment]
I tested this and it may have fixed some other problem, but what's in the issue can be reproduced:

1. New Source -> Maichimp
2. Select OAuth
3. Authenticate - The button should say "Re-authenticate" afterwards and it does
4. Select some other method
5. Switch back to Oauth - The button should say "Re-authenticate" but it does not
6. Save source - it saves!
7. Go to the source settings - The button should say "Re-authenticate" but it does not

**Comment by edmundito** [comment]
Also tested Google Sheets, which seems to have its own custom button:
image

**Comment by krishnaglick** [comment]
@edmundito Should be fixed! Also can you clarify with Tim about the messaging? I believe this ticket doesn't require any special messaging and should be fine as-is.

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx [hunk 2]
```diff
@@ -38,13 +46,19 @@ function useFormikOauthAdapter(connector: ConnectorDefinitionSpecification): {
     }
 
     setValues(newValues);
+    setHasRun(true);
   };
 
   const { run, loading, done } = useRunOauthFlow(connector, onDone);
+  const connectionObjectEmpty =
+    values?.connectionConfiguration?.credentials ?? values?.connectionConfiguration
+      ? Object.keys(values.connectionConfiguration?.credentials ?? values.connectionConfiguration).length <= 1
```
Comment (edmundito) [inline airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx:55]: `values.connectionConfiguration` is the object in the Formik form values that contains all the configuration of the connector, meaning that it may return an incorrect values if the user fills out all the fields except oauth because it would mean that values.connectionConfiguration > 1, therefore not empty?

**Review by edmundito — CHANGES_REQUESTED** [review]

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx (hunk 2 above)
Comment (krishnaglick) [reply airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx]: Just pushed a change that catches this. This is such a complex workflow!

**Review by edmundito — APPROVED** [review]
Code looks good. Tested create new connector (mailchimp and google sheets), and the settings.
