### PR TITLE
Skip CHECKs steps if previous sync success

### LINKED ISSUE #13459: Only run CHECKs after a failing Sync attempt
After https://github.com/airbytehq/airbyte/issues/12281, we now run each connector's CHECK command at the start of the sync.  This is great for reliability, but potentially slow, and uses more resources.  

This feature was added to catch /transient/ configuration errors, like an API Key becoming invalid over time. We rely on these checks to clearly assign the fault to the [FailureReason](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/FailureReason.yaml) `config-error`, rather than the connector code having a problem, e.g. `system-error`.  We also know that a sync which is failing due to `config-error` should not be retried, which saves some resources.

**Solution**
If the previous attempt for this connection was not successful, CHECKS should be run.  This does not include the first attempt, but it does check if the previous attempt in this job failed, or the previous attempt in the previous job failed.  We can skip the first attempt because the user will have just CHECKed as part of creating the connection - and if something goes wrong, the next attempt will CHECK again.  The "previous attempt" should consider only the most recent attempt before this one, and that might be an attempt within the same sync, or the previous sync's final attempt.  Each sync has up to 3 attempts.

This would allow regularly succeeding jobs to always skip the CHECK step.  Jobs with failure will be retried, and if the problem is due to user configuration problems, the job will have a terminal FailureReason of `config-error`, just like today.  

**Related Links**:
* [Customer Discuss](https://discuss.airbyte.io/t/temporal-scheduler-causing-multiple-syncs-to-hang/1293/5?u=lmossman)

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
Skip CHECKs steps if previous sync success

## How
First sync:

Second success sync after first success sync:

Second sync (first failure attempt) after first success sync:

Second sync (second success attempt) after first failure attempt (Please do not look at changing some of the logs, I just forgot to put them back when I took the screenshots =)):

Second success sync after first failure sync:

## Recommended reading order
1. `x.java`

## 🚨 User Impact 🚨
Skip CHECKs steps if previous sync success

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by andriikorotkov** [comment]
All I have to do is add new ones and update some existing tests.

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java [hunk 1]
```diff
@@ -333,6 +341,55 @@ public void ensureCleanJobState(final EnsureCleanJobStateInput input) {
...
+  public boolean isLastJobOrAttemptFailure(JobCheckFailureInput input) {
+    final int limit = 2;
+    boolean lastAttemptCheck = false;
+    boolean lastJobCheck = false;
+
+    Set<JobConfig.ConfigType> configTypes = new HashSet<>();
+    configTypes.add(SYNC);
+
+    try {
+      List<Job> jobList = jobPersistence.listJobsIncludingId(configTypes, input.getConnectionId().toString(), input.getJobId(), limit);
```
Comment (evantahler) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java:354]: To confirm: limit will query SQL for  2, but are we ordering by the right thing to get the most recent 2 attempts?

**Review by evantahler — COMMENTED** [review]
Nice! I think you are well on the right path.  Learning about Temporal is tricky - well done!

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java (hunk 1 above)
Comment (andriikorotkov) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java:354]: Good question. Judging by the way the structure of the method for obtaining jobs is built, the first request will be to get OffsetDateTime of creation of an active job. With the second request, we will receive the number of jobs whose creation date is greater than or equal to the result of the first request. Since we make a request with the identifier of the last active job, the number we will receive from the second request will always be 1. And then, during the calculation, we will receive the number of jobs that will be returned to us for processing - this will be calculated based on the result of the second request, and the limit we passed to this request - the result will always be 2.

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java [hunk 2]
```diff
@@ -401,7 +402,11 @@ private SyncCheckConnectionFailure checkConnections(final GenerateInputActivity.
     final StandardCheckConnectionInput sourceConfiguration = new StandardCheckConnectionInput().withConnectionConfiguration(sourceConfig);
     final CheckConnectionInput checkSourceInput = new CheckConnectionInput(jobRunConfig, sourceLauncherConfig, sourceConfiguration);
 
-    if (isResetJob(sourceLauncherConfig) || checkFailure.isFailed()) {
+    final JobCheckFailureInput jobStateInput =
+        new JobCheckFailureInput(Long.parseLong(jobRunConfig.getJobId()), jobRunConfig.getAttemptId().intValue(), connectionId);
+    var isLastJobOrAttemptFailure = jobCreationAndStatusUpdateActivity.isLastJobOrAttemptFailure(jobStateInput);
```
Comment (benmoriceau) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java:407]: You need to create a new workflow version here. Otherwise it will make the running workflow to fail when this is being deploy. The workflow version is a temporal internal functionality that ensure compatibility between an old running version of this workflow and the new one you are trying to introduce. You canfind an example of the usage of such a version on line 287 in the report success function. I will be happy to pair on this if needed.

Another issue here is that you need to wrap your activity code in the `runMandatoryActivityWithOutput` function. This is needed to ensure that we don't block the workflow is this activity fails for any reason.

**Review by benmoriceau — CHANGES_REQUESTED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java (hunk 2 above)
Comment (benmoriceau) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java:407]: I believe that for the version comment the test `WorkflowReplayingTest` should fail as of now.

Comment (andriikorotkov) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java]: @benmoriceau, I added the changes you posted above. But I'm not sure if I did it right because I failed to update the version correctly. Please review my pull request again and if I'm doing something wrong, tell me what I should add and change. (I'm working with temporal for the first time, and I may be wrong in something)

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java [hunk 3]
```diff
@@ -408,10 +411,15 @@ private SyncCheckConnectionFailure checkConnections(final GenerateInputActivity.
...
     final CheckConnectionInput checkSourceInput = new CheckConnectionInput(jobRunConfig, sourceLauncherConfig, sourceConfiguration);
 
-    final JobCheckFailureInput jobStateInput =
-        new JobCheckFailureInput(Long.parseLong(jobRunConfig.getJobId()), jobRunConfig.getAttemptId().intValue(), connectionId);
-    var isLastJobOrAttemptFailure = jobCreationAndStatusUpdateActivity.isLastJobOrAttemptFailure(jobStateInput);
+    final int checkJobOutputVersion =
+        Workflow.getVersion(CHECK_PREVIOUS_JOB_OUTPUT_TAG, Workflow.DEFAULT_VERSION, CHECK_PREVIOUS_JOB_OUTPUT_TAG_CURRENT_VERSION);
+    boolean isLastJobOrAttemptFailure = true;
 
+    if (checkJobOutputVersion < CHECK_PREVIOUS_JOB_OUTPUT_TAG_CURRENT_VERSION) {
```
Comment (benmoriceau) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java:418]: This should be `if (checkJobOutputVersion >= CHECK_PREVIOUS_JOB_OUTPUT_TAG_CURRENT_VERSION)`

**Review by benmoriceau — CHANGES_REQUESTED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java (hunk 3 above)
Comment (andriikorotkov) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java]: changed it. thanks for noticing

**Review by benmoriceau — APPROVED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java [hunk 4]
```diff
@@ -102,6 +103,9 @@ public class ConnectionManagerWorkflowImpl implements ConnectionManagerWorkflow
   private static final String RENAME_ATTEMPT_ID_TO_NUMBER_TAG = "rename_attempt_id_to_number";
   private static final int RENAME_ATTEMPT_ID_TO_NUMBER_CURRENT_VERSION = 1;
 
+  private static final String CHECK_PREVIOUS_JOB_OUTPUT_TAG = "rename_attempt_id_to_number";
```
Comment (benmoriceau) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java:106]: This tag need to be unique. Currently it is the same than `RENAME_ATTEMPT_ID_TO_NUMBER_TAG`

**Review by benmoriceau — CHANGES_REQUESTED** [review]

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java (hunk 4 above)
Comment (andriikorotkov) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java]: oh, that's my inattention. Thanks for noticing this

**Review by benmoriceau — APPROVED** [review]
LGTM, let's wait for the build to pass to make sure that the workflowReplayerTest is passing.
