### PR TITLE
[source-postgres, source-mysql] Translating top opaque and unfriendly error messages

### LINKED ISSUE #41614: Fix top opaque error messages
[Postgres: "something is wrong..."](https://airbyte.metabaseapp.com/question#eyJuYW1lIjoiVG9wIEVycm9yIE1lc3NhZ2VzIChieSBKb2IpIC0gRXhjbHVkZSBDYW5jZWxsZWQiLCJkZXNjcmlwdGlvbiI6bnVsbCwiZGF0YXNldF9xdWVyeSI6eyJkYXRhYmFzZSI6MiwicXVlcnkiOnsiZXhwcmVzc2lvbnMiOnsiTWFpbiBGYWlsdXJlIEZhdWx0IjpbImNhc2UiLFtbWyI9IixbImZpZWxkIiw2ODk3Nix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwic291cmNlIl0sWyJmaWVsZCIsNjkwNDkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLFtbIj0iLFsiZmllbGQiLDY4OTc2LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJkZXN0aW5hdGlvbiJdLFsiZmllbGQiLDY5MDQzLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSxbWyI9IixbImZpZWxkIiwyNTk2NTkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIm1hbnVhbF9jYW5jZWxsYXRpb24iXSwiQ2FuY2VsbGVkIl1dLHsiZGVmYXVsdCI6IlBsYXRmb3JtIn1dfSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw2OTA5Myx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZmFpbGVkIl0sWyI9IixbImZpZWxkIiw2OTAyOCx7ImJhc2UtdHlwZSI6InR5cGUvQm9vbGVhbiJ9XSx0cnVlXSxbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDY5MDEzLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLC0xMiwid2VlayJdLFsiIT0iLFsiZmllbGQiLDI1OTY1OSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwibWFudWFsX2NhbmNlbGxhdGlvbiJdLFsiPSIsWyJmaWVsZCIsMjc2ODE2LHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dLGZhbHNlXSxbIj0iLFsiZmllbGQiLDQzODE3Nyx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiU29tZXRoaW5nIHdlbnQgd3JvbmcgaW4gdGhlIGNvbm5lY3Rvci4gU2VlIHRoZSBsb2dzIGZvciBtb3JlIGRldGFpbHMuIl0sWyI9IixbImZpZWxkIiw2ODk3Nix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwic291cmNlIl0sWyI9IixbImZpZWxkIiwyNTk2NTkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sInN5c3RlbV9lcnJvciJdLFsiPSIsWyJleHByZXNzaW9uIiwiTWFpbiBGYWlsdXJlIEZhdWx0Iix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiUG9zdGdyZXMiXSxbIj0iLFsiZmllbGQiLDY5MDQ5LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJQb3N0Z3JlcyIsIk15U1FMIl1dLCJzb3VyY2UtdGFibGUiOjYzMDV9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImNvbHVtbl9zZXR0aW5ncyI6eyJbXCJyZWZcIixbXCJmaWVsZFwiLDQzODE3Nyx7XCJiYXNlLXR5cGVcIjpcInR5cGUvVGV4dFwifV1dIjp7ImNvbHVtbl90aXRsZSI6IkV4YW1wbGUgSW50ZXJuYWwgTWVzc2FnZSAoQ2xlYW5lZCkifX0sInRhYmxlLmNlbGxfY29sdW1uIjoiY291bnQiLCJ0YWJsZS5jb2x1bW5zIjpbeyJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNDM4MTc3LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDQzODE3Nyx7XCJiYXNlLXR5cGVcIjpcInR5cGUvVGV4dFwifV1dIiwibmFtZSI6Im1haW5fZmFpbHVyZV9leHRlcm5hbF9tZXNzYWdlX2NsZWFuZWQifSx7ImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw2ODk3Nix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw2ODk3Nix7XCJiYXNlLXR5cGVcIjpcInR5cGUvVGV4dFwifV1dIiwibmFtZSI6Im1haW5fZmFpbHVyZV9vcmlnaW4ifSx7ImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiwyNTk2NTkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsMjU5NjU5LHtcImJhc2UtdHlwZVwiOlwidHlwZS9UZXh0XCJ9XV0iLCJuYW1lIjoibWFpbl9mYWlsdXJlX3R5cGUifSx7ImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImV4cHJlc3Npb24iLCJNYWluIEZhaWx1cmUgRmF1bHQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJrZXkiOiJbXCJyZWZcIixbXCJleHByZXNzaW9uXCIsXCJNYWluIEZhaWx1cmUgRmF1bHRcIix7XCJiYXNlLXR5cGVcIjpcInR5cGUvVGV4dFwifV1dIiwibmFtZSI6Ik1haW4gRmFpbHVyZSBGYXVsdCJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiYWdncmVnYXRpb24iLDBdLCJrZXkiOiJbXCJuYW1lXCIsXCJjb3VudFwiXSIsIm5hbWUiOiJjb3VudCJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiYWdncmVnYXRpb24iLDFdLCJrZXkiOiJbXCJuYW1lXCIsXCJjb3VudF8yXCJdIiwibmFtZSI6ImNvdW50XzIifSx7ImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImFnZ3JlZ2F0aW9uIiwyXSwia2V5IjoiW1wibmFtZVwiLFwibWF4XCJdIiwibmFtZSI6Im1heCJ9XSwidGFibGUucGl2b3RfY29sdW1uIjoibWFpbl9mYWlsdXJlX3R5cGUifSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=)

```
io.airbyte.cdk.integrations.source.relationaldb.state.FailedRecordIteratorException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: ...Caused by: java.net.SocketException: Connection reset ...
```

```
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: permission denied for table xxx
```

```
java.lang.RuntimeException: org.postgresql.util.PSQLException: Result set exceeded maxResultBuffer limit. Received: 161061481; Current limit: 161061273 at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase$toUnsafeStream$1.tryAdvance(StreamingJdbcDatabase.kt:101) at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.kt:45) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.kt:65) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) at io.airbyte.cdk.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.kt:277) at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.kt:334) at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:184) at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:116) at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:672) Suppressed: java.lang.RuntimeException: java.sql.SQLException: Connection is closed at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase.unsafeQuery$lambda$0(StreamingJdbcDatabase.kt:68) at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) at io.airbyte.commons.util.AutoCloseableIterators.fromStream$lambda$0(AutoCloseableIterators.kt:74) at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.kt:12) at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.kt:53) at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.kt:55) at io.airbyte.commons.util.AutoCloseableIterators.transform$lambda$6(AutoCloseableIterators.kt:185) at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.kt:12) at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.kt:53) at io.airbyte.commons.util.AutoCloseableIterators.transform$lambda$6(AutoCloseableIterators.kt:185) at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.kt:12) at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.kt:53) at io.airbyte.commons.util.CompositeIterator.close(CompositeIterator.kt:126) at io.airbyte.commons.util.AutoCloseableIterators.appendOnClose$lambda$2(AutoCloseableIterators.kt:120) at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.kt:12) at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.kt:53) at io.airbyte.commons.util.AutoCloseableIterators.appendOnClose$lambda$2(AutoCloseableIterators.kt:120) at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.kt:12) at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.kt:53) at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:49) at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.kt:333) ... 3 more Caused by: java.sql.SQLException: Connection is closed at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:503) at jdk.proxy3/jdk.proxy3.$Proxy40.getAutoCommit(Unknown Source) at com.zaxxer.hikari.pool.HikariProxyConnection.getAutoCommit(HikariProxyConnection.java) at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase.unsafeQuery$lambda$0(StreamingJdbcDatabase.kt:60) ... 23 more Caused by: org.postgresql.util.PSQLException: Result set exceeded maxResultBuffer limit. Received: 161061481; Current limit: 161061273 at org.postgresql.core.PGStream.increaseByteCounter(PGStream.java:834) at org.postgresql.core.PGStream.receiveTupleV3(PGStream.java:611) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2368) at org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2598) at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:2235) at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java) at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase$toUnsafeStream$1.tryAdvance(StreamingJdbcDatabase.kt:89) ... 30 more
```

```
io.airbyte.cdk.integrations.source.relationaldb.state.FailedRecordIteratorException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout at io.airbyte.cdk.integrations.source.relationaldb.state.SourceStateIterator.computeNext(SourceStateIterator.kt:36) at io.airbyte.cdk.integrations.source.relationaldb.state.SourceStateIterator.computeNext(SourceStateIterator.kt:17) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.kt:65) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) at io.airbyte.cdk.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.kt:277) at io.airbyte.cdk.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.kt:334) at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:184) at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:116) at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:672) Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.kt:72) at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.queryTableIncremental$lambda$22(AbstractJdbcSource.kt:536) at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.kt:40) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46) at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.kt:42) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at io.airbyte.cdk.integrations.source.relationaldb.state.SourceStateIterator.computeNext(SourceStateIterator.kt:30) ... 25 more Caused by: org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134) at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.getActualCursorRecordCount(AbstractJdbcSource.kt:674) at io.airbyte.cdk.integrations.source.jdbc.AbstractJdbcSource.queryTableIncremental$lambda$22$lambda$21(AbstractJdbcSource.kt:555) at io.airbyte.cdk.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.kt:54) ... 34 more
```

[Postgres Hikari](https://airbyte.metabaseapp.com/question#eyJuYW1lIjoiVG9wIEVycm9yIE1lc3NhZ2VzIChieSBKb2IpIC0gRXhjbHVkZSBDYW5jZWxsZWQiLCJkZXNjcmlwdGlvbiI6bnVsbCwiZGF0YXNldF9xdWVyeSI6eyJkYXRhYmFzZSI6MiwicXVlcnkiOnsiZXhwcmVzc2lvbnMiOnsiTWFpbiBGYWlsdXJlIEZhdWx0IjpbImNhc2UiLFtbWyI9IixbImZpZWxkIiw2ODk3Nix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwic291cmNlIl0sWyJmaWVsZCIsNjkwNDkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLFtbIj0iLFsiZmllbGQiLDY4OTc2LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJkZXN0aW5hdGlvbiJdLFsiZmllbGQiLDY5MDQzLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSxbWyI9IixbImZpZWxkIiwyNTk2NTkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIm1hbnVhbF9jYW5jZWxsYXRpb24iXSwiQ2FuY2VsbGVkIl1dLHsiZGVmYXVsdCI6IlBsYXRmb3JtIn1dfSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw2OTA5Myx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZmFpbGVkIl0sWyI9IixbImZpZWxkIiw2OTAyOCx7ImJhc2UtdHlwZSI6InR5cGUvQm9vbGVhbiJ9XSx0cnVlXSxbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDY5MDEzLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLC0xMiwid2VlayJdLFsiIT0iLFsiZmllbGQiLDI1OTY1OSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwibWFudWFsX2NhbmNlbGxhdGlvbiJdLFsiPSIsWyJmaWVsZCIsMjc2ODE2LHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dLGZhbHNlXSxbIj0iLFsiZmllbGQiLDQzODE3Nyx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiTWVzc2FnZTogSGlrYXJpUG9vbC14IC0gQ29ubmVjdGlvbiBpcyBub3QgYXZhaWxhYmxlLCByZXF1ZXN0IHRpbWVkIG91dCBhZnRlciB4bXMgKHRvdGFsPXgsIGFjdGl2ZT14LCBpZGxlPXgsIHdhaXRpbmc9eCkiXSxbIj0iLFsiZmllbGQiLDY4OTc2LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJzb3VyY2UiXSxbIj0iLFsiZmllbGQiLDI1OTY1OSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiY29uZmlnX2Vycm9yIl0sWyI9IixbImV4cHJlc3Npb24iLCJNYWluIEZhaWx1cmUgRmF1bHQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJQb3N0Z3JlcyJdLFsiPSIsWyJmaWVsZCIsNjkwNDkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIlBvc3RncmVzIiwiTXlTUUwiXV0sInNvdXJjZS10YWJsZSI6NjMwNX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiY29sdW1uX3NldHRpbmdzIjp7IltcInJlZlwiLFtcImZpZWxkXCIsNDM4MTc3LHtcImJhc2UtdHlwZVwiOlwidHlwZS9UZXh0XCJ9XV0iOnsiY29sdW1uX3RpdGxlIjoiRXhhbXBsZSBJbnRlcm5hbCBNZXNzYWdlIChDbGVhbmVkKSJ9fSwidGFibGUuY2VsbF9jb2x1bW4iOiJjb3VudCIsInRhYmxlLmNvbHVtbnMiOlt7ImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw0MzgxNzcseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNDM4MTc3LHtcImJhc2UtdHlwZVwiOlwidHlwZS9UZXh0XCJ9XV0iLCJuYW1lIjoibWFpbl9mYWlsdXJlX2V4dGVybmFsX21lc3NhZ2VfY2xlYW5lZCJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDY4OTc2LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDY4OTc2LHtcImJhc2UtdHlwZVwiOlwidHlwZS9UZXh0XCJ9XV0iLCJuYW1lIjoibWFpbl9mYWlsdXJlX29yaWdpbiJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDI1OTY1OSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiwyNTk2NTkse1wiYmFzZS10eXBlXCI6XCJ0eXBlL1RleHRcIn1dXSIsIm5hbWUiOiJtYWluX2ZhaWx1cmVfdHlwZSJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZXhwcmVzc2lvbiIsIk1haW4gRmFpbHVyZSBGYXVsdCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImtleSI6IltcInJlZlwiLFtcImV4cHJlc3Npb25cIixcIk1haW4gRmFpbHVyZSBGYXVsdFwiLHtcImJhc2UtdHlwZVwiOlwidHlwZS9UZXh0XCJ9XV0iLCJuYW1lIjoiTWFpbiBGYWlsdXJlIEZhdWx0In0seyJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJhZ2dyZWdhdGlvbiIsMF0sImtleSI6IltcIm5hbWVcIixcImNvdW50XCJdIiwibmFtZSI6ImNvdW50In0seyJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJhZ2dyZWdhdGlvbiIsMV0sImtleSI6IltcIm5hbWVcIixcImNvdW50XzJcIl0iLCJuYW1lIjoiY291bnRfMiJ9LHsiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiYWdncmVnYXRpb24iLDJdLCJrZXkiOiJbXCJuYW1lXCIsXCJtYXhcIl0iLCJuYW1lIjoibWF4In1dLCJ0YWJsZS5waXZvdF9jb2x1bW4iOiJtYWluX2ZhaWx1cmVfdHlwZSJ9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==) 

```
io.airbyte.commons.exceptions.ConnectionErrorException: java.sql.SQLTransientConnectionException: HikariPool-x - Connection is not available, request timed out after xms (total=x, active=x, idle=x, waiting=x)

```

MySQL

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Connector configuration is not valid. Unable to connect: The server time zone value 'PDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'connectionTimeZone' configuration property) to use a more specific time zone value if you want to utilize time zone support.
```
MySQL hikari pool

```
io.airbyte.commons.exceptions.ConnectionErrorException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60002ms (total=0, active=0, idle=0, waiting=0)
```

### PR DESCRIPTION
**Pull request by theyueli**
## What

Fixes https://github.com/airbytehq/airbyte/issues/41614
Fixes https://github.com/airbytehq/oncall/issues/5750
Fixes https://github.com/airbytehq/oncall/issues/5346
Fixes https://github.com/airbytehq/oncall/issues/5381
Fixes https://github.com/airbytehq/airbyte-internal-issues/issues/7156
Fixes https://github.com/airbytehq/oncall/issues/5321
Fixes https://github.com/airbytehq/oncall/issues/5293
Fixes https://github.com/airbytehq/oncall/issues/5250
Fixes https://github.com/airbytehq/airbyte-internal-issues/issues/7155

This patch includes multiple translation rules for additional top opaque and system error messages that can be converted to transient or config errors. 

## How

Translation / error profiles are added into the exception handler class for Postgres and MySQL source. 

## Review guide

Main changes are in `MySqlSourceExceptionHandler.kt` and `PostgresSourceExceptionHandler.kt`

## User Impact
User will start seeing a translated error message instead of the original detailed error message.

## Can this PR be safely reverted and rolled back?

- [ X] YES 💚
- [ ] NO ❌

### CODE REVIEW

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt [hunk 1]
```diff
@@ -31,8 +31,73 @@ class MySqlSourceExceptionHandler : ConnectorExceptionHandler() {
...
                 sampleInternalMessage =
-                    "java.io.EOFException: Can not read response from server. Expected to read X bytes, read Y bytes before connection was unexpectedly lost."
-            )
+                    "java.io.EOFException: Can not read response from server. Expected to read X bytes, read Y bytes before connection was unexpectedly lost.",
+            ),
+        )
+
+        add(
+            ConnectorErrorProfile(
+                errorClass = "MySQL Hikari Connection Error",
```
Comment (evantahler) [inline airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: I interpreted this option to be matching on the classname of the exception that was thrown. But, I don't think that's what is happening here.  Is only the `regexMatchingPattern` used for finding the error to match?

Comment (evantahler) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: e.g. I would expect this to be `HikariPoolException` in this case

Comment (theyueli) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: I see; in this case, I think I did not interpret the `errorClass` correctly; I thought it was like a tag used to name the kind of errors...  so yes, currently, only regex is used, and the error message is still unique enough to get matched.

But yes, certainly, we can support this class as well. In your thoughts, this class should be a real type/class, but not a string, correct?

Comment (theyueli) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: and for Hikari errors like [this](https://github.com/airbytehq/oncall/issues/5346) (https://airbytehq.sentry.io/issues/5129832484/?project=6527718)

```
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 10001ms
```

It does not have HikariPoolException, but `java.sql.SQLTransientConnectionException`, so we shall use this as the class I guess?

Comment (evantahler) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: I think if you are only using the regular expression match, and you want that match to be applied to all errors of all classes, I think you can skip the errorClass option.  Yes, I would epxect errorClass to be a real class or array of classess.

Comment (theyueli) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: That sounds good; I will submit another PR to implement this; this should not be very complicated to add to the existing translation mechanism.

Comment (theyueli) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:40]: it's good you pointed out this.. i actually had difficulty explain what was the errorClass for.. now it makes much more sense...

**Review by akashkulk — APPROVED** [review]

**Review by xiaohansong — APPROVED** [review]

File: airbyte-integrations/connectors/source-postgres/src/main/kotlin/io/airbyte/integrations/source/postgres/PostgresSourceExceptionHandler.kt [hunk 2]
```diff
@@ -56,5 +56,109 @@ class PostgresSourceExceptionHandler : ConnectorExceptionHandler() {
...
+                        "java.lang.RuntimeException: org.apache.kafka.connect.errors.ConnectException: " +
+                        "An exception occurred in the change event producer. This connector will be stopped...." +
+                        "java.net.SocketException: Broken pipe",
+                referenceLinks = listOf("https://github.com/airbytehq/oncall/issues/5321"),
+            ),
+        )
+
+        add(
+            ConnectorErrorProfile(
+                errorClass = "Postgres Debezium Connection Error",
```
Comment (xiaohansong) [inline airbyte-integrations/connectors/source-postgres/src/main/kotlin/io/airbyte/integrations/source/postgres/PostgresSourceExceptionHandler.kt:146]: nit: consider creating enum/global static var to hold error class to avoid typos

Comment (theyueli) [reply airbyte-integrations/connectors/source-postgres/src/main/kotlin/io/airbyte/integrations/source/postgres/PostgresSourceExceptionHandler.kt:146]: thanks xiaohan! the error class will be repurposed to be real exception / error class instead of strings. It will be implemented as a feature / bug fix in a separate PR (see discussion with Evan above).

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt [hunk 3]
```diff
@@ -31,8 +31,73 @@ class MySqlSourceExceptionHandler : ConnectorExceptionHandler() {
...
+
+        add(
+            ConnectorErrorProfile(
+                errorClass = "MySQL Timezone Error",
+                regexMatchingPattern = ".*is unrecognized or represents more than one time zone*",
+                failureType = FailureType.CONFIG,
+                externalMessage =
+                    "Please configure your database with the correct timezone found in the detailed error message. " +
+                        "Please refer to the following documentation: https://dev.mysql.com/doc/refman/8.4/en/time-zone-support.html",
+                sampleInternalMessage =
```
Comment (cgardens) [inline airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:58]: @theyueli  What is this field supposed to be used for? I can't find any usages in the code base?

Comment (theyueli) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/MySqlSourceExceptionHandler.kt:58]: correct. We used this field to store a sample message which provides a bit more context for this error. This should be an optional field to fill. The purpose is similar to the reference link field which provides links to github/sentry issues.
