### PR TITLE
🐛Destination-gcs\destination-bigquery(gcs) - updated check() method to handle that user has both storage.objects.create and storage.multipartUploads.create roles

### LINKED ISSUE #9044: 🐛 Destination GCS: Multi-part upload permissions are not validated by the connection check step
While troubleshooting this [user's](https://airbytehq.slack.com/archives/C01MFR03D5W/p1640008671040700) problem I realized that the connection check could be improved to avoid false-positive connection checks.

## Current Behavior
On `check` GCS destination performs a **`putObject`** operation to check it has permission to write to the destination bucket:
```java
s3Client.putObject(destinationConfig.getBucketName(), "test", "check-content");
```

On `write` the `S3StreamTransferManagerHelper` is performing a **multipart upload**. 
On GCS `storage.multipartUploads.create` permission is required to write an object to the bucket, the `check` only requires `storage.objects.create` permission.
If the service account has  `storage.objects.create` permission but not `storage.multipartUploads.create` the `check` will pass but the sync will fail.

## Expected Behavior
`check` should fail if the service account does not have `storage.multipartUploads.create` permissions.

## Logs
[Logs_Mayur_Mahajan_20211220.txt](https://github.com/airbytehq/airbyte/files/7763226/Logs_Mayur_Mahajan_20211220.txt)

### PR DESCRIPTION
**Pull request by etsybaev**
## What
On write the S3StreamTransferManagerHelper is performing a multipart upload.
On GCS storage.multipartUploads.create permission is required to write an object to the bucket, the check only requires storage.objects.create permission.
If the service account has storage.objects.create permission but not storage.multipartUploads.create the check will pass but the sync will fail.

## Recommended reading order:
1. GcsDestination.java 
2. DestinationAcceptanceTest.java
P.S. ignore python files, there are only auto-formatting updates that occurred after running format command ("./gradlew --no-daemon format --scan")

## How
Updated check method to check both roles.

!!!!!! TODO once approved !!!!!!!!:
 - perform final test for user with missed roles for Multipart upload
 - pass PR checklists
 - update versions
 - update changelog
 - publish destination-gcs, destination-bigquery and destination-bigquery-denormalized

Also tested locally on UI:
here is the result for user without multipart upload role (fails with AccessDenied and printed expected roles):
Selection_363

Here is the result for user with all expected roles (verification passed):
Selection_364

## User Impact 
No breaks backward compatibility expected

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java [hunk 1]
```diff
@@ -31,13 +36,38 @@ public static void main(final String[] args) throws Exception {
...
+          .withS3Client(s3Client)
+          .build();
+
+      // Test Multipart Upload permissions
+      // TransferManager processes all transfers asynchronously,
+      // so this call returns immediately.
+      final File tmpFile = File.createTempFile(fileName, ".tmp");
+      final FileWriter writer = new FileWriter(tmpFile);
+      writer.write(testContent);
+      writer.close();
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java:58]: Could we use try-with-resources here, instead of `.close()`method?

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java [hunk 2]
```diff
@@ -31,13 +36,38 @@ public static void main(final String[] args) throws Exception {
...
+      final Upload upload = tm.upload(destinationConfig.getBucketName(), fileName, tmpFile);
+
+      upload.waitForCompletion();
+      LOGGER.info("Object upload complete");
+      s3Client.deleteObject(destinationConfig.getBucketName(), fileName);
+      LOGGER.info("All checks have passed.");
+      tm.shutdownNow(true);
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java:65]: I suggest to split this method flow to different private methods such as: `write, upload, etc`

**Comment by alexandertsukanov** [comment]
Finished with review, left comments.

**Comment by alexandertsukanov** [comment]
CC: @etsybaev

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java (hunk 1 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java]: Good catch, updated, thanks

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java (hunk 2 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/GcsDestination.java]: updated, thanks

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publishing and merging without airbyte review

File: airbyte-integrations/connectors/destination-gcs/build.gradle [hunk 3]
```diff
@@ -12,6 +12,7 @@ application {
 dependencies {
     implementation project(':airbyte-config:models')
     implementation project(':airbyte-protocol:models')
+    implementation project(':airbyte-workers')
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-gcs/build.gradle:15]: It looks like the worker is not needed?

Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/build.gradle]: Hi @tuliren.
I've added a new test for insufficient roles verification that calls runCheck method. If fails like this if airbyte-workers haven't been added. 
Selection_365


But you're right, that this is not required for the whole project, moved it to integrationTestJavaImplementation dependency.
Thanks

File: airbyte-integrations/connectors/destination-gcs/src/test-integration/java/io/airbyte/integrations/destination/gcs/GcsDestinationAcceptanceTest.java [hunk 4]
```diff
@@ -44,7 +48,8 @@
   protected static final Logger LOGGER = LoggerFactory.getLogger(GcsDestinationAcceptanceTest.class);
   protected static final ObjectMapper MAPPER = MoreMappers.initMapper();
 
-  protected final String secretFilePath = "secrets/config.json";
+  protected static final String SECRET_FILE_PATH = "secrets/config.json";
+  protected static final String SECRET_FILE_PATH_INSUFFICIENT_ROLES = "secrets/insufficientrolesconfig.json";
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-gcs/src/test-integration/java/io/airbyte/integrations/destination/gcs/GcsDestinationAcceptanceTest.java:52]: Nitpick. Can you add underscores in the filename to make it more readable? Like `insufficient_roles_config.json`.

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+          + "\n"
+          + "Praesent finibus scelerisque elit, accumsan condimentum risus mattis vitae. Donec tristique hendrerit facilisis. Curabitur metus purus, venenatis non elementum id, finibus eu augue. Quisque posuere rhoncus ligula, et vehicula erat pulvinar at. Pellentesque vel quam vel lectus tincidunt congue quis id sapien. Ut efficitur mauris vitae pretium iaculis. Aliquam consectetur iaculis nisi vitae laoreet. Integer vel odio quis diam mattis tempor eget nec est. Donec iaculis facilisis neque, at dictum magna vestibulum ut. Sed malesuada non nunc ac consequat. Maecenas tempus lectus a nisl congue, ac venenatis diam viverra. Nam ac justo id nulla iaculis lobortis in eu ligula. Vivamus et ligula id sapien efficitur aliquet. Curabitur est justo, tempus vitae mollis quis, tincidunt vitae felis. Vestibulum molestie laoreet justo, nec mollis purus vulputate at.";
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java:26]: Can we construct a string of this size automatically? Like `StringUtils.repeat("a", 3464)`.

(I think the string length is 3468, including the newline `\n` character. But I could be wrong in the exact number.)

**Review by tuliren — APPROVED** [review]
Cool. Thanks for adding the extra test.

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+public class Consts {
+
+  public static final String EXPECTED_ROLES = "storage.multipartUploads.abort, storage.multipartUploads.create, "
+      + "storage.objects.create, storage.objects.delete, storage.objects.get, storage.objects.list";
+
+  public static final String CHECK_ACTIONS_TMP_FILE_NAME = "test";
+
+  // Uploads this text size will automatically use a multipart upload strategy, while uploads smaller
+  // than this threshold will use
+  // a single connection to upload the whole object even if multipart upload option is ON.
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java:16]: Is there a documentation about this threshold that will trigger multipart upload? If so, you can paste the link here.

Comment (tuliren) [reply airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java:16]: Totally fine to ignore this comment if you find this threshold by trail and error.

**Review by alexandertsukanov — APPROVED** [review]
Looks good!

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java (hunk 5 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java]: Updated, thanks

File: airbyte-integrations/connectors/destination-gcs/src/test-integration/java/io/airbyte/integrations/destination/gcs/GcsDestinationAcceptanceTest.java (hunk 4 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/test-integration/java/io/airbyte/integrations/destination/gcs/GcsDestinationAcceptanceTest.java]: I thought that our secret manager doesn't allow such symbols. Updated, thanks!

File: airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java (hunk 6 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-gcs/src/main/java/io/airbyte/integrations/destination/gcs/util/Consts.java]: Done, thanks

**Comment by etsybaev** [comment]
The bigquery-denormalized connector currently seems to have broken integration tests after recent merging another PR. So the version will be bumped as part of its fixing

**Comment by mjaggard** [comment]
@etsybaev This change seems to require either `storage.multipartUploads.listParts` or `storage.multipartUploads.list` or both. Without them but with the listed permissions I got Access Denied when trying to add a destination.

**Comment by tuliren** [comment]
> @etsybaev This change seems to require either `storage.multipartUploads.listParts` or `storage.multipartUploads.list` or both. Without them but with the listed permissions I got Access Denied when trying to add a destination.

@mjaggard, yes, these permissions are required to write the data to GCS. See the doc here:

https://docs.airbyte.com/integrations/destinations/gcs#setup-guide

We use a multipart uploader to write the data. Without these permissions, the uploader cannot work properly. Even if @etsybaev does not add the check here, your sync will fail. It's better to do the permission check and fail early on, instead of getting the error after you set up the connection and start syncing data.

**Comment by tuliren** [comment]
Actually let me double check that our integration test is using a service account that only has these six permissions.

**Comment by tuliren** [comment]
The integration test passed locally with the six permissions, but failed on CI. I will look into it. https://github.com/airbytehq/airbyte/issues/9631

**Comment by mjaggard** [comment]
@etsybaev yes, that was my expectation from the docs here and from the docs on Google cloud, but my experience when using the latest version of airbyte was needing to add the list permission too.

Are you in a position to test that and update the docs on airbyte connector page if needed?

**Comment by tuliren** [comment]
I did not have time to fully investigate this last week. Will do it on Monday.
