### PR TITLE
Hotfix: Fix log_path bug for jobs with  multiple attempts

### LINKED ISSUE #1343: Multiple attempts with the same log_path
## Expected Behavior
* Each attempt should have its own log path.

## Current Behavior
* In one case two attempts were created with the same log path. It seems likely it is related to this behavior specified in a [comment in the code](https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java#L94-L98).
* Setting this to high urgency because there is a lot of undefined behavior that crops up when this happens.

## Steps to Reproduce
* Have not yet been able to reproduce it. It should not be possible to create an attempt for a job while it already has a running attempt.
* Evidence that it happened:
```
airbyte=# SELECT attempts.* FROM jobs LEFT OUTER JOIN attempts ON jobs.id = attempts.job_id where jobs.id=48;
 id | job_id | attempt_number |           log_path           | output | status  |          created_at           |          updated_at           | ended_at
----+--------+----------------+------------------------------+--------+---------+-------------------------------+-------------------------------+----------
 48 |     48 |              0 | /tmp/workspace/48/0/logs.log |        | failed  | 2020-12-15 22:34:02.793586+00 | 2020-12-15 22:34:09.056187+00 |
 50 |     48 |              2 | /tmp/workspace/48/1/logs.log |        | running | 2020-12-15 22:36:23.387997+00 | 2020-12-15 22:36:23.387997+00 |
 49 |     48 |              1 | /tmp/workspace/48/1/logs.log |        | failed  | 2020-12-15 22:35:13.094404+00 | 2020-12-15 23:37:26.446024+00 |
(3 rows)
```
* It seems like between this [line](https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/src/main/java/io/airbyte/scheduler/WorkerRunFactory.java#L82) and this [one](https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java#L99) another attempt was created for the job
* Things to check: 
  * can multiple job submitters run at once (this should not be the case but possible we do do this right)
  * possible fix would be to pass the attempt number into the job run factory.
  * i can't get the old schedule / submitter logs to see if we logged anything useful when this error occurred.

### LINKED ISSUE #1425: Stuck with Incomplete jobs status
## Expected Behavior
*Tell us what should happen.*

When I click buttons "sync now" or even "reset data", I expect a new sync attempt starting up

## Current Behavior

Nothing ever happens, it just creates new lines stating "Pending" with "Empty data"  as details.

Screenshot 2020-12-22 at 10 45 22

## Steps to Reproduce
Same as #1419
1. Configure an API SOURCE
1. Configure a local CSV
1. Replicate successfully
1. Change permissions in parallel in a terminal to remove write permissions to files in the /local/ directory 
1. Now, observe failing attempts until marked "Incomplete" when job is triggered
1. From here, the UI/server doesn't give new responses from any other buttons and I don't know what to do to keep going forward (even if I fix my write permissions externally)

How do I get my replication back to a working state after encountering failing/incomplete attempts?

## Severity of the bug for you
 High

### PR DESCRIPTION
**Pull request by cgardens**
Closes https://github.com/airbytehq/airbyte/issues/1425
Closes https://github.com/airbytehq/airbyte/issues/1343

## 2 Problems
* We swallowed exceptions throw in `LifecycledCallable` so it was hard to debug what was going wrong. This is why we were not seeing the exception that would have told us why multiple attempts were getting assigned the same log_path.
* `DefaultJobPersistence` has a bug for `getLastSyncJob`, `getCurrentState`, `getNextJob`. The query included a `LIMIT 1`, which meant that for the desired job it was not fetching all of its attempts. This is why the log paths were the same across multiple attempts. We use the number of attempts to determine the next log path, but because the query only pulled 0 or 1 attempts, the log paths never got passed 1. The fix makes sure we pull all of the attempts.

### CODE REVIEW

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java [hunk 1]
```diff
@@ -120,7 +119,8 @@ void submitJob(Job job) {
           }
           trackCompletion(job, output.getStatus());
         })
-        .setOnException(noop -> {
+        .setOnException(e -> {
+          LOGGER.error("Exception thrown in Job Submission: ", e);
```
Comment (cgardens) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java:123]: this is the reason exception in on start and run were getting swallowed.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java [hunk 2]
```diff
@@ -269,21 +273,27 @@ private Job getJob(DSLContext ctx, long jobId) {
 
   @Override
   public Optional<Job> getLastSyncJob(UUID connectionId) throws IOException {
-    return database.query(ctx -> getJobFromResult(ctx
+    return database.query(ctx -> ctx
         .fetch(BASE_JOB_SELECT_AND_JOIN + "WHERE scope = ? AND CAST(jobs.status AS VARCHAR) <> ? ORDER BY jobs.created_at DESC LIMIT 1",
```
Comment (cgardens) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java:277]: the problematic query style where it would pull only 1 attempt. now we get the job id of the attempt we care about and then use a helper to make sure we pull all attempts for that job.

File: airbyte-scheduler/src/test/java/io/airbyte/scheduler/persistence/DefaultJobPersistenceTest.java [hunk 3]
```diff
@@ -544,6 +545,50 @@ public void testGetOldestPendingJobOnlyPendingJobs() throws IOException {
     assertTrue(actual.isEmpty());
   }
 
+  @Test
```
Comment (cgardens) [inline airbyte-scheduler/src/test/java/io/airbyte/scheduler/persistence/DefaultJobPersistenceTest.java:548]: tests that catch this case for each method that uses the limit.

File: airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java [hunk 4]
```diff
@@ -75,9 +74,9 @@ public void run() {
     try {
       LOGGER.info("Running job-submitter...");
 
-      final Optional<Job> oldestPendingJob = persistence.getNextJob();
+      final Optional<Job> nextJob = persistence.getNextJob();
```
Comment (jrhizor) [inline airbyte-scheduler/src/main/java/io/airbyte/scheduler/JobSubmitter.java:77]: thank you

**Review by jrhizor — APPROVED** [review]
