### PR TITLE
Destinations snowflake+bigquery: Improve performance by filtering raw table on extracted_at

### LINKED ISSUE #28380: T&D Queries should analyze less data where possible by only considering recently emitted rows
Datawarehouses bill based on how much data is analyzed in the query.  If we can add more WHERE clauses to limit which rows are considered, that will help. 

See https://github.com/airbytehq/typing-and-deduping-sql/pull/23/files for some ideas of what to do.  Also, read this [slack thread](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1689364727121419).

Add a test case for this:
* a sync crashing and having un-typed data from a previous run

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/28380; based on https://github.com/airbytehq/typing-and-deduping-sql/pull/23

Adds a `_airbyte_extracted_at > ?` filter to two queries in T+D:
* Inserting new raw records to the final table
* Setting `_airbyte_loaded_at = current_timestamp`

And adds three tests to exercise this behavior.

This is a somewhat nontrivial change, so I'll roll it out to the internal workspace for bigquery first. If that works then I'll do a full release for both bigquery and snowflake (since the logic is basically identical for both destinations).

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`9666713f90`](https://github.com/airbytehq/airbyte/pull/31191/commits/9666713f90ca846919ee5d9eb25bdb37df0e8376)) - ❌

⏲️  Total pipeline duration: 09mn08s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ❌        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697065041/9666713f90ca846919ee5d9eb25bdb37df0e8376/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9666713f90ca846919ee5d9eb25bdb37df0e8376)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

File: airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java [hunk 1]
```diff
@@ -57,6 +58,7 @@ public class DefaultTyperDeduper<DialectTableDefinition> implements TyperDeduper
   private final ParsedCatalog parsedCatalog;
   private Set<StreamId> overwriteStreamsWithTmpTable;
   private final Set<Pair<String, String>> streamsWithSuccessfulSetup;
+  private final Map<StreamId, Optional<Instant>> minExtractedAtByStream;
```
Comment (edgao) [inline airbyte-integrations/bases/base-typing-deduping/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/DefaultTyperDeduper.java:61]: there are _so many_ parallel maps of stream -> (something)... I'll take some time tomorrow to shove those into a struct or something.

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`6b7bf355a1`](https://github.com/airbytehq/airbyte/pull/31191/commits/6b7bf355a1b42a24c3b97e2d3de951882abea27e)) - ❌

⏲️  Total pipeline duration: 05mn58s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ❌        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697065764/6b7bf355a1b42a24c3b97e2d3de951882abea27e/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6b7bf355a1b42a24c3b97e2d3de951882abea27e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`6b7bf355a1`](https://github.com/airbytehq/airbyte/pull/31191/commits/6b7bf355a1b42a24c3b97e2d3de951882abea27e)) - ❌

⏲️  Total pipeline duration: 07mn00s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697065764/6b7bf355a1b42a24c3b97e2d3de951882abea27e/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6b7bf355a1b42a24c3b97e2d3de951882abea27e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`f054547f00`](https://github.com/airbytehq/airbyte/pull/31191/commits/f054547f008ceab8ce289ab02534a4efcb15999b)) - ❌

⏲️  Total pipeline duration: 04mn36s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ❌        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697067312/f054547f008ceab8ce289ab02534a4efcb15999b/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f054547f008ceab8ce289ab02534a4efcb15999b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`7259a45b86`](https://github.com/airbytehq/airbyte/pull/31191/commits/7259a45b86c903589f89f61110b8ce4b903b6df0)) - ❌

⏲️  Total pipeline duration: 08mn43s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697067753/7259a45b86c903589f89f61110b8ce4b903b6df0/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7259a45b86c903589f89f61110b8ce4b903b6df0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`7259a45b86`](https://github.com/airbytehq/airbyte/pull/31191/commits/7259a45b86c903589f89f61110b8ce4b903b6df0)) - ❌

⏲️  Total pipeline duration: 07mn27s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697067753/7259a45b86c903589f89f61110b8ce4b903b6df0/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7259a45b86c903589f89f61110b8ce4b903b6df0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`72c9c71ec9`](https://github.com/airbytehq/airbyte/pull/31191/commits/72c9c71ec90600b50f076128c51dec909b3bffae)) - ❌

⏲️  Total pipeline duration: 04mn15s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697068920/72c9c71ec90600b50f076128c51dec909b3bffae/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:72c9c71ec90600b50f076128c51dec909b3bffae)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`72c9c71ec9`](https://github.com/airbytehq/airbyte/pull/31191/commits/72c9c71ec90600b50f076128c51dec909b3bffae)) - ❌

⏲️  Total pipeline duration: 20mn05s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ❌        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697068920/72c9c71ec90600b50f076128c51dec909b3bffae/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:72c9c71ec90600b50f076128c51dec909b3bffae)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`bc09667d55`](https://github.com/airbytehq/airbyte/pull/31191/commits/bc09667d55227a99fa192c0dcc47151f537978f2)) - ❌

⏲️  Total pipeline duration: 09mn45s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697126684/bc09667d55227a99fa192c0dcc47151f537978f2/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bc09667d55227a99fa192c0dcc47151f537978f2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`bc09667d55`](https://github.com/airbytehq/airbyte/pull/31191/commits/bc09667d55227a99fa192c0dcc47151f537978f2)) - ❌

⏲️  Total pipeline duration: 08mn14s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697126684/bc09667d55227a99fa192c0dcc47151f537978f2/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bc09667d55227a99fa192c0dcc47151f537978f2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQueryDestinationHandler.java [hunk 2]
```diff
@@ -51,6 +56,37 @@ public boolean isFinalTableEmpty(final StreamId id) {
...
+                WHERE _airbyte_loaded_at IS NULL
+              ),
+              (
+                SELECT MAX(_airbyte_extracted_at)
+                FROM ${raw_table}
+              )
+            )
+            """))
+        .build());
+    final FieldValue value = queryResult.iterateAll().iterator().next().get(0);
```
Comment (gisripa) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQueryDestinationHandler.java:82]: Is the `iterator.next()` guaranteed to return single element, no threat of NPE ?

Comment (edgao) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQueryDestinationHandler.java:82]: yep! the query is just a simple `select <something>`, so it always returns exactly one record. The subqueries have the actual `select ... from ...` statements.

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`b024f76823`](https://github.com/airbytehq/airbyte/pull/31191/commits/b024f768236da232ece8845303f6175ca0562c88)) - ❌

⏲️  Total pipeline duration: 08mn26s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697135968/b024f768236da232ece8845303f6175ca0562c88/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b024f768236da232ece8845303f6175ca0562c88)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`b024f76823`](https://github.com/airbytehq/airbyte/pull/31191/commits/b024f768236da232ece8845303f6175ca0562c88)) - ❌

⏲️  Total pipeline duration: 07mn46s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697135968/b024f768236da232ece8845303f6175ca0562c88/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b024f768236da232ece8845303f6175ca0562c88)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`0c71a11418`](https://github.com/airbytehq/airbyte/pull/31191/commits/0c71a1141846168cb0e58018ece3bfb04f2be3ab)) - ❌

⏲️  Total pipeline duration: 08mn19s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697146032/0c71a1141846168cb0e58018ece3bfb04f2be3ab/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0c71a1141846168cb0e58018ece3bfb04f2be3ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`93173d2ceb`](https://github.com/airbytehq/airbyte/pull/31191/commits/93173d2cebeb65592ac08647aec29e4b25590f77)) - ❌

⏲️  Total pipeline duration: 08mn19s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697146845/93173d2cebeb65592ac08647aec29e4b25590f77/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:93173d2cebeb65592ac08647aec29e4b25590f77)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`adbd07753d`](https://github.com/airbytehq/airbyte/pull/31191/commits/adbd07753d33f2d41b5d810f4ccf455044be2dbf)) - ❌

⏲️  Total pipeline duration: 08mn24s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697147768/adbd07753d33f2d41b5d810f4ccf455044be2dbf/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:adbd07753d33f2d41b5d810f4ccf455044be2dbf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`ac572ab979`](https://github.com/airbytehq/airbyte/pull/31191/commits/ac572ab979009dd0f365038864d899168026a67a)) - ❌

⏲️  Total pipeline duration: 09mn33s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697148548/ac572ab979009dd0f365038864d899168026a67a/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ac572ab979009dd0f365038864d899168026a67a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`ac572ab979`](https://github.com/airbytehq/airbyte/pull/31191/commits/ac572ab979009dd0f365038864d899168026a67a)) - ❌

⏲️  Total pipeline duration: 08mn03s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697148548/ac572ab979009dd0f365038864d899168026a67a/destination-bigquery/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ac572ab979009dd0f365038864d899168026a67a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeDestinationHandler.java [hunk 3]
```diff
@@ -72,6 +76,47 @@ public boolean isFinalTableEmpty(final StreamId id) throws SQLException {
...
+                      FROM ${raw_table}
+                      WHERE "_airbyte_loaded_at" IS NULL
+                    ),
+                    (
+                      SELECT MAX("_airbyte_extracted_at")
+                      FROM ${raw_table}
+                    )
+                  ),
+                  'YYYY-MM-DDTHH24:MI:SS.FF9TZH:TZM'
+                ) AS MIN_TIMESTAMP
```
Comment (evantahler) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeDestinationHandler.java:113]: Since we are in the realm of performacne - does having the COALESCE mean that we will always exec 2 table scans here (`min(_airbyte_extracted_at)` and `max(_airbyte_extracted_at)`), or will the second sub-query not be executed if the first one is non-null?  If so, we could split this into 2 SQL statements to skip part 2 if part one returns something

File: airbyte-integrations/bases/base-typing-deduping/src/test/java/io/airbyte/integrations/base/destination/typing_deduping/MockSqlGenerator.java [hunk 4]
```diff
@@ -35,8 +38,11 @@ public String softReset(final StreamConfig stream) {
   }
 
   @Override
-  public String updateTable(final StreamConfig stream, final String finalSuffix) {
-    return "UPDATE TABLE " + stream.id().finalTableId("", finalSuffix);
+  public String updateTable(final StreamConfig stream, final String finalSuffix, final Optional<Instant> minRawTimestamp) {
+    final String timestampFilter = minRawTimestamp
+        .map(timestamp -> " WITH extracted_at > " + timestamp)
```
Comment (evantahler) [inline airbyte-integrations/bases/base-typing-deduping/src/test/java/io/airbyte/integrations/base/destination/typing_deduping/MockSqlGenerator.java:43]:
```suggestion
        .map(timestamp -> " WHERE extracted_at > " + timestamp)
```
... WHERE maybe?

**Review by evantahler — APPROVED** [review]
I focused just on the SQL.  Some nits, and a perf question, but nothing blocking.

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeDestinationHandler.java (hunk 3 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeDestinationHandler.java:113]: owait you're suggesting just running two statements in sequence. That sounds easier :P

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`e0c675f509`](https://github.com/airbytehq/airbyte/pull/31191/commits/e0c675f509e6e5bfb58428c0fd5fefec41552ef0)) - ❌

⏲️  Total pipeline duration: 02mn32s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697218748/e0c675f509e6e5bfb58428c0fd5fefec41552ef0/destination-bigquery/2.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e0c675f509e6e5bfb58428c0fd5fefec41552ef0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`e0c675f509`](https://github.com/airbytehq/airbyte/pull/31191/commits/e0c675f509e6e5bfb58428c0fd5fefec41552ef0)) - ❌

⏲️  Total pipeline duration: 02mn24s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697218748/e0c675f509e6e5bfb58428c0fd5fefec41552ef0/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e0c675f509e6e5bfb58428c0fd5fefec41552ef0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`ca354d1ff0`](https://github.com/airbytehq/airbyte/pull/31191/commits/ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc)) - ❌

⏲️  Total pipeline duration: 09mn06s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697219511/ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc/destination-snowflake/3.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`ca354d1ff0`](https://github.com/airbytehq/airbyte/pull/31191/commits/ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc)) - ❌

⏲️  Total pipeline duration: 11mn47s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-bigquery                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697219511/ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc/destination-bigquery/2.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ca354d1ff02940cb20cadd8cd47bd6cd337d9cbc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`539e365eac`](https://github.com/airbytehq/airbyte/pull/31191/commits/539e365eacd2552f2c7aa678581fa94e0e3945a3)) - ✅

⏲️  Total pipeline duration: 08mn59s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697558054/539e365eacd2552f2c7aa678581fa94e0e3945a3/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:539e365eacd2552f2c7aa678581fa94e0e3945a3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`539e365eac`](https://github.com/airbytehq/airbyte/pull/31191/commits/539e365eacd2552f2c7aa678581fa94e0e3945a3)) - ✅

⏲️  Total pipeline duration: 07mn12s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697558054/539e365eacd2552f2c7aa678581fa94e0e3945a3/destination-bigquery/2.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:539e365eacd2552f2c7aa678581fa94e0e3945a3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`77db8103bf`](https://github.com/airbytehq/airbyte/pull/31191/commits/77db8103bf4c2cc0124715040a612d0007fa9727)) - ✅

⏲️  Total pipeline duration: 03mn13s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697563905/77db8103bf4c2cc0124715040a612d0007fa9727/destination-bigquery/2.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:77db8103bf4c2cc0124715040a612d0007fa9727)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`77db8103bf`](https://github.com/airbytehq/airbyte/pull/31191/commits/77db8103bf4c2cc0124715040a612d0007fa9727)) - ✅

⏲️  Total pipeline duration: 02mn45s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_filter_td_on_extracted_at/1697563905/77db8103bf4c2cc0124715040a612d0007fa9727/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:77db8103bf4c2cc0124715040a612d0007fa9727)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```
