### PR TITLE
Destination Snowflake : fixed duplicate rows on retries

### LINKED ISSUE #8832: 🐛 Destination Snowflake: duplicate rows on retries when using incremental staging
## Environment
- **Airbyte version**:  v0.33.12-alpha
- **OS Version / Instance**: Ubuntu
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.17
- **Destination Connector and version**: Snowflake 0.1.2
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
When creating a new sync, if the sync fails and it has to retry, all rows which have already been put on the stage will then have rows appended again to the stage. So there are duplicate rows.

## Expected Behavior
It should not have duplicate rows.

```
Uploading data from stage:  stream xxx. schema public, tmp table _airbyte_tmp_boa_xxx, stage PUBLIC_AIRBYTE_RAW_XXX
```

The stage should have a folder in it, as mentioned here https://docs.snowflake.com/en/user-guide/data-load-local-file-system-stage.html:
```
put file:///data/data.csv @~/staged/SOME UUID;
```

This way the uuid is used just for that sync, and other retries should then use a new UUID. On failure it should delete files from that uuid.

Attempt 1:
```
XXX GB | XXXX records | 1h 36m 14s
/tmp/workspace/3/0/logs.log.
```

Attempt 2:
```
XX.XX GB | XXXX records | 1h 41m 54s
/tmp/workspace/3/1/logs.log.
```

## Steps to Reproduce
1. Create a new destination with SF
2. At the end when it's inserting into SF (or during the process), cancel the query in SF
3. It then retries (good!), but has duplicate rows.

## Are you willing to submit a PR?
Maybe?

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
When creating a new sync, if the sync fails and it has to retry, all rows which have already been put on the stage will then have rows appended again to the stage. So there are duplicate rows.

## How
The stage now have a folder in it, as mentioned here https://docs.snowflake.com/en/user-guide/data-load-local-file-system-stage.html:

## Recommended reading order
1. `x.java`

## 🚨 User Impact 🚨
There should be no visible impact on the user

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java [hunk 1]
```diff
@@ -45,6 +46,7 @@
   private static final Logger LOGGER = LoggerFactory.getLogger(SnowflakeInternalStagingConsumerFactory.class);
 
   private static final long MAX_BATCH_SIZE_BYTES = 1024 * 1024 * 1024 / 4; // 256mb
+  private static final String currentSyncPath = UUID.randomUUID().toString();
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:49]: Please, use java convention for constants. Uppercase with underscores.

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java [hunk 2]
```diff
@@ -170,11 +172,18 @@ private static OnCloseFunction onCloseFunction(final JdbcDatabase database,
...
-          LOGGER.info("Uploading data from stage:  stream {}. schema {}, tmp table {}, stage {}", writeConfig.getStreamName(), schemaName,
-              srcTableName,
-              stageName);
+          final String path = namingResolver.getStagingPath(schemaName, dstTableName, currentSyncPath);
+          LOGGER.info("Uploading data from stage:  stream {}. schema {}, tmp table {}, stage path {}", writeConfig.getStreamName(), schemaName,
+                  srcTableName,
+                  path);
+          try {
+            sqlOperations.copyIntoTmpTableFromStage(database, path, srcTableName, schemaName);
+          }catch (Exception e){
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:181]: Looks like one space missed here before the catch, please reformat.

**Comment by alexandertsukanov** [comment]
@VitaliiMaltsev Minor comments, otherwise LGTM.

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java (hunk 2 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java]: fixed

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java (hunk 1 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java]: > Please, use java convention for constants. Uppercase with underscores.

renamed

**Comment by alexandertsukanov** [comment]
Looks like some conflicts with master, please resolve.

**Comment by VitaliiMaltsev** [comment]
> Looks like some conflicts with master, please resolve.

resolved

**Review by alexandertsukanov — APPROVED** [review]

**Comment by alexandertsukanov** [comment]
Approve from my side

**Comment by sherifnada** [comment]
@edgao do you mind reviewing this PR?

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSQLNameTransformer.java [hunk 3]
```diff
@@ -17,4 +17,7 @@ public String getStageName(String schemaName, String outputTableName) {
     return schemaName.concat(outputTableName).replaceAll("-", "_").toUpperCase();
   }
 
+  public String getStagingPath(String schemaName, String tableName, String currentSyncPath) {
+    return getStageName(schemaName,tableName).concat("/staged/").concat(currentSyncPath).toUpperCase();
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSQLNameTransformer.java:21]: nitpick: why not use `+` instead of `.concat`?

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java [hunk 4]
```diff
@@ -45,6 +46,7 @@
   private static final Logger LOGGER = LoggerFactory.getLogger(SnowflakeInternalStagingConsumerFactory.class);
 
   private static final long MAX_BATCH_SIZE_BYTES = 1024 * 1024 * 1024 / 4; // 256mb
+  private static final String CURRENT_SYNC_PATH = UUID.randomUUID().toString();
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:49]: I'd prefer for this to be an instance field (i.e. non-static). Then `SnowflakeInternalStagingDestination#getConsumer` would need to call `new SnowflakeInternalStagingConsumerFactory().create(...)`

generally I avoid non-constant static fields, since they can be confusing + difficult to test.

**Review by edgao — CHANGES_REQUESTED** [review]
could you add some tests for this behavior? (i.e. that we're creating different subdirectories per run, and that we're deleting the staging data on failure)

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSQLNameTransformer.java (hunk 3 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSQLNameTransformer.java]: > nitpick: why not use `+` instead of `.concat`?

replaced with +

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java (hunk 4 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:49]: _CURRENT_SYNC_PATH_ field used in static methods _recordWriterFunction_ and _onCloseFunction_. Non-static field can't be used in static methods

**Comment by VitaliiMaltsev** [comment]
> could you add some tests for this behavior? (i.e. that we're creating different subdirectories per run, and that we're deleting the staging data on failure)

@edgao During the implementation of this solution, while the airbyte sync lasts, I manually canceled the queries in the Snowflake console  exactly at the moment when the data from the stage is inserted into the tables, in order for this to lead to the retry and the next sync of the same connection in airbyte. I'm not sure how to make a test that reproduces the same behavior.

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java (hunk 4 above)
Comment (edgao) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:49]: I think those methods could just be switched to non-static as well (they're only called from `create`, so that should be safe)

**Comment by sherifnada** [comment]
@VitaliiMaltsev can you create a separate issue for testing this behavior and work on it after merging this PR? I agree with Edward that we should have a test but would love to release this fix asap as it's a critical issue

**Comment by edgao** [comment]
I think writing a unit test would be sufficient - if you pass in a mocked `SnowflakeStagingSqlOperations` and initialize it with `doThrow(...).when(mockedSqlOps.copyIntoTmpTableFromStage(...))`, then you can use `verify(mockedSqlOps).cleanUpStage(...)` to check that it handled the exception correctly

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java (hunk 4 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java]: @edgao switched to non-static

**Review by edgao — APPROVED** [review]
saw that you created https://github.com/airbytehq/airbyte/issues/9389 - :shipit:

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java [hunk 5]
```diff
@@ -149,13 +151,13 @@ private static RecordWriter recordWriterFunction(final JdbcDatabase database,
       final WriteConfig writeConfig = pairToWriteConfig.get(pair);
       final String schemaName = writeConfig.getOutputSchemaName();
       final String tableName = writeConfig.getOutputTableName();
-      final String stageName = namingResolver.getStageName(schemaName, tableName);
+      final String path = namingResolver.getStagingPath(schemaName, tableName, CURRENT_SYNC_PATH);
```
Comment (ChristopheDuong) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:154]: When there are multiple "flush" on the same stream during a sync, are all batches/files written to the same path / same object in the stage area?

Comment (tuliren) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeInternalStagingConsumerFactory.java:154]: The path is like a virtual folder. It is similar to S3:
https://docs.snowflake.com/en/user-guide/data-load-considerations-stage.html

We always use the temp filename as the file under the folder:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeStagingSqlOperations.java#L45
