### PR TITLE
JDBC Sources: validate actual source schema

### LINKED ISSUE #21413: Bigquery normalization failing with `Bad int64 value: 1.0`
## Environment
- **Deployment**: cloud
- **Source Connector and version**: postgres 1.0.36 
- **Destination Connector and version**: bigquery 1.2.9 
- **Step where error happened**: Sync job

## Current Behavior
See in the following [connection](https://cloud.airbyte.io/workspaces/fe2196de-87be-452d-b5ee-d26bd7aa6086/connections/8c9b7319-3c10-4b92-8eb5-dddf3c3530b1/status#1113540::2)
BigQuery normalization failing on a bad int64 value with
```
2023-01-12 23:04:09 normalization > Completed with 1 error and 0 warnings:
2023-01-12 23:04:09 normalization > Database Error in model orchestrator_segments (models/generated/airbyte_tables/analytics/orchestrator_segments.sql)
2023-01-12 23:04:09 normalization >   Bad int64 value: 1.0
2023-01-12 23:04:09 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/analytics/orchestrator_segments.sql
2023-01-12 23:04:09 normalization > Done. PASS=15 WARN=0 ERROR=1 SKIP=0 TOTAL=16
```

This may be related to [#oncall/1228](https://github.com/airbytehq/oncall/issues/1228), for which we made a fix for destination-bigquery-denormalizedbut **but not in destination-bigquery**.

## Expected Behavior
Successful sync

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
From [21413](https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/gh/airbytehq/airbyte/21413)
If the schema of the source was manually changed by the user and the structure of the table was changed (columns were added, data types were changed), but the user did not refresh and did not save the new schema in **airbyte-db**, the sync may fail

## How
Validate actual source schema vs catalog schema and log warning if the source schema was changed
schema-changed

## Recommended reading order
1. `AbstractDbSource.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java [hunk 1]
```diff
@@ -180,6 +183,34 @@ public AutoCloseableIterator<AirbyteMessage> read(final JsonNode config,
...
+      final List<Field> fields = table.getFields()
+          .stream()
+          .map(this::toField)
+          .distinct()
+          .collect(Collectors.toList());
+      final JsonNode currentJsonSchema = fieldsToJsonSchema(fields);
+
+      final JsonNode catalogSchema = stream.getJsonSchema();
+      if (!catalogSchema.equals(currentJsonSchema)) {
+        LOGGER.warn("Source schema changed for table  {}! Actual schema: {}. Catalog schema:  {}",
```
Comment (rodireich) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: Is this an error state?
Should we do something other than warn?

**Comment by rodireich** [comment]
@VitaliiMaltsev the change looks good.
I just wonder about the entire user flow - should we update the catalog in this case (run a discover).
should we stop the sync and ask the user to intervention?

Otherwise the warning would keep getting logged but connection would still fail eventually, right?

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: +1. Can we actually throw a `ConfigErrorException` here so that this is actionable to the user? With a message maybe : "The underlying schema changed for the table. Please refresh your source schema! Source schema changed for table {}! Actual schema: {}. Catalog schema: {}" 

Along those lines. In addition, could you add a unit test as well?

Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: @rodireich @akashkulk 
I'm not sure that throwing an exception here would be correct in all cases, the sync would fail if the datatype changed from integer to float, but if the change were the reverse (from float to integer), and all values in the database contained only integers, then the sync would be successful, also if the user manually added some columns - the sync will be successful, but in some cases when the column is deleted - the sync will fail
I think that there may be other possible variations of a successful/unsuccessful sync, for example, using an incremental mode, but at the same time, throwing an exception here will lead to a complete fail of the sync, while only one stream can fail, for which the user manually changed structure in the database, and all other streams should not fail
WDYT?

Comment (rodireich) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: I see. So some changes can go through but other will require to refresh the source schema.
My question: 
for non-breaking change (e.g user adds a column) - can we keep on syncing indefinitely with the old schema?
for breaking change (e.g user removes a column) - at what stage will the sync fail, is it deterministic or depending on sync type and other factors.

I think this change is making it better for identifying a state we're unaware of today, until something breaks. I wonder if we there's a good way to know what to do? (maybe it's impossible).
+1 to Akash's suggestion for adding a test

**Review by rodireich — APPROVED** [review]

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 1 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java]: @rodireich added the unit test

Answering your questions:
for non-breaking change - yes, sync could be indefinitely with the old schema
for breaking change - i'm not sure that we could determine the exact stage of sync failure . Potentially - it could be 1. On normalization step( as described [here]([21413](https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/gh/airbytehq/airbyte/21413))) , 
2. During WRITE(avro values mapping to the old avro schema or during json schema formatting in BigQuery Denormalized), 
3. During READ (at any place where old catalog used)

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java [hunk 2]
```diff
@@ -180,6 +183,35 @@ public AutoCloseableIterator<AirbyteMessage> read(final JsonNode config,
         });
   }
 
+  private void validateSourceSchema(Map<String, TableInfo<CommonField<DataType>>> fullyQualifiedTableNameToInfo,
+                                    ConfiguredAirbyteCatalog catalog,
+                                    Database database) {
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:188]: You can remove passing in the `Database` parameter. It's not being used

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java [hunk 3]
```diff
@@ -180,6 +183,35 @@ public AutoCloseableIterator<AirbyteMessage> read(final JsonNode config,
...
+      final TableInfo<CommonField<DataType>> table = fullyQualifiedTableNameToInfo.get(fullyQualifiedTableName);
+      final List<Field> fields = table.getFields()
+          .stream()
+          .map(this::toField)
+          .distinct()
+          .collect(Collectors.toList());
+      final JsonNode currentJsonSchema = fieldsToJsonSchema(fields);
+
+      final JsonNode catalogSchema = stream.getJsonSchema();
+      if (!catalogSchema.equals(currentJsonSchema)) {
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:205]: Does this account for column selection? The user could have specifically decided to not include certain columns in the configured catalog

**Review by akashkulk — CHANGES_REQUESTED** [review]
The platform already has an auto detect schema change feature which will catch these schema drifts, so I'm not sure if we need this logging.

**Comment by VitaliiMaltsev** [comment]
> The platform already has an auto detect schema change feature which will catch these schema drifts, so I'm not sure if we need this logging.

I did not find any platform logging if the source schema changed with the comparison actual schema vs catalog shema. Where can i find it?

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java [hunk 4]
```diff
@@ -253,6 +262,45 @@ public void testCanReadUtf8() throws Exception {
     }
   }
 
+  @Test
+  public void testValuesChangedOnChangedSourceSchema() throws Exception {
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java:265]: > I'm not sure I understand what's being tested in this test: IIUC this test is verifying that if the underlying schema is changed, the records read will be different
> 
> But won't this always be true? Across two different `reads`, even with without the changes in this PR the read will always return different records

updated this test with 4 different reads with the same catalog:
1 read - initial sync (integers)
2 read - nothing changed ==> values are same as in 1 read (integers)
3 read - added 1 record into the source table ==> added 1 airbyte record (integers)
4 read - user changed column definition from int to float ==> values in airbyte records become double

This test fully emulate behaviour from this [issue](https://github.com/airbytehq/airbyte/issues/21413)

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 3 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:204]: > Does this account for column selection? The user could have specifically decided to not include certain columns in the configured catalog

it is another one excellent example of why throwing an exception here is a bad idea
Column selection - is a valid case if the actual schema and catalog schema are not the same and sync will be successful

This PR is not a fix, it's just additional logging to detect quickly similar issues

Comment (akashkulk) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:204]: +1 on not throwing an exception.

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java [hunk 5]
```diff
@@ -180,6 +183,34 @@ public AutoCloseableIterator<AirbyteMessage> read(final JsonNode config,
         });
   }
 
+  private void validateSourceSchema(Map<String, TableInfo<CommonField<DataType>>> fullyQualifiedTableNameToInfo,
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:186]: I think this should be changed to be named `logSourceSchemaChange`

validate implies that if it isn't the same you'd be throwing an error

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java [hunk 6]
```diff
@@ -180,6 +183,34 @@ public AutoCloseableIterator<AirbyteMessage> read(final JsonNode config,
...
+                                    ConfiguredAirbyteCatalog catalog) {
+    for (final ConfiguredAirbyteStream airbyteStream : catalog.getStreams()) {
+      final AirbyteStream stream = airbyteStream.getStream();
+      final String fullyQualifiedTableName = getFullyQualifiedTableName(stream.getNamespace(),
+          stream.getName());
+      if (!fullyQualifiedTableNameToInfo.containsKey(fullyQualifiedTableName)) {
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:192]: If the source schema doesn't contain a previous stream, should you also log a warning?

**Comment by akashkulk** [comment]
> 

It's not in the logs. However, there is a new Review changes interstitial introduced. https://www.loom.com/i/e17df917d481406faed839595d3e97c4

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java:265]: But you aren't actually checking for the actual change you're making here, correct? i.e. you aren't verifying the correct logs are being outputted. 

In that case, I think you should remove this test altogether since that change is a logging one (and not a validation)

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 5 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:186]: Also add a quick comment on what this function is doing

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java]: > But you aren't actually checking for the actual change you're making here, correct? i.e. you aren't verifying the correct logs are being outputted.
> 
> In that case, I think you should remove this test altogether since that change is a logging one (and not a validation)

removed the test

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 5 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java]: > Also add a quick comment on what this function is doing

renamed this method and added a comment

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 6 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:194]: > If the source schema doesn't contain a previous stream, should you also log a warning?

I think that no logging is needed here, since the user can simply select which streams (tables) he needs for the synch, and the _fullyQualifiedTableNameToInfo_ will display all the tables that are in the database

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java (hunk 3 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: I think the confusion arises here since you're conflating JsonSchema (Airbyte type) vs source schema. 

I think that we should log changes in the Airbyte type. So, you'd need to change the logic to grab fields that are only present in the ``catalogSchema``. 

At the end of the day, normalization only cares about the Airbyte type (and not the source schema). Let me know if that makes sense - happy to jump on a call to explain what I'm thinking.

Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/AbstractDbSource.java:206]: > I think the confusion arises here since you're conflating JsonSchema (Airbyte type) vs source schema.
> 
> I think that we should log changes in the Airbyte type. So, you'd need to change the logic to grab fields that are only present in the `catalogSchema`.
> 
> At the end of the day, normalization only cares about the Airbyte type (and not the source schema). Let me know if that makes sense - happy to jump on a call to explain what I'm thinking.

@akashkulk the example that you give with normalization and airbyte_type is just one of the possible cases in which the sync can fail if the user has changed the database structure
I have described all potential fails [here](https://github.com/airbytehq/airbyte/pull/21844#discussion_r1093321662)
Therefore, in my opinion, it is better to leave the logging as it is.

**Review by akashkulk — APPROVED** [review]
