### PR TITLE
:window: :wrench: Introduce useAuthentication hook

### LINKED ISSUE #7495: Clicking the oauth button is not a required operation
## Enviroment
- **Airbyte version**:  Airbyte Cloud
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: Facebook latest
- **Severity**: Medium
- **Step where error happened**: Setup new connection 

## Current Behavior
I was setting up an FB marketing connector and accidentally forgot to click the authenticate button. I clicked the "setup connection" button and it happily accepted and tried to create the source. The source failed and I was confused about why. Then I realized I hadn't clicked the "authorize" button for oauth. 

## Expected Behavior
If I didn't click the authorize button then I shouldn't be able to click the "Create source" button -- it should be treated as a required param.

### LINKED ISSUE #17753: OAuth button in connector is no longer required before checking
Currently you can send a check of any connector using OAuth before actually signing up via the OAuth button.

This is a regression and we should prevent sending a check unless the OAuth login has happened.

### PR DESCRIPTION
**Pull request by timroes**
## What

Closes https://github.com/airbytehq/airbyte/issues/17753
Closes https://github.com/airbytehq/airbyte/issues/7495

This PR refactors the logic that is used to handle field rendering in the service form for OAuth fields into its own hook and fixes several issues:

* Make all OAuth buttons required and no longer allow sending a form without having signed into OAuth, which previously was allowed for connectors using `authSpecification`.
* If a connector that used `advancedAuth` in its specification had an empty `predicateKey`, the OAuth button so far wasn't shown at all, but instead we'd always render out the plain text fields to the user. This was an issue and the only connector affected was Smartsheets. This PR makes sure that the button will also render properly with `predicateKey`-less connectors.

## How

* Extracted all logic from different places into one `useAuthentication` hook instead.
* Combine the logic for `authSpecification` and `advancedAuth` into that hook, instead of as so far having `advancedAuth` being handled in the `ServiceFormContext` and `authSpecification` in the `useBuildForm` hook before rendering the form.
* Switch the logic how the auth buttons are rendered for `authSpecification`, so it can work inside `useAuthentication`. We're still planning to migrate all `authSpecification` connectors to use `advancedAuth` instead and remove that logic later. See https://github.com/airbytehq/airbyte/issues/15019

### Manual Testing

Tested in Cloud mode:

- Google Sheets (`authSpecification` with callback values being nested inside conditional)
- Instagram (`authSpecification` with callback values in root)
-  Mailchimp (`advancedAuth` with `predicateKey` inside conditional)
- Salesforce (`advancedAuth` with `predicateKey` on root for const value)
- Smartsheets (`advancedAuth` with empty `predicateKey`)

TODOS:

- [x] Tests
- [x] Test on OSS vs Master
- [x] Test all combination of OAuth connectors again
- [x] Write documentation
- [x] Remove debug output
- [x] Hide `authSpecification` button if other Auth conditional is selected

### CODE REVIEW

File: airbyte-webapp/src/views/Connector/ServiceForm/utils.ts [hunk 1]
```diff
@@ -3,8 +3,8 @@ import { naturalComparator } from "utils/objects";
 
 import { ConnectorDefinitionSpecification } from "../../../core/domain/connector";
 
-export function makeConnectionConfigurationPath(path: string[]): string {
-  return `connectionConfiguration.${path.join(".")}`;
+export function makeConnectionConfigurationPath(path: string[] = []): string {
+  return ["connectionConfiguration", ...path].join(".");
```
Comment (timroes) [inline airbyte-webapp/src/views/Connector/ServiceForm/utils.ts:7]: :information_source: Making sure this method also works with an empty `path` array passed in.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+  // To find the path inside the connector spec that matches the `rootPath` we'll need to insert `properties`
+  // and `oneOf`, since they'll appear in the JSONSchema, e.g. this turns `credentials.0` to `properties.credentials.oneOf.0`
+  const specPath = rootPath.flatMap((path) =>
+    isNumerical(path) ? ["oneOf", String(path)] : ["properties", String(path)]
+  );
+  // Get the part of the spec that `rootPath` point to
+  const credentialsSpecRoot = getIn(spec, specPath) as JSONSchema7 | undefined;
+
+  if (!credentialsSpecRoot?.properties) {
+    // if the part doesn't exist in the spec (which should not happen) we just show the auth button always.
```
Comment (lmossman) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:85]:
```suggestion
    // if the path doesn't exist in the spec (which should not happen) we just show the auth button always.
```

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+    return true;
+  }
+
+  // To find the value we're expecting, we run through all properties inside that matching spec inside the conditional
+  // to find the one that has a `const` value in it, since this is the actual value that will be written into the conditional
+  // field itself once it's selected.
+  const constProperty = Object.entries(credentialsSpecRoot.properties)
+    .map(([key, prop]) => [key, typeof prop !== "boolean" ? prop.const : undefined] as const)
```
Comment (lmossman) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:93]: I'm forgetting exactly why you added the whole `typeof prop !== "boolean"` piece, and the `as const` piece here. Since this code should be going away soon anyway its probably not super important to have a detailed comment explaining this, but I am curious for my own learning

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+    .find(([, constValue]) => !!constValue);
+
+  // If none of the conditional properties is a const value, we'll also show the auth button always (should not happen)
+  if (!constProperty) {
+    return true;
+  }
+
+  // Check if the value in the form match the found `const` value from the spec. If so we know the conditional
```
Comment (lmossman) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:101]:
```suggestion
  // Check if the value in the form matches the found `const` value from the spec. If so we know the conditional
```

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+  const legacyOauthSpec = selectedConnector?.authSpecification?.oauth2Specification;
+
+  const spec = selectedConnector?.connectionSpecification as JSONSchema7;
+
+  const isAuthButtonVisible = useMemo(() => {
+    const shouldShowAdvancedAuth =
+      advancedAuth && shouldShowButtonForAdvancedAuth(advancedAuth.predicateKey, advancedAuth.predicateValue, values);
+    const shouldShowLegacyAuth =
+      legacyOauthSpec && shouldShowButtonForLegacyAuth(spec, legacyOauthSpec.rootObject as Path, values);
+    return Boolean(allowOAuthConnector && (shouldShowAdvancedAuth || shouldShowLegacyAuth));
```
Comment (lmossman) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:143]: Why wrap this response in a `Boolean()`?

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.test.tsx [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+          submitCount: 1,
+        });
+        const result = useAuthentication();
+        expect(result.hiddenAuthFieldErrors).toEqual({
+          [accessTokenField]: "form.empty.error",
+          [clientIdField]: "another.error",
+        });
+      });
+
+      it("should return authErrors when conditional hasn't the correct option selected", () => {
```
Comment (lmossman) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.test.tsx:181]:
```suggestion
      it("should not return authErrors when conditional has the incorrect option selected", () => {
```

**Review by lmossman — APPROVED** [review]
Overall this looks great to me. I left several questions and suggestions mainly around typos and comments, but other than that the changes here make sense and having all of the authentication logic encapsulated in one place is a great readability improvement!

Test: my local npm -> frontend-dev
- Smartsheets and LinkedIn Ads properly rendered the OAuth button as desired, but clicking on it had no effect (is this expected on frontend-dev?)
- Google sheets rendered the google OAuth button as desired, and clicking it opened the google auth popup window which allowed me to authenticate my account
- All of the above connectors properly showed the `Authentication required` error message when I tried to submit without authenticating

Test: my local npm -> local OSS deployment
- OAuth buttons were not rendered, and their underlying auth fields were rendered instead (as expected)

**Comment by tealjulia** [comment]
@lmossman 
> Smartsheets and LinkedIn Ads properly rendered the OAuth button as desired, but clicking on it had no effect (is this expected on frontend-dev?)

Currently, yes.  We have to manually add OAuth apps to frontend-dev.  A complete list of what we have enabled is on Notion as `Testing OAuth Locally`.  That said, it's not difficult to add more!  The steps are on that same Notion doc.

**Comment by tealjulia** [comment]
@timroes are Smartsheets and Instagram enabled on `frontend-dev`?  You have them listed in your description but it doesn't look like they're wired up.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+      // A field should be hidden due to OAuth if we have OAuth enabled and selected (in case it's inside a oneOf)
+      // and the field is part of the OAuth flow parameters.
+      return isAuthButtonVisible && implicitAuthFieldPaths.includes(fieldPath);
+    },
+    [implicitAuthFieldPaths, isAuthButtonVisible]
+  );
+
+  const hiddenAuthFieldErrors = useMemo(() => {
+    if (!isAuthButtonVisible) {
+      // We don't want to return the errors if the auth button isn't visible.
```
Comment (tealjulia) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:177]: I'm interested how we might end up with errors on these fields if the button isn't visible.  Is this because if a user is using a different auth type in a oneOf we still get back an error for the OAuth fields?  That seems odd.

Or if a user has an error with OAuth and then chooses another auth method the errors persist?  That also seems odd.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 8]
```diff
@@ -0,0 +1,210 @@
...
+        authErrors[fieldName] = error;
+      }
+      return authErrors;
+    }, {});
+  }, [getFieldMeta, implicitAuthFieldPaths, isAuthButtonVisible, submitCount]);
+
+  const shouldShowAuthButton = useCallback(
+    (fieldPath: string) => {
+      if (!isAuthButtonVisible) {
+        // Never show the auth button anywhere if its not enabled or visible (inside a conditional that's not selected)
```
Comment (tealjulia) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:192]: should this say enabled AND visible?

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.test.tsx [hunk 9]
```diff
@@ -114,13 +118,14 @@ describe("auth button", () => {
     expect(successMessage).toBeInTheDocument();
   });
 
-  it("if authError is true, it renders the correct message", () => {
+  it("renders an error if there are any auth fields with empty values", () => {
```
Comment (tealjulia) [inline airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.test.tsx:121]: Are there any other types of errors we might encounter for this?  It looks like the button only actually accounts for missing credentials and no other errors, but I wonder if we want to expand that?

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx [hunk 10]
```diff
@@ -39,8 +40,9 @@ function getAuthenticateMessageId(connectorDefinitionId: string): string {
 }
 
 export const AuthButton: React.FC = () => {
-  const { selectedService, authErrors, selectedConnector } = useServiceForm();
-  const hasAuthError = Object.values(authErrors).includes("form.empty.error");
+  const { selectedService, selectedConnector } = useServiceForm();
+  const { hiddenAuthFieldErrors } = useAuthentication();
+  const requiresAuthError = Object.values(hiddenAuthFieldErrors).includes("form.empty.error");
```
Comment (tealjulia) [inline airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx:45]: should this be `requiredAuthError`?

**Review by teallarson — COMMENTED** [review]
This is so much cleaner than what we had!  Just a few questions/comments.

I was not able to complete the full test path you listed in the description -- it looks like we'll need to set up Instagram and Smartsheets on `frontend-dev` (and add to Notion) to do so.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx (hunk 5 above)
Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:143]: `shouldShowAdvancedAuth` and `shouldShowLegacyAuth` are of type `boolean | undefined`, since our check above is e.g. `advancedAuth && shouldShow...`, meaning if `advancedAuth` is not set in the spec and `undefined` `shouldShowAdvancedAuth` will be undefined and not `false`, since the value is simply assigned from that variable (and the rest behind `&&` would only be executed if the variable before is truthy.

So without that `Boolean` our result here would be `boolean | undefined` again, since in case `allowOAuthConnector` is `true`, and `shouldShowAdvancedAuth` is `undefined` the statement will end there and resolve to `undefined` itself again. Since we want to have `false` in this case, we just cast it to boolean manually, so the `undefined` will become `false`.

**Comment by timroes** [comment]
> Smartsheets and LinkedIn Ads properly rendered the OAuth button as desired, but clicking on it had no effect (is this expected on frontend-dev?)

> @timroes are Smartsheets and Instagram enabled on frontend-dev? You have them listed in your description but it doesn't look like they're wired up to test.

@tealjulia @lmossman Smartsheets and Instagram are currently not having any parameters stored on frontend-dev. I just validated that we're doing the right `get_consent_url` call, which would then 404 and nothing happens (Lake, that's the behavior you see). Since I haven't changed anything around how the actual OAuth callback values are handled, I wasn't too worried that anything after the actual modal would break, but we can enable them, if you feel we need the full e2e test to make sure this hasn't broken anything.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx (hunk 7 above)
Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:177]: In practise I don't think this happens at the moment, since we change our validation schema when the user actually changes the option of the `oneOf`, the "hidden" fields of the non-selected oneOf option won't be actually validated anymore and thus can't throw errors.

There is one case though why we need to filter out like that: the non OAuth option under the `oneOf` could have a field with the same name as one of the OAuth fields under the OAuth option, which would cause problems, since the actual field names, would not contain the index of the `oneOf`. E.g. if we imagine the following (pseudo) connector spec:

```
- credentials
  - oneOf
    - type: oauth
      properties:
      - token
      - client_id
    - type: token
      properties:
      - token
```

If the user would now select token in the oneOf and that `token` field is required there, but empty, we'd detect that as an OAuth error, because the OAuth field name `credentials.token` matches the same field name (since it doesn't have any notion of the selected oneOf in the field name). In theory that would still not cause a problem having this inside the `authErrors`, since the AuthButton itself (which currently is the only one using it) will never be rendered as long as the wrong option is selected, but I found it cleaner to not have this error in the `authErrors`, despite not being used.

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx (hunk 8 above)
Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:192]: could be :D Not a native speaker, I thought in a negated sentence `or` described that neither of both should be true :D

File: airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx (hunk 10 above)
Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx:45]: I think we parse the word differently :D I always parsed it as "we have an error, that our form 'requires auth'". I changed it to `authRequiredError` now, that might be less ambigious.

Comment (tealjulia) [reply airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx]: Ah!  I parsed it as "this requires an auth error" 😜

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx (hunk 3 above)
Comment (lmossman) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:93]: Huh, weird. The `| boolean` on that type doesn't make much sense to me either 🤷 but at least your code makes sense to me then
