### PR TITLE
[source-mongodb-v2] : Fail sync if initial snapshot for any stream fails

### LINKED ISSUE #34392: [Source-Mongo] : Discrepancies in initial sync compared to Postgres
### Connector Name

source-mongodb-v2

### Connector Version

1.2.3

### What step the error happened?

None

### Relevant information

The mongodb initial sync is different from the initial sync with Postgres/MySQL which might cause some issues : 
1. **Initial Sync Failures** : Failures during the initial sync do not block the entire sync. That is, the sync appears to have succeeded even when we have failed to perform a snapshot for a stream and we continue to read off of the WAL logs. Still trying to convince myself that 
2.  **Initial sync stopping** : For other initial snapshots, the max cursor value is queried and stored in state. it is used in the snapshot query : `select * from table where id > prev_cursor_val and id < max_cursor_val`. Where `max_cursor_val` is the maximum value of the cursor at the start of the first sync where a stream was added to the connection. This is not done for mongo, which we may want to consider adding, as this delays reading off of the WAL

### Relevant log output

_No response_

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by akashkulk**
Currently, if the initial snapshot associated with any stream fails, we keep moving onto the next stream. In general, a failing stream should NOT stall progress on existing syncs. However with the way the current connectors are set up, this shows up as a successful sync. 

The side-effect of this is that the platform schedules the next sync at the next configured scheduled time. In reality, since the initial snapshot is incomplete, a subsequent sync should be scheduled immediately to make sure the snapshot is completed as soon as possible. 

With this change, a failed snapshot for a stream fails the entire sync. The platform retry logic will kick in and continue scheduling syncs until the snapshots are completed***
This also brings the MongoDb behavior at parity with source-postgres and source-mysql.
*[Caveat](https://docs.google.com/document/d/1ywZazxJ5DO41V1afaHY_0UfKuMHeiqRqn8wborwTSkY/edit) : The sync will fail after 10 attempt

Closes https://github.com/airbytehq/airbyte/issues/34392

 In the future, perhaps a new protocol message can be emitted to indicate that an initial sync is occurring. The platform can keep scheduling retries in this case until that it no longer sees that message

### CODE REVIEW

File: airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/MongoDbStateIterator.java [hunk 1]
```diff
@@ -111,14 +117,22 @@ public MongoDbStateIterator(final MongoCursor<Document> iter,
...
     try {
       if (iter.hasNext()) {
         return true;
       }
     } catch (final MongoException e) {
-      // If hasNext throws an exception, log it and then treat it as if hasNext returned false.
-      iterThrewException = true;
+      // If hasNext throws an exception, log it and set the flag to indicate that the initial snapshot failed. This indicates to the main iterator
+      // to emit state associated with what has been processed so far.
+      initialSnapshotFailed = true;
```
Comment (rodireich) [inline airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/MongoDbStateIterator.java:132]: Why not throe and exception here instead?
Wouldn't that to the same job?

**Review by rodireich — APPROVED** [review]
