### PR TITLE
🐛 Destination S3: fixed s3 destination field naming for Parquet and Avro formats

### LINKED ISSUE #5149: Destination S3 `SchemaParseException: Illegal initial character`
## Enviroment
- **Airbyte version**:  0.29.2-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker 
- **Source Connector and version**: Facebook Marketing
- **Destination Connector and version**: S3 Parquet (default option)
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync Facebook Marketing to S3 Parquet doesnt works.
The connection hangs a
API Source can have complex JSON schemas where some formats maybe doesnt have native support.

## Expected Behavior
Should work fine maybe removing the illegal char.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-08-03 01:22:47 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.2-alpha
2021-08-03 01:22:47 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.29.2-alpha
2021-08-03 01:22:48 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 6 attempt id: 0
2021-08-03 01:22:48 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.ads_insights_platform_and_device=incremental - append, null.ads=incremental - append, null.ad_creatives=full_refresh - overwrite, null.campaigns=incremental - append, null.ad_sets=incremental - append, null.ads_insights=incremental - append, null.ads_insights_region=incremental - append, null.ads_insights_age_and_gender=incremental - append, null.ads_insights_country=incremental - append, null.ads_insights_dma=incremental - append}
2021-08-03 01:22:48 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-08-03 01:22:48 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-s3:0.1.9 exists...
2021-08-03 01:22:48 INFO () LineGobbler(voidCall):85 - airbyte/destination-s3:0.1.9 was found locally.
2021-08-03 01:22:48 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/6/0 --network host --log-driver none airbyte/destination-s3:0.1.9 write --config destination_config.json --catalog destination_catalog.json
2021-08-03 01:22:48 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-facebook-marketing:0.2.14 exists...
2021-08-03 01:22:48 INFO () LineGobbler(voidCall):85 - airbyte/source-facebook-marketing:0.2.14 was found locally.
2021-08-03 01:22:48 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/6/0 --network host --log-driver none airbyte/source-facebook-marketing:0.2.14 read --config source_config.json --catalog source_catalog.json
2021-08-03 01:22:48 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-08-03 01:22:48 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-08-03 01:22:48 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 INFO i.a.i.b.IntegrationRunner(run):81 - {} - Running integration: io.airbyte.integrations.destination.s3.S3Destination
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 INFO i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 INFO i.a.i.b.IntegrationRunner(run):85 - {} - Command: WRITE
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 INFO i.a.i.b.IntegrationRunner(run):86 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 INFO i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):42 - {} - S3 format config: {"format_type":"Parquet","page_size_kb":1024,"block_size_mb":128,"compression_codec":"UNCOMPRESSED","dictionary_encoding":true,"max_padding_size_mb":8,"dictionary_page_size_kb":1024}
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 WARN i.a.i.d.s.a.JsonToAvroSchemaConverter(getAvroSchema):126 - {} - Schema name contains illegal character(s) and is standardized: adlabels.items -> adlabels_items
2021-08-03 01:22:51 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-08-03 01:22:51 WARN i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):78 - {} - Airbyte message consumer: failed.

```

</details>

## Steps to Reproduce
1. Create a Facebook Marketing (using integration account)
2. Create S3 Destination with Parquet format (default values)
3. Sync using Incremental Append

## Are you willing to submit a PR?

Not at the moment.

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
The bug is described in detail in task https://github.com/airbytehq/airbyte/issues/5149. Issue seems to be that some fields in the source start with a numeric character.

## How
To avoid an invalid character bug when writing to avro/parquet, the "_" prefix has been added.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by etsybaev — APPROVED** [review]
LGTM, but please make sure all check\tests passed before moving forward

**Review by irynakruk — APPROVED** [review]

**Review by tuliren — CHANGES_REQUESTED** [review]
Adding the underscore to every identifier seems unnecessary. Can we do this just for names with invalid characters? I don't want all of our users to have to deal with this extra underscore just because facebook has an API that behaves weirdly. Facebook does not deserve this treatment.

**Comment by andriikorotkov** [comment]
@tuliren I can make the changes you mentioned above. I corrected this in the way the @sherifnada talked about in task https://github.com/airbytehq/airbyte/issues/5149. Sherif, could you tell me whether to leave the underscore for all identifiers or do it the way Liren suggested?

**Comment by sherifnada** [comment]
Liren is correct here IMO we should only do it for streams which start with invalid chars

**Comment by andriikorotkov** [comment]
@tuliren, I fixed the name transformer as you mentioned in the comment above. Please take a look at this pull request again.

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3NameTransformer.java [hunk 1]
```diff
@@ -37,7 +37,15 @@ protected String applyDefaultCase(String input) {
 
   @Override
   public String getIdentifier(String name) {
-    return "_" + convertStreamName(name);
+    return checkFirsCharInStreamName(convertStreamName(name));
+  }
+
+  private String checkFirsCharInStreamName(String name) {
+    if (name.substring(0, 1).matches("\\d")) {
```
Comment (sherifnada) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3NameTransformer.java:44]: would it be better if this should instead check if the first char is a valid first char (whitelist approach instead of blacklist)?

Comment (andriikorotkov) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3NameTransformer.java]: of course I have updated s3 name transformer.

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3NameTransformer.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+package io.airbyte.integrations.destination.s3;
+
+import com.google.common.annotations.VisibleForTesting;
+import io.airbyte.integrations.destination.ExtendedNameTransformer;
+
+@VisibleForTesting
```
Comment (sherifnada) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3NameTransformer.java:30]: is this annotation needed? not seeing a test for this

**Review by sherifnada — APPROVED** [review]
LGTM - could you also add a note in the docs about this behavior, and add a unit test for S3NameTransformer? 

We might also need to update/publish the GCS destination since it relies on the same S3 utilities

**Review by tuliren — APPROVED** [review]
Looks good. Thank you.

Maybe add a unit test?

**Comment by andriikorotkov** [comment]
@sherifnada, I fixed all the remarks, updated the documentation and added tests. the problem is that not all jobs are successful. can i merge this pull request without it?

**Comment by sherifnada** [comment]
@andriikorotkov yup
