### PR TITLE
🐛 Kube Pod Name Edge Case

### LINKED ISSUE #5331: Connector setup fails on Kubernetes for some image names
## Enviroment
- **Airbyte version**:  example is 0.29.2-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source/Destination Connector and version**: multiple
- **Severity**: Critical
- **Step where error happened**: Setup new connection / Update connector

## Current Behavior
setup and upgrade connector fails on kube if docker image name ends with `-` followed by exactly 10 characters, because pod name gets truncated to begin with `-`, which is invalid

## Expected Behavior
pod should be created and operation should succeed

## Logs
[scheduler-log.txt](https://github.com/airbytehq/airbyte/files/6966787/scheduler-log.txt)

## Steps to Reproduce
1. deploy on kube
2. either upgrade or setup connector with 10 character name (e.g. source "Google Ads" or "Prestashop", destination "Local JSON")

slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1628080477275700

### PR DESCRIPTION
**Pull request by jrhizor**
fixes https://github.com/airbytehq/airbyte/issues/5331

It has to start with an alphabetic character and end with an alphanumeric character. Our random string at the end is always alphanumeric, but the truncation at the beginning could hit dashes or numbers.

### CODE REVIEW

File: airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java [hunk 1]
```diff
@@ -134,7 +139,12 @@ protected static String createPodName(String fullImagePath, String jobId, int at
       podName = imageName + "-" + suffix;
     }
 
-    return podName;
+    final Matcher m = ALPHABETIC.matcher(podName);
+    // Since we add worker-UUID as a suffix a couple of lines up, there will always be a substring
+    // starting with an alphabetic character.
+    // If the image name is a no-op, this function should always return `worker-UUID` at the minimum.
+    m.find();
+    return podName.substring(m.start());
```
Comment (davinchia) [inline airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java:147]: @jrhizor I simplified this slightly.

**Review by davinchia — APPROVED** [review]
Looks good! Will merge after build passes.
