### PR TITLE
🪟 🐛 🧹 Fix workspace editing issues in cloud, cleanup CloudWorkspacesService

### LINKED ISSUE #16149: Clicking "Cancel" after saving changes reverts workspace general settings form to pre-save initial data
## Environment
- cloud
- Workspace Settings > General Settings (specifically, the `src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx` component)

## Current Behavior / Reproduction Steps
1) In a cloud-backed airbyte frontend, navigate to "Settings" and then to "Workspace Settings > General Settings"
2) Edit the workspace name
3) Click "save changes"
4) After waiting for the save to resolve successfully, click the "cancel" button
5) the workspace name is reverted to its original, pre-save value

This reversion is only in memory; refreshing the page restores the newly-saved value. Here's a gif I recorded (pay no attention to the "Advanced Mode" toggle, it's in-progress work related to https://github.com/airbytehq/airbyte/issues/15145):
workspace-general-settings--undoing-saved-change

## Expected Behavior
Steps 1-4 are identical
5) Clicking the "cancel" button should have no affect on persisted data, regardless of whether it was part of the initial render

### PR DESCRIPTION
**Pull request by edmundito**
## What
Fixes #16149

This change primarily fixes some issues when editing the cloud workspace name and advanced mode, including:
* The cancel button remained enabled after saving
* When only updating advanced mode after updating the name, the previous name would be filled out in the form
* No validation for empty workspace name
* Save button was always enabled
* After updating the name, the sidebar had the old name
* No i18n string usage in buttons

Also cleans up the cloud workspace code to distinguish it from the workspace code

## How
There are two endpoints for getting workspace data: One from the platform and one specific to cloud. The issue when saving the workspace name in cloud was that the workspace data for the platform was not getting invalidated (since it's cached with react-query), and so the name was not getting updated across the app. When the cloud workspace data is updated, the platform workspace data is invalidated, so it's re-fetched.

Additionally, some of the cache keys used with suspenseQuery were not quite matching, so those were fixed. Caused by #11746

There was a lot of mixup in the cloud between what's cloud workspace and platform workspace, so a lot of the functions have been renamed so that it's clear which is which.

## Recommended reading order
`WorkspaceSettingsView.tsx`
`CloudWorkspacesService.ts`
`WorkspacesService.ts`
Rest of code

### CODE REVIEW

File: airbyte-webapp/src/packages/cloud/services/workspaces/CloudWorkspacesService.tsx [hunk 1]
```diff
@@ -108,22 +107,20 @@ export function useRemoveWorkspace() {
...
 
   return useCallback(
-    () => queryClient.invalidateQueries([workspaceKeys.detail(workspaceId)]),
+    () => queryClient.invalidateQueries(workspaceKeys.detail(workspaceId)),
     [queryClient, workspaceId]
   );
 }
 
-export function useGetUsage(workspaceId: string): CloudWorkspaceUsage {
+export function useGetCloudWorkspaceUsage(workspaceId: string): CloudWorkspaceUsage {
```
Comment (krishnaglick) [inline airbyte-webapp/src/packages/cloud/services/workspaces/CloudWorkspacesService.tsx:122]: Should we convert these to const exports? I feel like eslint should flag it.
While you were in here were you able to identify the difference between this code and our normal code? I saw them both but wasn't sure what the difference was.

File: airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx [hunk 2]
```diff
@@ -27,13 +28,18 @@ const AdvancedModeSwitchLabel = () => (
...
+
 export const WorkspaceSettingsView: React.FC = () => {
   const { formatMessage } = useIntl();
   useTrackPage(PageTrackingCodes.SETTINGS_WORKSPACE);
   const { exitWorkspace } = useWorkspaceService();
   const workspace = useCurrentWorkspace();
-  const removeWorkspace = useRemoveWorkspace();
-  const updateWorkspace = useUpdateWorkspace();
+  const removeCloudWorkspace = useRemoveCloudWorkspace();
+  const updateCloudWorkspace = useUpdateCloudWorkspace();
```
Comment (krishnaglick) [inline airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx:41]: I think typically we do something like:
```suggestion
  const { mutateAsync: updateCloudWorkspace } = useUpdateCloudWorkspace();
```

File: airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx [hunk 3]
```diff
@@ -27,13 +28,18 @@ const AdvancedModeSwitchLabel = () => (
...
+});
+
 export const WorkspaceSettingsView: React.FC = () => {
   const { formatMessage } = useIntl();
   useTrackPage(PageTrackingCodes.SETTINGS_WORKSPACE);
   const { exitWorkspace } = useWorkspaceService();
   const workspace = useCurrentWorkspace();
-  const removeWorkspace = useRemoveWorkspace();
-  const updateWorkspace = useUpdateWorkspace();
+  const removeCloudWorkspace = useRemoveCloudWorkspace();
```
Comment (krishnaglick) [inline airbyte-webapp/src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx:40]:
```suggestion
  const const { mutateAsync: removeCloudWorkspace, isLoading } = = useRemoveCloudWorkspace();
```

**Review by krishnaglick — COMMENTED** [review]
Have not had a chance to test locally but left a few comments.

File: airbyte-webapp/src/packages/cloud/services/workspaces/CloudWorkspacesService.tsx (hunk 1 above)
Comment (edmundito) [reply airbyte-webapp/src/packages/cloud/services/workspaces/CloudWorkspacesService.tsx:122]: I'll update these manually. There is a lint rule to fix that needs to be introduced. It was excluded because the changes were not trivial in some areas. I'll see if they can be re-introduced.

Comment (edmundito) [reply airbyte-webapp/src/packages/cloud/services/workspaces/CloudWorkspacesService.tsx]: I'll look into the eslint rule and fix them separately.

**Review by krishnaglick — APPROVED** [review]
Code LGTM, have not tested locally.
