### PR TITLE
📝 Fix BigQuery Destination: fail when using Google Default Application Credentials

### LINKED ISSUE #32477: Destination BigQuery: using application default GCP credentials broken
### Connector Name

destination-bigquery

### Connector Version

2.3.14	

### What step the error happened?

During the sync

### Relevant information

https://github.com/airbytehq/airbyte/pull/32190/files#diff-71f64097f537f4492650bf539bdc98817ebf73178d7b7054a08b339abdd952f9 broke using application default credentials because it tries to parse the creds when they might be empty.

Broken since 2.3.7

### Relevant log output

```shell
2023-11-13 23:31:24 destination > java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isTextual()" because "serviceAccountKey" is null
2023-11-13 23:31:24 destination >         at io.airbyte.integrations.destination.bigquery.BigQueryDestination.getSerializedMessageConsumer(BigQueryDestination.java:243) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.50.33.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:186) ~[airbyte-cdk-core-0.4.5.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[airbyte-cdk-core-0.4.5.jar:?]
2023-11-13 23:31:24 destination >         at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:493) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.50.33.jar:?]
2023-11-13 23:32:27 INFO i.a.w.p.KubePodProcess(cleanup):732 - (pod: airbyte / source-typeform-read-2055-3-piwdq) - Destroying Kube process.
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by evantahler**
Fixes: https://github.com/airbytehq/airbyte/issues/32477

Same as https://github.com/airbytehq/airbyte/pull/34003, but with docs and tests run.  Thanks, @shikanime!

### CODE REVIEW

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java [hunk 1]
```diff
@@ -190,16 +190,17 @@ public static BigQuery getBigQuery(final JsonNode config) {
   }
 
   public static GoogleCredentials getServiceAccountCredentials(final JsonNode config) throws IOException {
-    if (!BigQueryUtils.isUsingJsonCredentials(config)) {
+    final JsonNode serviceAccountKey = config.get(BigQueryConsts.CONFIG_CREDS);
+    if (serviceAccountKey == null) {
       LOGGER.info("No service account key json is provided. It is required if you are using Airbyte cloud.");
       LOGGER.info("Using the default service account credential from environment.");
```
Comment (gisripa) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java:196]: // Follows this order of resolution 
      // https://cloud.google.com/java/docs/reference/google-auth-library/latest/com.google.auth.oauth2.GoogleCredentials#com_google_auth_oauth2_GoogleCredentials_getApplicationDefault__

Tried to add to the file but couldn't figure how to add suggestion

Comment (evantahler) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java:198]: added comment via https://github.com/airbytehq/airbyte/pull/34073/commits/d83cdc4113d975c0deca54255dc560ced80867d6

**Review by gisripa — APPROVED** [review]
lgtm
