### PR TITLE
🎉 Base Norrmalization: clean-up Redshift `tmp_schemas` after SAT

### LINKED ISSUE #13375: 🐛 Destination Redshift: integration tests fail due to OOM
## Environment
Integration tests currently fail on CI due to OOM.

## Logs
 2022-05-31 11:48:44 destination > Details: -----------------------------------------------
    2022-05-31 11:48:44 destination >   error:  Out Of Memory: 
    2022-05-31 11:48:44 destination >   code:      1004
    2022-05-31 11:48:44 destination >   context:   alloc(9992,MtPlan)
    2022-05-31 11:48:44 destination >   query:     7120875
    2022-05-31 11:48:44 destination >   location:  alloc.cpp:493
    2022-05-31 11:48:44 destination >   process:   query0_118_7120875 [pid=27884]

## Additional context
https://github.com/airbytehq/airbyte/runs/6669394169?check_suite_focus=true

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/airbyte/issues/13375

## How
- added new method `clean_tmp_tables` into `dbt_integrartion_test.py` to clean `tmp_tables` created during the test
- added `dbt_run_macro` method to run `dbt run-operation` to trigger the custom macro to clean-up the `tmp_tables` on the db
- moved `subprocess` logic to `run_check_dbt_subprocess` method
- added macro `clean_tmp_tables` into `dbt-project-template`

## 🚨 User Impact 🚨
No impact expected.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

File: airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+-- macro to clean Redshift normalization tmp tables
+{% macro redshift__clean_tmp_tables(schemas) %}
+    {%- for tmp_schema in schemas -%}
+        {% do log("\tDROPING SCHEMA " ~ tmp_schema, info=True) %}
+        {%- set drop_query -%}
+            drop schema if exists {{ tmp_schema }} cascade;
```
Comment (ChristopheDuong) [inline airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql:6]: Is it possible to add some `where clauses` as a safeguard and avoid dropping things too violently?

ie the schema to be dropped should validate certain criteria:
- been created in a certain date range
- match a regex pattern
- created by a certain user
- etc

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py [hunk 2]
```diff
@@ -458,6 +468,82 @@ def run_check_dbt_command(normalization_image: str, command: str, cwd: str, forc
...
+        )
+        print(message)
+        assert error_count == 0, message
+        assert process.returncode == 0, message
+        if error_count > 0:
+            return False
+        return process.returncode == 0
+
+    @staticmethod
+    def run_check_dbt_macro(normalization_image: str, cwd: str, macro: str, macro_args: str = None) -> bool:
```
Comment (ChristopheDuong) [inline airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:512]: call it by the actual dbt command? `run_dbt_run-operation` ?

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py [hunk 3]
```diff
@@ -552,3 +638,66 @@ def update_yaml_file(filename: str, callback: Callable):
...
+        test_folders: list = []
+        source_files: list = []
+        schemas_to_remove: list = []
+        macro_name: str = ""
+
+        # choose macro, based on destination_type, for future extendibility
+        # other destination-specific macros could be added by the path:
+        # dbt-project-template/macros/clean_tmp_tables.sql
+        if destination_type == DestinationType.REDSHIFT:
+            macro_name = "redshift__clean_tmp_tables"
```
Comment (ChristopheDuong) [inline airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:660]: Why is this useful?

Can't you define a clean_tmp_tables macro for default target (maybe that does a no-op?) and then override it for each destination in the macro folder, so you don't need to check anything on python side?

File: airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql (hunk 1 above)
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql:6]: Specifically for the Redshift, normalization schemas are created per each test individually with unique suffix like `_fhsfjh` this allows us to track individual tests run from different places at the same time to be unique per requester.
There is no need for `where clause` here because of the uniqueness of the schemas created for the tests. We drop only those what were created and registered in `sources.yml`.

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py (hunk 2 above)
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:512]: Done.

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py (hunk 3 above)
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:660]: Done.

File: airbyte-integrations/bases/base-normalization/integration_tests/test_ephemeral.py [hunk 4]
```diff
@@ -30,6 +30,8 @@ def before_all_tests(request):
     dbt_test_utils.setup_db(destinations_to_test)
     os.environ["PATH"] = os.path.abspath("../.venv/bin/") + ":" + os.environ["PATH"]
     yield
+    # clean-up tmp tables for Redshift
+    dbt_test_utils.clean_tmp_tables(destination_type=DestinationType.REDSHIFT, tmp_folders=temporary_folders)
```
[the remark this answers is not in the document]
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/integration_tests/test_ephemeral.py:34]: Done.

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py [hunk 5]
```diff
@@ -458,6 +467,82 @@ def run_check_dbt_command(normalization_image: str, command: str, cwd: str, forc
             command = f"{command} --full-refresh"
         print("Executing: ", " ".join(commands))
         print(f"Equivalent to: dbt {command} --profiles-dir={cwd} --project-dir={cwd}")
+
+        error_count = 0
+        with open(os.path.join(cwd, "dbt_output.log"), "ab") as f:
```
Comment (edgao) [inline airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:472]: is this identical to what `run_dbt_run_operation` is doing? This is a pretty complex bit of logic, so I'd prefer to pull it into a separate function instead of duplicating it

File: airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql [hunk 6]
```diff
@@ -0,0 +1,19 @@
+{% macro clean_tmp_tables(schemas) -%}
+  {{ adapter.dispatch('clean_tmp_tables')(schemas) }}
+{%- endmacro %}
+
+-- default
+{% macro default__clean_tmp_tables(schemas) -%}
+    {% do exceptions.warn("\tCLEANING TEST LEFTOVERS IS NOT IMPLEMENTED FOR THIS DESTINATION.\n") %}
```
Comment (edgao) [inline airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql:7]:
```suggestion
    {% do exceptions.warn("\tCLEANING TEST LEFTOVERS IS NOT IMPLEMENTED FOR THIS DESTINATION. This is not an error, but you may want to manually delete the test tables.\n") %}
```

**Review by edgao — APPROVED** [review]

File: airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql (hunk 6 above)
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/dbt-project-template/macros/clean_tmp_tables.sql:7]: Done.

File: airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py (hunk 5 above)
Comment (bazarnov) [reply airbyte-integrations/bases/base-normalization/integration_tests/dbt_integration_test.py:472]: Done.

**Comment by bazarnov** [comment]
@edgao @ChristopheDuong 
I believe - not, but to be sure I'll ask this:
- since this change doesn't touch the executable code of the `normalization` itself, should I bump the version of normalization image?

**Comment by edgao** [comment]
agree, no need to publish for this change.

**Comment by bazarnov** [comment]
> /test connector=bases/base-normalization
> 
> > 🕑 bases/base-normalization https://github.com/airbytehq/airbyte/actions/runs/2552192493

@edgao @ChristopheDuong 
Is there any way to collect the logs from hanged job like this? I can see the test is failed for some reason, but I couldn't check what wrong because logs are not available. 

FYI: same integration test for normalization works well locally.

**Comment by edgao** [comment]
I would just rerun it :/ seen this a few times but never figured out why it happens

**Comment by bazarnov** [comment]
> /test connector=bases/base-normalization

And again, it's already failed after 1h 39m...but no logs provided. I'll dig into the EC2 asap to try to find the `dbt_output.log` for each destination, probably this will reveal the truth)

**Review by lazebnyi — APPROVED** [review]
