### PR TITLE
27558 break a long running ctid query into smaller size serial sub queries

### LINKED ISSUE #27558: Break a long running ctid query into smaller size serial sub-queries
Leaving a long running query with `SELECT … WHERE ctid > '0,0'` doesn't look like a viable solution because in testing we're seeing an unpredictable behavior when queries fail at after about 200GB of serialized data and sometimes a query breaks with an SQLException but sometimes queries just hang for days.

This issue tracks the effort to break this query into multiple subqueries `SELECT … WHERE ctid > '0,0' AND ctid <= '(x,y)'`, controlled by amount rows or amount of data.
the assumption is that by not attempting to read entire tables all at once we can keep syncing longer in order to reach 1TB sizes without relying on platform retries.

### PR DESCRIPTION
**Pull request by rodireich**
Rather than making a single `SELECT … FROM … WHERE ctid > (0,0)`,
We are going to run a series of sub queries `SELECT … FROM … WHERE ctid > (lower bound) AND ctid <= (upper bound)`.
The range of bounds is calculated according to the approximate amount of data we set each subquery to retrieve.
Currently set at 1GB.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`89c4ed067d`](https://github.com/airbytehq/airbyte/pull/27687/commits/89c4ed067d94a09b5af6060addabab63da814e20)) - ❌

⏲️  Total pipeline duration: 1374 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-postgres docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1687851588/89c4ed067d94a09b5af6060addabab63da814e20/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java [hunk 1]
```diff
@@ -110,47 +123,100 @@ public List<AutoCloseableIterator<AirbyteMessage>> getIncrementalIterators(
...
+      if (upperBound != null) {
+        final String sql = "SELECT ctid, %s FROM %s WHERE ctid > ?::tid AND ctid <= ?::tid".formatted(wrappedColumnNames, fullTableName);
+        final PreparedStatement preparedStatement = connection.prepareStatement(sql);
+        preparedStatement.setObject(1, lowerBound.toString());
+        preparedStatement.setObject(2, upperBound.toString());
+        LOGGER.info("Executing query for table {}: {}", tableName, preparedStatement);
+        return preparedStatement;
       } else {
-        preparedStatement.setObject(1, "(0,0)");
+        final String sql = "SELECT ctid, %s FROM %s WHERE ctid > ?::tid".formatted(wrappedColumnNames, fullTableName);
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:214]: when can upperBound be null?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java [hunk 2]
```diff
@@ -28,21 +28,23 @@
...
+
   private static final Logger LOGGER = LoggerFactory.getLogger(PostgresQueryUtils.class);
 
   public static final String NULL_CURSOR_VALUE_WITH_SCHEMA_QUERY =
       """
         SELECT
           (EXISTS (SELECT FROM information_schema.columns WHERE table_schema = '%s' AND table_name = '%s' AND is_nullable = 'YES' AND column_name = '%s'))
         AND
-          (EXISTS (SELECT from \"%s\".\"%s\" where \"%s\" IS NULL LIMIT 1)) AS %s
+          (EXISTS (SELECT from "%s"."%s" where "%s" IS NULL LIMIT 1)) AS %s
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java:40]: why these changes?

Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java:40]: To remove spot check warnings.
No need to escape inside """ block

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java [hunk 3]
```diff
@@ -79,6 +81,11 @@ SELECT pg_relation_filenode('%s')
 
   public static final String TOTAL_BYTES_RESULT_COL = "totalbytes";
 
+  public static final String CTID_TABLE_BLOCK_SIZE =
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java:84]: Can we comment what this block size is? Is it the page size or some other Postgres internal

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java [hunk 4]
```diff
@@ -150,12 +162,45 @@ public static List<io.airbyte.protocol.models.v0.AirbyteStreamNameNamespacePair>
...
-      } catch (SQLException e) {
+      } catch (final SQLException e) {
         // Assume it's safe to progress and skip relation node and vaccuum validation
         LOGGER.warn("Failed to fetch vacuum for table {} info. Going to move ahead with the sync assuming it's safe", fullTableName, e);
       }
     });
     return streamsUnderVacuuming;
   }
 
+  public static Map<AirbyteStreamNameNamespacePair, TableBlockSize> getTableBlockSizeForStream(final JdbcDatabase database,
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java:173]: so page size/blocks size can be configured differently per table?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java [hunk 5]
```diff
@@ -53,14 +56,18 @@ public class PostgresCtidHandler {
   private final String quoteString;
   private final CtidStateManager ctidStateManager;
   private final Map<AirbyteStreamNameNamespacePair, Long> fileNodes;
+  final Map<AirbyteStreamNameNamespacePair, TableBlockSize> tableBlockSizes;
   private final Function<AirbyteStreamNameNamespacePair, JsonNode> streamStateForIncrementalRunSupplier;
   private final BiFunction<AirbyteStreamNameNamespacePair, JsonNode, AirbyteStateMessage> finalStateMessageSupplier;
+  private static final int QUERY_TARGET_SIZE_GB = 1; // TODO: find optimal size
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:62]: small nit : can we create a tracking work item to find the correct size?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java [hunk 6]
```diff
@@ -110,47 +123,100 @@ public List<AutoCloseableIterator<AirbyteMessage>> getIncrementalIterators(
...
+   * @param chunkSizeGB required amount of data in each partition
+   * @return a list of ctid that can be used to generate queries.
+   */
+  @VisibleForTesting
+  static List<Pair<Ctid, Ctid>> ctidQueryPlan(final Ctid startCtid, final long relationSize, final long blockSize, final int chunkSizeGB) {
+    final List<Pair<Ctid, Ctid>> chunks = new ArrayList<>();
+    long lowerBound = startCtid.page;
+    long upperBound;
+    final double oneGigaPages = MEGABYTE * 1000 / blockSize;
+    final long eachStep = 110_000; //(long)oneGigaPages * chunkSizeGB; // TEMP
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:142]: why is each step hard coded?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java [hunk 7]
```diff
@@ -110,47 +123,100 @@ public List<AutoCloseableIterator<AirbyteMessage>> getIncrementalIterators(
...
+   * @param blockSize page size
+   * @param chunkSizeGB required amount of data in each partition
+   * @return a list of ctid that can be used to generate queries.
+   */
+  @VisibleForTesting
+  static List<Pair<Ctid, Ctid>> ctidQueryPlan(final Ctid startCtid, final long relationSize, final long blockSize, final int chunkSizeGB) {
+    final List<Pair<Ctid, Ctid>> chunks = new ArrayList<>();
+    long lowerBound = startCtid.page;
+    long upperBound;
+    final double oneGigaPages = MEGABYTE * 1000 / blockSize;
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:141]: nit : can just have one GB

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java [hunk 8]
```diff
@@ -110,47 +123,100 @@ public List<AutoCloseableIterator<AirbyteMessage>> getIncrementalIterators(
...
-            connection -> createCtidQueryStatement(connection, columnNames, schemaName, tableName, airbyteStream), sourceOperations::recordWithCtid);
+            connection -> createCtidQueryStatement(connection, columnNames, schemaName, tableName, p.getLeft(), p.getRight()),sourceOperations::recordWithCtid);
+
         return AutoCloseableIterators.fromStream(stream, airbyteStream);
       } catch (final SQLException e) {
         throw new RuntimeException(e);
       }
-    }, airbyteStream);
+    }, airbyteStream)));
+    return AutoCloseableIterators.concatWithEagerClose(subQueriesIterators);
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:192]: nice! so this is essentially creating one iterator so that we enforce the one stream, one iterator principle?

File: airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandlerTest.java [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+    chunks = PostgresCtidHandler.ctidQueryPlan(Ctid.of(0,0),380545L, 8192L, 45);
+    expected = List.of(
+        Pair.of(Ctid.of(0, 0), null));
+    assertEquals(chunks, expected);
+
+    chunks = PostgresCtidHandler.ctidQueryPlan(Ctid.of(9876,5432),380545L, 8192L, 45);
+    expected = List.of(
+        Pair.of(Ctid.of(9876, 5432), null));
+    assertEquals(chunks, expected);
+
```
Comment (akashkulk) [inline airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandlerTest.java:43]: nit : Can we add a test cases for an edge cases where block size > table size (probably won't happen)

**Review by akashkulk — COMMENTED** [review]
One larger question I had is that in the previous implementation there was logic to understand if a full vacuum had occurred between runs (so as to reset). 

Is there any risk of something similar occuring between queries (since each of them is now it's own transaction)?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java (hunk 4 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java:173]: It's a server setting in fact.
That block size is also used for some WAL logs definition, shared buffers and all sort of things. it's a low level setting on the server.
There is of course a body of literary work around how to optimize it - https://www.postgresql.org/docs/current/runtime-config-preset.html

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java (hunk 6 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:142]: Sorry I was using this PR for pre releases testing on cloud.
I'll move to another branch to keep this merge ready

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java (hunk 8 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:192]: exactly. because from the outside it's a single iterator we just keep doing next() 
Internally we query the first, one and drain it out, then query the second and so on.
at each time there's a single open connection.

When we parallelize source-postgres it should be easy since it can be done on the outer composite iterator level.

**Comment by rodireich** [comment]
Interesting point.
There is a minuscule chance of getting a full vacuum right in between two subqueries.
The following log from cloud shows an end to subquery and opening a new one
```
2023-06-27 16:31:46 replication-orchestrator > Records read: 6585000 (1 GB)
2023-06-27 16:31:46 source > INFO i.a.c.u.CompositeIterator(lambda$emitCompleteStreamStatus$2):162 COMPLETE -> public_snowflake_1tb
2023-06-27 16:31:46 source > INFO i.a.c.u.CompositeIterator(lambda$emitStartStreamStatus$1):155 STARTING -> public_snowflake_1tb
2023-06-27 16:31:46 source > INFO i.a.i.s.p.c.PostgresCtidHandler(createCtidQueryStatement):226 Preparing query for table: snowflake_1tb
2023-06-27 16:31:46 source > INFO i.a.i.s.p.c.PostgresCtidHandler(createCtidQueryStatement):235 Executing query for table snowflake_1tb: HikariProxyPreparedStatement@2041611826 wrapping SELECT ctid, "f0","f1","f2","f3","f4","f5","f6","f7","f8","f9","f13","f14","f15" FROM "public"."snowflake_1tb" WHERE ctid > '(128000,0)'::tid AND ctid <= '(256000,0)'::tid
2023-06-27 16:31:46 source > INFO i.a.d.j.s.AdaptiveStreamingQueryConfig(initialize):31 Set initial fetch size: 10 rows
```
This is a split second and since the connection itself is maintained by hikari it's even faster.
Theoretically speaking - the very worst case a full vacuum started and is now taking an exclusive read privilege on the table,
Our query is going to hang and platform heartbeat will terminate us. 
The following attempt will be able to tell a full vacuum is running / ran and respond accordingly.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java (hunk 7 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:141]: didn't get that

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java (hunk 5 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:62]: - [ ] Investigate sync parameters for ctid with large tables.

Comment (rodireich) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:62]: #27787

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java (hunk 7 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/ctid/PostgresCtidHandler.java:141]: Was just saying we can have : 
final double oneGigaPages = ONE_GIGABYTE_BYTES / blockSize; instead

**Review by akashkulk — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`a6e1ea8510`](https://github.com/airbytehq/airbyte/pull/27687/commits/a6e1ea8510ac9997276c4f5711f10f41d9711f47)) - ❌

⏲️  Total pipeline duration: 1483 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-postgres docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1687935469/a6e1ea8510ac9997276c4f5711f10f41d9711f47/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by subodh1810 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`09b7a06494`](https://github.com/airbytehq/airbyte/pull/27687/commits/09b7a064946cb0fad8f54407ec9ecdeda8718b03)) - ❌

⏲️  Total pipeline duration: 1401 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-postgres docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1687952344/09b7a064946cb0fad8f54407ec9ecdeda8718b03/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`403c86584d`](https://github.com/airbytehq/airbyte/pull/27687/commits/403c86584d13d46f7a6b94aa15dc85bb557ab85b)) - ❌

⏲️  Total pipeline duration: 801 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ❌        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-postgres docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688157255/403c86584d13d46f7a6b94aa15dc85bb557ab85b/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`a4a6d00b00`](https://github.com/airbytehq/airbyte/pull/27687/commits/a4a6d00b0084ff2a3a7d207586f6757208402ad8)) - ❌

⏲️  Total pipeline duration: 11mn17s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688158208/a4a6d00b0084ff2a3a7d207586f6757208402ad8/source-postgres/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`c96424ff47`](https://github.com/airbytehq/airbyte/pull/27687/commits/c96424ff4733d301e1505b6a4d434753424bc1e3)) - ❌

⏲️  Total pipeline duration: 10mn52s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688158988/c96424ff4733d301e1505b6a4d434753424bc1e3/source-postgres/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`82fde9e7d0`](https://github.com/airbytehq/airbyte/pull/27687/commits/82fde9e7d0505fb8019d4928b3ff2c0df899bccc)) - ❌

⏲️  Total pipeline duration: 05mn46s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ❌        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688161173/82fde9e7d0505fb8019d4928b3ff2c0df899bccc/source-postgres-strict-encrypt/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`82fde9e7d0`](https://github.com/airbytehq/airbyte/pull/27687/commits/82fde9e7d0505fb8019d4928b3ff2c0df899bccc)) - ❌

⏲️  Total pipeline duration: 10mn46s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ❌        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688161173/82fde9e7d0505fb8019d4928b3ff2c0df899bccc/source-postgres/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`543ea1cd02`](https://github.com/airbytehq/airbyte/pull/27687/commits/543ea1cd02c32fe2679cf1bb5bf3b9cf45899450)) - ❌

⏲️  Total pipeline duration: 10mn57s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/27558-break-a-long-running-ctid-query-into-smaller-size-serial-sub-queries/1688162458/543ea1cd02c32fe2679cf1bb5bf3b9cf45899450/source-postgres/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```
