### PR TITLE
Display additional failure information when sync is expanded and jump to relevant log line

### LINKED ISSUE #12130: Log View: Allow linking to a specific line in a log
We want to give users the option to link to a specific line in the log view. That way we can craft links to specific log lines in other parts of our UI as well as allowing users to reference a specific line explicitally, e.g. when talking to support.

### LINKED ISSUE #12628: Display both `internalMessage` and `externalMessage` when viewing a `FailureReason`
When viewing a failed sync in the list view, we currently display the `externalReason` for the failure from [`FailureReasons`](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/FailureReason.yaml).  This message is "Human readable failure description for presentation in the UI to non-technical users.".  However, it may be useful for a user to also see the `internalReason` in the expanded view.

This mockup shows the "externalReason" as "Failure Details" as one possible implementation.
Screen Shot 2022-05-05 at 10 31 42 AM

### PR DESCRIPTION
**Pull request by evantahler**
When viewing your list of syncs, if there is an `internalMessage` on the failure, this PR will display that message to the user when the sync is expanded:

Screen Shot 2022-05-18 at 2 25 42 PM 

If there is a timestamp for that failure reason, you can now also choose to jump to the first line in the logs that matches that timestamp.

https://user-images.githubusercontent.com/303226/169158218-643e5e1c-cbe6-40a3-b962-3763df8572f8.mov

As the platform gets better at tracking errors (e.g. https://github.com/airbytehq/airbyte/pull/12423, there will be both a user-facing "externalMessage" and more detailed "internalMessage") about each failure.  This PR displays both to the user.  

Alternatives considered:
* A 'see more' modal next to the error that contained both failure messages and the stacktrace
* An 'errors' table that showed the internalMessage, externalMessage, and stack trace when expanded. 

Closes https://github.com/airbytehq/airbyte/issues/12628 and airbytehq/airbyte#12130

### CODE REVIEW

**Review by sherifnada — COMMENTED** [review]
ACK. removing myself as a reviewer since I am no good for reviewing UI code

File: airbyte-webapp/src/components/JobItem/components/FailureDetails.tsx [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+const ExpandedFailureContainer = styled.div`
+  font-size: 12px;
+  line-height: 15px;
+  padding: 10px;
+  padding-left: 40px;
+  color: ${({ theme }) => theme.greyColor40};
+`;
+
+const getFailureFromAttempt = (attempt: Attempt) => {
+  return attempt.failureSummary && attempt.failureSummary.failures[0];
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/components/FailureDetails.tsx:19]:
```suggestion
  return attempt.failureSummary?.failureSummary.failures[0];
```

**Comment by evantahler** [comment]
@timroes I decided to tackle both https://github.com/airbytehq/airbyte/issues/12628 and https://github.com/airbytehq/airbyte/issues/12130 in this PR, so the scope has gotten a little larger here.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 2]
```diff
@@ -57,4 +61,36 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
   );
 };
 
+/**
+ * Matching the log's line number by time makes the following assumptions:
+ * 1. The log's lines are already ordered by time
+ * 2. The timestamps used are in the same timezone
+ */
+const getMatchingLineNumbers = (matchTimestamp: number | undefined, lines: string[] | undefined) => {
```
Comment (evantahler) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:69]: This section is rather brittle, and might cause problems locking up the UI for particularly long logs.  If this is going to be a problem we could:
1. disable jumping to the right line if the log is > 10,000(?) lines
2. sample - rather than parse every line, we could parse timestamps from only 1000 lines sampled evenly.  We would jump to the closest line. 
3. pre-parse the logs to extract timestamps on the server.  I'd rather not pass this load to the server/worker, and keep this in the UI for now until we learn that this useful/utilized by our users. 

What are your thoughts?

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 3]
```diff
@@ -9,6 +9,7 @@ import Status from "core/statuses";
 
 import { useAttemptLink } from "./attemptLinkUtils";
 import ContentWrapper from "./components/ContentWrapper";
+import ErrorDetails from "./components/FailureDetails";
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:12]: nit: if we're importing this as `ErrorDetails` and exporting it as such within the file, should the file be named `ErrorDetails`?

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 4]
```diff
@@ -97,7 +102,13 @@ const JobItem: React.FC<IProps> = ({ shortInfo, ...props }) => {
           >
             {isOpen ? (
               isJobEntity(props) ? (
-                <JobLogs id={jobMeta.id} jobIsFailed={isFailed} />
+                <>
+                  <ErrorDetails
+                    attempts={isJobEntity(props) ? props.job.attempts : undefined}
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:107]: nit: looks like this whole `<ErrorDetails` component is already within an `isJobEntity(props)`

```suggestion
                    attempts={props.job.attempts}
```

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 5]
```diff
@@ -34,10 +34,12 @@ const LogsView = styled.div<{ isEmpty?: boolean }>`
 
 type LogsProps = {
   logsArray?: string[];
+  logTimestamp?: number;
 };
 
-const Logs: React.FC<LogsProps> = ({ logsArray }) => {
+const Logs: React.FC<LogsProps> = ({ logsArray, logTimestamp }) => {
   const logsJoin = logsArray?.length ? logsArray.join("\n") : "No logs available";
+  const matchingLineNumbers = getMatchingLineNumbers(logTimestamp, logsArray);
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:42]: Since `getMatchingLineNumbers` might take some time to iterate, is this something we may want to wrap in a `useMemo`?

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 6]
```diff
@@ -57,4 +61,38 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
+  const matcher = /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]/;
+
+  let lineCounter = lines.length - 1;
+  while (lineCounter >= 0) {
+    const timeString = lines[lineCounter].match(matcher);
+    if (timeString) {
+      const datetime = Date.parse(`${timeString[0].replace(" ", "T")}Z`);
+      if (datetime - 1000 <= matchTimestamp && datetime + 1000 >= matchTimestamp) {
+        matchingLineNumbers.push(lineCounter + 1);
+      } else if (datetime - 2001 <= matchTimestamp) {
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:88]: note: we'll be highlighting the log lines that are within +-1second of the trace message.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 7]
```diff
@@ -57,4 +61,38 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
+  }
+
+  const matchingLineNumbers: number[] = [];
+  const matcher = /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]/;
+
+  let lineCounter = lines.length - 1;
+  while (lineCounter >= 0) {
+    const timeString = lines[lineCounter].match(matcher);
+    if (timeString) {
+      const datetime = Date.parse(`${timeString[0].replace(" ", "T")}Z`);
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:85]: any time zone-related things to worry about here? are these `matchTimestamp` and `timeString`s always in the same TZ?

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 8]
```diff
@@ -57,4 +61,38 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
 };
 
+/**
+ * Matching the log's line number by time makes the following assumptions:
+ * 1. The log's lines are already ordered by time
+ * 2. The timestamps used are in the same timezone
+ * 3. The error is closer to the end of the log file than the beginning
+ * 4. Lines are matched by the start of a line with "YYYY-MM-DD HH:mm:ss" format, like "2022-05-17 23:00:19 DEBUG I am a log message"
+ *
+ * TODO: it appears that LazyLog only highlights the first 2 lines in the array.  Can this be fixed?
```
Comment (pedroslopez) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:71]: Could LazyLog be expecting a range instead of the individual line numbers? (e.g. `[10, 12]` instead of `[10, 11, 12]`)

**Review by pedroslopez — COMMENTED** [review]
Nice! This will be super useful for finding out what went wrong. Just a few comments, but I'll defer to the FE team for approval.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx (hunk 7 above)
Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx:85]: I *think* so, but the assumption is noted 🤷

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx (hunk 8 above)
Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx:71]: Genius!

**Comment by evantahler** [comment]
@timroes rebased on main with the new APIs. Please review again!

**Comment by evantahler** [comment]
Conversation notes w/ @timroes - In production, the server times are UTC and the browser times are (?).  So, we need to convert the timezones.  We'll need a way to know the viewer's timezone (can get this from browser APIs), and the server timezone - which is probably a new API.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 9]
```diff
@@ -57,4 +61,41 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
+
+  const resolutionOffset = 1000; // the resolution of the timestamps is in seconds
+  const matchingLineNumbers: number[] = [];
+  const matcher = /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]/;
+
+  let lineCounter = lines.length - 1;
+  while (lineCounter >= 0) {
+    const timeString = lines[lineCounter].match(matcher);
+    if (timeString) {
+      const datetime = Date.parse(`${timeString[0].replace(" ", "T")}Z`);
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:85]: We should try to avoid `Date.parse`. We already use day.js as a dependency for date handling (since `Date` in JS is pretty much the same as in Java - before jodatime made it mostly into the language - try to avoid it :D). We should leverage that for [parsing](https://day.js.org/docs/en/parse/string-format) the date here, which would also give us proper control of the format.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 10]
```diff
@@ -57,4 +61,41 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
+ * 3. The error is closer to the end of the log file than the beginning
+ * 4. Lines are matched by the start of a line with "YYYY-MM-DD HH:mm:ss" format, like "2022-05-17 23:00:19 DEBUG I am a log message"
+ */
+const getMatchingLineNumbers = (matchTimestamp: number | undefined, lines: string[] | undefined) => {
+  if (!matchTimestamp || !lines || lines.length === 0) {
+    return [];
+  }
+  const flooredMatchTimestamp = Math.floor(matchTimestamp / 1000) * 1000;
+
+  const resolutionOffset = 1000; // the resolution of the timestamps is in seconds
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:77]: :question: I am not fully udnerstanding why we need this? Why are we expecting the `failure.timestamp` to be not exactly the one in the log, that we try to search a bit "around" that time?

Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx:77]: Exactly - the Platform stores the timestamp of the failure with ms resolution... but the log lines we get back are in second resolution.  So the failure may have occurred within +/- 1 second for the logged timestamp.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx (hunk 9 above)
Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx]: Done! Was able to remove the custom regexp too!

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 11]
```diff
@@ -57,4 +68,39 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
...
+  const matchingLineNumbers: number[] = [];
+
+  let lineCounter = lines.length - 1;
+  while (lineCounter >= 0) {
+    const datetime = dayjs.utc(lines[lineCounter], dateTimeFormat, false)?.toDate()?.getTime();
```
Comment (evantahler) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:89]: If there is not a match, this will return `NaN`, should never throw... Thanks, dayJs!

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx (hunk 10 above)
Comment (timroes) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx:84]: I see, thanks makes sense for me now. Wouldn't it thought be easier (and potentially safer, so we're not getting "too early" log lines), to just conver the `failure.timestamp` into a second timestamp here, and compare against those matching? Otherwise we might match also on log timestamps that are in the second before the error?

Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx]: Moved to matching time in full 1-second chunks via 53a9f51f5cd8030caeb2b0415ad0da56e4a1d8ec

**Comment by timroes** [comment]
@evantahler The timezone should be working tested it locally. Though I feel that the overall behavior of the scrolling feels abit buggy at the moment, mostly because of the implementation inside LazyLog, which we're using. You can only click the View button once, after that scrolling around and clicking it again won't bring you back to the error position, and just does nothing (based on them not offering any imperative API to scroll to, but only the React property). Also in my tests most of the time it actually scrolls slightly outside the area we're giving thus the log won't even be visible...

I digged a bit through LazyLog, but we can't really fix that "easily" from the outside. Given that the implementation at the moment feels more buggy to me, I'd actually suggest we're skipping the scroll to feature for now. We also have https://github.com/airbytehq/airbyte/issues/12129 as an epic to go to a LogViewer version 2 (and most likely will exchange the library we're using as part of that), and I'd rather push of scroll-to functionallity till then, rather than deliverying now a rather buggy-feeling experience. Would that be fine with you?

**Comment by evantahler** [comment]
@timroes totally fine with deferring the scrolling until later.  I'll update this PR to replace the button with the timestamp so the user can at least get a hint where manually scroll too to learn more.

**Comment by evantahler** [comment]
ok @timroes we are now just showing the (properly formatted) failure timestamp and not scrolling. 

Screen Shot 2022-05-26 at 11 09 14 AM

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 12]
```diff
@@ -47,8 +46,10 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
           lineClassName="logLine"
           highlightLineClassName="highlightLogLine"
           selectableLines
-          follow
+          follow={true}
           style={{ background: "transparent" }}
+          scrollToLine={undefined}
+          highlight={[]}
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:52]: Is this a hack to prevent it from scrolling to a specific line?

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx [hunk 13]
```diff
@@ -47,8 +46,10 @@ const Logs: React.FC<LogsProps> = ({ logsArray }) => {
           lineClassName="logLine"
           highlightLineClassName="highlightLogLine"
           selectableLines
-          follow
+          follow={true}
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/components/Logs.tsx:49]: Actually, we prefer it without the `={true}`

**Review by edmundito — APPROVED** [review]
Code looks great. Tested locally.

File: airbyte-webapp/src/components/JobItem/components/Logs.tsx (hunk 12 above)
Comment (evantahler) [reply airbyte-webapp/src/components/JobItem/components/Logs.tsx:52]: yep - and it was undocumented and super hard to find.  That's why I left this in so we would remember this for the future when we get to https://github.com/airbytehq/airbyte/issues/12128

**Comment by evantahler** [comment]
Fun fact - I had to retry this flaky test 5x before it passed https://github.com/airbytehq/airbyte/actions/runs/2392338287
