### PR TITLE
[source-postgres]: fix getLsn() utils function for read replicas

### LINKED ISSUE #45396: [source-postgres] Logical replication not working on read replicas
### Connector Name

source-postgres

### Connector Version

 3.6.18

### What step the error happened?

Syncs never start.

### Relevant information

CDC Replication doesn't work on Postgres read replicas because it uses functions that can only be executed on the master - probably only one function:  `pg_current_wal_lsn()`. 
I believe this can be solved quickly by replacing usage of `pg_current_wal_lsn` function with `pg_last_wal_receive_lsn`.

Postgres version : 16.13R2

Good to know: [Debezium has solved this issue on their side very simply since V2.5](https://debezium.io/blog/2023/12/04/debezium-2-5-beta1-released/#:~:text=Streaming%20from%20PostgreSQL%2016%20stand%2Dbys), however the connector doesn't use Debezium for everything. 

### Relevant log output

```shell
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: recovery is in progress Hint: WAL control functions cannot be executed during recovery.
```

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by assaadhjb**
## What
This resolves https://github.com/airbytehq/airbyte/issues/45396.

It allows getLsn() function to be executed on read replicas instances as well as primary instances. 
This will unblock CDC replication for Postgres from read replicas, that currently cannot happen only because it is trying to execute functions proper to a master in a read replicas.

## How
by getting LSN number using a function that you can execute on a replica, in case you are on a replica.

## User Impact
Users will be able to use CDC on postgres replicas.

## Can this PR be safely reverted and rolled back?

- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Thanks @assaadhjb, @airbytehq/jdbc-connectors can someone take a look into this contribution?

**Review by theyueli — COMMENTED** [review]
Thanks for the contribution! The query looks good to me.

Instead of updating the README.md and version.properties of CDK (which was not modified in this PR), please update the changelog and bump up the `dockerImageTag` of the source-postgres connectors. They can be found here:

docs/integrations/sources/postgres.md
airbyte-integrations/connectors/source-postgres/metadata.yaml

File: airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt [hunk 1]
```diff
@@ -18,7 +18,11 @@ object PostgresUtils {
         val jsonNodes =
             database.bufferedResultSetQuery(
                 { conn: Connection ->
-                    conn.createStatement().executeQuery("select * from pg_current_wal_lsn()")
+                    conn
+                        .createStatement()
+                        .executeQuery(
+                            "SELECT CASE WHEN pg_is_in_recovery() THEN pg_last_wal_receive_lsn() ELSE pg_current_wal_lsn() END AS pg_current_wal_lsn;"
```
Comment (theyueli) [inline airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: I have a question here:

Say that our database has no replica, and the db is in recovery mode, this would run into calling pg_last_wal_receive_lsn(), which will return null? I guess this would cause issue?

**Comment by assaadhjb** [comment]
@theyueli Thank you for the review! I have addressed the changes requested

**Review by theyueli — APPROVED** [review]

File: airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt (hunk 1 above)
Comment (postamar) [inline airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: This change should also be carried over to `getLsn` in `PostgresUtils` in the CDK. Please do this in a separate PR because CDK releases are annoying to manage otherwise.

Comment (assaadhjb) [reply airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: Hello @postamar, so a new version of Airbyte CDK needs to be published. Is this correct? 
Shall I do this in this PR and open an other where I use the new version of CDK in Postgres Source where I bump its DockerTag?

File: docs/integrations/sources/postgres.md [hunk 2]
```diff
@@ -94,7 +94,7 @@ These are the additional steps required (after following the [quick start](#quic
 
 We recommend following the steps in the [quick start](#quick-start) section to confirm that Airbyte can connect to your Postgres database prior to configuring CDC settings.
 
-For CDC, you must connect to primary/master databases. Pointing the connector configuration to replica database hosts for CDC will lead to failures.
+For CDC from stand-by read-replicas, the required minimum version of Postgres is 16.
```
[the remark this answers is not in the document]
Comment (assaadhjb) [reply docs/integrations/sources/postgres.md:97]: Yes, because logical decoding on standbys is possible [only since PG 16](https://www.postgresql.org/docs/release/16.0/#:~:text=Allow%20logical%20decoding%20on%20standbys%20(Bertrand%20Drouvot%2C%20Andres%20Freund%2C%20Amit%20Khandekar))

File: airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt (hunk 1 above)
Comment (assaadhjb) [reply airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: @postamar could you please clarify the requested change here because Im not sure to get it fully 🙏

Comment (assaadhjb) [reply airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: @theyueli I think that was the initial change (bumping version in `airbyte-cdk` instead of source-postgres DockerTag. Could you please confirm that I need to revert to the initial change? Thanks 🙏

Comment (theyueli) [reply airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: @assaadhjb I spoke too fast... yes, your original change was correct. I thought `postgresutils.kt` is part of the connector not CDK. It is in the CDK. 

In this case, you just need to only bump up the CDK version as you did before. In addition, please change CDK's changelog `airbyte-cdk/java/airbyte-cdk/README.md`.  sorry for the confusion.

Comment (assaadhjb) [reply airbyte-cdk/java/airbyte-cdk/datastore-postgres/src/main/kotlin/io/airbyte/cdk/db/PostgresUtils.kt:24]: @theyueli No problem! I'll restore the old changes so we upgrade CDK and use it in a separate PR. Thanks again for your reviews 🙏

File: docs/integrations/sources/postgres.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (assaadhjb) [reply docs/integrations/sources/postgres.md:97]: So the version gate is not for the query, it is for attempting to replicate from a read-replica. In this case for older versions we would run into different errors unrelated to this change. 
The query is perfectly executable for older versions of PG (from 9.5 onwards) since it uses 
`pg_last_wal_receive_lsn()` and `pg_is_in_recovery()` functions that are both available in past version as well as the already used `pg_current_wal_lsn()`.

[the remark this answers is not in the document]
Comment (assaadhjb) [reply docs/integrations/sources/postgres.md:97]: To summarise. Airbyte can replicate from PG starting from 9.5 according to the docs. But to replicate from a read-replica, one needs PG 16 because it is only possible to perform cascading replications in general (regardless from airbyte or not) [only from PG 16 onwards ](https://github.com/airbytehq/airbyte/pull/45397/#:~:text=standbys%20is%20possible-,only%20since%20PG%2016,-Contributor)

**Comment by assaadhjb** [comment]
@theyueli @postamar  all changes are addressed 
@marcosmarxm could you please unblock merging so that I can open another PR to use the new version of CDK?

File: airbyte-cdk/java/airbyte-cdk/README.md [hunk 3]
```diff
@@ -174,6 +174,7 @@ corresponds to that version.
 
 | Version    | Date       | Pull Request                                                | Subject                                                                                                                                                        |
 |:-----------|:-----------|:------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|
+| 0.47.0     | 2024-09-24 | [\#45397](https://github.com/airbytehq/airbyte/pull/45397)  | Allow logical replication from Postgres 16 read-replicas|
```
Comment (theyueli) [inline airbyte-cdk/java/airbyte-cdk/README.md:177]: should be 0.46.2

File: docs/integrations/sources/postgres.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (theyueli) [reply docs/integrations/sources/postgres.md]: Thanks for the clarification!

**Review by theyueli — APPROVED** [review]
@marcosmarxm the change looks good to me. 

I will help publish the new CDK if it passes CI, then update source-postgres to use the latest CDK.

**Review by marcosmarxm — APPROVED** [review]

**Comment by theyueli** [comment]
@marcosmarxm hi Marcos, could you take a look at this CI failure? 

Vercel — Authorization required to deploy.

**Comment by marcosmarxm** [comment]
Hello @assaadhjb and @theyueli looks there is a problem in the CI pipeline. I'm working with tooling team to get it solved and merge your contribution.

File: airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties [hunk 4]
```diff
@@ -1 +1 @@
-version=0.47.0
+0.47.1
```
Comment (assaadhjb) [inline airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties:1]: @theyueli in my latest merge I mistakenly removed the key `version`. Apologies for that. I have corrected this here https://github.com/airbytehq/airbyte/pull/46101 🙏
