### PR TITLE
fix feed handling when feeds are unavailable

### LINKED ISSUE #2782: Failure to fetch connectors feed breaks Airbyte
## Expected Behavior
Failure when fetching connectors shouldn't break airbyte and should instead lead to a degraded experience.

A potential solution could be:
- if the internal of fetching the feed fails, just return the list as it was when core was released.
- tag the response with a last updated at so that the UI can display a little warning if it is too old and that the list of connectors and version isn't up-to-date

## Current Behavior
Extracted from the conversation:
When the airbyte server fails to fetch the list of connectors, the UI stops working. 
One valid scenario when that happens is if your environment has firewall rules that prevents fetching the connector feed from GitHub.

## Steps to Reproduce
`docker-compose up` in an environment that can't connect to Github

## Severity of the bug for you
Critical

## Airbyte Version
1.18.2

## Additional context
*Environment, version, integration...*

### PR DESCRIPTION
**Pull request by cgardens**
closes https://github.com/airbytehq/airbyte/issues/2782
## What
* when definition feeds aren't available the web app breaks.
* the common case for this is when the instance doesn't have access to the internet.

## How
* if there is a failure fetching feeds, return empty feeds.
* this _mostly_ just works in the ui (see screenshot). optionally we should remove the word latest if we don't have info on what the latest version is.

Screen Shot 2021-04-19 at 4 08 34 PM

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/services/AirbyteGithubStore.java [hunk 1]
```diff
@@ -59,12 +63,12 @@ public AirbyteGithubStore(String baseUrl) {
     this.baseUrl = baseUrl;
   }
 
-  public String getLatestDestinations() throws IOException, InterruptedException {
-    return getFile(DESTINATION_DEFINITION_LIST_LOCATION_PATH);
+  public List<StandardDestinationDefinition> getLatestDestinations() throws IOException, InterruptedException {
```
Comment (michel-tricot) [inline airbyte-server/src/main/java/io/airbyte/server/services/AirbyteGithubStore.java:66]: the interface is nicer now

**Review by michel-tricot — COMMENTED** [review]
LGTM

**Review by jrhizor — APPROVED** [review]

**Review by davinchia — APPROVED** [review]
