### PR TITLE
🐛 Jdbc sources: switch from "string" to "array" schema type for columns with JDBCType.ARRAY

### LINKED ISSUE #4357: Bigquery destination SCD table does not work with array type from source Postgres table
## Expected Behavior
The SCD table in BigQuery should have array values from postgres table populated instead of null.

## Current Behavior
The SCD table in BigQuery has null populated for array values. The _airbyte_raw_table has the array values transferred from postgres correctly. But the transformation from _airbyte_raw_table to table_scd populates null in the array field. Thanks to the help from @marcosmarxm on slack, we were able to find the root cause of the issue to be the usage of the [legacy](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#legacy_json_extraction_functions) JSON function - `json_extract_scalar` in the DBT model for the SCD in BigQuery. The `json_query` or `json_query_array` should be used based on if the destination column needs to be `string` or `array` type as per [this](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#standard_json_extraction_functions_recommended) Google docs.

## Logs
1. Postgres tables: [postgres_sql_log.txt](https://github.com/airbytehq/airbyte/files/6718463/postgres_sql_log.txt)
1. _airbyte_raw_table on BigQuery screenshot: airbyte_raw_array_test_table
1. SCD table on BigQuery screenshot: array_test_scd_table
1. Sync logs: [logs-55-0.txt](https://github.com/airbytehq/airbyte/files/6718483/logs-55-0.txt)
1. DBT generated models: [dbt_array_test_scd_sql.txt](https://github.com/airbytehq/airbyte/files/6718485/dbt_array_test_scd_sql.txt)

## Steps to Reproduce
1. Create a test table in postgres with `create table array_test (id bigserial primary key, values text[] not null, created_at timestamptz not null DEFAULT (NOW() AT TIME ZONE 'utc'));`
1. Insert some data - insert into array_test(values) values('{"a","b","c"}');
1. Configure a CDC from postgres to BigQuery
1. Run the Sync
1. Look at data in SCD tables. The data `{"a", "c", "c"}` is missing. (the data is present in _raw_airbyte_array_test)

## Severity of the bug for you
High

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
Destination (bigquery): 0.3.6
Source (postgres): 0.3.4

## Additional context
n/a

### LINKED ISSUE #7939: Json -> Avro / Parquet schema convert should support array field without items
An input Json schema may have an array field without the `items` specification. Our Json -> Avro schema converter should be flexible enough to handle that.

### PR DESCRIPTION
**Pull request by yurii-bidiuk**
## What
Fixes #4357, #7939

## How
Set type "array" for a catalog when the column's JDBC type is an array. Added mapping for array type.

## Recommended reading order
1. `PostgresSourceOperations.java`
2. `JDBCSourceOperations.java`
3. `AbstractJdbcCompatibleSourceOperations.java`
4. `JsonToAvroSchemaConverter.java`

## 🚨 User Impact 🚨
This PR sets JSON schema type as "array" for DB values that have JDBCType.ARRAY. Before it was set as "string. Parsed value for all arrays will be like `["value1","value2","value3"]` 

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java [hunk 1]
```diff
@@ -193,8 +194,11 @@ Schema getSingleFieldType(final String fieldName, final JsonSchemaType fieldType
         fieldSchema = Schema.createUnion(unionTypes);
       }
       case ARRAY -> {
-        final JsonNode items = fieldDefinition.get("items");
-        Preconditions.checkNotNull(items, "Array field %s misses the items property.", fieldName);
+        JsonNode items = fieldDefinition.get("items");
+        if (items == null) {
+          LOGGER.warn("Source connector provided schema for ARRAY with missed \"items\", will assume that it's a String type");
+          items = getTypeStringSchema();
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java:200]: Defaulting array field to an array of strings is fine. However, we also need to update the Json to Avro object converter. Otherwise, the objection conversion process will for sure run into exceptions. It is located in https://github.com/airbytehq/json-avro-converter. I can work on that.

Please also add test cases in [here](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter).

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java [hunk 2]
```diff
@@ -266,4 +270,12 @@ Schema getNullableFieldTypes(final String fieldName, final JsonNode fieldDefinit
     }
   }
 
+  private static JsonNode getTypeStringSchema() {
+    return Jsons.deserialize("{\n"
+        + "    \"type\": [\n"
+        + "      \"string\"\n"
+        + "    ]\n"
+        + "  }");
+  }
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java:279]: You can reuse the `STRING_SCHEMA` constant, and setup the Avro schema directly.

**Review by tuliren — COMMENTED** [review]
Looks good in general, except for the comments about json / avro schema converter.

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java (hunk 1 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java]: Added test cases

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java (hunk 2 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java]: fixed

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json [hunk 3]
```diff
@@ -778,5 +778,48 @@
...
+    "jsonSchema": {
+      "type": "object",
+      "properties": {
+        "identifier": {
+          "type": "array"
+        }
+      }
+    },
+    "jsonObject": {
+      "identifier": ["151", "152"]
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json:795]: Could you make the elements in this array a mixture of types? So that we can test that everything is converted to string. Currently both the elements are already strings, and no conversion is needed or tested.

```suggestion
      "identifier": ["151", 152, true, { "id": 153 }]
```

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json [hunk 4]
```diff
@@ -778,5 +778,48 @@
...
+        },
+        {
+          "name": "_airbyte_additional_properties",
+          "type": ["null", { "type": "map", "values": "string" }],
+          "default": null
+        }
+      ]
+    },
+    "avroObject": {
+      "identifier": ["151", "152"],
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json:821]: The corresponding Avro array would be:

```suggestion
      "identifier": ["151", "152", "true", "{\"id\": 153}"],
```

**Review by tuliren — COMMENTED** [review]
Thanks. The unit tests will fail currently, because the object converter does not know to auto convert unknown array to an array of string. I will make a change in the Json object converter accordingly.

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json (hunk 3 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json]: @tuliren done

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json (hunk 4 above)
Comment (yurii-bidiuk) [reply airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json]: done

**Comment by tuliren** [comment]
I created PR https://github.com/airbytehq/json-avro-converter/pull/10. @yurii-bidiuk, please take a look. I just added to that repo, but I could not tag you directly as a reviewer yet.

**Comment by tuliren** [comment]
There was a bug in my Json / Avro object converter [PR](airbytehq/json-avro-converter#10). I am working on a fix.

**Comment by tuliren** [comment]
The bug should have been fixed (https://github.com/airbytehq/json-avro-converter/pull/11). I have also updated the test case.

**Review by tuliren — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

**Comment by tuliren** [comment]
@yurii-bidiuk, this change has been merged to master together with PR #8726. My PR only publishes Postgres. Can you take care of the publication of the other databases that are affected by this array change?

**Comment by yurii-bidiuk** [comment]
@tuliren ok, I will publish it in separate PR
