### PR TITLE
🎉 Destination GCS: fix connection check

### LINKED ISSUE #9631: Investigate GCS destination integration test failure
The integration test passed locally, but failed on CI ([attempt](https://github.com/airbytehq/airbyte/actions/runs/1721221730/attempts/1)).

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Resolves https://github.com/airbytehq/airbyte/issues/9631.
- The check operation of the GCS destination uses native S3 `TransferManager` to test the multipart upload. However, in the sync operation, we use `StreamTransferManager` to do the job. It looks like the former requires two more permissions than the latter: `multipartUpload.list` and `multipartUpload.listAll`.
- This PR fixes this issue by using the `StreamTransferManager` to test the multipart upload. In this way, the check reflects what actually happens in the sync. In this way, users do not need to grant the client unnecessary permissions just to pass the connection check.
- The same check is applied to both S3 and GCS.

## 🚨 User Impact 🚨
- None expected.

## Pre-merge Checklist
<strong>Updating a connector</strong>
   
### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Comment by tuliren** [comment]
S3 version is bumped in https://github.com/airbytehq/airbyte/pull/10256. I will revert its version bump here, and do it in a separate PR.

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java [hunk 1]
```diff
@@ -33,7 +41,15 @@ public static void main(final String[] args) throws Exception {
   @Override
   public AirbyteConnectionStatus check(final JsonNode config) {
     try {
-      attemptS3WriteAndDelete(S3DestinationConfig.getS3DestinationConfig(config), config.get("s3_bucket_path").asText());
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java:36]: should we just replace all usages of this method, or is it possible that the staging warehouse destinations do actually need those extra permissions? E.g. https://github.com/airbytehq/airbyte/blob/ae2a87ee0563e8d54b341422ceb3ecef09afc69d/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeCopyS3Destination.java#L40

Comment (tuliren) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java:36]: I think it would depend on the use case, i.e. how the warehouse uses the S3 or other staging bucket. Since there is no complaint from the community about any permission issue for those destinations, we have not looked into them yet.
