### PR TITLE
fix: shows partialSuccess icon for all attempts instead of individual status

### LINKED ISSUE #10261: Fix: partialSuccess should be exposed from individual attempts
In the attempts UI 
image

we should use the red :x:  icon for attempts that had partialSuccess: false and the yellow :warning: icon for attempts that had partialSuccess: true. Right now, we use the :warning: icon for every attempt.

### PR DESCRIPTION
**Pull request by harshithmullapudi**
## What
Fixes #10261

### CODE REVIEW

File: airbyte-webapp/src/components/JobItem/components/JobLogs.tsx [hunk 1]
```diff
@@ -4,17 +4,22 @@ import { FormattedMessage } from "react-intl";
...
 
 type IProps = {
   id: number | string;
   jobIsFailed?: boolean;
-  isPartialSuccess?: boolean;
 };
 
-const JobLogs: React.FC<IProps> = ({ id, jobIsFailed, isPartialSuccess }) => {
+const isPartialSuccess = (attempt: Attempt) => {
+  return attempt.failureSummary?.partialSuccess ? true : false;
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/components/JobLogs.tsx:19]:
```suggestion
  return !!attempt.failureSummary?.partialSuccess;
```

File: airbyte-webapp/src/components/JobItem/components/MainInfo.tsx [hunk 2]
```diff
@@ -135,10 +140,13 @@ const MainInfo: React.FC<IProps> = ({
           {jobStatus}
           {shortInfo ? <FormattedMessage id="sources.additionLogs" /> : null}
           {attempts.length && !shortInfo ? (
-            <AttemptDetails
-              attempt={attempts[attempts.length - 1]}
-              configType={job.configType}
-            />
+            <div>
+              {attempts.length > 1 && <Text>Last Attempt:</Text>}
```
Comment (timroes) [inline airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:144]: This string still needs to be internationalized.

Comment (harshithmullapudi) [reply airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:144]: Yeah will do waiting for UI Look to be finalised. What do you think this is fine?

Comment (timroes) [reply airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:144]: Could you maybe attach a screenshot to the PR? It would help already getting a feeling and commenting on design (while waiting for everything to build locally :D)

Comment (harshithmullapudi) [reply airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:144]: Yep will do

**Comment by harshithmullapudi** [comment]
Screenshot 2022-02-11 at 4 44 13 PM

here is the image

**Review by timroes — APPROVED** [review]
Code LGTM. Tested locally with a job having some partial, some non partial results on Chrome Linux.

**Comment by pmossman** [comment]
Ah I had a sudden realization this morning that we should only show the 'Last Attempt:' text if there were multiple attempts, but you implemented it that way already, perfect! Thanks for getting this done so quickly!
