### PR TITLE
🐞 Postgres source: fix bug in intermediate state emission

### LINKED ISSUE #15427: Postgres intermediate state may lead to data loss for incremental sync
## Environment
- **Source Connector and version**: Postgres source version `0.4.41`
- **Step where error happened**: Incremental sync

## Current Behavior
- Intermediate state message emission was introduced to Postgres source in version `0.4.41`. But the implementation has a flaw that can lead to data loss.
- In this implementation, incremental syncs will sort the table with the cursor field, and emit the max cursor for every 10K records. The purpose is to emit the states frequently, so that if any transient failure occurs during a long sync, the next run does not need to start from the beginning, but can resume from the last successful intermediate state committed on the destination. The next run will start with `cursorField > cursor`.
- However, it is possible that there are multiple records with the same cursor value. If the intermediate state is emitted before all these records have been synced to the destination, some of these records may be lost.
- Here is an example:

| Record ID | Cursor Field | Other Field | |
| --- | --- | --- | --- |
| 1 | F1=16 | F2="abc" | |
| 2 | F1=16 | F2="def" | <- state emission and failure |
| 3 | F1=16 | F2="ghi" | |

If the intermediate state is emitted for record 2 and the sync fails immediately such that the cursor value `16` is committed, but only record 1 and 2 are actually synced, the next run will start with `F1 > 16` and skip record 3.

## Expected Behavior
Intermediate state emission should only happen when all records with the same cursor value has been synced to destination.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Only emit intermediate state messages when all records with the same cursor value have been emitted.
- Fix https://github.com/airbytehq/airbyte/issues/15427.

## 🚨 User Impact 🚨
- This PR fixes a bug introduced in version `0.4.41`.

### CODE REVIEW

**Comment by tuliren** [comment]
@ryankfu, this is the intermediate state emission bug fix that is relevant to your ticket. Now whenever you want the iterator to emit a state, just set `emitIntermediateState` to `true`, and the next call will emit the proper intermediate state when it is available.

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java [hunk 1]
```diff
@@ -60,36 +68,42 @@ private String getCursorCandidate(final AirbyteMessage message) {
...
+        return message;
+      }
+
+      totalRecordCount++;
       final AirbyteMessage message = messageIterator.next();
       if (message.getRecord().getData().hasNonNull(cursorField)) {
         final String cursorCandidate = getCursorCandidate(message);
-        if (IncrementalUtils.compareCursors(maxCursor, cursorCandidate, cursorType) < 0) {
+        final int cursorComparison = IncrementalUtils.compareCursors(maxCursor, cursorCandidate, cursorType);
+        if (cursorComparison < 0) {
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:84]: How come we're breaking this logic into a `cursorComparison` variable that seems to be used only once here instead of keeping the old logic of 

```java
if (IncrementalUtils.compareCursors(maxCursor, cursorCandidate, cursortype) {}
```

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java [hunk 2]
```diff
@@ -27,10 +28,16 @@ public class StateDecoratingIterator extends AbstractIterator<AirbyteMessage> im
...
-  private AirbyteMessage intermediateStateMessage;
   private boolean hasEmittedFinalState;
-  private int recordCount;
+
+  // The intermediateStateMessage is set to the latest state message.
+  // For every stateEmissionFrequency messages, emitIntermediateState is set to true and
+  // the latest intermediateStateMessage will be emitted.
+  private int totalRecordCount = 0;
+  private boolean emitIntermediateState = false;
+  private AirbyteMessage intermediateStateMessage = null;
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:40]: How come we're setting the `intermediateStateMessage = null` here over the previous code where it was originally `intermediateStateMessage`? Is it mainly to be explicit with the default value?

File: airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java [hunk 3]
```diff
@@ -191,19 +201,27 @@ void testStateEmission1() {
...
-    assertEquals(STATE_MESSAGE_2, iterator1.next());
+    // emit state 1 because it is the latest state ready for emission
+    assertEquals(STATE_MESSAGE_1, iterator1.next());
     assertEquals(RECORD_MESSAGE_3, iterator1.next());
-    // final state message should only be emitted once
+    assertEquals(STATE_MESSAGE_2, iterator1.next());
+    assertEquals(RECORD_MESSAGE_4, iterator1.next());
     assertEquals(STATE_MESSAGE_3, iterator1.next());
+    assertEquals(RECORD_MESSAGE_5, iterator1.next());
+    // state 3 is not emitted because there is no more record and only
```
Comment (ryankfu) [inline airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java:214]: I'm a bit confused by this comment, based on my understanding every time the iterator executes it _should_ emit a new intermittent `STATE_MESSAGE` that is **not** the initial or the final cursor so in this example I would have expected the `STATE_MESSAGE`s for 2 - 4. How come the `STATE_MESSAGE`s are from 1 - 3 and the code does not emit 4?

**Review by ryankfu — CHANGES_REQUESTED** [review]
Left some comments to clarify the naming of tests to be more clear with emphasis on `testStateEmission4` being difficult to follow without context into the [github issue](https://github.com/airbytehq/airbyte/issues/15427)

Also would like to clarify why certain code changes were made when the original code _could_ be reused

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java (hunk 1 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:84]: This branch is separated from another one I am working on. In that one, I also need to handle the case when `cursorComparison == 0`.

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java (hunk 2 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:40]: Yes. I just want to make it explicit.

File: airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java (hunk 3 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java:214]: This stream has no initial cursor (`null`). It is supposed to emit state for every record. Here is what happens.

- Emit record 1.
- It should emit state 1 after record 1. But at this point, it is unclear whether there will be more records with the same cursor. There is no state ready for emission. So no state is emitted.
- Emit record 2. Now it is clear that the cursor has moved to a new value. So state 1 is ready to be emitted.
- Emit state 1.
- Emit record 3. Same logic that state 2 is ready.
- Emit state 2.
- Emit record 4. State 3 is ready.
- Emit state 3.
- Emit record 5. State 4 is ready.
- There is no more record. So only the final state, state 5, will be emitted. This is why state 4 is NOT emitted.

File: airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java [hunk 4]
```diff
@@ -215,16 +233,48 @@ void testStateEmission2() {
...
+    assertEquals(STATE_MESSAGE_2, iterator1.next());
+    assertEquals(RECORD_MESSAGE_4, iterator1.next());
+    assertEquals(STATE_MESSAGE_3, iterator1.next());
+    assertEquals(RECORD_MESSAGE_5, iterator1.next());
+    assertEquals(STATE_MESSAGE_5, iterator1.next());
+    assertFalse(iterator1.hasNext());
+  }
+
+  @Test
+  @DisplayName("When there are multiple records with the same cursor value")
```
[the remark this answers is not in the document]
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java:297]: Added the javadoc.

The method names do no matter since there is the `DisplayName` annotation explaining what each test is about.

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java (hunk 1 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java]: Reverted.

File: airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/test/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIteratorTest.java:297]: Renamed.

**Review by ryankfu — APPROVED** [review]
Looks good to me, thanks for clarifying the reasons for breaking out some of the logic adding a more clear understanding for the `testStateEmissionForRecordsSharingSameCursorValue`

**Comment by haimelo** [comment]
HI! everyone. I have a need when my python destination throws exception I want postgres emit 1 state after 10000record. But the behavior of postgres is not like that. When my destination error, the job was interrupted and half of the previous data entered my system. When I re-sync, my data is duplicated.

So my question is how to make postgres emit state every 10000 records. I want to persist cursor_record_count when my destination error instead emit the last offset.
ảnh
