### PR TITLE
🐛 Source CockroachDB: Fix cockroach Datatypes

### LINKED ISSUE #4408: Source CockroachDB: Connector provides wrong values for some datatypes
Found by comprehensive tests #3562

## Expected Behavior
A connector should transform source data into an Airbyte datatype without value/meaning losses.

## Current Behavior
General source implementation:
- `bit`. Can't handle values like this "B'101'"
- `date. Cant handle any BC dates  (Ex. '199-10-10 BC" would be missed BC attribute and returned as an AD date). This is caused as JdbcUtils-> DATE_FORMAT is set as "yyyy-MM-dd'T'HH:mm:ss'Z' so it doesn't suppose to handle BC  dates.
- 'float', 'float8' cant' handle "-Infinity', 'Infinity', 'Nan' values. The reason is due to JdbcUtils -> setJsonField contains:
    case FLOAT, DOUBLE -> o.put(columnName, nullIfInvalid(() -> r.getDouble(i), Double::isFinite)); Double can't contains a such.
- 'numeric', 'decimal'. Numeric and decimal types in Postres may contain Nan', inf, infinity, +inf, +infinity, -inf,
    // -infinity types, but in JdbcUtils-> rowToJson we currently try to map it like this, so it fails
"case NUMERIC, DECIMAL -> o.put(columnName, nullIfInvalid(() -> r.getBigDecimal(i)));"
- 'time', 'timetz'. Time only (ex. 04:05:06) would be represented like "1970-01-01T04:05:06Z" which is incorrect. This causes as  JdbcUtils-> DATE_FORMAT is set as ""yyyy-MM-dd'T'HH:mm:ss'Z'"" for both Date and Time types.

## Steps to Reproduce
Short way:
1. Checkout master branch
2. Go to `CockroachSourceComprehensiveTest.java` and find tests with appropriate types. Use example values from comment to insert to addInsertValues and addExpectedValues
4. Run the test.
5. :bomb: 
NOTES: To REMEMBER while fixing this bug: Most of the cases would need to be corrected at JdbcUtils, but this is based class that is used by all others JDBC DBs, i.e. all other JDBC DBs will be affected

## Severity of the bug for you
High

## Connector Version
0.1.0

### PR DESCRIPTION
**Pull request by alexandertsukanov**
## What
SQLException appears in some cases during parsing of Cockroach DB datatypes. Fixed such cases.

## How
Override methods from  `JdbcSourceOperations.java`. Created custom `CockroachJdbcSourceOperations.java` class. 

## Recommended reading order
1. `x.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

File: airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    return jsonNode;
+  }
+
+  private void putCockroachSpecialDataType(ResultSet resultSet, int index, ObjectNode node) throws SQLException {
+    String columnType = resultSet.getMetaData().getColumnTypeName(index);
+    String columnName = resultSet.getMetaData().getColumnName(index);
+    if ("numeric".equalsIgnoreCase(columnType)) {
+      final double value = resultSet.getDouble(index);
+      node.put(columnName, value);
+    }
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java:59]: Should there be an `else` branch here? Otherwise the result may be ignored.

File: airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java [hunk 2]
```diff
@@ -315,25 +302,21 @@ protected void initTests() {
             .addExpectedValues("a", "abc", "Миші йдуть;", "櫻花分店", "", null, "\\xF0\\x9F\\x9A\\x80")
             .build());
 
-    // TODO https://github.com/airbytehq/airbyte/issues/4408
-    // JdbcUtils-> DATE_FORMAT is set as ""yyyy-MM-dd'T'HH:mm:ss'Z'"" for both Date and Time types.
-    // So Time only (04:05:06) would be represented like "1970-01-01T04:05:06Z" which is incorrect
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java:320]: This comment is still relevant since the returned value still have 1970-01-01 in the full date string.

File: airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java [hunk 3]
```diff
@@ -315,25 +302,21 @@ protected void initTests() {
...
             .airbyteType(JsonSchemaPrimitive.STRING)
-            .addInsertValues("null")
+            .addInsertValues("'04:05:06'", null)
+            .addExpectedValues("1970-01-01T04:05:06Z")
             .addNullExpectedValue()
             .build());
 
-    // https://github.com/airbytehq/airbyte/issues/4408
-    // TODO JdbcUtils-> DATE_FORMAT is set as ""yyyy-MM-dd'T'HH:mm:ss'Z'"" for both Date and Time types.
-    // So Time only (04:05:06) would be represented like "1970-01-01T04:05:06Z" which is incorrect
```
Comment (tuliren) [inline airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java:331]: Same for this comment.

**Review by tuliren — APPROVED** [review]

File: airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java (hunk 1 above)
Comment (alexandertsukanov) [reply airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java:65]: Added else statement and handling of SQLException as well.

File: airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java (hunk 2 above)
Comment (alexandertsukanov) [reply airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java:320]: Agreed. Returned back the comment, regarding the DateTime format. However, all java source connectors will send full DateTime in JSON for now. As we need standardization for all related DateTime formats.
Please, see:
https://github.com/airbytehq/airbyte/blob/d71871edc61c84d87aca57cfdadaa9dee36e9471/airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java#L20

So this behavior will be changed when we will sure all destination connectors are able to parse date and time formats.

File: airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java (hunk 3 above)
Comment (alexandertsukanov) [reply airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java:331]: The same is related to this one.

File: airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java (hunk 1 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-cockroachdb/src/main/java/io/airbyte/integrations/source/cockroachdb/CockroachJdbcSourceOperations.java:65]: Do we know what types may go to the `else` branch or give a `SQLException`? Depending on what type it can be, defaulting to `null` may or may not be the best solution.

File: airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java (hunk 2 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-cockroachdb/src/test-integration/java/io/airbyte/integrations/source/cockroachdb/CockroachDbSourceDatatypeTest.java:320]: Got it. Make sense.
