### PR TITLE
Fix incorrect path selection for oneOf cases in jsonschema

### LINKED ISSUE #9980: 🐛 Destination GCS: `Set up destination` button does nothing when setting up a destination with compression
## Environment
- **Airbyte version**:  0.35.14-alpha
- **Deployment**: Docker
- **Destination Connector and version**: Google Cloud Storage (GCS) 0.1.20
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
`Set up destination` button does nothing when setting up a `Google Cloud Storage (GCS)` Destination.

* **No HTTP request is being made.**
* **No error in the front-end console**

image

## Expected Behavior
Destination should be set, or at least get an error message stating what's wrong in the front-end.

## Steps to Reproduce
1. Reproduce example provided in above image

### PR DESCRIPTION
**Pull request by jamakase**
## What
Fixes a problem, when wrong validation schema path was selected for oneOf field. Closes #9980

## How
For some reason when we were building validationSchema we were combining current path with property key ( so in oneOf case, instead of `format.compression_codec` it was `format.format.compression_codec`, as a result always first entry in oneOf was selected.

### CODE REVIEW

File: airbyte-webapp/src/core/jsonSchema/schemaToYup.ts [hunk 1]
```diff
@@ -34,20 +34,22 @@ export const buildYupFormForJsonSchema = (
...
+    // Select first oneOf path if no item selected
+    selectedSchema = selectedSchema ?? jsonSchema.oneOf[0];
+
     if (selectedSchema && typeof selectedSchema !== "boolean") {
       return buildYupFormForJsonSchema(
         { type: jsonSchema.type, ...selectedSchema },
         uiConfig,
         jsonSchema,
         propertyKey,
-        propertyPath ? `${propertyPath}.${propertyKey}` : propertyKey
```
Comment (timroes) [inline airbyte-webapp/src/core/jsonSchema/schemaToYup.ts:50]: We're having the same logic two times more further down. Once inside an object and once inside the array branch. For the object the `propertyKey` we're actually having is not the one passed into this method, but for array it's the same as passed into, and thus the logic the same as here. Could you please explain (and give some example schemas to illustrate it), why the logic needs adjustment in this place, but for the other two calls to `buildYupFormForJsonSchema` further down it's the correct behavior?

**Review by timroes — APPROVED** [review]
Tested locally, fixes the linked issue for me. Should this also close https://github.com/airbytehq/airbyte/issues/8291 ?

File: airbyte-webapp/src/core/jsonSchema/schemaToYup.ts (hunk 1 above)
Comment (Jamakase) [reply airbyte-webapp/src/core/jsonSchema/schemaToYup.ts:50]: @timroes let me know if it's still unclear. I will try to provide a more accurate answer

**Comment by Jamakase** [comment]
> Tested locally, fixes the linked issue for me. Should this also close #8291 ?

No, it is a bit different one problem I believe
