### PR TITLE
:bug: Destination S3: avro and parquet formats have issues with JsonToAvroSchemaConverter

### LINKED ISSUE #8242: Destination S3: `avro` and `parquet` formats have issues with `JsonToAvroSchemaConverter`
## Enviroment
- **Airbyte version**:  0.32.6-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Github 0.2.6
- **Destination Connector and version**:  S3 0.1.13
- **Severity**: High
- **Step where error happened**: Sync job 
## Current Behavior
I've tried to write to CSV / Parquet / JSONL, writing fails 
Source and destination pass the connection test 

## Expected Behavior
Sync should run successfully

## Logs

<details>
<summary>LOG</summary> 
``
2021-11-24 16:15:39 INFO () WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.32.6-alpha
2021-11-24 16:15:39 INFO () TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.32.6-alpha
2021-11-24 16:15:39 WARN () Databases(createPostgresDatabaseWithRetry):41 - Waiting for database to become available...
2021-11-24 16:15:39 INFO () JobsDatabaseInstance(lambda$static$2):25 - Testing if jobs database is ready...
2021-11-24 16:15:39 INFO () Databases(createPostgresDatabaseWithRetry):58 - Database available!
2021-11-24 16:15:39 INFO () DefaultReplicationWorker(run):99 - start sync worker. job id: 15 attempt id: 1
2021-11-24 16:15:39 INFO () DefaultReplicationWorker(run):108 - configured sync modes: {null.commit_comments=full_refresh - append, null.assignees=full_refresh - append, null.issue_events=full_refresh - append, null.issues=full_refresh - append, null.teams=full_refresh - append, null.issue_milestones=full_refresh - append, null.reviews=full_refresh - append, null.issue_comment_reactions=full_refresh - append, null.issue_reactions=full_refresh - append, null.commit_comment_reactions=full_refresh - append, null.tags=full_refresh - append, null.pull_request_comment_reactions=full_refresh - append, null.pull_requests=full_refresh - append, null.comments=full_refresh - append, null.commits=full_refresh - append, null.issue_labels=full_refresh - append, null.organizations=full_refresh - append, null.branches=full_refresh - append, null.review_comments=full_refresh - append, null.pull_request_stats=full_refresh - append, null.releases=full_refresh - append, null.projects=full_refresh - append, null.events=full_refresh - append, null.users=full_refresh - append, null.collaborators=full_refresh - append, null.repositories=full_refresh - append, null.stargazers=full_refresh - append}
2021-11-24 16:15:39 INFO () DefaultAirbyteDestination(start):64 - Running destination...
2021-11-24 16:15:39 INFO () LineGobbler(voidCall):82 - Checking if airbyte/destination-s3:0.1.13 exists...
2021-11-24 16:15:39 INFO () LineGobbler(voidCall):82 - airbyte/destination-s3:0.1.13 was found locally.
2021-11-24 16:15:39 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/15/1 --network host --log-driver none airbyte/destination-s3:0.1.13 write --config destination_config.json --catalog destination_catalog.json
2021-11-24 16:15:39 INFO () LineGobbler(voidCall):82 - Checking if airbyte/source-github:0.2.6 exists...
2021-11-24 16:15:39 INFO () LineGobbler(voidCall):82 - airbyte/source-github:0.2.6 was found locally.
2021-11-24 16:15:39 INFO () DockerProcessFactory(create):127 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/15/1 --network host --log-driver none airbyte/source-github:0.2.6 read --config source_config.json --catalog source_catalog.json --state input_state.json
2021-11-24 16:15:39 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):243 - Destination output thread started.
2021-11-24 16:15:39 INFO () DefaultReplicationWorker(run):136 - Waiting for source thread to join.
2021-11-24 16:15:39 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):207 - Replication thread started.
[34msource[0m - 2021-11-24 16:15:40 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Starting syncing SourceGithub
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [32mINFO[m i.a.i.b.IntegrationRunner(run):76 - {} - Running integration: io.airbyte.integrations.destination.s3.S3Destination
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [32mINFO[m i.a.i.b.IntegrationRunner(run):80 - {} - Command: WRITE
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [32mINFO[m i.a.i.b.IntegrationRunner(run):81 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-24 16:15:41 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:41 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - {} - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[35mdestination[0m - 2021-11-24 16:15:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:42 [32mINFO[m i.a.i.d.s.S3FormatConfigs(getS3FormatConfig):22 - {} - S3 format config: {"flattening":"Root level flattening","format_type":"CSV","part_size_mb":5}
[35mdestination[0m - 2021-11-24 16:15:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:42 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_assignees': s3://tricky-bronze/airbyte_data_sync/github/github_assignees/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:42 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:42 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_assignees/2021_11_24_1637770542844_0.csv with full ID NOQ1TT26u1Z7VhiY7z.vcIizEgS1suwByAndNy55TX.wUOnMi_6j.ud5OD4xh9FtJhKpYthubY3l274reXudCieh6DVDzsqNYaYCmbr3Qy0wUYjIaIp9hLT6Zqdw7zYg
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_branches': s3://tricky-bronze/airbyte_data_sync/github/github_branches/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_branches/2021_11_24_1637770542844_0.csv with full ID OEDNCFN17IyqTx4otH07bwYJ_oha26_cpBSZFE0q0ZvUL2UWJ1CfmAkOe.qOuJiNc2N0wx40Hxpq4YSzYzbkQ5qJcNsl27Z0wqiKs4BjQocD_6sR112Adts79oP4YWY.
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_collaborators': s3://tricky-bronze/airbyte_data_sync/github/github_collaborators/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_collaborators/2021_11_24_1637770542844_0.csv with full ID 8FSaeITYHx3YxezEBqSvnceTPp6yxL6B2d4Qqr3a5jfzO8ifNyHMkckMVUA4DKdoqDCtdUAi0NNPTCaMcaGJdzI_0bPIbGE2UMsAPSMGLshOPLsInAkC9izATALO46W6
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_comments': s3://tricky-bronze/airbyte_data_sync/github/github_comments/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_comments/2021_11_24_1637770542844_0.csv with full ID t3ZZgQnM5ynI6QDpWpu7Yh.4jWCR0T9upCagTbfAleDnETYQOGQgqtwu.HyFAs9DA8W0C0siZzs5jYY.dBg1txcV3mPi6psb9WQ7wBF4Swnhad2RSaaz9vMHtQDY8DW8
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_commit_comment_reactions': s3://tricky-bronze/airbyte_data_sync/github/github_commit_comment_reactions/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_commit_comment_reactions/2021_11_24_1637770542844_0.csv with full ID PIEbLGJmgm51Tuz49pg9JaL4Dgey2ZU1tAJn9UdNKEM0t0ftRemeMFZ7pcxZ.mFIaqLp9JpC.ZaK9D6fL8xQcsR.cTrWJJX3bMfMyTiwLnEjdORjmYUww97zm3vxwCXu
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_commit_comments': s3://tricky-bronze/airbyte_data_sync/github/github_commit_comments/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_commit_comments/2021_11_24_1637770542844_0.csv with full ID Vfb8c4INMjoYp_K_bFjG0awCOfwDP32p.LqEhRuYO2EFhZDfqs5tJ4sukIUcj8N14fuFzMuYi0mdX91SZf97fFKDF5lwQjA64bLag5SEUkMZ0DY_tAWBE2yKj8KDsQ.Z
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_commits': s3://tricky-bronze/airbyte_data_sync/github/github_commits/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_commits/2021_11_24_1637770542844_0.csv with full ID u5q20bUlFryO9lb_TVMd0LGBZMGnRyVz4QjaXGwTMSwaxeVbH2CaYNxneoqAytQ.frma2nxA.H6A0cmgqxhgDS.mJhu3Qad3HML.ehjj_uLaeviwHwgER9wWU3jVYfhO
[34msource[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: assignees 
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_events': s3://tricky-bronze/airbyte_data_sync/github/github_events/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_events/2021_11_24_1637770542844_0.csv with full ID Vf58EAPYYsTdbH7kHqD.PHfQu2XZOBZzzgLQyYwIU8ATy.2r9owZxA71jKw4Ic3g8CeS6R7GSO1m0Eys0ve63sVuIB0zm3gYIk9iUnGzZY.px27fhXdkoEzi7M2rQWYh
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issue_comment_reactions': s3://tricky-bronze/airbyte_data_sync/github/github_issue_comment_reactions/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issue_comment_reactions/2021_11_24_1637770542844_0.csv with full ID CEr5Y5c8nTMnSk60fPFAV2Y0W33tBkKquWjhJ_UPcZoKpAHUIxH2BcnEYPthAjX7SKoYKFJ7OGSF3Z_fEMRKaI7atABNDAafyQYddl6t6PjMOeVXbIbweIPNc7PpDLR_
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issue_events': s3://tricky-bronze/airbyte_data_sync/github/github_issue_events/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issue_events/2021_11_24_1637770542844_0.csv with full ID hjIfxae6nZJF2hvzheJZwQOfJ6KIVgOomC8NZF0BYDyAqw9elehCGk_387lse0DvVnWBE2Yu.63PjqiojsJDbtEF8evIus5UBgsF0t1yliMutNUv0DKu8QMsBa1L3cnf
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issue_labels': s3://tricky-bronze/airbyte_data_sync/github/github_issue_labels/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issue_labels/2021_11_24_1637770542844_0.csv with full ID QvPmdoCpsaQMnMkwmCnSvfQE_EJPFQUdXmHM7zfY0_Y4DtBby6Rtio0kfdJw9EIiCiwn4pT_piov2aDg.L4QtGUsM7fQtaMLnZQOAAuU9EOwucwGXftRg5Dyj_FKbgR0
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issue_milestones': s3://tricky-bronze/airbyte_data_sync/github/github_issue_milestones/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:43 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:43 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issue_milestones/2021_11_24_1637770542844_0.csv with full ID xk6_09gTSafufhfKbJ2PV6oXYUc0cEjiYpUwIxmHr0bhAj43xHjs.A6xoXZUGfPzNRpHJnQDgc5sGHIj6zPPSGgtBcgU8l8dscTkU6YuKD4z41qznnK5HpnAo8SiaoBZ
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issue_reactions': s3://tricky-bronze/airbyte_data_sync/github/github_issue_reactions/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issue_reactions/2021_11_24_1637770542844_0.csv with full ID tG6YHuEqnyUhxJNZdUanGtV73LC1kMFtAmnfBTnqmHh69oZ2W8M1kmLzGYMnN.c5d2Fz9TPpInOXxeN0K_tNPKxsSPUXf0uE6dB0mjO7h_YkS_V.5M8UvUJVu1ro5Qsw
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_issues': s3://tricky-bronze/airbyte_data_sync/github/github_issues/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_issues/2021_11_24_1637770542844_0.csv with full ID ajl77r74cfxeKe31Z3sSoCDCP8eeMFNzrQORZJioAlYUeQghRPPum82bPQJgxvHvJAsnzVPWGQomj5tqicc.VGyWB3rj98y3MDSkO870SSWqbXkvMIWp.2mXbqSthF21
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_organizations': s3://tricky-bronze/airbyte_data_sync/github/github_organizations/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_organizations/2021_11_24_1637770542844_0.csv with full ID WZuOfW03oh0IcBNEw9AwgsVA7PSv4qCpJ8_1SGWwki4IqioiCDbgC3oEwH447trEEvov4pzl7N736MlXeEHeust_k_65fSSC2NvkKFvnYzWZFDNvTLpyu2yC.DvEBRj2
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_projects': s3://tricky-bronze/airbyte_data_sync/github/github_projects/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_projects/2021_11_24_1637770542844_0.csv with full ID xH51Af6ooYTRs0aXsefnqXhk6dqFjmdJJ_xM8APBtV1ygowXT2XdYeuB2Pnd_dcQaYd.N56Q93OqYD6DdNao_oX6vc63EUXYJo8k2CAScVt8b3qvG.D0grd8oor71upA
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_pull_request_comment_reactions': s3://tricky-bronze/airbyte_data_sync/github/github_pull_request_comment_reactions/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_pull_request_comment_reactions/2021_11_24_1637770542844_0.csv with full ID I8Oc0kJObU6z63ZMOKRZ5t9UtLtBdqx3uv6sao3wDE8QQr40fqQUW9udiB_y1GKuVz2W6OYpZ.IWIbgUWYtXyjMBqdVdaSs__tWMqD0IgH1gd.0vMwiA3ieHWZArEqz.
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_pull_request_stats': s3://tricky-bronze/airbyte_data_sync/github/github_pull_request_stats/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_pull_request_stats/2021_11_24_1637770542844_0.csv with full ID SyMVzBgKGmts6RrupdLQr44QjZcVpoKdyFRlyS18zGrK8rkTY4p1lsWxFMJusIHbC134TJfjIVouXIQ6ia3Zb.7N_H5FH.W7ExlTYi5RhLiHFA4MLgcnwNskFB37_0zg
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_pull_requests': s3://tricky-bronze/airbyte_data_sync/github/github_pull_requests/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_pull_requests/2021_11_24_1637770542844_0.csv with full ID wPQ7c5R2hmMLJg8FfIZVkD_u.fDAMgxNA2V3eV6VFw0h5v6jv_vdQx4Imbbnb5O.3D.jxADPJkI0zirxNWi5M4693Se_cJ7yR1dYBH5LPicihyKZP7oIGtoX4Vci5HAw
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_releases': s3://tricky-bronze/airbyte_data_sync/github/github_releases/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_releases/2021_11_24_1637770542844_0.csv with full ID aGcXmpoBzmkpIV8M94_sFtc5ScQ35jBI8WbTVJMCPoIn5aDRKEduqUzfxZf2pkf.eDi7u_FWZFVeiM2U1yJOipUHx3pdb8X.CiGWIpbTFkLyuOzoy137gkhFbni619Vu
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_repositories': s3://tricky-bronze/airbyte_data_sync/github/github_repositories/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_repositories/2021_11_24_1637770542844_0.csv with full ID NPxKcO73WV425Nn8KzMcdwVlc5YoCmEEhm4QkGxffI3Y2mm5qfSgjZqQnRPw4KR3NvI0K6XfGctlP__FzGde8FYk1woRRkihhFlJBSsJe4ZQBINOCqhdS9Ooe.xK_pNy
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_review_comments': s3://tricky-bronze/airbyte_data_sync/github/github_review_comments/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_review_comments/2021_11_24_1637770542844_0.csv with full ID .MhRbDVkX8bhUQiGmFKdteqP_F0ryg_byPdXylh_d.5TXB8TBaTH4ViCEqTLB32gH3I8meSNCJ9CVRQSjHYButPhc1McztXFhJbZN5md6Vj0XBUET0dO5VJsRAfxQt7h
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_reviews': s3://tricky-bronze/airbyte_data_sync/github/github_reviews/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_reviews/2021_11_24_1637770542844_0.csv with full ID x_HsGQRg10WqGIYGKXzvd6LjXevsKza18UIZ6tKCV3l7ptDq0_wkGmeXZSbgzhXjLoIdt16SQfuEEu213lpJYv0BMHyFkIQKMkB29mbzCmwbDzOhCFSQOFNaORfZQQDS
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_stargazers': s3://tricky-bronze/airbyte_data_sync/github/github_stargazers/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_stargazers/2021_11_24_1637770542844_0.csv with full ID sVWErzbIlkV3E1FHpkUiTeVmpkKE2EPbv2FwhAU7h6Thw2zbhXXj3sEvVndAZlJaa_qB1L0SmkRV3VMystacuTRQyCFBYfjNy5869HcHrHLNpEaCo9hltxtL0wWpfAZr
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_tags': s3://tricky-bronze/airbyte_data_sync/github/github_tags/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_tags/2021_11_24_1637770542844_0.csv with full ID xS3Xc_stfgLDozCCNBNuxEbACARoh5FJjwuvF6.p1lmj8CccA92bESXAYEk_q28zsi8WJdwnxDfibKpTa8WMQvqsgu1IJo.GahMy450j2Sh4yfSthlv9MZRsS3h79XVu
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_teams': s3://tricky-bronze/airbyte_data_sync/github/github_teams/2021_11_24_1637770542844_0.csv
[34msource[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 34 records from assignees stream
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[34msource[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: branches 
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_teams/2021_11_24_1637770542844_0.csv with full ID 2BScag6rdzovy5s5r_yEfzXCVs9iJHK3dp1TOgDGqFiWrKTRChkzNgybTCxhDAye2Hyhmss_bGG2IjI_sr2WuSUYaI.r5bGltTGgPDLE9rlRTAwGck2k2i6R4eW4iA2u
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.c.S3CsvWriter(<init>):51 - {} - Full S3 path for stream 'github_users': s3://tricky-bronze/airbyte_data_sync/github/github_users/2021_11_24_1637770542844_0.csv
[35mdestination[0m - 2021-11-24 16:15:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:44 [32mINFO[m i.a.i.d.s.u.S3StreamTransferManagerHelper(getDefault):55 - {} - PartSize arg is set to 5 MB
[35mdestination[0m - 2021-11-24 16:15:45 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:15:45 [32mINFO[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to tricky-bronze/airbyte_data_sync/github/github_users/2021_11_24_1637770542844_0.csv with full ID B9AS1MDFDb4DUi5n_P7lBseFT7Y1SdLabFNO0dbsHX567Jkkxw7qBdiyfRGgoq9xh6Xdtd9yvFMq1rVKqYWVnMRdalutA9pHy4O22bOwSKyPOfoZFR38zbNlN7.Mmlee
[34msource[0m - 2021-11-24 16:15:45 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 77 records from branches stream
[34msource[0m - 2021-11-24 16:15:45 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: collaborators 
[34msource[0m - 2021-11-24 16:15:46 WARN () DefaultAirbyteStreamFactory(internalLog):96 - Syncing `collaborators` stream isn't available for repository `tricky-dev/dernieredose-front` and your `access_token`, seems like you don't have permissions for this stream.
[34msource[0m - 2021-11-24 16:15:47 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 11 records from collaborators stream
[34msource[0m - 2021-11-24 16:15:47 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: comments 
[34msource[0m - 2021-11-24 16:15:49 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from comments stream
[34msource[0m - 2021-11-24 16:15:49 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: commit_comment_reactions 
[34msource[0m - 2021-11-24 16:15:50 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from commit_comment_reactions stream
[34msource[0m - 2021-11-24 16:15:50 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: commit_comments 
[34msource[0m - 2021-11-24 16:15:50 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from commit_comments stream
[34msource[0m - 2021-11-24 16:15:50 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: commits 
[34msource[0m - 2021-11-24 16:15:54 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 683 records from commits stream
[34msource[0m - 2021-11-24 16:15:54 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: events 
2021-11-24 16:15:56 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):220 - Records read: 1000
[34msource[0m - 2021-11-24 16:15:58 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 561 records from events stream
[34msource[0m - 2021-11-24 16:15:58 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issue_comment_reactions 
[34msource[0m - 2021-11-24 16:15:59 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from issue_comment_reactions stream
[34msource[0m - 2021-11-24 16:15:59 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issue_events 
2021-11-24 16:16:05 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):220 - Records read: 2000
[34msource[0m - 2021-11-24 16:16:05 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 715 records from issue_events stream
[34msource[0m - 2021-11-24 16:16:05 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issue_labels 
[34msource[0m - 2021-11-24 16:16:07 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 45 records from issue_labels stream
[34msource[0m - 2021-11-24 16:16:07 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issue_milestones 
[34msource[0m - 2021-11-24 16:16:09 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from issue_milestones stream
[34msource[0m - 2021-11-24 16:16:09 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issue_reactions 
[34msource[0m - 2021-11-24 16:17:03 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from issue_reactions stream
[34msource[0m - 2021-11-24 16:17:03 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: issues 
[34msource[0m - 2021-11-24 16:17:06 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 187 records from issues stream
[34msource[0m - 2021-11-24 16:17:06 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: organizations 
[34msource[0m - 2021-11-24 16:17:07 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 1 records from organizations stream
[34msource[0m - 2021-11-24 16:17:07 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: projects 
[34msource[0m - 2021-11-24 16:17:11 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from projects stream
[34msource[0m - 2021-11-24 16:17:11 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: pull_request_comment_reactions 
[34msource[0m - 2021-11-24 16:17:16 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from pull_request_comment_reactions stream
[34msource[0m - 2021-11-24 16:17:16 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: pull_request_stats 
[34msource[0m - 2021-11-24 16:18:45 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 187 records from pull_request_stats stream
[34msource[0m - 2021-11-24 16:18:45 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: pull_requests 
[34msource[0m - 2021-11-24 16:18:49 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 187 records from pull_requests stream
[34msource[0m - 2021-11-24 16:18:49 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: releases 
[34msource[0m - 2021-11-24 16:18:56 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from releases stream
[34msource[0m - 2021-11-24 16:18:56 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: repositories 
[34msource[0m - 2021-11-24 16:18:57 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 5 records from repositories stream
[34msource[0m - 2021-11-24 16:18:57 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: review_comments 
[34msource[0m - 2021-11-24 16:19:01 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from review_comments stream
[34msource[0m - 2021-11-24 16:19:01 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: reviews 
[34msource[0m - 2021-11-24 16:20:08 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 6 records from reviews stream
[34msource[0m - 2021-11-24 16:20:08 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: stargazers 
[34msource[0m - 2021-11-24 16:20:18 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 1 records from stargazers stream
[34msource[0m - 2021-11-24 16:20:18 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: tags 
[34msource[0m - 2021-11-24 16:20:28 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Read 0 records from tags stream
[34msource[0m - 2021-11-24 16:20:28 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: teams 
[34msource[0m - 2021-11-24 16:20:30 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream SourceGithub
Traceback (most recent call last):
  File "/airbyte/integration_code/source_github/streams.py", line 100, in read_records
    yield from super().read_records(stream_slice=stream_slice, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 284, in _send
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/orgs/tricky-dev/teams?per_page=100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_github/streams.py", line 114, in read_records
    f"Syncing `{self.name}` stream isn't available for repository "
KeyError: 'repository'
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/source_github/streams.py", line 100, in read_records
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     yield from super().read_records(stream_slice=stream_slice, **kwargs)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     response = self._send_request(request, request_kwargs)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send_request
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     return backoff_handler(user_backoff_handler)(request, request_kwargs)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     ret = target(*args, **kwargs)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     ret = target(*args, **kwargs)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 284, in _send
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     response.raise_for_status()
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     raise HTTPError(http_error_msg, response=self)
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/orgs/tricky-dev/teams?per_page=100
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - 
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - During handling of the above exception, another exception occurred:
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - 
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/main.py", line 13, in <module>
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     launch(source, sys.argv[1:])
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in launch
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     for message in source_entrypoint.run(parsed_args):
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 99, in run
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     for message in generator:
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     raise e
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     internal_config=internal_config,
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     for record in record_iterator:
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     for record in records:
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/source_github/streams.py", line 114, in read_records
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 -     f"Syncing `{self.name}` stream isn't available for repository "
[34msource[0m - 2021-11-24 16:20:30 ERROR () LineGobbler(voidCall):82 - KeyError: 'repository'
2021-11-24 16:20:30 INFO () DefaultReplicationWorker(run):138 - Source thread complete.
2021-11-24 16:20:30 INFO () DefaultReplicationWorker(run):139 - Waiting for destination thread to join.
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):60 - {} - Airbyte message consumer: succeeded.
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issues'.
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issues/2021_11_24_1637770542844_0.csv with id ajl77r74c...XbqSthF21]: Uploading leftover stream [Part number 1 containing 0.46 MB]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issues/2021_11_24_1637770542844_0.csv with id ajl77r74c...XbqSthF21]: Finished uploading [Part number 1 containing 0.46 MB]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issues/2021_11_24_1637770542844_0.csv with id ajl77r74c...XbqSthF21]: Completed
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issues'.
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_assignees'.
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:30 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_assignees/2021_11_24_1637770542844_0.csv with id NOQ1TT26u...6Zqdw7zYg]: Uploading leftover stream [Part number 1 containing 0.03 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_assignees/2021_11_24_1637770542844_0.csv with id NOQ1TT26u...6Zqdw7zYg]: Finished uploading [Part number 1 containing 0.03 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_assignees/2021_11_24_1637770542844_0.csv with id NOQ1TT26u...6Zqdw7zYg]: Completed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_assignees'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_teams'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_teams/2021_11_24_1637770542844_0.csv with id 2BScag6rd...R4eW4iA2u]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_teams/2021_11_24_1637770542844_0.csv with id 2BScag6rd...R4eW4iA2u]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_teams/2021_11_24_1637770542844_0.csv with id 2BScag6rd...R4eW4iA2u]: Completed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_teams'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_events'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_events/2021_11_24_1637770542844_0.csv with id Vf58EAPYY...i7M2rQWYh]: Uploading leftover stream [Part number 1 containing 4.55 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_events/2021_11_24_1637770542844_0.csv with id Vf58EAPYY...i7M2rQWYh]: Finished uploading [Part number 1 containing 4.55 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_events/2021_11_24_1637770542844_0.csv with id Vf58EAPYY...i7M2rQWYh]: Completed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_events'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issue_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_comment_reactions/2021_11_24_1637770542844_0.csv with id CEr5Y5c8n...Nc7PpDLR_]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_comment_reactions/2021_11_24_1637770542844_0.csv with id CEr5Y5c8n...Nc7PpDLR_]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_comment_reactions/2021_11_24_1637770542844_0.csv with id CEr5Y5c8n...Nc7PpDLR_]: Completed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issue_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_collaborators'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_collaborators/2021_11_24_1637770542844_0.csv with id 8FSaeITYH...ATALO46W6]: Uploading leftover stream [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_collaborators/2021_11_24_1637770542844_0.csv with id 8FSaeITYH...ATALO46W6]: Finished uploading [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_collaborators/2021_11_24_1637770542844_0.csv with id 8FSaeITYH...ATALO46W6]: Completed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_collaborators'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_repositories'.
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_repositories/2021_11_24_1637770542844_0.csv with id NPxKcO73W...oe.xK_pNy]: Uploading leftover stream [Part number 1 containing 0.02 MB]
[35mdestination[0m - 2021-11-24 16:20:31 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:31 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_repositories/2021_11_24_1637770542844_0.csv with id NPxKcO73W...oe.xK_pNy]: Finished uploading [Part number 1 containing 0.02 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_repositories/2021_11_24_1637770542844_0.csv with id NPxKcO73W...oe.xK_pNy]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_repositories'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issue_labels'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_labels/2021_11_24_1637770542844_0.csv with id QvPmdoCps...yj_FKbgR0]: Uploading leftover stream [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_labels/2021_11_24_1637770542844_0.csv with id QvPmdoCps...yj_FKbgR0]: Finished uploading [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_labels/2021_11_24_1637770542844_0.csv with id QvPmdoCps...yj_FKbgR0]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issue_labels'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_pull_request_stats'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_stats/2021_11_24_1637770542844_0.csv with id SyMVzBgKG...kFB37_0zg]: Uploading leftover stream [Part number 1 containing 0.21 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_stats/2021_11_24_1637770542844_0.csv with id SyMVzBgKG...kFB37_0zg]: Finished uploading [Part number 1 containing 0.21 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_stats/2021_11_24_1637770542844_0.csv with id SyMVzBgKG...kFB37_0zg]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_pull_request_stats'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_stargazers'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_stargazers/2021_11_24_1637770542844_0.csv with id sVWErzbIl...L0wWpfAZr]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_stargazers/2021_11_24_1637770542844_0.csv with id sVWErzbIl...L0wWpfAZr]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_stargazers/2021_11_24_1637770542844_0.csv with id sVWErzbIl...L0wWpfAZr]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_stargazers'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_commit_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comment_reactions/2021_11_24_1637770542844_0.csv with id PIEbLGJmg...zm3vxwCXu]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comment_reactions/2021_11_24_1637770542844_0.csv with id PIEbLGJmg...zm3vxwCXu]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comment_reactions/2021_11_24_1637770542844_0.csv with id PIEbLGJmg...zm3vxwCXu]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_commit_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_branches'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_branches/2021_11_24_1637770542844_0.csv with id OEDNCFN17...79oP4YWY.]: Uploading leftover stream [Part number 1 containing 0.02 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_branches/2021_11_24_1637770542844_0.csv with id OEDNCFN17...79oP4YWY.]: Finished uploading [Part number 1 containing 0.02 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_branches/2021_11_24_1637770542844_0.csv with id OEDNCFN17...79oP4YWY.]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_branches'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_pull_requests'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_requests/2021_11_24_1637770542844_0.csv with id wPQ7c5R2h...X4Vci5HAw]: Uploading leftover stream [Part number 1 containing 2.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_requests/2021_11_24_1637770542844_0.csv with id wPQ7c5R2h...X4Vci5HAw]: Finished uploading [Part number 1 containing 2.00 MB]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_requests/2021_11_24_1637770542844_0.csv with id wPQ7c5R2h...X4Vci5HAw]: Completed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_pull_requests'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_reviews'.
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:32 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_reviews/2021_11_24_1637770542844_0.csv with id x_HsGQRg1...aORfZQQDS]: Uploading leftover stream [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_reviews/2021_11_24_1637770542844_0.csv with id x_HsGQRg1...aORfZQQDS]: Finished uploading [Part number 1 containing 0.01 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_reviews/2021_11_24_1637770542844_0.csv with id x_HsGQRg1...aORfZQQDS]: Completed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_reviews'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_commit_comments'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comments/2021_11_24_1637770542844_0.csv with id Vfb8c4INM...Kj8KDsQ.Z]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comments/2021_11_24_1637770542844_0.csv with id Vfb8c4INM...Kj8KDsQ.Z]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commit_comments/2021_11_24_1637770542844_0.csv with id Vfb8c4INM...Kj8KDsQ.Z]: Completed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_commit_comments'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_releases'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_releases/2021_11_24_1637770542844_0.csv with id aGcXmpoBz...Fbni619Vu]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_releases/2021_11_24_1637770542844_0.csv with id aGcXmpoBz...Fbni619Vu]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_releases/2021_11_24_1637770542844_0.csv with id aGcXmpoBz...Fbni619Vu]: Completed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_releases'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_review_comments'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_review_comments/2021_11_24_1637770542844_0.csv with id .MhRbDVkX...sRAfxQt7h]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_review_comments/2021_11_24_1637770542844_0.csv with id .MhRbDVkX...sRAfxQt7h]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_review_comments/2021_11_24_1637770542844_0.csv with id .MhRbDVkX...sRAfxQt7h]: Completed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_review_comments'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issue_events'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_events/2021_11_24_1637770542844_0.csv with id hjIfxae6n...sBa1L3cnf]: Uploading leftover stream [Part number 1 containing 3.20 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_events/2021_11_24_1637770542844_0.csv with id hjIfxae6n...sBa1L3cnf]: Finished uploading [Part number 1 containing 3.20 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_events/2021_11_24_1637770542844_0.csv with id hjIfxae6n...sBa1L3cnf]: Completed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issue_events'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_commits'.
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commits/2021_11_24_1637770542844_0.csv with id u5q20bUlF...WU3jVYfhO]: Uploading leftover stream [Part number 1 containing 2.49 MB]
[35mdestination[0m - 2021-11-24 16:20:33 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:33 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commits/2021_11_24_1637770542844_0.csv with id u5q20bUlF...WU3jVYfhO]: Finished uploading [Part number 1 containing 2.49 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_commits/2021_11_24_1637770542844_0.csv with id u5q20bUlF...WU3jVYfhO]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_commits'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issue_reactions'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_reactions/2021_11_24_1637770542844_0.csv with id tG6YHuEqn...Vu1ro5Qsw]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_reactions/2021_11_24_1637770542844_0.csv with id tG6YHuEqn...Vu1ro5Qsw]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_reactions/2021_11_24_1637770542844_0.csv with id tG6YHuEqn...Vu1ro5Qsw]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issue_reactions'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_organizations'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_organizations/2021_11_24_1637770542844_0.csv with id WZuOfW03o...C.DvEBRj2]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_organizations/2021_11_24_1637770542844_0.csv with id WZuOfW03o...C.DvEBRj2]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_organizations/2021_11_24_1637770542844_0.csv with id WZuOfW03o...C.DvEBRj2]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_organizations'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_users'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_users/2021_11_24_1637770542844_0.csv with id B9AS1MDFD...lN7.Mmlee]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_users/2021_11_24_1637770542844_0.csv with id B9AS1MDFD...lN7.Mmlee]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_users/2021_11_24_1637770542844_0.csv with id B9AS1MDFD...lN7.Mmlee]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_users'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_issue_milestones'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_milestones/2021_11_24_1637770542844_0.csv with id xk6_09gTS...Ao8SiaoBZ]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_milestones/2021_11_24_1637770542844_0.csv with id xk6_09gTS...Ao8SiaoBZ]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_issue_milestones/2021_11_24_1637770542844_0.csv with id xk6_09gTS...Ao8SiaoBZ]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_issue_milestones'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_pull_request_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_comment_reactions/2021_11_24_1637770542844_0.csv with id I8Oc0kJOb...HWZArEqz.]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_comment_reactions/2021_11_24_1637770542844_0.csv with id I8Oc0kJOb...HWZArEqz.]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_pull_request_comment_reactions/2021_11_24_1637770542844_0.csv with id I8Oc0kJOb...HWZArEqz.]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_pull_request_comment_reactions'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_tags'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_tags/2021_11_24_1637770542844_0.csv with id xS3Xc_stf...sS3h79XVu]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_tags/2021_11_24_1637770542844_0.csv with id xS3Xc_stf...sS3h79XVu]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_tags/2021_11_24_1637770542844_0.csv with id xS3Xc_stf...sS3h79XVu]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_tags'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_comments'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_comments/2021_11_24_1637770542844_0.csv with id t3ZZgQnM5...HtQDY8DW8]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_comments/2021_11_24_1637770542844_0.csv with id t3ZZgQnM5...HtQDY8DW8]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_comments/2021_11_24_1637770542844_0.csv with id t3ZZgQnM5...HtQDY8DW8]: Completed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_comments'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):102 - {} - Uploading remaining data for stream 'github_projects'.
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [33mWARN[m a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(complete):367 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_projects/2021_11_24_1637770542844_0.csv with id xH51Af6oo...8oor71upA]: Uploading leftover stream [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:34 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:34 [32mINFO[m a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_projects/2021_11_24_1637770542844_0.csv with id xH51Af6oo...8oor71upA]: Finished uploading [Part number 1 containing 0.00 MB]
[35mdestination[0m - 2021-11-24 16:20:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:35 [32mINFO[m a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to tricky-bronze/airbyte_data_sync/github/github_projects/2021_11_24_1637770542844_0.csv with id xH51Af6oo...8oor71upA]: Completed
[35mdestination[0m - 2021-11-24 16:20:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:35 [32mINFO[m i.a.i.d.s.w.BaseS3Writer(close):104 - {} - Upload completed for stream 'github_projects'.
2021-11-24 16:20:35 INFO () JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: null found, object expected
2021-11-24 16:20:35 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: null
[35mdestination[0m - 2021-11-24 16:20:35 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-24 16:20:35 [32mINFO[m i.a.i.b.IntegrationRunner(run):133 - {} - Completed integration: io.airbyte.integrations.destination.s3.S3Destination
2021-11-24 16:20:35 INFO () DefaultReplicationWorker(run):141 - Destination thread complete.
2021-11-24 16:20:35 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:117) ~[io.airbyte-airbyte-workers-0.32.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:143) ~[io.airbyte-airbyte-workers-0.32.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.32.6-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.32.6-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-11-24 16:20:35 INFO () DefaultReplicationWorker(run):169 - sync summary: io.airbyte.config.ReplicationAttemptSummary@5f9fafd9[status=failed,recordsSynced=2700,bytesSynced=13279762,startTime=1637770539760,endTime=1637770835130]
2021-11-24 16:20:35 INFO () DefaultReplicationWorker(run):178 - Source did not output any state messages
2021-11-24 16:20:35 WARN () DefaultReplicationWorker(run):186 - State capture: No new state, falling back on input state: io.airbyte.config.State@638679b0[state={}]
2021-11-24 16:20:35 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-11-24 16:20:35 INFO () ReplicationActivityImpl(replicate):121 - sync summary: io.airbyte.config.StandardSyncOutput@17991f9e[standardSyncSummary=io.airbyte.config.StandardSyncSummary@49d0471f[status=failed,recordsSynced=2700,bytesSynced=13279762,startTime=1637770539760,endTime=1637770835130],state=io.airbyte.config.State@638679b0[state={}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@5573f72b[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@4ced6742[stream=io.airbyte.protocol.models.AirbyteStream@13d7e4ae[name=github_assignees,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"repository":{"type":["string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@5874b174[stream=io.airbyte.protocol.models.AirbyteStream@1274dffe[name=github_branches,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"name":{"type":["null","string"]},"commit":{"type":["null","object"],"properties":{"sha":{"type":["null","string"]},"url":{"type":["null","string"]}}},"protected":{"type":["null","boolean"]},"protection":{"type":["null","object"],"properties":{"required_status_checks":{"type":["null","object"],"properties":{"contexts":{"type":["null","array"],"items":{"type":["null","string"]}},"enforcement_level":{"type":["null","string"]}}}}},"repository":{"type":["string"]},"protection_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@35846d85[stream=io.airbyte.protocol.models.AirbyteStream@19da1d0f[name=github_collaborators,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"repository":{"type":["string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"permissions":{"type":["null","object"],"properties":{"pull":{"type":["null","boolean"]},"push":{"type":["null","boolean"]},"admin":{"type":["null","boolean"]}}},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@64d8f051[stream=io.airbyte.protocol.models.AirbyteStream@5067481b[name=github_comments,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"user_id":{"type":["null","integer"]},"html_url":{"type":["null","string"]},"issue_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"author_association":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4619ffd7[stream=io.airbyte.protocol.models.AirbyteStream@fe2a07e[name=github_commit_comment_reactions,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"content":{"type":["null","string"]},"node_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@2c9b93ab[stream=io.airbyte.protocol.models.AirbyteStream@465631b3[name=github_commit_comments,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"line":{"type":["null","integer"]},"path":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"position":{"type":["null","integer"]},"commit_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"author_association":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4f3899e9[stream=io.airbyte.protocol.models.AirbyteStream@55433120[name=github_commits,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"sha":{"type":["null","string"]},"url":{"type":["null","string"]},"author":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"commit":{"type":["null","object"],"properties":{"url":{"type":["null","string"]},"tree":{"type":["null","object"],"properties":{"sha":{"type":["null","string"]},"url":{"type":["null","string"]}}},"author":{"type":["null","object"],"properties":{"date":{"type":["null","string"],"format":"date-time"},"name":{"type":["null","string"]},"email":{"type":["null","string"]}}},"message":{"type":["null","string"]},"committer":{"type":["null","object"],"properties":{"date":{"type":["null","string"],"format":"date-time"},"name":{"type":["null","string"]},"email":{"type":["null","string"]}}},"verification":{"type":["null","object"],"properties":{"reason":{"type":["null","string"]},"payload":{"type":["null","string"]},"verified":{"type":["null","boolean"]},"signature":{"type":["null","string"]}}},"comment_count":{"type":["null","integer"]}}},"node_id":{"type":["null","string"]},"parents":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"sha":{"type":["null","string"]},"url":{"type":["null","string"]},"html_url":{"type":["null","string"]}}}},"html_url":{"type":["null","string"]},"committer":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"comments_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[created_at],sourceDefinedPrimaryKey=[[sha]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[created_at],destinationSyncMode=append,primaryKey=[[sha]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@2535f6e8[stream=io.airbyte.protocol.models.AirbyteStream@52198054[name=github_events,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","string"]},"org":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"login":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"gravatar_id":{"type":["null","string"]}}},"repo":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]}}},"type":{"type":["null","string"]},"actor":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"public":{"type":["null","boolean"]},"payload":{"type":["null","object"],"properties":{}},"created_at":{"type":["null","string"]},"repository":{"type":["string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[created_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[created_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@59e5bc2f[stream=io.airbyte.protocol.models.AirbyteStream@15635c02[name=github_issue_comment_reactions,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"content":{"type":["null","string"]},"node_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1f6b7af0[stream=io.airbyte.protocol.models.AirbyteStream@16e4269[name=github_issue_events,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"actor":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"event":{"type":["null","string"]},"issue":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"number":{"type":["null","integer"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"labels_url":{"type":["null","string"]},"comments_url":{"type":["null","string"]},"repository_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"commit_id":{"type":["null","string"]},"commit_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[created_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[created_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@759e82af[stream=io.airbyte.protocol.models.AirbyteStream@7a925352[name=github_issue_labels,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"color":{"type":["null","string"]},"default":{"type":["null","boolean"]},"node_id":{"type":["null","string"]},"repository":{"type":["string"]},"description":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@3e6a1a0a[stream=io.airbyte.protocol.models.AirbyteStream@4d646aa4[name=github_issue_milestones,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"due_on":{"type":["null","string"],"format":"date-time"},"number":{"type":["null","integer"]},"creator":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"closed_at":{"type":["null","string"],"format":"date-time"},"created_at":{"type":["null","string"],"format":"date-time"},"labels_url":{"type":["null","string"]},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"description":{"type":["null","string"]},"open_issues":{"type":["null","integer"]},"closed_issues":{"type":["null","integer"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4cee125d[stream=io.airbyte.protocol.models.AirbyteStream@240ed051[name=github_issue_reactions,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"content":{"type":["null","string"]},"node_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4ada3490[stream=io.airbyte.protocol.models.AirbyteStream@24855625[name=github_issues,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"labels":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"color":{"type":["null","string"]},"default":{"type":["null","boolean"]},"node_id":{"type":["null","string"]},"description":{"type":["null","string"]}}}},"locked":{"type":["null","boolean"]},"number":{"type":["null","integer"]},"node_id":{"type":["null","string"]},"user_id":{"type":["null","integer"]},"assignee":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"comments":{"type":["null","integer"]},"html_url":{"type":["null","string"]},"assignees":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}}},"closed_at":{"type":["null","string"],"format":"date-time"},"milestone":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"due_on":{"type":["null","string"],"format":"date-time"},"number":{"type":["null","integer"]},"creator":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"closed_at":{"type":["null","string"],"format":"date-time"},"created_at":{"type":["null","string"],"format":"date-time"},"labels_url":{"type":["null","string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"description":{"type":["null","string"]},"open_issues":{"type":["null","integer"]},"closed_issues":{"type":["null","integer"]}}},"created_at":{"type":["null","string"],"format":"date-time"},"events_url":{"type":["null","string"]},"labels_url":{"type":["null","string"]},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"comments_url":{"type":["null","string"]},"pull_request":{"type":["null","object"],"properties":{"url":{"type":["null","string"]},"diff_url":{"type":["null","string"]},"html_url":{"type":["null","string"]},"patch_url":{"type":["null","string"]}}},"repository_url":{"type":["null","string"]},"active_lock_reason":{"type":["null","string"]},"author_association":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@18c5c412[stream=io.airbyte.protocol.models.AirbyteStream@4a9b0303[name=github_organizations,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"blog":{"type":["null","string"]},"name":{"type":["null","string"]},"plan":{"type":["null","object"],"properties":{"name":{"type":["null","string"]},"seats":{"type":["null","integer"]},"space":{"type":["null","integer"]},"filled_seats":{"type":["null","integer"]},"private_repos":{"type":["null","integer"]}}},"type":{"type":["null","string"]},"email":{"type":["null","string"]},"login":{"type":["null","string"]},"company":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"location":{"type":["null","string"]},"followers":{"type":["null","integer"]},"following":{"type":["null","integer"]},"hooks_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"disk_usage":{"type":["null","integer"]},"events_url":{"type":["null","string"]},"issues_url":{"type":["null","string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"description":{"type":["null","string"]},"is_verified":{"type":["null","boolean"]},"members_url":{"type":["null","string"]},"public_gists":{"type":["null","integer"]},"public_repos":{"type":["null","integer"]},"billing_email":{"type":["null","string"]},"collaborators":{"type":["null","integer"]},"private_gists":{"type":["null","integer"]},"twitter_username":{"type":["null","string"]},"public_members_url":{"type":["null","string"]},"owned_private_repos":{"type":["null","integer"]},"total_private_repos":{"type":["null","integer"]},"has_repository_projects":{"type":["null","boolean"]},"members_can_create_pages":{"type":["null","boolean"]},"has_organization_projects":{"type":["null","boolean"]},"default_repository_permission":{"type":["null","string"]},"two_factor_requirement_enabled":{"type":["null","boolean"]},"members_can_create_public_pages":{"type":["null","boolean"]},"members_can_create_repositories":{"type":["null","boolean"]},"members_can_create_private_pages":{"type":["null","boolean"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@51fec074[stream=io.airbyte.protocol.models.AirbyteStream@5f448010[name=github_projects,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"name":{"type":["null","string"]},"state":{"type":["null","string"]},"number":{"type":["null","integer"]},"creator":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"owner_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"columns_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@69172abe[stream=io.airbyte.protocol.models.AirbyteStream@7b06bf84[name=github_pull_request_comment_reactions,jsonSchema={"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"content":{"type":["null","string"]},"node_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@5c5c3df0[stream=io.airbyte.protocol.models.AirbyteStream@27e3726b[name=github_pull_request_stats,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"merged":{"type":["null","boolean"]},"number":{"type":["null","integer"]},"commits":{"type":["null","integer"]},"node_id":{"type":["null","string"]},"comments":{"type":["null","integer"]},"additions":{"type":["null","integer"]},"deletions":{"type":["null","integer"]},"mergeable":{"type":["null","boolean"]},"merged_by":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"rebaseable":{"type":["null","boolean"]},"repository":{"type":["string"]},"changed_files":{"type":["null","integer"]},"mergeable_state":{"type":["null","string"]},"review_comments":{"type":["null","integer"]},"maintainer_can_modify":{"type":["null","boolean"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@7771fef3[stream=io.airbyte.protocol.models.AirbyteStream@39459506[name=github_pull_requests,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"base":{"type":["null","object"],"properties":{"ref":{"type":["null","string"]},"sha":{"type":["null","string"]},"label":{"type":["null","string"]},"repo_id":{"type":["null","integer"]},"user_id":{"type":["null","integer"]}}},"body":{"type":["null","string"]},"head":{"type":["null","object"],"properties":{"ref":{"type":["null","string"]},"sha":{"type":["null","string"]},"label":{"type":["null","string"]},"repo_id":{"type":["null","integer"]},"user_id":{"type":["null","integer"]}}},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"draft":{"type":["null","boolean"]},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"_links":{"type":["null","object"],"properties":{"html":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"self":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"issue":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"commits":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"comments":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"statuses":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"review_comment":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"review_comments":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}}}},"labels":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"color":{"type":["null","string"]},"default":{"type":["null","boolean"]},"node_id":{"type":["null","string"]},"description":{"type":["null","string"]}}}},"locked":{"type":["null","boolean"]},"number":{"type":["null","integer"]},"node_id":{"type":["null","string"]},"assignee":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"diff_url":{"type":["null","string"]},"html_url":{"type":["null","string"]},"assignees":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}}},"closed_at":{"type":["null","string"],"format":"date-time"},"issue_url":{"type":["null","string"]},"merged_at":{"type":["null","string"],"format":"date-time"},"milestone":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"state":{"type":["null","string"]},"title":{"type":["null","string"]},"due_on":{"type":["null","string"],"format":"date-time"},"number":{"type":["null","integer"]},"creator":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"closed_at":{"type":["null","string"],"format":"date-time"},"created_at":{"type":["null","string"],"format":"date-time"},"labels_url":{"type":["null","string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"description":{"type":["null","string"]},"open_issues":{"type":["null","integer"]},"closed_issues":{"type":["null","integer"]}}},"patch_url":{"type":["null","string"]},"auto_merge":{"type":["null","boolean"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"commits_url":{"type":["null","string"]},"comments_url":{"type":["null","string"]},"statuses_url":{"type":["null","string"]},"requested_teams":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"slug":{"type":["null","string"]},"parent":{"type":["null","object"],"properties":{}},"node_id":{"type":["null","string"]},"privacy":{"type":["null","string"]},"html_url":{"type":["null","string"]},"permission":{"type":["null","string"]},"description":{"type":["null","string"]},"members_url":{"type":["null","string"]},"repositories_url":{"type":["null","string"]}}}},"merge_commit_sha":{"type":["null","string"]},"active_lock_reason":{"type":["null","string"]},"author_association":{"type":["null","string"]},"review_comment_url":{"type":["null","string"]},"requested_reviewers":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}}},"review_comments_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@44b8c63[stream=io.airbyte.protocol.models.AirbyteStream@3887d6ab[name=github_releases,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"name":{"type":["null","string"]},"draft":{"type":["null","boolean"]},"assets":{"type":["null","array"],"items":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"size":{"type":["null","integer"]},"label":{"type":["null","string"]},"state":{"type":["null","string"]},"node_id":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"updated_at":{"type":["null","string"],"format":"date-time"},"uploader_id":{"type":["null","integer"]},"content_type":{"type":["null","string"]},"download_count":{"type":["null","integer"]},"browser_download_url":{"type":["null","string"]}}}},"author":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"tag_name":{"type":["null","string"]},"assets_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"prerelease":{"type":["null","boolean"]},"repository":{"type":["string"]},"upload_url":{"type":["null","string"]},"tarball_url":{"type":["null","string"]},"zipball_url":{"type":["null","string"]},"published_at":{"type":["null","string"],"format":"date-time"},"target_commitish":{"type":["null","string"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[created_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[created_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@40f9212e[stream=io.airbyte.protocol.models.AirbyteStream@55816192[name=github_repositories,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"fork":{"type":["null","boolean"]},"name":{"type":["null","string"]},"size":{"type":["null","integer"]},"owner":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"topics":{"type":["null","array"],"items":{"type":["null","string"]}},"git_url":{"type":["null","string"]},"license":{"type":["null","object"],"properties":{"key":{"type":["null","string"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"node_id":{"type":["null","string"]},"spdx_id":{"type":["null","string"]},"html_url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"private":{"type":["null","boolean"]},"ssh_url":{"type":["null","string"]},"svn_url":{"type":["null","string"]},"archived":{"type":["null","boolean"]},"disabled":{"type":["null","boolean"]},"has_wiki":{"type":["null","boolean"]},"homepage":{"type":["null","string"]},"html_url":{"type":["null","string"]},"keys_url":{"type":["null","string"]},"language":{"type":["null","string"]},"tags_url":{"type":["null","string"]},"blobs_url":{"type":["null","string"]},"clone_url":{"type":["null","string"]},"forks_url":{"type":["null","string"]},"full_name":{"type":["null","string"]},"has_pages":{"type":["null","boolean"]},"hooks_url":{"type":["null","string"]},"pulls_url":{"type":["null","string"]},"pushed_at":{"type":["null","string"],"format":"date-time"},"teams_url":{"type":["null","string"]},"trees_url":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"events_url":{"type":["null","string"]},"has_issues":{"type":["null","boolean"]},"issues_url":{"type":["null","string"]},"labels_url":{"type":["null","string"]},"merges_url":{"type":["null","string"]},"mirror_url":{"type":["null","string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"visibility":{"type":["null","string"]},"archive_url":{"type":["null","string"]},"commits_url":{"type":["null","string"]},"compare_url":{"type":["null","string"]},"description":{"type":["null","string"]},"forks_count":{"type":["null","integer"]},"is_template":{"type":["null","boolean"]},"permissions":{"type":["null","object"],"properties":{"pull":{"type":["null","boolean"]},"push":{"type":["null","boolean"]},"admin":{"type":["null","boolean"]}}},"branches_url":{"type":["null","string"]},"comments_url":{"type":["null","string"]},"contents_url":{"type":["null","string"]},"git_refs_url":{"type":["null","string"]},"git_tags_url":{"type":["null","string"]},"has_projects":{"type":["null","boolean"]},"releases_url":{"type":["null","string"]},"statuses_url":{"type":["null","string"]},"assignees_url":{"type":["null","string"]},"downloads_url":{"type":["null","string"]},"has_downloads":{"type":["null","boolean"]},"languages_url":{"type":["null","string"]},"default_branch":{"type":["null","string"]},"milestones_url":{"type":["null","string"]},"stargazers_url":{"type":["null","string"]},"watchers_count":{"type":["null","integer"]},"deployments_url":{"type":["null","string"]},"git_commits_url":{"type":["null","string"]},"subscribers_url":{"type":["null","string"]},"contributors_url":{"type":["null","string"]},"issue_events_url":{"type":["null","string"]},"stargazers_count":{"type":["null","integer"]},"subscription_url":{"type":["null","string"]},"collaborators_url":{"type":["null","string"]},"issue_comment_url":{"type":["null","string"]},"notifications_url":{"type":["null","string"]},"open_issues_count":{"type":["null","integer"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@df1c7d5[stream=io.airbyte.protocol.models.AirbyteStream@b456a4e[name=github_review_comments,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"body":{"type":["null","string"]},"line":{"type":["null","integer"]},"path":{"type":["null","string"]},"side":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"_links":{"type":["null","object"],"properties":{"html":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"self":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"pull_request":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"position":{"type":["null","integer"]},"commit_id":{"type":["null","string"]},"diff_hunk":{"type":["null","string"]},"created_at":{"type":["null","string"],"format":"date-time"},"repository":{"type":["string"]},"start_line":{"type":["null","integer"]},"start_side":{"type":["null","string"]},"updated_at":{"type":["null","string"],"format":"date-time"},"original_line":{"type":["null","integer"]},"in_reply_to_id":{"type":["null","integer"]},"pull_request_url":{"type":["null","string"]},"original_position":{"type":["null","integer"]},"author_association":{"type":["null","string"]},"original_commit_id":{"type":["null","string"]},"original_start_line":{"type":["null","integer"]},"pull_request_review_id":{"type":["null","integer"]}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[updated_at],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updated_at],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@23cca59[stream=io.airbyte.protocol.models.AirbyteStream@5c6fa67d[name=github_reviews,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"body":{"type":["null","string"]},"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"state":{"type":["null","string"]},"_links":{"type":["null","object"],"properties":{"html":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}},"pull_request":{"type":["null","object"],"properties":{"href":{"type":["null","string"]}}}}},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"commit_id":{"type":["null","string"]},"repository":{"type":["string"]},"submitted_at":{"type":["null","string"],"format":"date-time"},"pull_request_url":{"type":["null","string"]},"author_association":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@5fa30d4a[stream=io.airbyte.protocol.models.AirbyteStream@7f940bea[name=github_stargazers,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"user":{"type":["null","object"],"properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},"user_id":{"type":["null","integer"]},"repository":{"type":["string"]},"starred_at":{"type":["null","string"],"format":"date-time"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=true,defaultCursorField=[starred_at],sourceDefinedPrimaryKey=[[user_id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[starred_at],destinationSyncMode=append,primaryKey=[[user_id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@1b9e6843[stream=io.airbyte.protocol.models.AirbyteStream@3ae37903[name=github_tags,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"name":{"type":["null","string"]},"commit":{"type":["null","object"],"properties":{"sha":{"type":["null","string"]},"url":{"type":["null","string"]}}},"node_id":{"type":["null","string"]},"repository":{"type":["string"]},"tarball_url":{"type":["null","string"]},"zipball_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@7d6dea48[stream=io.airbyte.protocol.models.AirbyteStream@22797554[name=github_teams,jsonSchema={"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"name":{"type":["null","string"]},"slug":{"type":["null","string"]},"parent":{"type":["null","string"]},"node_id":{"type":["null","string"]},"privacy":{"type":["null","string"]},"html_url":{"type":["null","string"]},"permission":{"type":["null","string"]},"repository":{"type":["null","string"]},"description":{"type":["null","string"]},"members_url":{"type":["null","string"]},"organization":{"type":["null","string"]},"repositories_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}], io.airbyte.protocol.models.ConfiguredAirbyteStream@4a4dcd28[stream=io.airbyte.protocol.models.AirbyteStream@6b478e03[name=github_users,jsonSchema={"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"id":{"type":["null","integer"]},"url":{"type":["null","string"]},"type":{"type":["null","string"]},"login":{"type":["null","string"]},"node_id":{"type":["null","string"]},"html_url":{"type":["null","string"]},"gists_url":{"type":["null","string"]},"repos_url":{"type":["null","string"]},"avatar_url":{"type":["null","string"]},"events_url":{"type":["null","string"]},"site_admin":{"type":["null","boolean"]},"gravatar_id":{"type":["null","string"]},"starred_url":{"type":["null","string"]},"organization":{"type":["null","string"]},"followers_url":{"type":["null","string"]},"following_url":{"type":["null","string"]},"organizations_url":{"type":["null","string"]},"subscriptions_url":{"type":["null","string"]},"received_events_url":{"type":["null","string"]}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[[id]],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=append,primaryKey=[[id]],additionalProperties={}]],additionalProperties={}]]
2021-11-24 16:20:35 INFO () ConfigRepository(updateConnectionState):518 - Updating connection a1f91e6c-fb74-4de5-aad7-36141ec9491c state: io.airbyte.config.State@34d0b49a[state={}]
2021-11-24 16:20:35 INFO () DatabaseConfigPersistence(updateConfigRecord):273 - Updating STANDARD_SYNC_STATE record a1f91e6c-fb74-4de5-aad7-36141ec9491c``
</details>

## Steps to Reproduce
1. Fresh EC2 air byte instance
2. setup Github source with new token 
3. setup S3 destination with new access ID/key 
4.  launch sync to either parquet/CSV/JSONL

## Are you willing to submit a PR?
probably underqualified, sorry

### LINKED ISSUE #8261: 🐛 Destination S3: Issues with converting JsonSchema to Avro format
## Enviroment
- **Airbyte version**:  latest
- **OS Version / Instance**: NA
- **Deployment**: Local Docker
- **Source Connector and version**: source-shopify:latest
- **Destination Connector and version**: destination-s3 (avro format)
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
During the sync some parts of the JsonSchema cannot be converted to AVRO format. See logs attached. 

## Expected Behavior
The destination operation of converting JsonSchema to Avro and other formats for destination-s3 proceed correctly. 

## Logs
[logs-1-0.txt](https://github.com/airbytehq/airbyte/files/7604939/logs-1-0.txt)

## Steps to Reproduce
1. Build & setup the `Shopify` connector from this PR: https://github.com/airbytehq/airbyte/pull/7783
2. Setup the `destination-s3 (with avro format)` as destination.
3. Run the sync on some streams, like: `abandoned_checkouts`

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
Sync failed for Github Source (stream **commits**) 
Logs: 
```
[35mdestination[0m - 2021-11-26 13:17:54 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-26 13:17:54 [33mWARN[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):58 - {} - Airbyte message consumer: failed.
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" org.apache.avro.SchemaParseException: Can't redefine: author
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$Names.put(Schema.java:1542)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:805)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:967)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1234)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:995)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:979)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1234)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:995)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:979)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema.toString(Schema.java:419)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at org.apache.avro.Schema.toString(Schema.java:391)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.s3.writer.ProductionWriterFactory.create(ProductionWriterFactory.java:42)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.s3.S3Consumer.startTracked(S3Consumer.java:53)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.start(FailureTrackingAirbyteMessageConsumer.java:34)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:142)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
[35mdestination[0m - 2021-11-26 13:17:54 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:29)
2021-11-26 13:17:54 INFO () DefaultReplicationWorker(run):141 - Destination thread complete.
2021-11-26 13:17:54 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
```

## How
According to Apache Avro documentation https://avro.apache.org/docs/current/spec.html#names
_A schema or protocol may not contain multiple definitions of a fullname._ 
Added namespace to avro records

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨

There should not be any user impact in scope of Airbyte streams processing. This PR only add unique namespace into avro schemas for record types, previous namespace value for avro records was null. Only one potential impact is for further processing avro/parquet files outside of airbyte, cause earlier fullname of avro records was consist from **name**, with these changes would be consits from **namespace.name**

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

**Review by sherifnada — COMMENTED** [review]
@VitaliiMaltsev could you describe the user impact? Is this causing a breaking change for users?

**Review by sherifnada — COMMENTED** [review]
Also, can you add a test case to DAT to catch this in the future for all destinations?

File: airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/AvroNameTransformer.java [hunk 1]
```diff
@@ -26,4 +30,12 @@ private String checkFirsCharInStreamName(final String name) {
     }
   }
 
+  public String resovleNamespace(String fieldName, List<String> recordFieldNames) {
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/AvroNameTransformer.java]: fixed

**Comment by VitaliiMaltsev** [comment]
> @VitaliiMaltsev could you describe the user impact? Is this causing a breaking change for users?

@sherifnada updated user impact section

**Comment by VitaliiMaltsev** [comment]
> Also, can you add a test case to DAT to catch this in the future for all destinations?

Please advise which test case do you mean for all destinations? This PR makes changes only to the conversion of the Json schema to the Avro schema in the JsonToAvroSchemaConverter class, since the avro schema, according to the documentation, does not allow having records with the same names. JsonToAvroSchemaConverter is only used for **Destination S3** and **GCS**. JsonToAvroSchemaConverter class is covered by unit tests with in the JsonToAvroConverterTest class (test case "**schema_with_the_same_object_names**")

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json [hunk 2]
```diff
@@ -706,5 +815,221 @@
...
+              "namespace": "_airbyte_avro_namespace.commit_1",
+              "fields": [
+                {
+                  "name": "author",
+                  "type": [
+                    "null",
+                    {
+                      "type": "record",
+                      "name": "author",
+                      "namespace": "_airbyte_avro_namespace.author_2",
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json:941]: Oh, this is nice. Namespace is a known missing feature fo the schema converter.

I have two general questions about how we want to implement the namespace.
1. Should we drop the `_airbyte_avro_namespace` prefix? It seems unnecessary.
2. Instead of appending numbers to clashing field names, what about chaining the field names together to construct the full namespace? For example, the namespace here would become `commit.author`. In this way, the namespace is more informative, because users immediately know the parent fields.

**Comment by tuliren** [comment]
FYI, there are merge conflicts in `json_conversion_test_cases.json` because I added some extra test cases in https://github.com/airbytehq/airbyte/pull/8725.

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json (hunk 2 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json]: > Oh, this is nice. Namespace is a known missing feature fo the schema converter.
> 
> I have two general questions about how we want to implement the namespace.
> 
> 1. Should we drop the `_airbyte_avro_namespace` prefix? It seems unnecessary.
> 2. Instead of appending numbers to clashing field names, what about chaining the field names together to construct the full namespace? For example, the namespace here would become `commit.author`. In this way, the namespace is more informative, because users immediately know the parent fields.

@tuliren removed namespace prefix and updated namespace generation with your suggestion. Please review

**Comment by tuliren** [comment]
Sorry that my previous proposal was wrong. Based on the Avro spec:
https://avro.apache.org/docs/current/spec.html#names

> Record, enums and fixed are named types. Each has a fullname that is composed of two parts; a name and a namespace.
> ...
> For example, one might use "name": "X", "namespace": "org.foo" to indicate the fullname org.foo.X.

So the namespace should not include the field name itself. For example, the nested `author` field should have namespace = `commit` instead of `commit.author`.

Also keeping a `jsonNodePathMap` to store every json node along the way does not seem necessary. I think we just need to track the parent namespace when constructing each object field.

I will make a patch.

File: airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json [hunk 3]
```diff
@@ -774,5 +1008,597 @@
...
+          "_airbyte_additional_properties": null
+        },
+        "message": "test commit message",
+        "_airbyte_additional_properties": null
+      },
+      "_airbyte_additional_properties": null
+    }
+  },
+  {
+    "schemaName": "schema_with_the_same_object_names_and_inner_object",
```
Comment (tuliren) [inline airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json:1274]: What is this case testing against? It seems similar to `schema_with_the_same_object_names`.

Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/destination-s3/src/test/resources/parquet/json_schema_converter/json_conversion_test_cases.json]: removed this test case

**Comment by VitaliiMaltsev** [comment]
> Sorry that my previous proposal was wrong. Based on the Avro spec: https://avro.apache.org/docs/current/spec.html#names
> 
> > Record, enums and fixed are named types. Each has a fullname that is composed of two parts; a name and a namespace.
> > ...
> > For example, one might use "name": "X", "namespace": "org.foo" to indicate the fullname org.foo.X.
> 
> So the namespace should not include the field name itself. For example, the nested `author` field should have namespace = `commit` instead of `commit.author`.
> 
> Also keeping a `jsonNodePathMap` to store every json node along the way does not seem necessary. I think we just need to track the parent namespace when constructing each object field.
> 
> I will make a patch.

@tuliren updated namespace generation logic. Now for the nested `author` field namespace = `commit`. For the nested `pr` field namespace = `commit.author`. Please take a look in test case **schema_with_the_same_object_names**
**jsonNodePathMap** currently store only nested json nodes with non-empty parent

**Review by tuliren — APPROVED** [review]
Thanks a lot for the update.

Can you format the code before merging the PR? Some of the formats are off.

**Comment by VitaliiMaltsev** [comment]
> Thanks a lot for the update.
> 
> Can you format the code before merging the PR? Some of the formats are off.

formatted

**Comment by VitaliiMaltsev** [comment]
/publish connector=connectors/destination-bigquery-denormalized
