### PR TITLE
Destination Redshift - additional check method check, fix s3 file deletion

### LINKED ISSUE #33552: [Redshift Dv2] Handle `svv_table_info` permissions
From [Slack thread](https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1702311247948029?thread_ts=1702299183.996059&cid=C0690DFUDGS).

>(paraphrased) V2 introduced a new "is your table empty" check, which relies on querying the `svv_table_info` view. we could modify that check to do some sort of select exists(...) query to avoid asking for more permissions, but presumably there’s a minor cost tradeoff there, especially wrt to upgrading.

Data point: beta user was OK with granting more permission to the Airbyte user (if we stick with this route, we should add this info to the docs)

### LINKED ISSUE #33983: redshift-destination: Verify purge stage data flag is honored and files deleted from S3
...Also add check for permissions to delete in S3 when flag enabled. 

See: https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1704481421195789

### PR DESCRIPTION
**Pull request by jbfbell**
This changes Destination Redshift's check method to verify access to the `svv_table_info` table as well as fixes a bug related to the removal of s3 staging files if users selected this option

### CODE REVIEW

File: airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/jdbc/AbstractJdbcDestination.java [hunk 1]
```diff
@@ -114,6 +115,15 @@ public AirbyteConnectionStatus check(final JsonNode config) {
...
   }
 
+  /**
+   * Specific Databases may have additional checks unique to them which they need to perform, override
+   * this method to add additional checks.
+   *
+   * @param database the database to run checks against
+   * @throws Exception
+   */
+  protected void destinationSpecificTableOperations(final JdbcDatabase database) throws Exception {}
```
Comment (edgao) [inline airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/jdbc/AbstractJdbcDestination.java:125]: what do you think of having redshift override the `check` method instead of adding a new overridable method?
```java
class RedshiftDestination {
  @Override
  AirbyteConnectionStatus check(config) {
    status = super.check(config);
    if (status != SUCCESS) { return status }
    if (!svvTableInfoAccess(config)) { return FAILED }
    return SUCCESS;
  }
}
```

File: airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/operations/RedshiftS3StagingSqlOperations.java [hunk 2]
```diff
@@ -59,6 +59,7 @@ public RedshiftS3StagingSqlOperations(final NamingConventionTransformer nameTran
    *
    */
   @Override
+  @Deprecated
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/operations/RedshiftS3StagingSqlOperations.java:62]: is the superclass method also deprecated? or just the redshift implementation of it

and nit - would be nice to have `@Deprecated("Becuase xyz, use foo instead")`

File: airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/util/RedshiftUtil.java [hunk 3]
```diff
@@ -36,4 +39,9 @@ private static boolean isNullOrEmpty(final JsonNode jsonNode) {
     return null == jsonNode || "".equals(jsonNode.asText());
   }
 
+  public static void checkSvvTableAccess(final JdbcDatabase database) throws Exception {
+    log.info("checking SVV_TABLE_INFO permissions");
+    database.queryJsons("SELECT 1 FROM SVV_TABLE_INFO LIMIT;");
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/util/RedshiftUtil.java:44]:
```suggestion
    database.queryJsons("SELECT 1 FROM SVV_TABLE_INFO LIMIT 1;");
```
?

File: docs/integrations/destinations/redshift.md [hunk 4]
```diff
@@ -94,12 +94,26 @@ connection only. S3 is secured through public HTTPS access only.
...
    [Create](https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html) a
    staging S3 bucket \(for the COPY strategy\).
-6. Create a user with at least create table permissions for the schema. If the schema does not exist
-   you need to add permissions for that, too. Something like this:
 
-```
-GRANT CREATE ON DATABASE database_name TO airflow_user; -- add create schema permission
-GRANT usage, create on schema my_schema TO airflow_user; -- add create table permission
+### Permissions in Redshift
+Airbyte writes data into two schemas, whichever schema you want your data to land in, e.g. `my_schema`
```
Comment (edgao) [inline docs/integrations/destinations/redshift.md:99]: probably should clarify that this is specific to dv2 since that hasn't gone GA yet

**Review by edgao — APPROVED** [review]
mostly nits. curious what you think about overriding `check` directly vs exposing the method in the base class. lgtm otherwise

**Comment by jbfbell** [comment]
> mostly nits. curious what you think about overriding `check` directly vs exposing the method in the base class. lgtm otherwise

@edgao opted to not override check because of the connection and exception handling already present. I wanted the additional checks to run inside of all that without duplicating, I think overriding the check method I would have to something more sequential like
```
super.check()
try {
additionalChecks()
} catch (Exception e) {
...
}
finally {
close()
}
```

File: airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/util/RedshiftUtil.java (hunk 3 above)
Comment (jbfbell) [reply airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/util/RedshiftUtil.java:44]: :doh: copy pasta, thank you

**Comment by edgao** [comment]
makes sense! :shipit:

File: docs/integrations/destinations/redshift.md (hunk 4 above)
Comment (jbfbell) [reply docs/integrations/destinations/redshift.md:99]: 🤷 I think I'd rather just let this go into the GA release, or I'd be ok with the astute reader giving us slightly too many permissions that sets them up for success migrating to v2

**Comment by gisripa** [comment]
Rebase from master, Now redshift uses everything from CDK (no TD project dependency) .

File: airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/operations/RedshiftS3StagingSqlOperations.java (hunk 2 above)
Comment (jbfbell) [reply airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/operations/RedshiftS3StagingSqlOperations.java:62]: Looked into this today and it is not used anywhere meaningful, removing it
image
