### PR TITLE
Destination Postgres - fix tests

### LINKED ISSUE #33459: Use latest CDK in postgres destination
Adapt the postgres destination to the new CDK interfaces and consumer building.

### LINKED ISSUE #33466: Make postgres main running successful tests (current baseline)

### PR DESCRIPTION
**Pull request by gisripa**
## What
Closes: #33459 
Closes: #33466 
Fix postgres destination tests.

## How
* Port changes to newer CDK.
* Fix postgres test containers setup and DRY the tests.
* There should be no functional changes, only making tests green. 

Depends on cdk publish #33506 

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java [hunk 1]
```diff
@@ -19,10 +19,11 @@
 public class PostgresTestDatabase extends
     TestDatabase<PostgreSQLContainer<?>, PostgresTestDatabase, PostgresTestDatabase.PostgresConfigBuilder> {
 
-  public static enum BaseImage {
```
Comment (stephane-airbyte) [inline airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java:22]: why are you making this non static ?

File: airbyte-integrations/connectors/destination-postgres/build.gradle [hunk 2]
```diff
@@ -28,8 +28,21 @@ application {
...
+    implementation project(':airbyte-cdk:java:airbyte-cdk:typing-deduping')
 
     testImplementation libs.testcontainers.postgresql
 
     integrationTestJavaImplementation libs.testcontainers.postgresql
+
+    integrationTestJavaImplementation testFixtures(project(':airbyte-cdk:java:airbyte-cdk:typing-deduping'))
+    //TODO: Needs dependency on source-postgres testFixtures for PostgresContainerFactory & PostgresDatabase.
+    // Move it to common module in cdk ?
+    integrationTestJavaImplementation testFixtures(project(':airbyte-integrations:connectors:source-postgres'))
```
Comment (stephane-airbyte) [inline airbyte-integrations/connectors/destination-postgres/build.gradle:41]: please don't make a destination connector depend on a source connector. There's already way too much coupling in our codebase

File: airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java (hunk 1 above)
Comment (gisripa) [reply airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java:22]: Intellij auto fix, nested static is redundant is for enum.

File: airbyte-integrations/connectors/destination-postgres/build.gradle (hunk 2 above)
Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/build.gradle:41]: @stephane-airbyte  Thanks for taking a look, I was gonna ask about this today 😅   I'm not too keen on this too but I might have to end up copy pasting the 2 classes that exist in testFixtures into destinations. Do you have any suggestions to pull into common module somwhere ?

Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/build.gradle]: Removed dependency and copied the classes. Will revert source changes

File: airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java (hunk 1 above)
Comment (stephane-airbyte) [reply airbyte-integrations/connectors/source-postgres/src/testFixtures/java/io/airbyte/integrations/source/postgres/PostgresTestDatabase.java:22]: yeah, I didn't realize that it was redundant.

File: airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java [hunk 3]
```diff
@@ -13,4 +15,31 @@ public SshTunnel.TunnelMethod getTunnelMethod() {
     return SshTunnel.TunnelMethod.SSH_PASSWORD_AUTH;
   }
 
+  @Disabled
+  @Override
+  public void testIncrementalDedupeSync() throws Exception {
```
Comment (stephane-airbyte) [inline airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java:20]: instead of doing both the @Disabled and override with an empty test, can you just do the @Disabled and call the super here anyways ?

Comment (stephane-airbyte) [reply airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java:20]: also, do we know why those tests are failing and if they should be fixed? the @Disabled annotation allows for a comment. Ideally, the comment would point to a github issue

Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java:20]: I think the functionality is broken and never tested with sshpass tunnel for Dbt normalizations. That functionality will go away with Destinations v2 so ignoring the tests. Same functionality is tested through ssh key based tunnel which works fine.  I'll add message in disabled with the issue we created to track for later.

Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java:20]: > just do the @disabled and call the super here anyways ?  

I guess. switched to it to see if that correctly disables the test.

File: airbyte-integrations/connectors/destination-postgres/src/testFixtures/java/io/airbyte/integrations/destination/postgres/PostgresContainerFactory.java [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+
+import io.airbyte.cdk.testutils.ContainerFactory;
+import java.io.IOException;
+import java.io.UncheckedIOException;
+import org.testcontainers.containers.Network;
+import org.testcontainers.containers.PostgreSQLContainer;
+import org.testcontainers.utility.DockerImageName;
+import org.testcontainers.utility.MountableFile;
+
+public class PostgresContainerFactory implements ContainerFactory<PostgreSQLContainer<?>> {
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-postgres/src/testFixtures/java/io/airbyte/integrations/destination/postgres/PostgresContainerFactory.java:15]: copying from slack dm - if these classes were copied out of source-postgres, let's add a comment explaining their origin

**Review by edgao — COMMENTED** [review]
you should also update the strict-encrypt version to use the updated cdk! (+metadata.yaml) otherwise this won't get released to cloud

File: airbyte-integrations/connectors/destination-postgres/build.gradle [hunk 5]
```diff
@@ -4,12 +4,12 @@ plugins {
 }
 
 airbyteJavaConnector {
-    cdkVersionRequired = '0.2.0'
+    cdkVersionRequired = '0.7.4'
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-postgres/build.gradle:7]:
```suggestion
    cdkVersionRequired = '0.8.0'
```

File: airbyte-integrations/connectors/destination-postgres/metadata.yaml [hunk 6]
```diff
@@ -1,9 +1,13 @@
 data:
+  ab_internal:
+    ql: 200
+    sl: 100
   connectorSubtype: database
   connectorType: destination
   definitionId: 25c5221d-dce2-4163-ade9-739ef790f503
-  dockerImageTag: 0.4.0
+  dockerImageTag: 0.4.1
```
[the remark this answers is not in the document]
Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/metadata.yaml:8]: Thats fair since Async framework is getting introduced in this. I'll update to minor bump

**Review by edgao — APPROVED** [review]

File: airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java (hunk 3 above)
Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/SshPasswordPostgresDestinationAcceptanceTest.java:19]: Done as suggested. Resolving
