### PR TITLE
14652 source mysql cdc meta fields encoded incorrectly to protobuf

### LINKED ISSUE #66735: BigQuery v3.0.7 destination writes _ab_cdc_deleted_at as '' instead of NULL/timestamp (MySQL CDC source)
### Connector Name

BigQuery

### Connector Version

3.0.7

### What step the error happened?

During the sync

### Relevant information

Using MySQL CDC source (Debezium, ROW + FULL binlog) into BigQuery destination 3.0.7 with CDC deletion mode = Soft delete.
The _ab_cdc_deleted_at field is written as an empty string ('') instead of NULL or a proper timestamp.

on this example the line with null is before i deleted, the line with empty is after i deleted

Image
logs : 
[test__bigquery_destination_3_0_logs_38046_txt.txt](https://github.com/user-attachments/files/22595195/test__bigquery_destination_3_0_logs_38046_txt.txt)

Image
Image

### Relevant log output

```shell

```

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by rodireich**
## What
Among other CDC_* fields, CDC_UPDATED_AT and CDC_DELETED_AT fields are sent as part of CDC snapshot and incremental records.
These two are unique because their catalog definition (AirbyteSchemaType) is a String, but the values they hold are date time.
Json encoding relied on the fact that all dates encode to string in json but in protobuf we encoded these values using `.setTimestampWithTimezone` which prevented destination from pulling the value out of protobuf. Destination relies on the catalog type to know how to decode messages.
We need to ensure that these fields are encoded to protobuf using `.setString` instead in order to match the catalog type definition.

#### Note: The CDK portion of this PR was separated to https://github.com/airbytehq/airbyte/pull/67152. Once the CDK PR is merged this PR will only include connector changes.

*** Please ignore the CDK changes on this PR ***

## How
Updated CDC Meta field type to support a unique type that accepts an `OffsetDateTime` but encodes the value in protobuf as a string.

## User Impact
Users who previously used Mysql CDC in speed mode will need to refresh those streams.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

Resolves https://github.com/airbytehq/airbyte/issues/66735

### CODE REVIEW

**Review by burakku — APPROVED** [review]

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt [hunk 1]
```diff
@@ -148,52 +147,43 @@ class MySqlSourceDebeziumOperations(
...
-            transactionTimestampJsonNode,
-        )
         resultRow[CommonMetaField.CDC_UPDATED_AT.id] =
-            FieldValueEncoder(transactionOffsetDateTime, OffsetDateTimeCodec)
+            FieldValueEncoder(
+                transactionOffsetDateTime,
+                CommonMetaField.CDC_UPDATED_AT.type.jsonEncoder as JsonEncoder<Any>
+            )
 
-        data.set<JsonNode>(
```
Comment (mwbayley) [inline airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt:160]: it looks like all of these `data.set` calls were already extraneous?

File: airbyte-integrations/connectors/source-mysql/gradle.properties [hunk 2]
```diff
@@ -1,3 +1,3 @@
 testExecutionConcurrency=1
 JunitMethodExecutionTimeout=5m
-cdkVersion=0.1.28
+cdkVersion=local
```
Comment (mwbayley) [inline airbyte-integrations/connectors/source-mysql/gradle.properties:3]: needs update

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt [hunk 3]
```diff
@@ -86,6 +84,7 @@ class MySqlSourceDebeziumOperations(
         configuration.incrementalConfiguration as CdcIncrementalConfiguration
     }
 
+    @Suppress("UNCHECKED_CAST")
```
Comment (mwbayley) [inline airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt:87]: The addition of this annotation isn't ideal. I assume it's necessary?

**Review by mwbayley — APPROVED** [review]
LGTM

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt (hunk 3 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt:87]: Yes. It's because FieldValueEncoder has a JsonEncoder<Any> instead of JsonEncoder<*>.
Should be possible to change it but I wasn't able to yet

File: airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt (hunk 1 above)
Comment (rodireich) [reply airbyte-integrations/connectors/source-mysql/src/main/kotlin/io/airbyte/integrations/source/mysql/MySqlSourceDebeziumOperations.kt:160]: Yes. Leftover from pre speed work. It's no longer used for anything

**Comment by rodireich** [comment]
~@davinchia @subodh1810 ~
~I did a final test before this went out but on a mysql <> BQ speed connection the values are still null.~
~[[thread](https://airbytehq-team.slack.com/archives/C08FV1N47PF/p1759864394251269?thread_ts=1759338344.219609&cid=C08FV1N47PF)]~

~As far as I can tell mysql encodes the `_ab_cdc_updated_at` value correctly using `Builder.setString()`~

**Comment by rodireich** [comment]
My bad, 
Full refresh stream are not decorated
