### PR TITLE
check for permissions error on snowflake destinations

### LINKED ISSUE #20343: Snowflake destination: Report access to schema errors as config errors
Looking at the error in this connection attempt: https://cloud.airbyte.io/workspaces/69b7b606-b6e3-44cc-8a9b-0e083c93d204/connections/78e1ace0-d4b9-4d45-962a-5379cc3f5587/status#938512::2

CHECK passed, but right after that, sync failed with:
```
Schema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
```

### PR DESCRIPTION
**Pull request by jbfbell**
## What
Check for known Configuration Issues with the Snowflake Destination for #20343 

## How
Verify the exceptions thrown do not match any of our expected exception scenarios.

## 🚨 User Impact 🚨
For users who walk through the Snowflake Destination setup and select "Mirror Source" ( or any user who doesn't have the permissions properly configured) they will see a configuration error in the UI.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/destination-jdbc/src/test/java/io/airbyte/integrations/destination/jdbc/TestJdbcSqlOperations.java [hunk 1]
```diff
@@ -19,4 +24,17 @@ public void insertRecordsInternal(final JdbcDatabase database,
     // Not required for the testing
   }
 
+  @Test
+  public void testCreateSchemaIfNotExists() {
+    final JdbcDatabase db = Mockito.mock(JdbcDatabase.class);
+    final var schemaName = "foo";
+    try {
+      Mockito.doThrow(new SQLException("TEST")).when(db).execute(Mockito.anyString());
+      createSchemaIfNotExists(db, schemaName);
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-jdbc/src/test/java/io/airbyte/integrations/destination/jdbc/TestJdbcSqlOperations.java:33]: I think there's an `assertThrows` method for this exact situation - currently your test will pass even if this method doesn't throw

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java [hunk 2]
```diff
@@ -73,4 +80,12 @@ protected String generateFilesList(final List<String> files) {
     }
   }
 
+  @Override
+  protected Optional<ConfigErrorException> checkForKnownConfigExceptions(Exception e) {
+    if (e instanceof SnowflakeSQLException && e.getMessage().contains(NO_PRIVILEGES_ERROR_MESSAGE)) {
+      return Optional.of(new ConfigErrorException("Encountered Error with Snowflake Configuration, please verify your privileges", e));
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java:86]: can we be more specific about what permissions are needed? (this is an actual question, I don't know how specific snowflake's error message is)

File: airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java [hunk 3]
```diff
@@ -43,12 +44,27 @@ protected JdbcSqlOperations(final DataAdapter dataAdapter) {
...
   public void createSchemaIfNotExists(final JdbcDatabase database, final String schemaName) throws Exception {
-    if (!schemaSet.contains(schemaName) && !isSchemaExists(database, schemaName)) {
-      database.execute(String.format("CREATE SCHEMA IF NOT EXISTS %s;", schemaName));
-      schemaSet.add(schemaName);
+    try {
+      if (!schemaSet.contains(schemaName) && !isSchemaExists(database, schemaName)) {
+        database.execute(String.format("CREATE SCHEMA IF NOT EXISTS %s;", schemaName));
+        schemaSet.add(schemaName);
+      }
+    } catch (Exception e) {
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java:52]: maybe we should log the original exception here, since it's hard to guarantee that subclasses always handle it correctly? I'm always a bit conflicted about this, since we might end up logging the same exception multiple times

**Review by edgao — APPROVED** [review]
lgtm! a couple minor comments, but only the assertThrows one is really blocking

File: airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java (hunk 3 above)
Comment (jbfbell) [reply airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java:52]: Since the use case hasn't presented itself I'm going to err on the side of inaction and not assume anything just yet. As for now the current behavior will log the original exception and the snowflake subclass will pass along the original exception in the Config Exception

File: airbyte-integrations/connectors/destination-jdbc/src/test/java/io/airbyte/integrations/destination/jdbc/TestJdbcSqlOperations.java (hunk 1 above)
Comment (jbfbell) [reply airbyte-integrations/connectors/destination-jdbc/src/test/java/io/airbyte/integrations/destination/jdbc/TestJdbcSqlOperations.java:33]: Ahh good catch! that's what I was trying to remember

File: airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java (hunk 2 above)
Comment (ryankfu) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java:86]: `+1` to Ed's comment, do we know what are the ways a customer can resolve this 

```
Schema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator.
```

Also, looking at the `SnowflakeSQLException` class, it extends off of `SQLException` which has a method `getSQLState()`, is that something we can more accurately map so this test doesn't become fragile?

Comment (jbfbell) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java:86]: The SQL state was `SQLState = "42710"` but AFAICT this didn't map to anything beside the `SQLComilationError` here's the entire content of the exception 
```
this = {SnowflakeInternalStagingSqlOperations@5796} 
e = {SnowflakeSQLException@5797} "net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:\nSchema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object."
  queryId = "01a9da10-0000-eef5-0000-53b903d214ba"
  retryCount = 0
  issocketTimeoutNoBackoff = false
  elapsedSeconds = 0
  SQLState = "42710"
  vendorCode = 3041
  next = null
  backtrace = {Object[6]@5801} 
  detailMessage = "SQL compilation error:\nSchema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object."
  cause = {SnowflakeSQLException@5797} "net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:\nSchema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object."
  stackTrace = {StackTraceElement[29]@5806} 
  depth = 29
  suppressedExceptions = {Collections$EmptyList@5804}  size = 0
```
I'm open to any thoughts here

Comment (ryankfu) [reply airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java:86]: This is a little tricky since Snowflake has poor documentation on their SQLSTATE codes but it appears a few other DB documentation [Postgres](https://www.postgresql.org/docs/current/errcodes-appendix.html) and [IBM](https://www.ibm.com/docs/en/i/7.3?topic=codes-listing-sqlstate-values) both use `42710` for marking `duplicate object`

I'll leave it up to your discretion, although I _might_ consider if you go with a string check to have it 

```
ACCOUNTADMIN role may be required to manage the privileges on the object.
```

Since if someone were to see that within the code it makes a bit more sense what they _may_ need to do in order to resolve their issue. Granted the usage of the `ConfigErrorException` is for a actionable message for the user to resolve this configuration issue

**Review by ryankfu — APPROVED** [review]
LGTM, pending update of tests to use and potentially any ways you can consider for a less fragile test for `SnowflakeSqlOperations`

```java
assertThrows(Exception.class, () -> executable)
```

**Comment by ryankfu** [comment]
@jbfbell base on [this comment](https://github.com/airbytehq/airbyte/issues/20343#issuecomment-1396285911), it sounds like you followed all the steps that Airbyte documents for getting a user setup with a sync between Postgres <> Snowflake. Since it sounds like this change will only convert the Exception to a `ConfigErrorException`

Were you able to find the steps to mitigate this issue and if so that seems we should update our `snowflake.md` docs, right? From the vantage point of the user, all they know is something fails but this change doesn't alleviate the issue

**Comment by jbfbell** [comment]
> @jbfbell base on [this comment](https://github.com/airbytehq/airbyte/issues/20343#issuecomment-1396285911), it sounds like you followed all the steps that Airbyte documents for getting a user setup with a sync between Postgres <> Snowflake. Since it sounds like this change will only convert the Exception to a `ConfigErrorException`
> 
> Were you able to find the steps to mitigate this issue and if so that seems we should update our `snowflake.md` docs, right? From the vantage point of the user, all they know is something fails but this change doesn't alleviate the issue

@ryankfu I think its only an issue if the user chooses to "mirror source schema" Maybe this is something to address as a part of #20561 ?

**Comment by ryankfu** [comment]
@jbfbell If I'm reading that ticket correctly, it's the true fix to the issue, however, if we're marking an `Exception` as a `ConfigErrorException` this won't get propagated up to our error monitoring tool. The concern is if you were able to follow our instructions and we're no longer going to report this failure then we should at least inform the user what the most probable cause is so they have a way to avoid this failure until the `mirror source schema` issue is resolved

**Comment by jbfbell** [comment]
@ryankfu Added some troubleshooting docs

File: docs/integrations/destinations/snowflake.md [hunk 4]
```diff
@@ -272,6 +272,16 @@ Now that you have set up the Snowflake destination connector, check out the foll
 - [Migrate your data from Redshift to Snowflake](https://airbyte.com/tutorials/redshift-to-snowflake)
 - [Orchestrate ELT pipelines with Prefect, Airbyte and dbt](https://airbyte.com/tutorials/elt-pipeline-prefect-airbyte-dbt)
 
+## Troubleshooting
+
+### 'Current role does not have permissions on the target schema'
+If you receive an error stating `Current role does not have permissions on the target schema` make sure that the 
+Snowflake destination `SCHEMA` is one that the role you've provided has permissions on. When creating a connection,
+it may allow you to select `Mirror source structure` for the `Destination namespace`, which if you have followed
+some of our default examples and tutorials may result in the connection trying to right to a `PUBLIC` schema.
```
Comment (ryankfu) [inline docs/integrations/destinations/snowflake.md:281]: I think this should be `write` instead of `right`

Comment (jbfbell) [reply docs/integrations/destinations/snowflake.md:281]: :doh: good catch
