### PR TITLE
Change Server init conditional

### LINKED ISSUE #3168: Version mismatch between 0.22.0-alpha and 0.22.0-alpha
## Expected Behavior
* Airbyte should boot up normally without error. 

## Current Behavior
* Restarting server running Airbyte version 0.22.0-alpha leads to version mismatch error.

## Logs
```json
{"error":"Version mismatch between 0.22.0-alpha and 0.22.0-alpha.\nPlease upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte"}
```

## Steps to Reproduce
1. Create a VM Google Compute Engine
2. Have the script below as metadata_startup_script. The UI works fine for the first time the instance startup.
3. Reboot the instance and was met with the error above. 

Startup script:
```bash
#! /bin/bash
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add --
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -a -G docker $USER

sudo apt-get -y install wget
sudo wget https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m) -O /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

cd
if [[ ! -e airbyte ]]; then
    git clone https://github.com/airbytehq/airbyte.git
elif [[ ! -d airbyte ]]; then
    echo "airbyte already exists but is not a directory" 1>&2
fi
cd airbyte
docker-compose up -d

EOF
```

## Severity of the bug for you
Critical

## Airbyte Version
0.22.0-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
GCE instance running on Ubuntu 20, e2-medium instance

### PR DESCRIPTION
**Pull request by marcosmarxm**
## What
Resolves #3168.

Steps to reproduce error (airbyte 0.22.0-alpha):
1. docker-compose up 
2. docker-compose down
3. docker-compose up 

Server logs for the second run:
[airbyte-server.log](https://github.com/airbytehq/airbyte/files/6411483/airbyte-server.log)

## How
Change conditional and function `isCompatible` to return true if is compatible.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `ServerApp.java`
1. `AirbyteVersion.java`

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]

File: airbyte-server/src/main/java/io/airbyte/server/ServerApp.java [hunk 1]
```diff
@@ -206,13 +206,14 @@ public static void main(String[] args) throws Exception {
     final JobPersistence jobPersistence = new DefaultJobPersistence(database);
 
     final String airbyteVersion = configs.getAirbyteVersion();
-    final Optional<String> airbyteDatabaseVersion = jobPersistence.getVersion();
-    if (airbyteDatabaseVersion.isEmpty()) {
+    final Optional<String> checkAirbyteInitDBVersion = jobPersistence.getVersion();
+    if (checkAirbyteInitDBVersion.isEmpty()) {
```
Comment (jrhizor) [inline airbyte-server/src/main/java/io/airbyte/server/ServerApp.java:210]:
```suggestion
    if (jobPersistence.getVersion().isEmpty()) {
```

The difference between `checkAirbyteInitDBVersion` and `airbyteDatabaseVersion` would be less confusing if we just inlined here and made `checkAirbyteInitDBVersion` unnecessary.

**Review by jrhizor — APPROVED** [review]
We should try to get this in today and have a point release so people trying out Airbyte don't run into this issue.

**Comment by michel-tricot** [comment]
Thanks @marcosmarxm !
