### PR TITLE
🎉  SAT: fix of stdout reading

### LINKED ISSUE #8746: 🐛  SAT: incorrect reading of container's logs
There is incorrect logic of containers' logs. Some logs can be printed to "stdout" stream and as result Trackback logs can be hidden.

### LINKED ISSUE #8770: SAT test_check Status.Exception failed for airbyte-cdk >= 0.1.41
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Starting from `airbyte-cdk >= 0.1.41` all uncatched exceptions printed as AirbyteLog messages to `stdout` stream.
Current SAT tests still catch this exceptions on `stderr` stream.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by antixar**
## What
 There is incorrect logic of containers' logs. Some logs can be printed to "stdout" stream and as result Trackback logs can be hidden. 

## Fixes
* All containers' logs should be handled
* All containers' logs are provided as generator. (Before logs were available after full loading only)
* Auto-removing of unused docker containers.

### CODE REVIEW

File: airbyte-integrations/bases/source-acceptance-test/scripts/py_script.sh [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+fi
+
+if [ -z ${PY_ACCEPTANCE_FILE} ] && [ ! -z ${PY_UNIT_TESTS_FOLDER} ]; then
+  echo "not found any custom tests..."
+  exit 0
+fi
+
+pip install --quiet flake8
+echo "run flake8...."
+flake8 --exclude=.venv,models,.eggs --extend-ignore=E203,E231,E501,W503 ${CONNECTOR_FOLDER}
```
Comment (keu) [inline airbyte-integrations/bases/source-acceptance-test/scripts/py_script.sh:37]: all configuration should be in project or ini file

File: airbyte-integrations/bases/source-acceptance-test/setup.py [hunk 2]
```diff
@@ -20,6 +20,7 @@
     "dpath~=2.0.1",
     "jsonschema~=3.2.0",
     "jsonref==0.2",
+    "flake8",
```
[the remark this answers is not in the document]
Comment (keu) [reply airbyte-integrations/bases/source-acceptance-test/setup.py:23]: also tools like pylint, flake, black needs to have pinned versions

File: airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py [hunk 3]
```diff
@@ -90,26 +92,59 @@ def call_read_with_state(self, config, catalog, state, **kwargs) -> List[Airbyte
...
-                yield AirbyteMessage.parse_raw(line)
-            except ValidationError as exc:
-                logging.warning("Unable to parse connector's output %s", exc)
+        logging.debug(f"Docker run {self._image}: \n{cmd}\n"
+                      f"input: {self.input_folder}\noutput: {self.output_folder}")
+
+        container = self._client.containers.run(
+            image=self._image, command=cmd,
+            working_dir="/data", volumes=volumes,
+            auto_remove=True, detach=True,
```
Comment (keu) [inline airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py:101]: `detach=True` in past we had issues with parsing output, need to check

File: airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py [hunk 4]
```diff
@@ -90,26 +92,59 @@ def call_read_with_state(self, config, catalog, state, **kwargs) -> List[Airbyte
...
+            else:
+                yield line
+                buffer = buffer[found + 1:]
+        if not has_exception and buffer:
+            yield buffer.decode("utf-8")
+
+        exit_status = container.wait()
+        if exit_status["StatusCode"]:
+            error = buffer.decode("utf-8") or exit_status["Error"]
+            logging.error(f"Docker container was failed, "
```
Comment (keu) [inline airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py:138]: it is not an error

File: airbyte-integrations/bases/source-acceptance-test/scripts/py_script.sh (hunk 1 above)
Comment (antixar) [reply airbyte-integrations/bases/source-acceptance-test/scripts/py_script.sh]: it was unused file. Removed

File: airbyte-integrations/bases/source-acceptance-test/setup.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (antixar) [reply airbyte-integrations/bases/source-acceptance-test/setup.py]: I Agree. using of Python tools will be created misunderstanding. I've removed this. 
But I've saved one new option:  --acceptance-tests
Sometimes we need to run/prepare some additional envs/data for SAT. For instance: the source of S3 needs an active 'minio' server for tests' running.

File: airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py (hunk 4 above)
Comment (antixar) [reply airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py:138]: A buffer includes the latest traceback because  exit_status["Error"] can be some docker error only.
I made this code part more obvious. Please check again

File: airbyte-integrations/bases/source-acceptance-test/setup.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (keu) [reply airbyte-integrations/bases/source-acceptance-test/setup.py]: yes, for this case we have a session-scoped fixture defined in `integration_tests/acceptance.py` in each connector

File: airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/airbyte_entrypoint.py [hunk 5]
```diff
@@ -0,0 +1,132 @@
...
+            command=cmd,
+            volumes=volumes, auto_remove=True
+        )
+        for line in ConnectorRunner.read(container, with_ext=False):
+            print(line)
+        exit_status = container.wait()
+        logger.info(f"Result: {exit_status}")
+        return exit_status["StatusCode"]
+
+    def __build_py_test_image(self, client: DockerClient) -> Image:
```
Comment (keu) [inline airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/airbyte_entrypoint.py:81]: when I look at this function I can't get rid of the feeling that Python is not the right tool for the job

File: airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/input_config.py [hunk 6]
```diff
@@ -0,0 +1,73 @@
+#
```
Comment (keu) [inline airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/input_config.py:1]: I think I don't fully understand what is the purpose of this config and the scripts around it. How do you see the new DX flow?
I think running both - unit and international tests should be easy and use minimal or 0 external toolsets, so `pytest unit_tests` or `pytest integration_tests` should be enough.
SAT is a bit different in this case because it doesn't execute directly but interacts with the docker image via Airbyte protocol.

Comment (keu) [reply airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/input_config.py:1]: the only thing SAT needs is the path to the config file, all paths inside this file will be relative to the config file location. It is not necessary to mean that it is located in the connector source folder or we have a connector source at all. SAT written with the possibility to test any docker image that follows Airbyte protocol, executing as much generic tests as needed to verify that connector follows Aibyty protocol, conventions, and guarantees/promises.

**Comment by antixar** [comment]
@keu ,
I've removed all new enchantments from this PR and saved bugfixes only. Because other PRs are waiting these fixes a lot. I'll create a separate PR this my features.

**Review by keu — APPROVED** [review]
lgtm
