### PR TITLE
Fix cancel button when it doesn't provide feedback to the user + UX improvements

### LINKED ISSUE #12091: The cancel button doesn't seem to work or provide feedback to the user
Current Behavior:
- When a Sync is running, I see a Cancel button. 
- Click the Cancel button.
- Nothing seems to happen

Proposed Behavior:
- Provide some feedback that Airbyte is canceling or attempting to cancel the sync. I imagine it might take some time for the cancelation to complete.
-

### PR DESCRIPTION
**Pull request by dizel852**
## What
Closes [12091](https://github.com/airbytehq/airbyte/issues/12091)
 + Improve UX

## How
+ Add loading state when a user tries to cancel a sync job
+ Add loading state for buttons at Modal window when a user resets the data
+ Disable 'Reset Data' and 'Sync now' buttons if sync is in the 'running' or 'pending' state
+ Show notification message in case of error during async action using useLoadingState

CPT2205041711-1200x533_flow1
CPT2205041714-1207x874_flow2_2
Screenshot at May 10 19-00-19

### CODE REVIEW

File: airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx [hunk 1]
```diff
@@ -69,10 +73,12 @@ const ResetDataModal: React.FC<IProps> = ({ onClose, onSubmit, modalType }) => {
       <Content>
         {modalText()}
         <ButtonContent>
-          <ButtonWithMargin onClick={onClose} secondary>
+          <ButtonWithMargin onClick={onClose} secondary disabled={isLoading}>
             {modalCancelButtonText()}
           </ButtonWithMargin>
-          <Button onClick={onSubmit}>{modalSubmitButtonText()}</Button>
+          <LoadingButton onClick={onSubmitBtnClick} isLoading={isLoading} disabled={isLoading}>
+            {modalSubmitButtonText()}
```
Comment (krishnaglick) [inline airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:80]: Rather than an invoked function within the return, memoizing this value feels like it would be a better option. Or just not making this a function.

Comment (krishnaglick) [inline airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:80]: Rather than an invoked function within the return, memoizing this value feels like it would be a better option. Or just not making this a function.

Comment (krishnaglick) [reply airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:80]: Unsure how others feel about this stylistically.

File: airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx [hunk 2]
```diff
@@ -87,24 +125,8 @@ const StatusView: React.FC<StatusViewProps> = ({ connection, frequencyText }) =>
...
-                    <FormattedMessage id={"sources.syncingNow"} />
-                  ) : (
-                    <>
-                      <TryArrow icon={faRedoAlt} />
-                      <FormattedMessage id={"sources.syncNow"} />
-                    </>
-                  )}
-                </SyncButton>
+                {wrapWithTooltip(resetDataBtn)}
+                {wrapWithTooltip(syncNowBtn)}
```
Comment (krishnaglick) [inline airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx:129]: Again a more stylistic comment:
```
<WithTooltip>
{syncNowBtn}
</WithTooltip>
```
Or just putting all the jsx in the render.

**Review by krishnaglick — COMMENTED** [review]
Just some thoughts on how much we want to lean into js vs jsx!

File: airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx (hunk 1 above)
Comment (dizel852) [reply airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:80]: Yeap, agree. This actually was here before my changes. 
IMO small refactoring should not affect anything. Will update it.

File: airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx (hunk 2 above)
Comment (dizel852) [reply airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx:129]: Ok, sure. This is probably the best solution that we can implement with the current implementation of ToolTip.
I was wondering why we can't control tooltip appearing via props like 
`<ToolTip control={component} show={isAtLeastOneJobRunningOrPending}> ... />`

File: airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx [hunk 3]
```diff
@@ -23,56 +24,61 @@ const ButtonContent = styled.div`
...
-    return <FormattedMessage id="form.resetData" />;
-  };
+  return <FormattedMessage id="form.resetDataText" />;
+};
 
-  const modalCancelButtonText = () => {
-    if (modalType === ModalTypes.UPDATE_SCHEMA) {
-      return <FormattedMessage id="form.cancel" />;
-    }
+const ResetDataModal: React.FC<IProps> = ({ onClose, onSubmit, modalType }) => {
```
Comment (edmundito) [inline airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:46]: We can probably replace this entire modal with the confirmationModalService instead.

File: airbyte-webapp/src/components/JobItem/components/MainInfo.tsx [hunk 4]
```diff
@@ -142,8 +144,14 @@ const MainInfo: React.FC<IProps> = ({
...
-          <CancelButton secondary onClick={onCancelJob}>
-            <FormattedMessage id="form.cancel" />
+          <CancelButton
+            secondary
+            disabled={isLoading}
+            isLoading={isLoading}
+            wasActive={showFeedback}
+            onClick={onCancelJob}
+          >
+            {showFeedback ? <FormattedMessage id="form.canceling" /> : <FormattedMessage id="form.cancel" />}
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:154]: Better to change the value than to have duplicate component render logic
```suggestion
            <FormattedMessage id={showFeedback ? "form.canceling" : "form.cancel"} />}
```

File: airbyte-webapp/src/components/JobItem/components/MainInfo.tsx [hunk 5]
```diff
@@ -97,11 +98,12 @@ const MainInfo: React.FC<IProps> = ({
...
   isPartialSuccess,
 }) => {
+  const { isLoading, showFeedback, startAction } = useLoadingState();
   const cancelJob = useCancelJob();
 
-  const onCancelJob = async (event: React.SyntheticEvent) => {
+  const onCancelJob = (event: React.SyntheticEvent) => {
     event.stopPropagation();
-    return cancelJob(job.id);
+    return startAction({ action: () => cancelJob(job.id) });
```
Comment (edmundito) [inline airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:106]: What happens if canceling fails?

**Review by edmundito — COMMENTED** [review]
Looking good so far. Just had a question and some minor feedback.

File: airbyte-webapp/src/components/JobItem/components/MainInfo.tsx (hunk 5 above)
Comment (dizel852) [reply airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:106]: `Cancel` button will have a loading state until our job switch from `Running` state
Screenshot at May 06 18-24-51

File: airbyte-webapp/src/components/JobItem/components/MainInfo.tsx (hunk 4 above)
Comment (dizel852) [reply airbyte-webapp/src/components/JobItem/components/MainInfo.tsx:154]: Agree, will fix it

File: airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx (hunk 3 above)
Comment (dizel852) [reply airbyte-webapp/src/components/ResetDataModal/ResetDataModal.tsx:46]: Oh, didn't notice that we have a new confirmationModalService. 
Yes, I think we indeed can replace it with this kind of service. 
Thanks for the hint 👍🏻

**Review by krishnaglick — APPROVED** [review]
Pending Edmundo comments, looks good to me. Tested locally, worked.

**Review by edmundito — APPROVED** [review]
Tested confirmation delete modal when navigating away from modified settings

File: airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx [hunk 6]
```diff
@@ -152,9 +161,8 @@ const ConnectionForm: React.FC<ConnectionFormProps> = ({
 
         const requiresReset =
           mode === "edit" && !equal(initialValues.syncCatalog, values.syncCatalog) && !editSchemeMode;
-        if (requiresReset) {
-          setResetModalIsOpen(true);
-        }
+
+        if (requiresReset) openResetDataModal();
```
Comment (krishnaglick) [inline airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx:165]: Nitpick
```suggestion
        if (requiresReset) {
          openResetDataModal();
        }
```

**Review by krishnaglick — COMMENTED** [review]
One minor nitpick, nothing else jumped out at me.

File: airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx (hunk 6 above)
Comment (dizel852) [reply airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx]: Done 
Screenshot at May 10 21-49-57

**Review by krishnaglick — APPROVED** [review]

**Review by krishnaglick — APPROVED** [review]
