### PR TITLE
Source Postgres: Handle Arrays data types

### LINKED ISSUE #15157: JDBC sources: verify handling of arrays data types
In [issue](https://github.com/airbytehq/oncall/issues/351) was raised that postgres source has incorrect schema for array data types. Need to verify jdbc sources if  other sources support Array data types and handle array data types.

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
At the moment, when emitting data of the array type, a json schema is formed that looks like an array without items, and the data is transferred simply as a string. this can lead to incorrect data transfer and also some types of arrays are not implemented at all
```
{
  "type": "array"
}
```
Data type handling should be able to handle all data types that Postgres [supports](https://www.postgresql.org/docs/current/arrays.html)

## How
Updated mapping of all types of arrays for json schema, implemented conversion for СDС and STANDARD replication
Example
```
BIT[]  ==> 
{
  "type": "array",
  "items": {
    "type": "boolean"
  }
}

VARCHAR[] ==>
{
  "type": "array",
  "items": {
    "type": "string"
  }
}
```

## Recommended reading order
1. `JsonSchemaType.java`
2. `PostgresSourceOperations.java`
3. `PostgresConverter.java`

## 🚨 User Impact 🚨
There should not be any user impact

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java [hunk 1]
```diff
@@ -82,4 +89,288 @@ public boolean testCatalog() {
     return true;
   }
 
+  @Override
+  protected void initTests() {
+    super.initTests();
+    addArraysTestData();
+  }
+
+  private void addArraysTestData() {
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java:98]: These tests be added in AbstractPostgresSourceDatatypeTest so that they run for CDC mode as well.

**Review by subodh1810 — CHANGES_REQUESTED** [review]
This behaviour should not be limited to NON-CDC mode. The same behaviour should also be applied to CDC mode

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 2]
```diff
@@ -227,44 +399,162 @@ protected void putTimestamp(final ObjectNode node, final String columnName, fina
...
     return switch (jdbcType) {
       case BOOLEAN -> JsonSchemaType.BOOLEAN;
       case TINYINT, SMALLINT, INTEGER, BIGINT -> JsonSchemaType.INTEGER;
       case FLOAT, DOUBLE, REAL, NUMERIC, DECIMAL -> JsonSchemaType.NUMBER;
       case BLOB, BINARY, VARBINARY, LONGVARBINARY -> JsonSchemaType.STRING_BASE_64;
       case ARRAY -> JsonSchemaType.ARRAY;
+      case BIT_ARRAY -> JsonSchemaType.builder(JsonSchemaPrimitive.ARRAY)
+              .withItems(JsonSchemaType.builder(JsonSchemaPrimitive.BOOLEAN)
+                      .build())
+              .withAirbyteType("bit_array")
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:459]: We shouldn't be defining new `airbyte_type` values like this. Each airbyte_type should represent a primitive type; complex types (such as arrays) should be defined using the jsonschema equivalent, e.g.
```json
{
  "type": "array",
  "items": {
    "type": "string",
    "airbyte_type": "timestamp_with_timezone"
  }
}
```

Note that the top-level JsonSchema (type:array) does _not_ declare airbyte_type; only the nested type does.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+    ROWID(Types.ROWID),
+    NCHAR(Types.NCHAR),
+    NVARCHAR(Types.NVARCHAR),
+    LONGNVARCHAR(Types.LONGNVARCHAR),
+    NCLOB(Types.NCLOB),
+    SQLXML(Types.SQLXML),
+    REF_CURSOR(Types.REF_CURSOR),
+    TIME_WITH_TIMEZONE(Types.TIME_WITH_TIMEZONE),
+    TIMESTAMP_WITH_TIMEZONE(Types.TIMESTAMP_WITH_TIMEZONE),
+    VARCHAR_ARRAY(Types.ARRAY),
```
Comment (edgao) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java:47]: is there any way to avoid these duplicated types? Currently this means that if we later need to add a type, we have to remember to add both `WHATEVER_NEW_TYPE` and `WHATEVER_NEW_TYPE_ARRAY`

also - my understanding is that postgres doesn't support nested arrays, is that correct? I.e. we won't need to support `TEXT_ARRAY_ARRAY`

**Review by edgao — CHANGES_REQUESTED** [review]

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java (hunk 3 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java:47]: > is there any way to avoid these duplicated types? Currently this means that if we later need to add a type, we have to remember to add both `WHATEVER_NEW_TYPE` and `WHATEVER_NEW_TYPE_ARRAY`
> 
> also - my understanding is that postgres doesn't support nested arrays, is that correct? I.e. we won't need to support `TEXT_ARRAY_ARRAY`

no, we don't need to remember that when adding a WHATEVER_NEW_TYPE, we also need to add an array of this type WHATEVER_NEW_TYPE_ARRAY

Postgres supports a limited number of arrays, you can see them [here](https://github.com/pgjdbc/pgjdbc/blob/b73899106949e92e497e3143b24f613cf2f9f203/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L84
)

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 2 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: > We shouldn't be defining new `airbyte_type` values like this. Each airbyte_type should represent a primitive type; complex types (such as arrays) should be defined using the jsonschema equivalent, e.g.
> 
> ```json
> {
>   "type": "array",
>   "items": {
>     "type": "string",
>     "airbyte_type": "timestamp_with_timezone"
>   }
> }
> ```
> 
> Note that the top-level JsonSchema (type:array) does _not_ declare airbyte_type; only the nested type does.

@edgao i have updated json schema mapping

Comment (edgao) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: sorry, to clarify - this is what it should look like:
```java
      case BIT_ARRAY -> JsonSchemaType.builder(JsonSchemaPrimitive.ARRAY)
              .withItems(JsonSchemaType.builder(JsonSchemaPrimitive.BOOLEAN).build())
              .build();
      // (skipping some entries...)
      case INT8_ARRAY -> JsonSchemaType.builder(JsonSchemaPrimitive.ARRAY)
              .withItems(JsonSchemaType.builder(JsonSchemaPrimitive.NUMBER)
                      .withAirbyteType("integer")
                      .build())
              .build();
```

Which is equivalent to these JSON schemas:
```json
{
  "type": "array",
  "items": {
    "type": "boolean"
  }
}
```
```json
{
  "type": "array",
  "items": {
    "type": "number",
    "airbyte_type": "integer"
  }
}
```

The only valid airbyte_type values are the ones already used in JsonSchemaType. Defining new values for them is a protocol change, and would require additional work beyond just this PR (e.g. updating normalization to handle them).

(fyi: airbyte_type is going away, and will be replaced by https://github.com/airbytehq/airbyte/pull/17486. But the basic statement remains the same: we shouldn't define new types without significant discussion)

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java (hunk 1 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostgresSourceDatatypeTest.java]: > These tests should be added in AbstractPostgresSourceDatatypeTest so that they run for CDC mode as well.

updated tests for CDC

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 2 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java]: @edgao updated json schema mapping

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java [hunk 4]
```diff
@@ -0,0 +1,141 @@
+/*
+ * Copyright (c) 2022 Airbyte, Inc., all rights reserved.
+ */
+
+package io.airbyte.integrations.source.postgres;
+
+import java.sql.SQLType;
+import java.sql.Types;
+
+public enum PostgresType implements SQLType {
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java:10]: Am just concerned that if we ever upgrade the JDBC driver, these types might change and now we will have to maintain our own version of all the types and we might miss out on the changes

**Review by subodh1810 — COMMENTED** [review]
I have few questions : 
1. How is the new array type being handled downstream? Specifically are we using the `types` attribute in normalization/destination.
2. The introduction of PostgresType might leave a backdoor open for bugs in case we upgrade the JDBC driver

File: airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java [hunk 5]
```diff
@@ -106,6 +138,65 @@ private void registerText(final RelationalColumn field, final ConverterRegistrat
...
+    }
+    switch (fieldType) {
+      case "_MONEY":
+
+        final String nativeMoneyValue = ((PgArray) x).toString();
+        final String substringM = Objects.requireNonNull(nativeMoneyValue).substring(1, nativeMoneyValue.length() - 1);
+        final char currency = substringM.charAt(0);
+        final String regex = "\\" + currency;
+        List<String> myListM = new ArrayList<>(Arrays.asList(substringM.split(regex)));
+        return myListM.stream()
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:160]: > am not sure I understand why we are doing this replace all, can you add a comment explaining why this is required.

conversion from pgarray happens incorrectly and the _Failed to convert PgArray:org.postgresql.util.PSQLException: Bad value for type double : $999.99"_ exception is thrown, so for money array I made a tricky conversion
Data in pgarray looks something like this {$999.99,\"$1,001.01\",\"$45,000.00\",$1.00,$800.00,\"$22,222.01\",\"$1,001.01\"}
In order to correctly convert them to double, I first split by the currency  sign, and then remove all unnecessary characters (commas, quotes, etc.), except for numbers and dots, and as a result we get the correct double array
{999.99,1001.01,45000.00,1.00,800.00,22222.01,1001.01}

File: airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java [hunk 6]
```diff
@@ -23,6 +23,7 @@ public class JsonSchemaType {
   public static final String CONTENT_ENCODING = "contentEncoding";
   public static final String BASE_64 = "base64";
   public static final String AIRBYTE_TYPE = "airbyte_type";
+  public static final String ITEMS = "items";
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java:26]: > I dont understand where this items parameter is being used?

in Builder

```
    public Builder withItems(final JsonSchemaType items) {
      typeMapBuilder.put(ITEMS, items.getJsonSchemaTypeMap());
      return this;
    }
```

File: airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java [hunk 7]
```diff
@@ -106,6 +138,65 @@ private void registerText(final RelationalColumn field, final ConverterRegistrat
...
+        return Arrays.stream(values).map(value -> value == null ? null : Double.valueOf(value.toString())).collect(Collectors.toList());
+      case "_TIME":
+        return Arrays.stream(values).map(value -> value == null ? null : convertToTime(value)).collect(Collectors.toList());
+      case "_DATE":
+        return Arrays.stream(values).map(value -> value == null ? null : convertToDate(value)).collect(Collectors.toList());
+      case "_TIMESTAMP":
+        return Arrays.stream(values).map(value -> value == null ? null : convertToTimestamp(value)).collect(Collectors.toList());
+      case "_TIMESTAMPTZ":
+        return Arrays.stream(values).map(value -> value == null ? null : convertToTimestampWithTimezone(value)).collect(Collectors.toList());
+      case "_TIMETZ":
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:176]: > Why cant we use the `convertToTimeWithTimezone` method just like we are doing for the rest of the types?

debezium handles timetz and timetz [] differently
pgarray returns an array of java.sql.Time and not java.time.OffsetTime while the timezone that uses the customer is lost, so for timetz [] I use a custom implementation to transfer data without losing the timezone

**Comment by VitaliiMaltsev** [comment]
> How is the new array type being handled downstream? Specifically are we using the types attribute in normalization/destination

Seems like normalization can handle array with types
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py#L463

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java (hunk 4 above)
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresType.java:10]: > Am just concerned that if we ever upgrade the JDBC driver, these types might change and now we will have to maintain our own version of all the types and we might miss out on the changes

@subodh1810 very good point. At the moment, the postgres source in master branch uses JDBCType, which is included in the java.sql package, so even now we cannot handle all the data types that postgres has. When updating the jdbc driver, the postgres data types may change and we still won’t be able to map them to JDBCType correctly
PostgresType is just copy-paste JDBCType + postgres arrays

I didn't find any other way to add new data types other than adding PostgresType as JDBCType is generic for most databases and doesn't support any custom types
Do you have any advice on how to map custom postgres data types?

**Review by edgao — COMMENTED** [review]
LGTM from data types design POV. Will defer to Subodh on actual implementation.

File: airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (subodh1810) [reply airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java:26]: I meant will this be used in downstream in normalization?

@edgao ^

**Review by subodh1810 — COMMENTED** [review]
We are almost there! @edgao can you clarify how the new `items` attribute in the json schema will be used downstream?

File: airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java:26]: normalization has handling for arrays, and respects the `items` parameter https://github.com/airbytehq/airbyte/blob/022fca824f0cd018c0f48fb6ec2fe3526317f331/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py#L368

[the remark this answers is not in the document]
Comment (edgao) [reply airbyte-protocol/protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemaType.java:26]: there's probably work in specific destinations (e.g. destination-s3 avro doesn't seem to handle arrays at all). But the worst case is that we just stringify the array, so this change shouldn't break anything.

File: airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/bases/debezium-v1-9-6/src/main/java/io/airbyte/integrations/debezium/internals/PostgresConverter.java:179]: > Let's add this logic to method convertToTimeWithTimezone in class DateTimeConverter and add a condition like

> if (time instanceof final java.sql.Time timetz) then do what you are doing

@subodh1810 the approach of converting to  java.sql.Time is not entirely correct, because in this case we lose information about the time zone. That's why I refused to use it.
In my implementation, just java.lang.String is used and we shouldn't add this implementation in DateTimeConverter.convertToTimeWithTimezone() as it only applies to Debezium and Postgres array processing

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 8]
```diff
@@ -211,6 +233,156 @@ public void setJsonField(final ResultSet resultSet, final int colIndex, final Ob
...
+      if (timestamp == null) {
+        arrayNode.add(NullNode.getInstance());
+      } else {
+        arrayNode.add(DateTimeConverter.convertToTimestamp(timestamp));
+      }
+    }
+    node.set(columnName, arrayNode);
+  }
+
+  private void putTimestampTzArray(ObjectNode node, String columnName, ResultSet resultSet, int colIndex) throws SQLException {
```
[the remark this answers is not in the document]
Comment (VitaliiMaltsev) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:278]: > this got left out

added **final**

**Review by edgao — APPROVED** [review]
lgtm, probably worth waiting for @subodh1810's approval before merging

**Review by subodh1810 — APPROVED** [review]
Sadly we cant get this out until code freeze is lifted
