### PR TITLE
:window: :bug: Fix direct job linking to work with pagination

### LINKED ISSUE #16369: Fix linking directly to jobs with pagination
## What

See slack thread for context: https://airbytehq-team.slack.com/archives/C03088BTMFC/p1662035572680009?thread_ts=1662024825.781549&cid=C03088BTMFC

With the introduction of [pagination in the job list page](https://github.com/airbytehq/airbyte/issues/10323), loading that page now only loads the most recent 25 jobs for the connection, until the user clicks the `Load more` button at the bottom which loads the next 25 and so on.

This means that if someone links directly to a job outside of these first 25 jobs, the UI will only load those first 25, and will not expand the linked job until the user clicks `Load more` enough times to load that job.

## How

The approach we have decided on is to update the list jobs API endpoint to accept a specific job ID to retrieve "up to", which should then return that job and any more recent jobs as well. This way, if someone has linked a specific job, that ID can be passed in and we will be guaranteed to retrieve the right jobs.

This approach is preferred over a frontend-only change to repeatedly request the list jobs endpoint until it finds the right page, as this is slow, complicated, and not a great user experience.

### PR DESCRIPTION
**Pull request by lmossman**
## What
Resolves https://github.com/airbytehq/airbyte/issues/16369

See above linked issue for context. 

## How
This PR solves the problem by utilizing the list job API improvements made in https://github.com/airbytehq/airbyte/pull/16415 to directly fetch the desired list of jobs when a job ID is linked to in the URL. This means that if someone links to a job outside of the first page of jobs, this view will immediately load the necessary number of pages required to include the linked job, as demonstrated in this screen recording:

https://user-images.githubusercontent.com/22731524/189250007-bd0d8bce-f24d-4d73-9bee-3fea2e30f49b.mov

This PR also adds a fallback view for the edge case where someone puts an invalid job ID into the URL, with a link back to the normal sync history:

https://user-images.githubusercontent.com/22731524/189250199-26ec56f5-1100-4646-9117-90bcc98439ce.mov

Lastly, this PR also contains a small fix to utilize the new `totalJobCount` property in the list jobs response, to decide if there are more jobs to load and therefore whether the Load more button should be shown.

## Recommended reading order
1. `StatusView.tsx` - main changes to the sync history view
2. `JobService.tsx` - adding the `includingJobId` to the react-query keys, so that jobs are properly fetched when this is changed
3. The rest are small hopefully self-explanatory changes

## 🚨 User Impact 🚨
Direct job linking should now work as expected again.

### CODE REVIEW

File: airbyte-webapp/src/components/JobItem/JobItem.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const JobItem: React.FC<JobItemProps> = ({ job }) => {
   const didSucceed = didJobSucceed(job);
 
   const onExpand = () => {
-    setIsOpen(!isOpen);
+    setIsOpen((prevIsOpen) => !prevIsOpen);
```
Comment (lmossman) [inline airbyte-webapp/src/components/JobItem/JobItem.tsx:51]: Just updating this to use the best practice of using the arrow function for a change to a state value that depends on itself

File: airbyte-webapp/src/services/job/JobService.tsx [hunk 2]
```diff
@@ -31,13 +32,19 @@ function useGetJobService() {
...
 export const useListJobs = (listParams: JobListRequestBody) => {
   const service = useGetJobService();
-  const result = useQuery(jobsKeys.list(listParams.configId, listParams.pagination), () => service.list(listParams), {
-    refetchInterval: 2500, // every 2,5 seconds,
-    keepPreviousData: true,
-    suspense: true,
-  });
-  // cast to JobWithAttemptsRead[] because (suspense: true) means we will never get undefined
-  return { jobs: result.data?.jobs as JobWithAttemptsRead[], isPreviousData: result.isPreviousData };
+  console.log(`listParams: ${JSON.stringify(listParams)}`);
```
Comment (edmundito) [inline airbyte-webapp/src/services/job/JobService.tsx:35]:
```suggestion
```

File: airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx [hunk 3]
```diff
@@ -170,7 +183,20 @@ const StatusView: React.FC<StatusViewProps> = ({ connection }) => {
...
+          <JobsList jobs={jobs} />
+        ) : linkedJobNotFound ? (
+          <EmptyResource
+            text={<FormattedMessage id="connection.linkedJobNotFound" />}
+            description={
+              <Link to={pathname}>
+                <FormattedMessage id="connection.returnToSyncHistory" />
+              </Link>
+            }
+          />
```
Comment (edmundito) [inline airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx:196]: I wonder if instead of showing this, what if it showed an error notification at the bottom of the screen but still showed the jobs list? I suppose that in this case, the API would need to still return the jobs as usual.

**Review by edmundito — COMMENTED** [review]
Tested locally. The code looks good but had a few comments.

File: airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx (hunk 3 above)
Comment (lmossman) [reply airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx:196]: Yeah that was how I had originally implemented the backend API, but the backend team pushed back on that a bit saying it made the endpoint somewhat confusing to return results even if the specific job ID could not be found (it was basically behaving in two different ways depending on that), which I kind of agreed with. 

I don't expect users to run into this situation very often, since it would require them to manually edit the job ID in the URL, so hopefully having this separate view with a single click to get back to the main job view is not too cumbersome

**Review by edmundito — APPROVED** [review]
