### PR TITLE
🐛Destination-bigquery: added additional verifications to Check method

### LINKED ISSUE #16992: Destination BigQuery: Check should fail if we have insufficient permissions
from https://github.com/airbytehq/oncall/issues/640

destinatoin-bigquery failed with:
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://www.googleapis.com/bigquery/v2/projects/<redacted>
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Access Denied: Dataset <redacted>: Permission bigquery.tables.create denied on dataset <redacted> (or it may not exist).",
    "reason" : "accessDenied"
  } ],
  "message" : "Access Denied: Dataset <redacted>: Permission bigquery.tables.create denied on dataset <redacted> (or it may not exist).",
  "status" : "PERMISSION_DENIED"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:185)
        ... 16 more
```
Normalization also failed:
```
Database Error
  Access Denied: Project <redacted>: User does not have bigquery.datasets.create permission in project <redacted>.,retryable=<null>,timestamp=1663764411243
```

### PR DESCRIPTION
**Pull request by etsybaev**
## What
The check stage sometimes may pass the verification but then fail on sync.

## How
Updated check stage -  added additional verifications

Tested locally:
Selection_051

Test with valid creds
Selection_052

Test with valid GCS creds

Selection_053

## 🚨 User Impact 🚨
Existing users shouldn't be affected

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by grishick** [comment]
@akashkulk could you please check if this change will report the error in the way that aligns with what you are working on for  sources and that errors will be reported as config errors?

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java [hunk 1]
```diff
@@ -115,6 +116,20 @@ public static void createDataset(final BigQuery bigquery, final String datasetId
     }
   }
 
+  public static void checkHasCreateAndDeleteDatasetRole(final BigQuery bigquery, final String datasetId, final String datasetLocation) {
```
Comment (akashkulk) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java:119]: There has been a push to make error messages more descriptive and actionable. I have a PR out here https://github.com/airbytehq/airbyte/pull/18560 that will change handling config errors. TLDR once that PR is in the change to made is:
- throw a ConfigErrorException with the message you'd like to show to the user if this check fails

If this is more urgent and can't wait for that PR, then at the very least populate the message assc with the ``AirbyteConnectionStatus`` with a relevant message.

**Review by akashkulk — CHANGES_REQUESTED** [review]

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 2]
```diff
@@ -235,6 +237,40 @@ void testCheckFailure(final DatasetIdResetter resetDatasetId) {
     assertEquals(expected, actual.withMessage(""));
   }
 
+  @ParameterizedTest
+  @MethodSource("datasetIdResetterProvider")
+  void testCheckFailureInsufficientPermissionForCreateDataset(final DatasetIdResetter resetDatasetId) throws IOException {
+
+    if (!Files.exists(CREDENTIALS_WITHMISSED_CREATE_DATASET_ROLE_PATH)) {
```
Comment (ryankfu) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:244]: I see this occurring in other parts of the code, what exactly is this supposed to do that is causing a test to throw an `IllegalStateException`?

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java (hunk 1 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java:119]: Hi @akashkulk. It's ok, I think I may wait. Can I ask you to ping me please when you're done with your changes?

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java (hunk 2 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:244]: This it a test creds that supposed to fail.
I will fail on CI if somebody removes or change secret in GSM or to somebody, who will try to run integrationTest locally without having these creds locally in secret folder. This is a common integration test's approach for connectors that calls real DB  i.e. requires real creds that obviously can't be committed.

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 3]
```diff
@@ -235,6 +237,40 @@ void testCheckFailure(final DatasetIdResetter resetDatasetId) {
...
+      throw new IllegalStateException(
+          "Must provide path to a big query credentials file. By default {module-root}/config/credentialsWithMissedDatasetCreationRole.json. "
```
Comment (etsybaev) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:246]: TODO update path to file MSG

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java:119]: @etsybaev I have merged PR: https://github.com/airbytehq/airbyte/pull/18989 which should unblock you. You can throw a ConfigErrorException here

Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryUtils.java:119]: Updated this PR, thanks

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java [hunk 4]
```diff
@@ -86,28 +87,27 @@ public AirbyteConnectionStatus check(final JsonNode config) {
...
-        }
+        checkGcsPermission(config);
       }
 
       final ImmutablePair<Job, String> result = BigQueryUtils.executeQuery(bigquery, queryConfig);
       if (result.getLeft() != null) {
         return new AirbyteConnectionStatus().withStatus(Status.SUCCEEDED);
       } else {
-        return new AirbyteConnectionStatus().withStatus(Status.FAILED).withMessage(result.getRight());
+        throw new ConfigErrorException(result.getRight());
```
Comment (akashkulk) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java:106]: Config errors should be something that can be readable/informative for the user. Is this readable for the user?

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 5]
```diff
@@ -227,12 +230,53 @@ void testCheckSuccess(final DatasetIdResetter resetDatasetId) {
   void testCheckFailure(final DatasetIdResetter resetDatasetId) {
     ((ObjectNode) config).put(BigQueryConsts.CONFIG_PROJECT_ID, "fake");
     resetDatasetId.accept(config);
-    final AirbyteConnectionStatus actual = new BigQueryDestination().check(config);
-    final String actualMessage = actual.getMessage();
+
+    // Assert that check throws exception. Later it will be handled by IntegrationRunner
+    final Exception ex = assertThrows(RuntimeException.class, () -> {
```
Comment (akashkulk) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:235]: can you specifically test for ConfigErrorException here?

**Comment by akashkulk** [comment]
Minor comments from my end - looks good, just update that one test. Will let @ryankfu do the rest of the review

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java (hunk 4 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java:106]: Yup, the BigQuery SDK provides a clear response. I did nothing but just adopted a way how will be handled to follow the new approach. Basically, this is even not a part of my PR or ticket :)  It already was there before I started working on my ticket

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java (hunk 5 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java]: Updated, thanks

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java [hunk 6]
```diff
@@ -149,11 +149,7 @@ public AirbyteConnectionStatus checkGcsPermission(final JsonNode config) {
       message.append(" Please make sure the service account can access the bucket path, and the HMAC keys are correct.");
 
       LOGGER.error(message.toString(), e);
-
-      return new AirbyteConnectionStatus()
-          .withStatus(AirbyteConnectionStatus.Status.FAILED)
-          .withMessage("Could access the GCS bucket with the provided configuration.\n" + e
-              .getMessage());
+      throw new ConfigErrorException("Could access the GCS bucket with the provided configuration.\n", e);
```
Comment (ryankfu) [inline airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java:152]: It seems this message should be "Could **not** access the GCS bucket with the provided configuration.\n", right because we're saying that it failed

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 7]
```diff
@@ -72,6 +74,8 @@
 class BigQueryDestinationTest {
 
   protected static final Path CREDENTIALS_PATH = Path.of("secrets/credentials.json");
+  protected static final Path CREDENTIALS_WITHMISSED_CREATE_DATASET_ROLE_PATH =
```
Comment (ryankfu) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:77]: Missing an `_` between with and missed

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 8]
```diff
@@ -227,12 +231,53 @@ void testCheckSuccess(final DatasetIdResetter resetDatasetId) {
...
-    final AirbyteConnectionStatus actual = new BigQueryDestination().check(config);
-    final String actualMessage = actual.getMessage();
+
+    // Assert that check throws exception. Later it will be handled by IntegrationRunner
+    final ConfigErrorException ex = assertThrows(ConfigErrorException.class, () -> {
+      new BigQueryDestination().check(config);
+    });
+
+    final String actualMessage = ex.getMessage();
+    LOGGER.info("Checking expected failure message:" + actualMessage);
```
Comment (ryankfu) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:241]: Not sure if this `LOGGER` is needed. To keep the test simpler, may suggest just having this as 

```java
assertThat(ex.getMessage()).contains("Access Denied");
```

cc: @ChristopheDuong is there any reason we may want to keep this `LOGGER.info`?

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java [hunk 9]
```diff
@@ -227,12 +231,53 @@ void testCheckSuccess(final DatasetIdResetter resetDatasetId) {
...
+      new BigQueryDestination().check(insufficientRoleConfig);
+    });
+
+    final String actualMessage = ex.getMessage();
     LOGGER.info("Checking expected failure message:" + actualMessage);
-    assertTrue(actualMessage.contains("Access Denied:"));
-    final AirbyteConnectionStatus expected = new AirbyteConnectionStatus().withStatus(Status.FAILED).withMessage("");
-    assertEquals(expected, actual.withMessage(""));
+    assertThat(actualMessage)
+        .contains("Project dataline-integration-testing: User does not have bigquery.datasets.create permission");
```
Comment (ryankfu) [inline airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:280]: I would probably remove the `dataline-integration-testing:` portion since that's really internal to Airbyte and better to keep this not directly exposed since it provides no value to anybody else

Also same comment as above, if the `LOGGER` class is not needed then this `assertThat` can be simplified into one line

**Review by ryankfu — APPROVED** [review]
Overall looks good, some minor nits with the `checkGcsPermission` message. Lets not provide an odd message but overall after that change it should be good to move forward

**Comment by grishick** [comment]
Looks good. Please address @ryankfu 's comments before publishing and merging.

**Review by akashkulk — APPROVED** [review]

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java (hunk 8 above)
Comment (ChristopheDuong) [reply airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java:241]: > Not sure if this LOGGER is needed. 

probably not? just for surfacing information in the logs

File: airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java (hunk 6 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java]: Hm... Interesting fact, it's been there for already almost half a year. Updated, thanks

File: airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java (hunk 9 above)
Comment (etsybaev) [reply airbyte-integrations/connectors/destination-bigquery/src/test-integration/java/io/airbyte/integrations/destination/bigquery/BigQueryDestinationTest.java]: updated, thanks

**Comment by etsybaev** [comment]
/publish connector=connectors/destination-bigquery-denormalized
