### PR TITLE
Fix bugs in form behavior

### LINKED ISSUE #12328: Default connectors name no longer set
Some recent change broke [this code](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx#L76-L88) from working. When switching connectors when creating a new source/destination the name of the connector should by default be the name of the selected service. We're still running through this method, but it seems to no longer set the name (I suspect it might be related to the recent `dirty` handling changes of the form).

### LINKED ISSUE #13012: Error from a connection check persists when changing the connector type
We currently keep the error around from a check of connection after changing the connector type.

**Expected behavior**: When changing connector types we should reset the full form including the error shown.

https://user-images.githubusercontent.com/877229/169262892-a45627ee-000b-4972-b3bb-89df879ac2f3.mp4

### PR DESCRIPTION
**Pull request by timroes**
## What

Fixes #13012
Fixes #12328

This solves two issues with the form handling:

* The connector specification name will now be used as a name for the actual created connector again.
* Errors from the connection check will no longer persist when changing connector types.

### CODE REVIEW

File: airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx [hunk 1]
```diff
@@ -85,7 +85,11 @@ const SetDefaultName: React.FC = () => {
 
   useEffect(() => {
     if (selectedService) {
-      setFieldValue("name", selectedService.name);
+      setTimeout(() => {
```
Comment (timroes) [inline airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx:88]: :information_source: I'm not entirely sure why this broke, but this seems to be "expected behavior" that this call won't have any effect if it's done while the form is still in it's initial "initialiation" render, in which case it will just take the `initialValues`. I've solved it in this "quick and dirty" way, since I want to open an issue for a larger refactoring of the service form component, that would also solve this issue in a proper way later on.

Comment (edmundito) [reply airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx:85]: Should the effect clear the timeout when the selected service changes?

Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx]: Done

**Review by edmundito — APPROVED** [review]
