### PR TITLE
🪟🐛 Keep refetching debug infos while job is running

### LINKED ISSUE #14244: Log view doesn't auto refresh for running jobs anymore
When viewing a log of a running job we earlier auto refreshed that log automatically. This is currently broken. We should make sure to enable auto-refresh of logs of non-finished jobs again (`get_debug_info` call should run periodically while the log view is open).

### PR DESCRIPTION
**Pull request by timroes**
## What

Fixes https://github.com/airbytehq/airbyte/issues/14244

Before changing the querying infrastructure we used the logs from the `useGetJob` call which auto refreshed after 2.5 seconds. Since the switch to the auto generated client, we use `get_debug_info` for the logs (since the `useGetJob` returns different types). This call wasn't auto refreshing so far.

This PR now makes this call to auto refresh while the job it's fetching debug infos for hasn't been finished less than 2 minutes ago. We need some buffer time, since logs come in for some time even after the job is marked as done.

### CODE REVIEW

File: airbyte-webapp/src/services/job/JobService.tsx [hunk 1]
```diff
@@ -39,11 +39,25 @@ export const useGetJob = (id: number, enabled = true) => {
...
+    refetchInterval: !refetchWhileRunning
+      ? false
+      : (data) => {
+          // If refetchWhileRunning was true, we keep refetching debug info (including logs), while the job is still
+          // running or hasn't ended too long ago. We need some time after the last attempt has stopped, since logs
+          // keep incoming for some time after the job has already been marked as finished.
+          const lastAttemptEndTimestamp = data?.attempts[data.attempts.length - 1].attempt.endedAt;
+          // While no attempt ended timestamp exists yet (i.e. the job is still running) or it hasn't ended
+          // more than 2 minutes (2 * 60 * 1000ms) ago, keep refetching
+          return lastAttemptEndTimestamp && Date.now() - lastAttemptEndTimestamp * 1000 > 2 * 60 * 1000 ? false : 2500;
```
Comment (tealjulia) [inline airbyte-webapp/src/services/job/JobService.tsx:59]: The PR description says 6 minutes, but this looks like 2.  Is one of them incorrect?

Comment (timroes) [reply airbyte-webapp/src/services/job/JobService.tsx:59]: Sorry, forgot to update that :) I created this originally with 6 minutes, but Davin clarified for me, that the log is supposed to be max 1 minute late based on how our log fetching implementation worked, so I felt 2 minutes might be a long enough grace period to make sure.

**Review by teallarson — APPROVED** [review]
