### PR TITLE
🎉 Postgres source: emit state messages more frequently for incremental sync

### LINKED ISSUE #7132: Fail to sync between Postgres DB in increamental-deduped-history mode
## Enviroment
- **Airbyte version**:  0.29.19-alpha
- **OS Version / Instance**: macOS
- **Deployment**:  Docker Desktop
- **Source Connector and version**: Postgres DB on AWS RDS
- **Destination Connector and version**: Postgres DB on AWS RDS
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
I want to sync up about 70GB data from source (Postgres DB A) to destination (Postgres DB B).

I configured the sync mode as 

` increamental-deduced-history
`
Because I want the destination postgres DB to get updated for every add/modify/delete on source when a syncing happens.

However, it failed after syncing about 300k records when a postgres IO error occurs -> retied 2 more times, but still failed to sync all the data. Here are the logs:

[1st-sync-logs-attempt-1.txt](https://github.com/airbytehq/airbyte/files/7367691/1st-sync-logs-attempt-1.txt)
[1st-sync-logs-attempt-2.txt](https://github.com/airbytehq/airbyte/files/7367692/1st-sync-logs-attempt-2.txt)
[1st-sync-logs-attempt-3.txt](https://github.com/airbytehq/airbyte/files/7367693/1st-sync-logs-attempt-3.txt)

Then I manually triggered the sync again, but still got err:

[2nd-sync-10-17-airbyte-logs-attempt-1.txt](https://github.com/airbytehq/airbyte/files/7367699/2nd-sync-10-17-airbyte-logs-attempt-1.txt)

Seems I will always fail to sync now.

## Expected Behavior

It should finish syncing and I should be able to see all source records in destination.

## Logs
Please see complete log from attachment: logs-19-0.txt
[logs-19-0 (1).txt](https://github.com/airbytehq/airbyte/files/7240164/logs-19-0.1.txt)

## Follow up questions
1. What does table_name_scd mean? I saw 3 tables (source db name, temp db name, and db_name_scd) in destination for a table I want to map.

Thank you very much!

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Allow Postgres to emit intermediate state messages for incremental syncs.
- Resolve https://github.com/airbytehq/airbyte/issues/7132.

## How
- Let database connector specify an intermediate state emission frequency.
- If this frequency is > 0, add an "order by" clause to the incremental query, and emit state messages according to this frequency.
- Currently only Postgres is affected. All the other DB connectors do not emit intermediate states. I am limiting this change to Postgres to avoid scope creep. But it should be easy to turn this on for other connectors.

## 🚨 User Impact 🚨
- Postgres incremental syncs will sort the tables by the cursor column.
- Even if an incremental sync fails, some part of the data may be successfully synced to the destination. The next attempt will pick up from where it fails. This should hopefully make failures after long syncs less damaging.

### CODE REVIEW

**Comment by tuliren** [comment]
@subodh1810, I am still working on testing, but can you take a brief review of the overall implementation?

The main changes are:
1. Let database connector specify an intermediate state emission frequency.
2. If this frequency is > 0, add an "order by" clause to the incremental query, and emit state messages according to this frequency.

Currently only Postgres is affected. All the other DB connectors do not emit intermediate states. I am limiting this change to Postgres to avoid scope creep. But it should be easy to turn this on for other connectors.

File: airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java [hunk 1]
```diff
@@ -266,21 +266,26 @@ public AutoCloseableIterator<JsonNode> queryTableIncremental(final JdbcDatabase
...
                   sourceOperations.enquoteIdentifierList(connection, columnNames),
-                  sourceOperations
-                      .getFullyQualifiedTableNameWithQuoting(connection, schemaName, tableName),
-                  sourceOperations.enquoteIdentifier(connection, cursorField));
+                  sourceOperations.getFullyQualifiedTableNameWithQuoting(connection, schemaName, tableName),
+                  quotedCursorField));
+              // if the connector emits intermediate states, the incremental query must be sorted by the cursor
+              // field
+              if (getStateEmissionFrequency() > 0) {
+                sql.append(String.format(" ORDER BY %s ASC", quotedCursorField));
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java:284]: Probably a dumb question but are we sure `ORDER BY %s ASC` would be compatible with all the AbstractJDBC based sources? I assume it should be!

**Review by subodh1810 — COMMENTED** [review]
This makes sense

File: airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java [hunk 2]
```diff
@@ -59,24 +69,36 @@ protected AirbyteMessage computeNext() {
...
-          pair,
-          stateManager.getOriginalCursorField(pair).orElse(null),
-          stateManager.getOriginalCursor(pair).orElse(null),
-          stateManager.getCursorField(pair).orElse(null),
-          stateManager.getCursor(pair).orElse(null));
-      if (stateManager.getCursor(pair).isEmpty()) {
-        LOGGER.warn("Cursor was for stream {} was null. This stream will replicate all records on the next run", pair);
+      if (stateEmissionFrequency > 0 && recordCount % stateEmissionFrequency == 0) {
+        final boolean isFinalState = !messageIterator.hasNext();
+        emitStateMessage(isFinalState);
```
[the remark this answers is not in the document]
Comment (tuliren) [reply airbyte-integrations/connectors/source-relational-db/src/main/java/io/airbyte/integrations/source/relationaldb/StateDecoratingIterator.java:74]: We don't have to. The purpose is to prevent sending the same state message twice if this intermediate message happens to be the last one. Given that it is really simple, I think it's better to do it. In this way, we don't need to worry about this edge case in unit testing.

File: airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java (hunk 1 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java:284]: Good point. This is basic ANSI SQL syntax, so I think all of them should follow it. But I will double check.

**Review by subodh1810 — APPROVED** [review]

**Comment by tuliren** [comment]
Will publish a new version in a separate PR.
