### PR TITLE
report synchronous check/spec/discover failures to JobErrorReporter

### LINKED ISSUE #13857: Report connector check/spec/discover job failures to Sentry
Building on #13336, which sets up reporting of sync job failures, the goal of this ticket is to also report failures from the `check`, `spec`, and `discover` jobs. These jobs do not currently process `AirbyteTraceMessages` nor build a `FailureReason`.

## Implementation

There are two main pieces to this:
1. Getting the `AirbyteTraceMessage` from the output and building up a `FailureReason`
2. Sending that `FailureReason` to the `JobErrorReporter`

### Getting error information
Grabbing the `AirbyteTraceMessage` should be pretty straightforward, as these jobs already look through stdout to determine the job's response. For example, here is how the `DiscoverCatalogWorker` grabs the catalog:

https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-workers/src/main/java/io/airbyte/workers/general/DefaultDiscoverCatalogWorker.java#L60-L63

Similarly, we can also filter and find any `AirbyteTraceMessage` that may be present.

### Sending error information to the JobErrorReporter
We are currently sending these failures to Segment via `track` calls in the `SynchronousSchedulerClient.exectute` method:

https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java#L109-L119

However, we need more information from the job execution to correctly report these failures (e.g. error message info and stacktraces, as found from the `AirbyteTraceMessage`)

Currently, these "Synchronous Jobs" either return the corresponding response directly (e.g. `AirbyteCatalog` for `discover`, `ConnectorSpecification` for `spec`, etc) or throw a `WorkerException` if a non-zero exit code was encountered or no response was found. This means that sending that `FailureReason` back up is kind of tricky.

Two ideas:
1. Change the output of each of these jobs to have a `FailureReason`. This likely looks like a generic class that wraps the current outputs. Because we're changing the output, this has effects on callers of these jobs as well as how the "success" of the job is determined.
2. Add the failure reason to the current `WorkerException` and add it to the `TemporalResponse` so it can be accessed later.

### PR DESCRIPTION
**Pull request by pedroslopez**
## What

Builds on #14715 to send failure reasons for synchronous jobs (check/spec/discover) to the JobErrorReporter (e.g. Sentry)

closes #13857

## How
- Initialize the JobErrorReporter and client in ServerApp (this requires passing some new env vars to the server container)
- Modify the `DefaultSynchronousSchedulerClient` to report `FailureReason`s for relevant jobs to the `JobErrorReporter`, following patterns from tracking jobs (segment)
- Refactor some common logic in JobErrorReporter to be reused when reporting other job types
- Allow a `null` workspace when reporting job failures to support reporting `spec` jobs (as these are not related to a specific workspace)

### CODE REVIEW

File: airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReportingClient.java [hunk 1]
```diff
@@ -16,6 +17,9 @@ public interface JobErrorReportingClient {
   /**
    * Report a job failure reason
    */
-  void reportJobFailureReason(StandardWorkspace workspace, final FailureReason reason, final String dockerImage, Map<String, String> metadata);
+  void reportJobFailureReason(@Nullable StandardWorkspace workspace,
```
Comment (sherifnada) [inline airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReportingClient.java:20]: why is this nullable?

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java [hunk 2]
```diff
@@ -177,4 +189,34 @@ private <T> void track(final UUID jobId,
...
+          (JobCheckConnectionConfig) jobConfig);
+      case DISCOVER_SCHEMA -> jobErrorReporter.reportDiscoverJobFailure(
+          connectorDefinitionId,
+          workspaceId,
+          ((ConnectorJobOutput) jobOutput).getFailureReason(),
+          (JobDiscoverCatalogConfig) jobConfig);
+      case GET_SPEC -> jobErrorReporter.reportSpecJobFailure(
+          ((ConnectorJobOutput) jobOutput).getFailureReason(),
+          (JobGetSpecConfig) jobConfig);
+      default -> throw new IllegalArgumentException(
```
Comment (sherifnada) [inline airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:217]: since this is for reporting, should we instead log rather than throw an exceptoin?

**Review by sherifnada — APPROVED** [review]
I'm not sure why there is a nullable workspace situation, aren't all operations running in the context of a workspace?

File: airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReportingClient.java (hunk 1 above)
Comment (pedroslopez) [reply airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReportingClient.java:20]: We talked about this during sprint demos, but adding here for context:

Because connector specs are cached, they don't really run when setting up a connector for any particular workspace. Instead, this job runs when updating connector versions or adding a new connector where there is no related workspace.

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 2 above)
Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java]: 👍🏻 done in [da903d4](https://github.com/airbytehq/airbyte/pull/14818/commits/da903d43e09f4e97e74a441d6eedf394de0532f2)

**Review by gosusnp — COMMENTED** [review]
Overall looks good to me.
One thing I am wondering is if it makes sense to wrap the configs in some POJO in order to channel more information to the error reporting. If there is no current need for it, we can leave that for later.

Also left a couple of questions for Benoit. This part of the codebase still feels pretty new to me.

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java [hunk 3]
```diff
@@ -106,18 +117,20 @@ public SynchronousResponse<ConnectorSpecification> createGetSpecJob(final String
...
   }
 
   @VisibleForTesting
-  <T, U> SynchronousResponse<T> execute(final ConfigType configType,
-                                        @Nullable final UUID connectorDefinitionId,
-                                        final Function<UUID, TemporalResponse<U>> executor,
-                                        final Function<U, T> outputMapper,
-                                        final UUID workspaceId) {
+  <T, U, V> SynchronousResponse<T> execute(final ConfigType configType,
+                                           final V jobConfig,
```
Comment (gosusnp) [inline airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:129]: @benmoriceau, do you know if there's a risk of leaking secrets? I am not sure where this happens compared to the secret expansion.

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java [hunk 4]
```diff
@@ -55,6 +63,7 @@ public SynchronousResponse<StandardCheckConnectionOutput> createSourceCheckConne
 
     return execute(
         ConfigType.CHECK_CONNECTION_SOURCE,
+        jobCheckConnectionConfig,
         source.getSourceDefinitionId(),
         jobId -> temporalClient.submitCheckConnection(UUID.randomUUID(), 0, jobCheckConnectionConfig),
```
[the remark this answers is not in the document]
Comment (benmoriceau) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:68]: Yes it makes senses:
- Workflow ID are unique in temporal and multiple check connection should be able to run in parallel for the same workspace and even more for the same actor definition.
- When running the check connection, the actor doesn't exist nor the connection so we don't have a id discriminant enough to use instead of a random UUID.
- For the sync and connection manager workflow, we want unicity and we have discriminant ids,

File: airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReporter.java [hunk 5]
```diff
@@ -64,50 +72,156 @@ public JobErrorReporter(final ConfigRepository configRepository,
...
-      metadata.put(FAILURE_ORIGIN_META_KEY, failureOrigin.value());
-      metadata.put(FAILURE_TYPE_META_KEY, failureReason.getFailureType().value());
-
-      try {
+    Exceptions.swallow(() -> {
+      final List<FailureReason> traceMessageFailures = failureSummary.getFailures().stream()
+          .filter(failure -> failure.getMetadata() != null && failure.getMetadata().getAdditionalProperties().containsKey(FROM_TRACE_MESSAGE))
+          .toList();
+
+      final StandardWorkspace workspace = configRepository.getStandardWorkspaceFromConnection(connectionId, true);
```
[the remark this answers is not in the document]
Comment (benmoriceau) [reply airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReporter.java:80]: No the temporal activities are calling the persistence directly.

**Review by benmoriceau — CHANGES_REQUESTED** [review]

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 3 above)
Comment (benmoriceau) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:129]: Somehow my previous comment didn't get publish.

I think that Jimmy is right. We need to call `prepareSecretsForOutput` from the class `JsonSecretsProcessor` before reporting the job config. I wish we can make that automated... 

That's a great catch Jimmy!

Comment (benmoriceau) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:129]: It is impossible to say if it has been sanitize before so it is preferable to sanitize it as close as possible to the print/export.

Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:129]: Interesting! I didn't realize these job configs would contain secrets. However, the configs aren't being sent to the JobErrorReportingClient - we're just using them to get the docker image like so:

https://github.com/airbytehq/airbyte/blob/da903d43e09f4e97e74a441d6eedf394de0532f2/airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReporter.java#L118

If this is still a concern and we don't want the job configs to go anywhere near the JobErrorReporter, then I could change this to instead pass the docker image directly instead of the whole config, since masking secrets requires the connector spec, which I don't know if we have access to.

Comment (gosusnp) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:129]: Even if the current goal is to only get the docker image, it increases the risk since having the object around will be tempting for someone to dump it for more details. I'd be fine passing a sanitized version of the config.

I expect that we will want to add more information through this pipe as time goes. Looking at other comment, `workflowId` would also be a good candidate.
That brings me back to my other question of passing a POJO as a container for debugging/error reporting details.
For example, what about a `record JobDetails(UUID connectionId, UUID workflowId, String dockerImage)` that we could extend later on in order to avoid having to change all the function signatures every time?

File: airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReporter.java [hunk 6]
```diff
@@ -64,50 +72,156 @@ public JobErrorReporter(final ConfigRepository configRepository,
...
-      metadata.put(WORKSPACE_ID_META_KEY, workspace.getWorkspaceId().toString());
-      metadata.put(CONNECTION_ID_META_KEY, connectionId.toString());
-      metadata.put(CONNECTION_URL_META_KEY, connectionUrl);
-      metadata.put(AIRBYTE_VERSION_META_KEY, airbyteVersion);
-      metadata.put(DEPLOYMENT_MODE_META_KEY, deploymentMode.name());
-      metadata.put(FAILURE_ORIGIN_META_KEY, failureOrigin.value());
-      metadata.put(FAILURE_TYPE_META_KEY, failureReason.getFailureType().value());
-
-      try {
+    Exceptions.swallow(() -> {
```
[the remark this answers is not in the document]
Comment (pedroslopez) [reply airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_error_reporter/JobErrorReporter.java:75]: done in [23922a7](https://github.com/airbytehq/airbyte/pull/14818/commits/23922a75dd73f38b675c58e642bf41488410492e)

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java]: I noticed we were generating two UUIDs and using one for segment tracking and generating another for the actual job (even though the UUID generated for segment was being passed), so I updated this logic a bit as part of [833ddcb](https://github.com/airbytehq/airbyte/pull/14818/commits/833ddcb7eaa83ac715b2f109261875fbf7e99d1a) to make sure the same uuid is being used

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 3 above)
Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java]: Nice @gosusnp ! I have implemented this in [833ddcb](https://github.com/airbytehq/airbyte/pull/14818/commits/833ddcb7eaa83ac715b2f109261875fbf7e99d1a), though I had to implement a different POJO for sync jobs as it required something slightly different (e.g. two docker images) here [0de45f8](https://github.com/airbytehq/airbyte/pull/14818/commits/0de45f8448a709bd49c4e6b934ca057c21eb6349). I think this should be more future proof and addresses the concerns about secrets in configs.

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java [hunk 7]
```diff
@@ -62,11 +64,14 @@ public SynchronousResponse<StandardCheckConnectionOutput> createSourceCheckConne
         .withConnectionConfiguration(sourceConfiguration)
         .withDockerImage(dockerImage);
 
+    final UUID jobId = UUID.randomUUID();
+    final ConnectorJobReportingContext jobReportingContext = new ConnectorJobReportingContext(jobId, dockerImage);
```
Comment (gosusnp) [inline airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:68]: I think we are running into one of the oddities due to Temporal. This UUID that is mislabeld as `jobIb` in a lot of functions is actually a `workflowId` from a Temporal point of view.
If we report that as `jobIb`, it might end up being confusing because we have a jobs table with `jobId`s that are actual ints. My understanding is that since we do not always wait for a job to actually be started, we do not have a proper jobId yet.
I think we should track and report them as `workflowId`s to reduce the confusion.

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (gosusnp) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java]: Sounds good, thanks!

File: airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java (hunk 7 above)
Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:68]: Hmm, I opened up the temporal UI to check this out and it seems like this UUID is passed on as a jobId and workflowId is something else:

image

(notice workflowId is a different UUID) - I confirmed the `jobId` is the one being reported to sentry in the current implementation. There do seem to be two "formats" for job Ids though, one is a long used in sync jobs and then there's these UUIDs used in the other synchronous connector jobs (check/spec/discover)

Comment (pedroslopez) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:68]: @benmoriceau any thoughts here RE: jimmy's comments on this actually being a workflow ID?

Comment (benmoriceau) [reply airbyte-scheduler/client/src/main/java/io/airbyte/scheduler/client/DefaultSynchronousSchedulerClient.java:68]: It is not a workflow Id, it is needed to be able to create the s3 bucket that will contain the job logs (see: https://console.cloud.google.com/storage/browser/prod-ab-app-logs/job-logging/workspace?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&project=prod-ab-cloud-proj&supportedpurview=project&prefix=&forceOnObjectsSortingFiltering=false). It says it is a `workspace` folder but it is not, for example if you search for `442761 ` you will find the logs for one attempt of https://cloud.airbyte.io/workspaces/bd7f276c-fb96-46bf-8f3c-53d194add358/connections/547bd37c-1652-45e0-9095-c1663870012d/status.

**Review by benmoriceau — APPROVED** [review]
LGTM, I answered to the comment raised by Jimmy.

**Review by gosusnp — APPROVED** [review]
