### PR TITLE
✨ [source-mssql] skip sql server agent check if EngineEdition == 8

### LINKED ISSUE #20847: Source MSSQL - CDC replication not supported for Azure SQL Managed Instance
## Environment
- **Airbyte version**:  0.40.26
- **OS Version / Instance**: Ubuntu 20.04, Azure VM Standard E8s v3 (8 vcpus, 64 GiB memory)
- **Deployment**: Docker
- **Source Connector and version**: MSSQL 0.4.26
- **Destination Connector and version**: N/A
- **Step where error happened**: Setup new source connection

## Current Behavior
When trying to set up a new source connection to an Azure SQL Managed Instance, if you select "Logical Replication (CDC)" as the "Replication Method" and hit set up source, you will get an exception "Could not connect with provided configuration. Error: Index 0 out of bounds for length 0".

My Azure Managed Instance's database:
- has CDC enabled at the database level
- has CDC enabled on each table
- has snapshot isolation enabled
- has the SQL Server Agent CDC jobs running

Note that "Standard" replication method works fine, it's only when you try to set it up with "Logical Replication (CDC)" that you will see that exception.

## Expected Behavior
The source setup should succeed.

## Logs
[workerlogs.txt](https://github.com/airbytehq/airbyte/files/10290544/workerlogs.txt)

This comment in the MSSQL source connector code points out that the standard SQL Server Agent checks won't work for an Azure Managed Instance: https://github.com/airbytehq/airbyte/blob/e34963c07e8c179fcc605a2246909f4d0c84f113/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java#L306

In an Azure MI, running the query `SELECT status_desc FROM sys.dm_server_services WHERE [servicename] LIKE 'SQL Server Agent%' OR [servicename] LIKE 'SQL Server 代理%'` does not return anything, even if the sql server agent is running. It always returns an empty list, hence the index 0 out of bounds exception.

## Steps to Reproduce
1. Create an Azure SQL Managed Instance and create + populate a database in it
2. Enable CDC and snapshot isolation at the database level, and enable CDC for at least one table
3. In Airbyte, set up a new MSSQL source connection and point it to your Azure SQL Managed Instance, and make sure to select "Logical Replication (CDC)" as the "Replication Method"

## Are you willing to submit a PR?
Not currently.

### PR DESCRIPTION
**Pull request by dwallace0723**
## What
This PR proposes updating the `assertSqlServerAgentRunning` check for the MssqlSource to assume the SQL Server Agent is running when the `EngineEdition` property equals `8`, which represents Azure SQL Managed Instance ([link](https://learn.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver16)). Otherwise, the queries that are run do not return any results on Azure SQL Managed Instance, which leads to this check failing even though the docs clearly state that SQL Server Agent is _always_ running on Azure SQL Managed Instance ([link](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/transact-sql-tsql-differences-sql-server?view=azuresql#sql-server-agent)).

I believe this will also resolve #20847 

## How
Add an additional piece of logic that checks the `EngineEdition` property.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*
No breaking changes. I believe this would be a patch release.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @dwallace0723 were you able to build the image locally and run tests using Azure SQL Managed instance?

**Comment by dwallace0723** [comment]
> Thanks for the contribution @dwallace0723 were you able to build the image locally and run tests using Azure SQL Managed instance?

@marcosmarxm I didn't see instructions for that in the [Code Contirbutions](https://docs.airbyte.com/contributing-to-airbyte/#code-contributions) documentation. Is there existing documentation on which steps to follow to do this?

**Comment by marcosmarxm** [comment]
You can use the `airbyte-ci` https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md

File: airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java [hunk 1]
```diff
@@ -417,18 +417,23 @@ protected void assertCdcSchemaQueryable(final JsonNode config, final JdbcDatabas
...
-        final PreparedStatement ps = connection.prepareStatement(sql);
-        LOGGER.info(String.format("Checking that the SQL Server Agent is running using the query: '%s'", sql));
-        return ps;
-      }, sourceOperations::rowToJson);
-
-      if (!(queryResponse.get(0).get("status_desc").toString().contains("Running"))) {
-        throw new RuntimeException(String.format(
-            "The SQL Server Agent is not running. Current state: '%s'. Please check the documentation on ensuring SQL Server Agent is running.",
-            queryResponse.get(0).get("status_desc").toString()));
+      final Int engineEdition = database.queryInt("SELECT ServerProperty('EngineEdition')");
```
Comment (stephane-airbyte) [inline airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java:420]: Thank you so much for your contribution. Could you just add a comment above your change pointing to https://learn.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver16 so that future editors can quickly see what 8 is and what other values are?

Comment (dwallace0723) [reply airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java:424]: @stephane-airbyte done!

**Comment by dwallace0723** [comment]
@marcosmarxm sorry, I'm still a little confused at exactly which commands I need to run. I've installed the `airbyte-ci` tool, but it isn't clear exactly which commands you'd like me to run.

**Comment by stephane-airbyte** [comment]
@dwallace0723 I think what @marcosmarxm meant is that you can test your changes locally. You can run `airbyte-ci connectors --name source-mssql build` and then execute `./run-ab-platform.sh` from the repo's rood directory. Then, you can create change your mssql source default to "dev", which should pick up your changes

**Comment by dwallace0723** [comment]
> @dwallace0723 I think what @marcosmarxm meant is that you can test your changes locally. You can run `airbyte-ci connectors --name source-mssql build` and then execute `./run-ab-platform.sh` from the repo's rood directory. Then, you can create change your mssql source default to "dev", which should pick up your changes

Yep! thank you for the clarification. Working through that now.

**Comment by dwallace0723** [comment]
@marcosmarxm @stephane-airbyte I was able to build the image locally and successfully connected to Azure SQL managed Instance 🎉

File: airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java [hunk 2]
```diff
@@ -417,18 +417,27 @@ protected void assertCdcSchemaQueryable(final JsonNode config, final JdbcDatabas
...
+      // https://learn.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver16
+      // SQL Server Agent is always running on SQL Managed Instance:
+      // https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/transact-sql-tsql-differences-sql-server?view=azuresql#sql-server-agent
+      final Integer engineEdition = database.queryInt("SELECT ServerProperty('EngineEdition')");
+      if (engineEdition == 8) {
+        LOGGER.info(String.format("SQL Server Agent is assumed to be running when EngineEdition == '%s'", engineEdition));
+      } else {
+        final List<JsonNode> queryResponse = database.queryJsons(connection -> {
+          final String sql =
+              "SELECT status_desc FROM sys.dm_server_services WHERE [servicename] LIKE 'SQL Server Agent%' OR [servicename] LIKE 'SQL Server 代理%' ";
```
Comment (samoor64) [inline airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java:430]: What is this doing `LIKE 'SQL Server 代理%' ?

**Comment by dwallace0723** [comment]
@marcosmarxm @stephane-airbyte could you please advise as to next steps here?

**Comment by stephane-airbyte** [comment]
Yes. Right now we’re fighting our CI and we’re trying to get all the tests
passing. Once we’ve done that, we’ll merge your PR after rebasing it.

---

Stephane GeneixTechnical Support

GitHub <https://github.com/airbytehq/airbyte> | Twitter
<https://twitter.com/AirbyteHQ> | LinkedIn
<https://www.linkedin.com/company/airbytehq/>


We're hiring, come work with me! <https://airbyte.io/careers> [image: 🚀]

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]
