### PR TITLE
🎉 8890 Source MySql: Fix large table issue by fetch size

### LINKED ISSUE #8890: Trying to read a 14GB table fails without reading any rows. It seems to time out after 5 minutes while waiting for query results
## Environment
- Is this your first time deploying Airbyte: No 
- OS Version / Instance: macOS 11.6.1
- Memory / Disk: 16GB / 500GB SSD 
- Deployment: Docker
- Airbyte Version: 0.34.0-alpha
- Source name/version: MySQL 0.4.13 (0.5.0 and 0.5.1 fail the connection test)
- Destination name/version: S3 0.1.16
- Step: On sync 
- Description: Extracting MySQL tables to S3 as parquet files with snappy compression is working for tables as large as 6GB so far, but trying on a 14GB table fails without reading any rows.  It seems to time out after 5 minutes while waiting for query results

## Problems
There are two issues:
1. When using MySQL `0.5.x`, the connection check fails:
    > javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2. When using MySQL `0.4.13`, the connection check passes. However, when the database is relatively large, data sync fails before any row is read.

## Expected Behavior
*Tell us what should happen.*

## Logs
Slack [thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1639681034424500).

### PR DESCRIPTION
**Pull request by suhomud**
## What
The combination of `useCursorFetch=true` and `preparedStatement.setFetchSize(10);` push to use cursor on MySql DB instance side. This leads to consuming DB instance disk memory when we try to fetch more than aware table size. In the test we did table with 1 000 000 records and near 14GB size. The only way to fix this issue was to increase disk memory from 50GB to 65GB.

## How
The other approach will be to use `preparedStatement.setFetchSize(Integer.MIN_VALUE);` It actually just disables client-side caching of the entire response and gives you responses as they arrive as a result it has no affect on the DB

### CODE REVIEW

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java [hunk 1]
```diff
@@ -279,7 +279,7 @@ protected void initTests() {
               .fullSourceDataType(fullSourceType)
               .airbyteType(JsonSchemaType.STRING_TIME_WITHOUT_TIMEZONE)
               // JDBC driver can process only "clock"(00:00:00-23:59:59) values.
-              .addInsertValues("'-22:59:59'", "'23:59:59'", "'00:00:00'")
```
Comment (subodh1810) [inline airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: Why this change?

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlStreamingQueryConfig.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  private static final Logger LOGGER = LoggerFactory.getLogger(MySqlStreamingQueryConfig.class);
+
+  public MySqlStreamingQueryConfig() {
+    super();
+  }
+
+  @Override
+  public void initialize(final Connection connection, final Statement preparedStatement) throws SQLException {
+    connection.setAutoCommit(false);
+    preparedStatement.setFetchSize(Integer.MIN_VALUE);
```
Comment (rodireich) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlStreamingQueryConfig.java:25]: Can you explain this? 
Why is changing fetch size from 10 rows needed?
What is the meaning of putting a negative value (-2^31)

Comment (suhomud) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlStreamingQueryConfig.java:25]: More in the [ticket](https://github.com/airbytehq/airbyte/issues/8890) but in short: 
We have an issue to fetch data when mysql db table has more than 1 000 000 records (approximately).  Because we are using `jdbcUrl.append("?useCursorFetch=true")` and fetch size 10 it loads MySql resources significantly (disk storage and memory). So if instance has enough resources it will lead to a long waiting before the sync start like in this [issue](https://github.com/airbytehq/airbyte/issues/5724) 4-5 hours for 23 355 867 records. In case if instance cannot handle request (in my case it was not enough disk storage 50 GB instance for 14 GB table) it will fail the sync. Also to release instance memory I have to restart the instance.

The `setFetchSize(Integer.MIN_VALUE)` disables client-side caching of the entire response and gives you responses as they arrive there is no round-trip per row required. With this approach the sync starts immediately with any table size and no memory load on db. 

We tested sync between Mysql Source and S3 destination with 1 000 000 record table.
**Fetch size 10**
7 minutes to start the sync and 6 minutes to load 1 GB from table
**Fetch size  Integer.MIN_VALUE**
Start sync immediately and 6 minutes to load 1GB from table

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (suhomud) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: I'm a bit confused why it passed before with a negative date. I'm having: 
`SQLState: S1009, Message: The value '-22:59:59' is an invalid TIME value. JDBC Time objects represent a wall-clock time and not a duration as MySQL treats them. If you are treating this type as a duration, consider retrieving this value as a string and dealing with it according to your requirements.`
`-22:59:59` looks as invalid value for me or should mysql handle it? Could you explain?

**Review by rodireich — APPROVED** [review]

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (grishick) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: I second what Subodh is saying here. The functional change in this PR does not seem related to this test change. However, if this test passes before the functional changes and does not pass after - something is wrong with the functional changes.

**Review by grishick — CHANGES_REQUESTED** [review]

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (suhomud) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: It seems like a bug for me in mysql-connector-java checked (8.0.22 and 8.0.30). 

So if I use `useCursorFetch=true` mysql-connector-java will use `MysqlBinaryValueDecoder` for `MysqlType.FIELD_TYPE_TIME ` which will remove negative value by: 
```
        if (negative) {
            days *= -1;
        } 
```
But if I useCursorFetch=false Decoder will be `MysqlTextValueDecoder` which also has decodeTime method but it did change this transformation twice. First from negative to positive value and then back and in the end it checks if value is negative then throw an Error 🤔 

So what options do we have? 

1. Return useCursorFetch=true in this case mysql will create some tmp tables for selects queries. I did not notice the performance change with useCursorFetch true or false and setFetchSize(Integer.MIN_VALUE). Also open new ticket about removing useCursorFetch
2. Remove test with negative time as for now. But it can leads to issues if someone has a negative time value in db 
3. Try older mysql-connector-java but then we can face some other old issues. 

Not sure what else I can try as for now. Any advice? 

@grishick @subodh1810

Comment (suhomud) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: I pushed [changes](https://github.com/airbytehq/airbyte/pull/17236/commits/ca12f87512b44c2de2a78fc245061aa61fc26b9d). Please have a look 
@grishick @subodh1810

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (grishick) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: Thank you for digging into this. My preference is to Return `useCursorFetch=true ` since you have not seen this affecting performance negatively while using  `setFetchSize(Integer.MIN_VALUE)`. Our test coverage is not exhaustive and so I am more concerned about what other behaviors may change because of switching to `MysqlTextValueDecoder` instead of `MysqlBinaryValueDecoder`.

**Review by grishick — CHANGES_REQUESTED** [review]

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (suhomud) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: @grishick returning useCursorFetch=true is also fine for me since I did not notice performance change or DB resource consuming. I added it back  https://github.com/airbytehq/airbyte/pull/17236/commits/8257491e7d6a2ec912bb6877ee067a4a1afac17d

**Comment by suhomud** [comment]
Seems like integration tests were broken by this PR https://github.com/airbytehq/airbyte/pull/17394

**Review by grishick — APPROVED** [review]

File: airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java (hunk 1 above)
Comment (rtuin) [reply airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/AbstractMySqlSourceDatatypeTest.java:282]: I know this is an old thread but this is the most relevant place I could think of mentioning:
I'm running into an issue with a MySQL TIME type, with the following error:

```
SQLState: S1009, Message: The value '30:00:00' is an invalid TIME value. JDBC Time objects represent a wall-clock time and not a duration as MySQL treats them. If you are treating this type as a duration, consider retrieving this value as a string and dealing with it according to your requirements.
```

This is regardless of `useCursorFetch=true` or `useCursorFetch=false`, happens for both.
I'm currently debugging the issue, but any help or thoughts is most welcome.
