### PR TITLE
Destination Postgres: Fix casing for raw table in T+D query

### LINKED ISSUE #34632: Destination Postgres: Fix T+D query to use lowercased raw tables
Closes: https://github.com/airbytehq/alpha-beta-issues/issues/2819

### PR DESCRIPTION
**Pull request by gisripa**
## What
* Fixes: #34632 

## How
* Change the raw table convention to always use lowercase, since that is the default when created as unquoted identifier.
This still preserves the mixed case identifers in Final tables.

### CODE REVIEW

**Comment by gisripa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/34630?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* `master`
  * **#34533** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/34533?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **#34630** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/34630?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gisripa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java [hunk 1]
```diff
@@ -60,8 +61,28 @@ public class PostgresSqlGenerator extends JdbcSqlGenerator {
       "timestamptz", "timestamp with time zone",
       "timetz", "time with time zone");
 
+  private final NamingConventionTransformer namingTransformer;
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java:64]: nit: make the superclass field `protected` and then delete this field?

(... and then we'd need to release the cdk for this pr, sorry :( )

File: airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java [hunk 2]
```diff
@@ -60,8 +61,28 @@ public class PostgresSqlGenerator extends JdbcSqlGenerator {
...
+    // There is a mismatch between convention used in create table query in SqlOperations vs this.
+    // For postgres specifically, when a create table is issued without a quoted identifier, it will be
+    // converted to lowercase.
+    // To keep it consistent when querying raw table in T+D query, convert it to lowercase.
+    // TODO: This logic should be unified across Raw and final table operations in a single class
+    // operating on a StreamId.
+    return new StreamId(
+        namingTransformer.getNamespace(namespace),
+        namingTransformer.convertStreamName(name),
+        namingTransformer.getNamespace(rawNamespaceOverride),
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java:82]: do we need to lowercase the schema name as well? since I assume it's also not quoted

File: airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresTypingDedupingTest.java [hunk 3]
```diff
@@ -72,4 +80,31 @@ protected JdbcCompatibleSourceOperations<?> getSourceOperations() {
     return new PostgresSqlGeneratorIntegrationTest.PostgresSourceOperations();
   }
 
+  @Test
+  public void testMixedCasedSchema() throws Exception {
```
Comment (edgao) [inline airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresTypingDedupingTest.java:84]: this might be worth having in the base test class

**Review by edgao — APPROVED** [review]
change makes sense. I had a few comments which also increase the scope of this pr :P if they're a lot of work feel free to ignore

File: airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresTypingDedupingTest.java (hunk 3 above)
Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/src/test-integration/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresTypingDedupingTest.java:84]: This I avoided because I don't know how all other destinations behave and might be another whack-a-mole for T+D query changes.

File: airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java (hunk 2 above)
Comment (gisripa) [reply airbyte-integrations/connectors/destination-postgres/src/main/java/io/airbyte/integrations/destination/postgres/typing_deduping/PostgresSqlGenerator.java:82]: I guess, i'll do that for consistency if they provided a mixed case `raw_namespace_override`

**Comment by gisripa** [comment]
### Merge activity

* **Jan 29, 8:25 PM**: @gisripa merged this pull request with [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/34630).
