### PR TITLE
[Source MySQL] : Improvements to schema snapshotting and error handling

### LINKED ISSUE #33107: [Source MySQL] : Failure to get load schema history
There are 2 main groups of errors we are seeing : 

1. Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config[Example](https://cloud.airbyte.com/workspaces/a6b434d5-760d-499c-82cd-e964ffdaa089/connections/d6f7d9e3-91e6-4091-aec6-bfae5828e00b/job-history#6157012::4)

> This happens when reading schema history is timing out and and we are sending an empty schema change file. Consequently, the debezium task fails to start. 

2. Source process exited with non-zero exit code 1 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/cdc-db-history13989736358536046491/dbhistory.dat [Example](https://cloud.airbyte.com/workspaces/5f2293da-e1c1-4bd5-8ccf-8bf6d9f4dffb/connections/d25fe0bc-686f-4368-8607-3c2dfbeffa8a/job-history#6159825::3)

> This happens when reading schema history errors out. In this case, we cannot read the schema history file, and that is what the error is indicating 

In both cases the correct thing to do is : 
1. Fail loud and clear if we fail to get schema history or timeout. Perhaps prompting the user to increase timeout. 
2. Change default minimum timeout by default

### PR DESCRIPTION
**Pull request by akashkulk**
Closes https://github.com/airbytehq/airbyte/issues/33107

### CODE REVIEW

File: airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java [hunk 1]
```diff
@@ -287,6 +288,7 @@ public JsonNode constructInitialDebeziumState(final Properties properties,
     final JsonNode asJson = serialize(offset, schemaHistory);
     LOGGER.info("Initial Debezium state constructed: {}", asJson);
 
+    assert !asJson.get(MysqlCdcStateConstants.MYSQL_DB_HISTORY).asText().isBlank();
```
Comment (postamar) [inline airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java:291]: Do we really want assertions here? Shouldn't we be raising exceptions instead? I doubt that our production code runs with assertions enabled.

File: airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java [hunk 2]
```diff
@@ -255,8 +255,8 @@ public JsonNode constructInitialDebeziumState(final Properties properties,
       while (!publisher.hasClosed()) {
         final ChangeEvent<String, String> event = queue.poll(10, TimeUnit.SECONDS);
         if (event == null) {
-          Duration initialWaitingDuration = Duration.ofMinutes(5L);
-          // If initial waiting seconds is configured and it's greater than 5 minutes, use that value instead
+          Duration initialWaitingDuration = Duration.ofMinutes(10L);
+          // If initial waiting seconds is configured and it's greater than 10 minutes, use that value instead
```
Comment (postamar) [inline airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java:259]: Just curious but why do we impose a minimum value here? Do our users foot-gun themselves by setting them too low otherwise?

**Review by postamar — APPROVED** [review]

File: airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java (hunk 1 above)
Comment (akashkulk) [reply airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java:291]: Ack, will change to exception

File: airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java (hunk 2 above)
Comment (akashkulk) [reply airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java]: Paired with @stephane-airbyte on this. We decided that skipping the timeout and setting the `schema.history.internal.store.only.captured.databases.ddl = true` would reduce the time taken to perform the snapshot

**Review by stephane-airbyte — APPROVED** [review]
