### PR TITLE
Read seeds from YAML files directly

### LINKED ISSUE #5373: Importing configs without connections results in error
## Enviroment
- **Airbyte version**:  example is 0.29.-alpha
- **OS Version / Instance**: MacOS
- **Deployment**: Docker
- **Severity**: Low
- **Step where error happened**: Config ImportAirbyte

## Current Behavior
- When the configs are imported into the system, if the configs do not contain any source or destination connection specification, the import will fail.
- The root cause is [this](https://github.com/airbytehq/airbyte/blob/6f568334736ef1d45cc4066c8c579f362eeefefb/airbyte-server/src/main/java/io/airbyte/server/ConfigDumpImporter.java#L245-L255):

```java
if (configSchema == ConfigSchema.SOURCE_CONNECTION) {
  sourceProcessed[0] = true;
  configs = configs.peek(config -> sourceDefinitionsToMigrate.add(((SourceConnection) config).getSourceDefinitionId().toString()));
} else if (configSchema == ConfigSchema.DESTINATION_CONNECTION) {
  destinationProcessed[0] = true;
  configs = configs.peek(config -> destinationDefinitionsToMigrate.add(((DestinationConnection) config).getDestinationDefinitionId().toString()));
} else if (configSchema == ConfigSchema.STANDARD_SOURCE_DEFINITION) {
  configs = getDefinitionStream(sourceDefinitionsToMigrate, sourceProcessed[0], configSchema, configs, latestSeeds);
} else if (configSchema == ConfigSchema.STANDARD_DESTINATION_DEFINITION) {
  configs = getDefinitionStream(destinationDefinitionsToMigrate, destinationProcessed[0], configSchema, configs, latestSeeds);
}
```

The code always expect there is some source or destination connection. Otherwise, `sourceProcessed` or `destinationProcessed` will be `false`, and lead to an exception [later on](https://github.com/airbytehq/airbyte/blob/6f568334736ef1d45cc4066c8c579f362eeefefb/airbyte-server/src/main/java/io/airbyte/server/ConfigDumpImporter.java#L269-L271):

```java
if (!definitionsPopulated) {
  throw new RuntimeException("Trying to process " + configSchema + " without populating the definitions to migrate");
}
```

To patch it, we can mark `sourceProcessed` or `destinationProcessed` as `true` when the source connection or destination connection stream is empty, respectively.

## Expected Behavior
- Users can import configs even if there is no source or destination connection specification.

## Steps to Reproduce
1. Launch a new Airbyte instance.
2. Export the configs.
3. Import the configs.

## Are you willing to submit a PR?
Yes.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- This is the first PR for airbytehq/airbyte#4890.
  - This PR does not remove the config volume.
  - This PR does not mount the directories for the local connectors.
- Resolves airbytehq/airbyte#5373.

## How
-  Previously the seed container copies the configs to the storage root, it may take some time for the operation to complete and for the `CONFIG_DIR` to show up. So we cannot infer anything based on the existence of this directory. Now this seed generation step has been removed. So we can tell immediately whether `CONFIG_DIR` exists or not.
  - If `CONFIG_DIR` exists, it means the user has just migrated Airbyte from an old version that uses this file system config persistence.
  - Otherwise, we can seed the config persistence from the YAML files.

## Recommended reading order
- `ConfigDumpImporter.java`.
- `ConfigPersistenceBuilder.java` and `FileSystemConfigPersistence.java`.
- The rest.

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/ConfigDumpImporter.java [hunk 1]
```diff
@@ -186,93 +185,87 @@ private void checkImport(String targetVersion, Path tempFolder, Path seed) throw
 
       final ConfigSchema configSchema = configSchemaOptional.get();
       Stream<T> configs = readConfigsFromArchive(sourceRoot, configSchema);
+
+      // If there is no source or destination connection, mark them as processed respectively.
+      if (configSchema == ConfigSchema.STANDARD_SOURCE_DEFINITION && !data.containsKey(ConfigSchema.SOURCE_CONNECTION)) {
+        sourceProcessed[0] = true;
+      } else if (configSchema == ConfigSchema.STANDARD_DESTINATION_DEFINITION && !data.containsKey(ConfigSchema.DESTINATION_CONNECTION)) {
+        destinationProcessed[0] = true;
+      }
```
Comment (tuliren) [inline airbyte-server/src/main/java/io/airbyte/server/ConfigDumpImporter.java:194]: This is the bug fix for #5373.

File: airbyte-config/init/build.gradle [hunk 2]
```diff
@@ -7,42 +7,3 @@ dependencies {
 
     implementation project(':airbyte-config:models')
 }
-
-// generate seed for each yaml file.
-task generateSeed {
```
Comment (cgardens) [inline airbyte-config/init/build.gradle:12]: removing the configs in `airbyte-config/init/src/main/resources/config/` is going to break old versions of airbyte. This is annoying because it breaks them in such a way that means the user has to run the manual upgrade process. just a heads up. this is a bandaid we need to rip off eventually though. 

@jrhizor @sherifnada opinions on how when we should do this?

Comment (cgardens) [reply airbyte-config/init/build.gradle:12]: If we do it now, we need to document for users of old versions how they can get back into a working state with the manual upgrade process.

File: airbyte-config/persistence/src/main/java/io/airbyte/config/persistence/FileSystemConfigPersistence.java [hunk 3]
```diff
@@ -58,18 +59,25 @@
...
-    while (!Files.exists(configRoot)) {
-      LOGGER.warn("Config volume is not ready yet (waiting time: {} s)", totalWaitingSeconds);
-      Thread.sleep(INTERVAL_WAITING_SECONDS * 1000);
-      totalWaitingSeconds += INTERVAL_WAITING_SECONDS;
+  /**
+   * Check if there are existing configs under the storage root. Previously the seed container copies
+   * the configs to the storage root, it may take some time for the operation to complete and for the
+   * CONFIG_DIR to show up. So we cannot infer anything based on the existence of this directory. Now
+   * this seed generation step has been removed. So we can tell immediately whether CONFIG_DIR exists
+   * or not. If CONFIG_DIR exists, it means the user has just migrated Airbyte from an old version
```
Comment (cgardens) [inline airbyte-config/persistence/src/main/java/io/airbyte/config/persistence/FileSystemConfigPersistence.java:67]: how do we know they "just" migrated? does the directory get deleted?

**Review by cgardens — CHANGES_REQUESTED** [review]
This looks great. Thank you!

I'm doing request changes, because there is one backwards incompatible thing here that we need to make a decision on before merging (see comment below). Once that is resolved it is an approve.

File: airbyte-config/init/build.gradle (hunk 2 above)
Comment (tuliren) [reply airbyte-config/init/build.gradle:12]: Do you mean an old Airbyte version looks for configs on GitHub? In that case, we can keep this directory. Is it a problem if these configs stay stale since the `generateSeed` task is removed and they will never be updated?

File: airbyte-config/persistence/src/main/java/io/airbyte/config/persistence/FileSystemConfigPersistence.java (hunk 3 above)
Comment (tuliren) [reply airbyte-config/persistence/src/main/java/io/airbyte/config/persistence/FileSystemConfigPersistence.java:67]: Yes. This config directory will not be created in newer Airbyte versions, as the copy step is removed in `seed.Dockerfile`:

```diff
- COPY build/config_init/resources/main/config seed/config 
```

So only the old users will see it.

File: airbyte-config/init/build.gradle (hunk 2 above)
Comment (cgardens) [reply airbyte-config/init/build.gradle:12]: > Do you mean an old Airbyte version looks for configs on GitHub?

yes

> A follow up question is that will it be a problem if these configs stay stale since the generateSeed task is removed and they will never be updated?

i don't think having stale version for old versions of airbyte are a problem. the old versions are stale too :D

**Review by cgardens — APPROVED** [review]
@tuliren based on our conversation [here](https://github.com/airbytehq/airbyte/pull/5335#discussion_r690175165), it sounds like you are now well aware of the problem with old versions. going to approve so i don't block. if you'd like me to take another pass to look at whatever solution you come up with, lmk and I'm happy to do it.
