### PR TITLE
Repair temporal state when performing manual actions

### LINKED ISSUE #10931: [EPIC] Perform self-healing operations on temporal workflows that are in an unexpected terminal state
## What

Temporal can ends in a state where the previous workflow either failed or didn't continue as new because of a bug. This is not an expected state but it can happen. In order to be able to improve the reliability of the temporal workflow, we need to be able to perform operation from this state.
Those operations need to start a new workflow and then send a signal. Temporal provides [helper](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java#L237) for that.

The operation that need to be perform are (They are order by priority, the manual sync, reset and update have the same priority):
- [x] https://github.com/airbytehq/airbyte/issues/11214
  -  Delete: delete the connection (TBD: Cancel all non-terminal running jobs)
- [ ] https://github.com/airbytehq/airbyte/issues/11217
  - Cancel: cancel all the running jobs and the related attempts. Then continue as new.
- [ ] https://github.com/airbytehq/airbyte/issues/11213
  - Manual sync: create a new workflow that won't wait.
- [x] https://github.com/airbytehq/airbyte/issues/11215
  - Update: Start a new workflow as if it was the first run.
- [ ] https://github.com/airbytehq/airbyte/issues/11216
  - Manual reset: Start a new workflow that performs a reset.

## DoD

New signal methods are a implemented and tested to handle the scenario describe in the issue.

### LINKED ISSUE #11213: [Unexpected state] Start manual sync
## Tell us about the problem you're trying to solve

Temporal can be in an unknown state because of a bug. This ticket is about addressing the scenario where no workflow exists and a manual sync is submitted.

This ticket is about implementing [this](https://docs.google.com/document/d/1I_uY1ML087HUwP2s55lOoEVb4DyVXzZZMjRX1WEwaVk/edit#heading=h.ma0thubuo72n) diagram. 

## What is expected

When trying to submit a manual sync, if in the `TemporalClient` we detect that there is no existing temporal workflow, need to:
- Create a new workflow
- Submit a manual sync using a signal

No modification is expected in the `ConnectionManagerWorkflow`.

### LINKED ISSUE #11216: [Unexpected state] Start manual reset
## Tell us about the problem you're trying to solve

Temporal can be in an unknown state because of a bug. This ticket is about addressing the scenario where no workflow exists and a manual reset is submitted.

This ticket is about implementing [this](https://docs.google.com/document/d/1I_uY1ML087HUwP2s55lOoEVb4DyVXzZZMjRX1WEwaVk/edit#heading=h.5bra1f7oarq6) diagram. 

## What is expected

When trying to submit a manual reset, if in the `TemporalClient` we detect that there is no existing temporal workflow, need to:
- Create a new workflow
- Submit a manual reset using a signal

No modification is expected in the `ConnectionManagerWorkflow`.

### LINKED ISSUE #12160: Deleting an already-deleted connection fails with WorkflowNotFoundException
## Current Behavior
When calling `https://cloud.airbyte.io/api/v1/connections/delete` on an already-deleted connection, an Internal Server Error is produced, resulting from a `WorkflowNotFoundException` error coming from the server.

A fix was already attempted for this issue: [this logic](https://github.com/airbytehq/airbyte/blob/f065d361b1c1b2da91d64b6e4c07cf4fc313dc53/airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java#L255-L281) is supposed to check if the workflow exists when deleting the connection, and start it first if it doesn't.

However, it doesn't appear that this logic works, as there have been several OC tickets showing that deleting an already-deleted connection fails: 
https://github.com/airbytehq/oncall/issues/190
https://github.com/airbytehq/oncall/issues/202

Note: this issue is currently exacerbated by the fact that when a connection is _first_ deleted, that delete request is actually successful, but the UI does not change at all to show that the delete was successful. This is what prompts users to try to perform a second delete request on the same connection. [This frontend issue](https://github.com/airbytehq/oncall/issues/195) captures that UI problem, and once solved should greatly reduce occurrences of this problem.

**The main goal of this ticket is to determine why our approach for checking if there is an active temporal workflow for the connection is not working, and fix that if possible.**

## Expected Behavior
Deleting an already-deleted connection should effectively be a no-op.

## Logs
https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-05T15:46:24.624547883Z;query=resource.labels.pod_name%3D%22airbyte-server-bfc448969-k6qfx%22%0Atimestamp%3D%222022-04-05T15:46:24.624547883Z%22%0AinsertId%3D%221xg6kk4raioz4lb1%22;timeRange=2022-04-05T15:46:24.624Z%2F2022-04-05T15:46:24.624Z--PT1H?project=prod-ab-cloud-proj

```
io.temporal.client.WorkflowNotFoundException: workflowId='connection_manager_59b17dae-ca1b-45c7-8d7b-93bae20b8478', runId='', workflowType='ConnectionManagerWorkflow'}
	at io.temporal.internal.sync.WorkflowStubImpl.signal(WorkflowStubImpl.java:98) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.signalWorkflow(WorkflowInvocationHandler.java:297) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:274) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:178) ~[temporal-sdk-1.6.0.jar:?]
	at jdk.proxy3.$Proxy134.deleteConnection(Unknown Source) ~[?:?]
	at io.airbyte.workers.temporal.TemporalClient.deleteConnection(TemporalClient.java:257) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.scheduler.client.TemporalEventRunner.deleteConnection(TemporalEventRunner.java:39) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.server.handlers.ConnectionsHandler.deleteConnection(ConnectionsHandler.java:328) ~[airbyte-server-0.35.64-alpha.jar:?]
	at io.airbyte.server.wrapped.ConfigurationApiWrapped.lambda$deleteConnection$73(ConfigurationApiWrapped.java:834) ~[io.airbyte-cloud-airbyte-server-wrapped-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.lambda$execute$1(AuthHelper.java:181) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.execute(AuthHelper.java:189) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.execute(AuthHelper.java:180) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.runForWorkspace(AuthHelper.java:173) ~[io.airbyte-cloud-cloud-auth-0.35.64-alpha.jar:?]
	at io.airbyte.server.wrapped.ConfigurationApiWrapped.deleteConnection(ConfigurationApiWrapped.java:829) ~[io.airbyte-cloud-airbyte-server-wrapped-0.35.64-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [airbyte-server-0.35.64-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [airbyte-server-0.35.64-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

## Steps to Reproduce
1. Delete a connection
2. Try deleting it again

### PR DESCRIPTION
**Pull request by lmossman**
## What
Resolves https://github.com/airbytehq/airbyte/issues/10931
Resolves https://github.com/airbytehq/airbyte/issues/11216
Resolves https://github.com/airbytehq/airbyte/issues/11213
Resolves https://github.com/airbytehq/airbyte/issues/12160

The main goal of this PR is to fix our interactions with connection manager workflow in the TemporalClient. After some investigation, I found that our TemporalClient was not correctly handling the various states that a workflow can be in.

Namely, if a connection and its workflow have been deleted, the workflow and its state are still retrievable using the WorkflowClient, but signal methods cannot be executed on the workflow because it is in state "Completed" (this was the root cause of [this issue](https://github.com/airbytehq/airbyte/issues/12160)). Separately, if a workflow is terminated, then its state cannot be retrieved at all.
This PR makes both of these cases more explicit through new exceptions, and updates the various manual operation methods to handle these exceptions and attempt to automatically repair workflows that are in bad states.

## How
By refactoring the TemporalClient and using the new `repairAndRetrieveConnectionManagerWorkflow()` method, this PR makes each manual operation correctly handle the deleted case, and automatically repair the workflow in the "unexpected state" case.

The plan is to follow this up with another PR to address the [start from a clean state ticket](https://github.com/airbytehq/airbyte/issues/11217), so that when these automatic workflow repairs are performed, they do not cause any weird issues with job state.
_**I plan to wait to merge this PR until that second PR has been reviewed and merged into this one, at which point they will be merged to master together**, because we should really add both at the same time to be safe._

This PR also renames some classes and methods to be more consistent, and adds more TemporalClient tests.

## Recommended reading order
1. TemporalClient.java
2. TemporalClientTest.java
3. The rest is mostly side effects of refactoring the above

### CODE REVIEW

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java [hunk 1]
```diff
@@ -469,23 +454,61 @@ private <T> T getWorkflowOptionsWithWorkflowId(final Class<T> workflowClass, fin
...
-      throw new IllegalStateException("No reachable workflow for the connection {} while trying to delete it");
+  /**
+   * Attempts to retrieve the connection manager workflow for the provided connection.
+   *
+   * @param connectionId the ID of the connection whose workflow should be retrieved
+   * @return the healthy ConnectionManagerWorkflow
+   * @throws DeletedWorkflowException if the workflow was deleted, according to the workflow state
+   * @throws UnreachableWorkflowException if the workflow is unreachable
+   */
+  private ConnectionManagerWorkflow getConnectionManagerWorkflow(final UUID connectionId)
```
Comment (lmossman) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:465]: This method and the following method are the main changes in this PR - these methods offer the rest of this class a way to retrieve the connection manager workflow while also enforcing that they handle the deleted case and the unreachable workflow case through exceptions. The second method `repairAndRetrieveConnectionManagerWorkflow` handles the unreachable case automatically by automatically restarting the temporal workflow.

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java [hunk 2]
```diff
@@ -512,7 +512,7 @@ private ConnectorSpecification getSpecFromDestinationDefinitionId(final UUID des
   private JobInfoRead createNewSchedulerCancellation(final Long id) throws IOException {
```
Comment (cgardens) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java:512]: name of this class is a bit hard for me to follow. had to go open the class to figure out what it was all about. would `createNewSchedulerCancellation ` => `submitCancellationToWorker` help?

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java [hunk 3]
```diff
@@ -523,25 +523,25 @@ private JobInfoRead createNewSchedulerCancellation(final Long id) throws IOExcep
...
-    if (manualSyncSubmissionResult.getFailingReason().isPresent()) {
-      throw new IllegalStateException(manualSyncSubmissionResult.getFailingReason().get());
+    if (manualOperationResult.getFailingReason().isPresent()) {
+      throw new IllegalStateException(manualOperationResult.getFailingReason().get());
     }
 
-    final Job job = jobPersistence.getJob(manualSyncSubmissionResult.getJobId().get());
+    final Job job = jobPersistence.getJob(manualOperationResult.getJobId().get());
 
     return jobConverter.getJobInfoRead(job);
```
Comment (cgardens) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java:534]: I think this same few lines of code is repeated 3 times. Now that all of the event runners are returning the same `ManualOperationResult`, I think it would be worthwhile to consolidate it down.

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java (hunk 2 above)
Comment (cgardens) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java:512]: If you do change this probably worth doing the same for `createManualRun` => `submitManualSyncToWorker` and `resetConnectionWithNewScheduler` => `submitResetConnectionToWorker`

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java [hunk 4]
```diff
@@ -338,70 +328,58 @@ public ManualSyncSubmissionResult startNewManualSync(final UUID connectionId) {
...
-          Optional.of("No scheduler workflow is reachable for: " + connectionId),
+    final ConnectionManagerWorkflow connectionManagerWorkflow;
+    try {
+      connectionManagerWorkflow = repairAndRetrieveConnectionManagerWorkflow(connectionId);
+    } catch (final DeletedWorkflowException e) {
+      log.error("Can't cancel a deleted workflow");
+      return new ManualOperationResult(
+          Optional.of(e.getMessage()),
           Optional.empty());
     }
```
Comment (cgardens) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:347]: this block of code is repeated a bunch of times in this class (except for the contents of the log message). can we DRY it?

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/exception/DeletedWorkflowException.java [hunk 5]
```diff
@@ -0,0 +1,13 @@
+/*
+ * Copyright (c) 2021 Airbyte, Inc., all rights reserved.
+ */
+
+package io.airbyte.workers.temporal.exception;
+
+public class DeletedWorkflowException extends Exception {
```
Comment (cgardens) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/exception/DeletedWorkflowException.java:7]: maybe helpful for this exception and the other one to add a javadoc comment explaining what they mean and why they might occur.

**Review by cgardens — APPROVED** [review]
Nice! I like this approach alot. Made a couple clean up suggestions but otherwise it looks good!

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java [hunk 6]
```diff
@@ -469,23 +454,61 @@ private <T> T getWorkflowOptionsWithWorkflowId(final Class<T> workflowClass, fin
...
+      workflowState = connectionManagerWorkflow.getState();
+    } catch (final Exception e) {
+      throw new UnreachableWorkflowException(
+          String.format("Failed to retrieve ConnectionManagerWorkflow for connection %s due to the following error:", connectionId),
+          e);
     }
 
-    final ConnectionManagerWorkflow connectionManagerWorkflow =
-        getExistingWorkflow(ConnectionManagerWorkflow.class, getConnectionManagerName(connectionId));
+    if (workflowState.isDeleted()) {
```
Comment (benmoriceau) [inline airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: I don't understand how this block is working. I means than for most of the deleted workflow, we will consider them as Unreachable because the workflow are suppose to be terminated.

Comment (lmossman) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: @benmoriceau One thing I discovered while investigating this issue is that when we delete a connection, the temporal workflow is actually **not** terminated. The temporal workflow in the delete case has status `Completed`, which is a separate status from `Terminated`. For these deleted workflows, we can actually still retrieve the workflow and ready values from its workflowState, but we cannot call any signal methods on the workflow because it is not actively running.

I think the reason the temporal workflow is `Completed` and not `Terminated` in the deletion case is because we just `return` in that case: https://github.com/airbytehq/airbyte/blob/f816946a09a890c553ee42550d86d6b6ed4b231a/airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java#L105-L109
And I think when the `run` method `return`s, temporal marks the workflow as `Completed`

Comment (lmossman) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: So my new understanding is that the "unreachable" case is not ever really expected, which is why we repair the workflow in that case

Comment (benmoriceau) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: I see and for a `Terminated` workflow, I guess we can't query the state.

Comment (lmossman) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: Yep that's correct

Comment (benmoriceau) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:478]: Thank, approved then.

**Comment by benmoriceau** [comment]
> **I plan to wait to merge this PR until that second PR has been reviewed and merged into this one, at which point they will be merged to master together**, because we should really add both at the same time to be safe.

This looks fine to me with this assumption. I have one  more concern about the fact that we are starting the workflow asynchronously is that I am wondering if we should use https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#newSignalWithStartRequest-- and https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#signalWithStart-io.temporal.client.BatchRequest- to ensure that there won't be any race condition between the workflow being accessible and the signal being send after a restart.

**Comment by lmossman** [comment]
> > **I plan to wait to merge this PR until that second PR has been reviewed and merged into this one, at which point they will be merged to master together**, because we should really add both at the same time to be safe.
> 
> This looks fine to me with this assumption. I have one more concern about the fact that we are starting the workflow asynchronously is that I am wondering if we should use https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#newSignalWithStartRequest-- and https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#signalWithStart-io.temporal.client.BatchRequest- to ensure that there won't be any race condition between the workflow being accessible and the signal being send after a restart.

@benmoriceau to make sure I understand correctly, you are suggesting that in these cases where we restart the workflow before sending a signal, we should instead submit the signal with the start request in the same `BatchRequest`, like the current deleteConnection implementation is doing [here](https://github.com/airbytehq/airbyte/blob/2fae6e3e04d1899388e1b220a52558d03d3a0134/airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java#L275-L277), correct? I think this is a good callout, I hadn't considered that. I can look into that change

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java (hunk 2 above)
Comment (lmossman) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java]: Good suggestions. Done.

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java (hunk 3 above)
Comment (lmossman) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java]: Done!

**Comment by benmoriceau** [comment]
> > > **I plan to wait to merge this PR until that second PR has been reviewed and merged into this one, at which point they will be merged to master together**, because we should really add both at the same time to be safe.
> > 
> > 
> > This looks fine to me with this assumption. I have one more concern about the fact that we are starting the workflow asynchronously is that I am wondering if we should use https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#newSignalWithStartRequest-- and https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.3/io/temporal/client/WorkflowClient.html#signalWithStart-io.temporal.client.BatchRequest- to ensure that there won't be any race condition between the workflow being accessible and the signal being send after a restart.
> 
> @benmoriceau to make sure I understand correctly, you are suggesting that in these cases where we restart the workflow before sending a signal, we should instead submit the signal with the start request in the same `BatchRequest`, like the current deleteConnection implementation is doing [here](https://github.com/airbytehq/airbyte/blob/2fae6e3e04d1899388e1b220a52558d03d3a0134/airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java#L275-L277), correct? I think this is a good callout, I hadn't considered that. I can look into that change

@lmossman  yes it is exactly that. Temporal will ensure that the workflow is reachable before submitting the signal to it.

File: airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java (hunk 4 above)
Comment (lmossman) [reply airbyte-workers/src/main/java/io/airbyte/workers/temporal/TemporalClient.java:347]: I think this is a hard piece of logic to DRY, because this logic means that _this_ method should return a ManualOperationResult in the case of a DeletedWorkflowException. So if I try to move this logic into another method, that method will need to somehow indicate to this method that it should return a ManualOperationResult in that case, or return a ConnectionManagerWorkflow in the normal case, and this method will need to handle both cases with a conditional. So I think either way, this will be somewhat ugly if we try to DRY it.

**Comment by lmossman** [comment]
@benmoriceau I was able to finalize the stuff that you and I paired on during sit together - I think it ended up having a decent and fairly DRY structure. Lmk what you think

**Review by benmoriceau — APPROVED** [review]
LGTM

**Comment by benmoriceau** [comment]
> @benmoriceau I was able to finalize the stuff that you and I paired on during sit together - I think it ended up having a decent and fairly DRY structure. Lmk what you think

LGTM, I have approved it.
