### PR TITLE
Fix issue when not found docs were failing the app

### LINKED ISSUE #9015: UI should fail gracefully when a connector's documentation cannot be found
## Environment
- **Airbyte version**:  v0.34.4-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker 
- **Source Connector and version**: source-e2e-test 0.1.1 (custom source used for testing) 
- **Destination Connector and version**: N/A 
- **Severity**: Low
- **Step where error happened**: Setup new source

## Current Behavior
Adding the `source-e2e-test` custom connector does not work due to missing connector documentation. Instead of handling this gracefully, the UI breaks in a confusing manner and does not inform the user what went wrong.

## Expected Behavior
- The [useDocumentation hook](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/hooks/services/useDocumentation.ts) attempts to convert the `documentationUrl` from the source spec to a markdown file path that can be fetched locally. 
- If a markdown file cannot be found locally, the UI should fail gracefully, and potentially allow the user to continue setting up the connector. It should at least inform the user that there is an issue with the `documentationUrl`

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG (from browser Console)</summary> 

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED example.com.md/:1 

TypeError: Failed to fetch
    at <anonymous>:1:876
    at Documentation.ts:2
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21

```

</details>

## Steps to Reproduce
1. Add new custom source via Settings page, choose `airbyte/source-e2e-test`:
image

2. Go to Sources tab, click `+ new source` button
3. Choose the custom source from first step, UI redirects to error page:
image
Note the failed fetch to `example.com.md`.

## Are you willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by jamakase**
## What
Fix a problem that crashed app if doc markdown file was not present when selecting the connector ( #9015 )

## How
Load file without suspense mode

### CODE REVIEW

File: airbyte-webapp/src/hooks/services/useDocumentation.ts [hunk 1]
```diff
@@ -22,6 +22,8 @@ const useDocumentation = (documentationUrl: string): UseDocumentationResult => {
       enabled: !!documentationUrl,
       refetchOnMount: false,
       refetchOnWindowFocus: false,
+      retry: false,
+      suspense: false,
```
Comment (davinchia) [inline airbyte-webapp/src/hooks/services/useDocumentation.ts:26]: what is suspense mode?

**Review by davinchia — APPROVED** [review]

File: airbyte-webapp/src/hooks/services/useDocumentation.ts (hunk 1 above)
Comment (Jamakase) [reply airbyte-webapp/src/hooks/services/useDocumentation.ts:26]: in terms of react-query: it is suspense mode from [React](https://reactjs.org/docs/concurrent-mode-suspense.html). It is enabled in the app by default but in this particular case we don't need it as we want to handle loading and error manual. 

Main difference is that in suspense mode, dom rendering will be postponed until the request is resolved ( nearest `<Suspense />` component will be displayed instead while something is loading. Without suspense mode - we could achieve the same by `loading, data, error` props.
