### PR TITLE
destination-s3: don't reuse names of existing objects

### LINKED ISSUE #6417: Source Stripe: sync freeze with 80k records
## Enviroment
- **Airbyte version**:  ~
- **OS Version / Instance**: 4vCPU, 16GB RAM VM on Google Cloud
- **Deployment**: Docker
- **Source Connector and version**: Stripe
- **Destination Connector and version**: Bigquery
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Look that for one user Stripe connector cant finish the sync, or took 17h to sync 80k. Other user comment that he is able to sync 500k in 4h. I opened this issue to record this and investigate further if there is any option in Stripe we need inform to users enable.
[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1631110038489400).

>  I already did reduce the data to one month. The job halts at the very same 79000 records. What kind of requests the start_date filters? It’s like Airbyte keeps syncing 79871 balance transactions regardless the start date parameter.
Actually, it continues 17 hours later. :open_mouth: But it cannot find the BigQuery endpoint. Can it be due to the prolonged run time?

> when limiting the scope to invoices, invoice_lines and invoice_line_items, the job succeeded, although took more than 6 hours to finish because it synced all the data.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by stephane-airbyte**
Instead of counting the number of files and starting creating file based on that counter, we create files starting at 0 and avoid overriding files that were already present.

The problem was that in case of an overwrite sync, the 1st sync would create files `1, 2, 3`. Sync 2 would notice there's 3 files and would create files `4, 5 , 6` and delete `1, 2, 3` at the end of the sync. Sync3 and after would see there's 3 files, would overwrite `4, 5, 6` and delete them because they were here before the sync started, leaving us with no files. 

fixes #6417

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
* **#45143** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45143?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stephane-airbyte and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: airbyte-cdk/java/airbyte-cdk/s3-destinations/src/main/kotlin/io/airbyte/cdk/integrations/destination/s3/S3StorageOperations.kt [hunk 1]
```diff
@@ -263,31 +275,27 @@ open class S3StorageOperations(
...
-                                .withPrefix(objectPath)
-                                .withMarker(objects.nextMarker),
-                        )
-                    if (objects != null) {
-                        objectCount += objects.objectSummaries.size
-                    }
+        objectNameByPrefix.computeIfAbsent(
+            objectPath,
+        ) {
+            var objectList: Set<String> = setOf()
```
Comment (gisripa) [inline airbyte-cdk/java/airbyte-cdk/s3-destinations/src/main/kotlin/io/airbyte/cdk/integrations/destination/s3/S3StorageOperations.kt:281]: You can probably use this [method](https://github.com/airbytehq/airbyte/blob/0e56f8d68193ff8889ca3da8ac3c843271b4b08b/airbyte-cdk/java/airbyte-cdk/s3-destinations/src/main/kotlin/io/airbyte/cdk/integrations/destination/s3/S3StorageOperations.kt#L308) here right ?

**Review by gisripa — APPROVED** [review]
lgtm

**Review by johnny-schmidt — APPROVED** [review]
Makes sense:
* when writing a new file
  * try to get a partId for the prefix
    * start at 0
    * first time for the prefix: build a map of prefix -> { all existing full names with prefix }
    * while there's a conflict: increment and try again
  * (no need to store the object you just made, because all subsequent calls should just increment any time there's a confict)

So:

Sync 1: write(0, 1, 2)
Sync 2: write(3, 4, 5, 6) delete(0, 1, 2)
Sync 3: write(0, 1, 2, 7, 8)

etc
