### PR TITLE
🪟 🐛 New OAuth connectors should never say "re-authenticate"

### LINKED ISSUE #16599: Service Form should not say "Re-Authenticate" for new connectors
I'd already Oauthed in to Google to create a google sheets source.  I went to create another one and it said "re-authenticate" so I assumed it would re-use the auth token.

Connection test failed.

1. this should not say "re-authenticate" for a new source
2. we should show a better error for this situation
3. this should apply to other oauth connectors as well.

### PR DESCRIPTION
**Pull request by teallarson**
## What
closes #16599 

Previously, some OAuth connectors would render a button that said "Re-Authenticate" when a user was creating a new connection.  Some of this was resolved with #17965 when the new `useAuthentication` hook was introduced.  This PR resolves the rest of it.

## How
Previously, we were looking to see if there was an empty `credentials` object to determine whether a user had OAuthed yet or not.  However, in some cases the keys are present already, but all values are undefined.  This PR changes that to check for either no `credentials` object, or an object with no defined values.

## Recommended reading order
The one file

## Testing
Previously, you could see this bug by OAuthing a Google connector (we have Google Sheets on `frontend-dev`) and then trying to create a Google Ads source.  This was the only connector I was able to find with the bug remaining after #17965.

Now, if you create a Google Sheets OAuth source, then go to create a Google Ads source, you should see `Sign in with Google` and not `Re-authenticate` on the OAuth button.

Choosing an existing connector and going to settings should display "Re-authenticate"

### CODE REVIEW

**Comment by timroes** [comment]
Not introduced by this PR, but I feel I asked this already on the original PR that introduced this: `credentials` is just one arbitrary path inside values that could hold the information, but they could as well also just sit on the root level? Or any other path defined in the spec. How does the current code handle that? E.g. can we verify this works e.g. with the Instagram or Salesforce connector which have the button on the root of the form?

**Comment by tealjulia** [comment]
> 

Salesforce never says "re-authenticate" as it stands, due to what you mentioned.

**Comment by timroes** [comment]
I think that would be exactly the right solution, @tealjulia. Maybe let's in general move this as a flag into the useAuhentication hook as something like `hasAuthFieldValues` or such

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 1]
```diff
@@ -202,9 +208,22 @@ export const useAuthentication = (): AuthenticationHook => {
     [advancedAuth, isAuthButtonVisible, legacyOauthSpec]
   );
 
+  const hasAuthFieldValues: boolean = useMemo(() => {
+    if (
+      implicitAuthFieldPaths.some((path) => {
+        return get(values, path) !== undefined;
```
Comment (tealjulia) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:214]: generally not a fan of using lodash, but this seemed a lot cleaner than parsing the string and traversing the object more manually.  happy to go that direction if it seems better to whomever reviews, though.

Comment (timroes) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:214]: We can actually use getIn here which is from formik and already used across this file, which does the same. So we wouldn't need to pull in another library in this place.

Comment (tealjulia) [reply airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:214]: Ah thank you!

**Review by lmossman — APPROVED** [review]
The solution looks good to me!

I tested this out on frontend-dev and was able to reproduce the re-authenticate issue you described in the PR description, and then I spun up this branch on npm and that solved the problem. I still got a 404 when clicking the oauth button on Google Ads, but I think that is expected based on that source not being listed [here](https://www.notion.so/Testing-OAuth-Locally-fea17aeb14c74cacb5f3ed856daae753)

Not super sure about your Google branding question. @timroes maybe that is something we can check with the Google team? Not sure what that process looks like

File: airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx [hunk 2]
```diff
@@ -202,9 +207,22 @@ export const useAuthentication = (): AuthenticationHook => {
...
+  const hasAuthFieldValues: boolean = useMemo(() => {
+    if (
+      implicitAuthFieldPaths.some((path) => {
+        return getIn(values, path) !== undefined;
+      })
+    ) {
+      return true;
+    }
+
+    return false;
```
Comment (timroes) [inline airbyte-webapp/src/views/Connector/ServiceForm/useAuthentication.tsx:219]: Minor code nitpick, since we're anyway just returning `true` and `false` here:

```suggestion
    return implicitAuthFieldPaths.some((path) => getIn(values, path) !== undefined);
```

**Comment by timroes** [comment]
Regarding the Sign-In branding question. Their branding guidelines are documented here: https://developers.google.com/identity/branding-guidelines

There is no specific rules around the "reauthentication" purpose, so I think we'l be fine with this. We can always change it, if they'd would reach out and see this as a problem (which they tend to do).

**Review by timroes — APPROVED** [review]
Code LGTM, have not tested locally since the suggested refactoring
