### PR TITLE
🐛 Source postgres: fix money type with amount > 1000

### LINKED ISSUE #7870: Source Postgres: money type fails when amount is > 1000
## Current Behavior
 The money type fails when the amount is > 1000. The reason is that in JDBC implementation money type is tried to get as Double (JDBC implementation). Max values for Money type: "-92233720368547758.08", "92233720368547758.07"

## Expected Behavior
The connector should recognize all possible values for money type: from 92233720368547758.08 to 92233720368547758.07

## Steps to Reproduce
1. Go to `PostresSourceDatatypeTest.class` line: 333
2. Set any value that is more than 1000 
3. Run tests

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Close #7870.

## How
- Add a Postgres source operation class to handle the `MONEY` type.

## Reference
- https://github.com/pgjdbc/pgjdbc/issues/425
- https://github.com/pgjdbc/pgjdbc/issues/1835

### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Review by yurii-bidiuk — APPROVED** [review]

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java [hunk 1]
```diff
@@ -54,13 +54,13 @@ protected Database setupDatabase() throws SQLException {
...
-    database.query(ctx -> ctx.fetch("CREATE TYPE inventory_item AS (\n"
-        + "    name            text,\n"
-        + "    supplier_id     integer,\n"
-        + "    price           numeric\n"
-        + ");"));
+    database.query(ctx -> {
+      ctx.execute("CREATE SCHEMA TEST;");
+      ctx.execute("CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');");
+      ctx.execute("CREATE TYPE inventory_item AS (name text, supplier_id integer, price numeric);");
+      ctx.execute("SET lc_monetary TO 'en_US.utf8';");
```
Comment (sherifnada) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java:61]: should the actual source connector also run this query? I don't follow why we run tests against this configuration -- do we expect all user databases to also have this configuration?

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+      // convert to java types that will convert into reasonable json.
+      setJsonField(queryContext, i, jsonNode);
+    }
+
+    return jsonNode;
+  }
+
+  @Override
+  protected void putDouble(final ObjectNode node, final String columnName, final ResultSet resultSet, final int index) throws SQLException {
```
Comment (sherifnada) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:51]: is the reason this is difficult to convert to double is because its formatted weird with symbols i.e: `$200,000`? Honestly I kind of feel like we should find a way to output this as a proper double rather than a string. Otherwise we are offloading the burden of converting this to a number onto our users.

**Review by sherifnada — COMMENTED** [review]
this feels like the wrong direction to go because we are offloading the burden of cleaning up what is fundamentally a numeric type. Is there anything we can do to output this as a double?

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java (hunk 1 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java:61]: The purpose of this setting is to make sure the locale is US, and the currency symbol is `$`, which matches what we expect in the unit test case. User databases do not need to have this config. They can set it to any locale, but the output currency symbol will be different.

But I will remove this, since I agree that we'd better convert the money value to double. So the currency symbol is no loner a concern.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 2 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:51]: Ok. I will change it to double.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+    if (resultSet.getMetaData().getColumnTypeName(index).equals("money")) {
+      putMoney(node, columnName, resultSet, index);
+    } else {
+      super.putDouble(node, columnName, resultSet, index);
+    }
+  }
+
+  private void putMoney(final ObjectNode node, final String columnName, final ResultSet resultSet, final int index) throws SQLException {
```
Comment (sherifnada) [inline airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:56]: we should probably have a unit test for this method to make sure it correctly parses symbols/commas

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java [hunk 4]
```diff
@@ -294,17 +293,13 @@ protected void initTests() {
...
-    // implementation)
     // Max values for Money type: "-92233720368547758.08", "92233720368547758.07"
     addDataTypeTestData(
         TestDataHolder.builder()
             .sourceType("money")
-            .airbyteType(JsonSchemaPrimitive.STRING)
-            .addInsertValues("null", "'999.99'")
-            .addExpectedValues(null, "999.99")
+            .airbyteType(JsonSchemaPrimitive.NUMBER)
+            .addInsertValues("null", "'999.99'", "'1001.01'", "'-92233720368547758.08'", "'92233720368547758.07'")
```
Comment (sherifnada) [inline airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java:301]: how can we make sure this parses does it make sense to also add something with some currency symbols e.g: `$1,000`  to ensure it is working correctly?

**Review by sherifnada — APPROVED** [review]
Looks great, just one request for some unit tests

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java (hunk 4 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java]: Done.

File: airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java (hunk 3 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java:57]: Done.

File: airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java (hunk 4 above)
Comment (tuliren) [reply airbyte-integrations/connectors/source-postgres/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/PostresSourceDatatypeTest.java]: Well, the values are inserted into an Postgres instance (via test container). It is Postgres that should guarantee the correctness of such insertion operations. So actually we should not need to test inserting a money value with the currency symbol.

**Comment by tuliren** [comment]
Wow, last time `source-postgres` test took 1 hour to complete. Something is definitely wrong there.

Created an issue: #8284.
