### PR TITLE
🎉 Destination redshift: reenable T+D optimizations; bigquery+snowflake: bump to latest CDK version

### LINKED ISSUE #33685: [JDBC Destinations] Fix Failing Unit tests
There are tests which are currently failing because of the table state in JDBC destinations

- [minTimestampBehavesCorrectly](https://github.com/airbytehq/airbyte/blob/d27ea33ffe12fe068a9531504af23aff6b2d7ea8/airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java#L429C64-L429C64)
- [handleNoPreexistingRecords](https://github.com/airbytehq/airbyte/blob/d27ea33ffe12fe068a9531504af23aff6b2d7ea8/airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java#L543)
- [handlePreexistingRecords](https://github.com/airbytehq/airbyte/blob/d27ea33ffe12fe068a9531504af23aff6b2d7ea8/airbyte-cdk/java/airbyte-cdk/typing-deduping/src/testFixtures/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java#L516C16-L516C16)

We should update the [initial table state](https://github.com/airbytehq/airbyte/blob/d27ea33ffe12fe068a9531504af23aff6b2d7ea8/airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/jdbc/typing_deduping/JdbcDestinationHandler.java#L62) to ensure these tests are passing

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/33685

1. revert the test change in https://github.com/airbytehq/airbyte/pull/33124/files#diff-f687bfd57a60258955e78d454447802be81912d73fec4a28916f909c3dca15d4
2. Implement the method correctly in JdbcDestinationHandler (this code is mostly copied from the preexisting RedshiftDestinationHandler.getMinTimestamp method)
3. Remove redundant code from RedshiftDestinationHandler

snowflake+bigquery technically aren't affected by this (the only CDK code change is in the JdbcDestinationHandler, which neither of them rely on) but figured I might as well trigger their test suites.

### CODE REVIEW

File: airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/jdbc/typing_deduping/JdbcDestinationHandler.java [hunk 1]
```diff
@@ -59,7 +65,49 @@ public boolean isFinalTableEmpty(final StreamId id) throws Exception {
...
+                .where(DSL.condition("_airbyte_loaded_at IS NULL"))
+                .getSQL()),
+        record -> record.getTimestamp("min_timestamp"))) {
+      // Filter for nonNull values in case the query returned NULL (i.e. no unloaded records).
+      final Optional<Timestamp> minUnloadedTimestamp = timestampStream.filter(Objects::nonNull).findFirst();
+      if (minUnloadedTimestamp.isPresent()) {
+        // Decrement by 1 second since timestamp precision varies between databases.
+        final Optional<Instant> ts = minUnloadedTimestamp
+            .map(Timestamp::toInstant)
+            .map(i -> i.minus(1, ChronoUnit.SECONDS));
```
Comment (edgao) [inline airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/jdbc/typing_deduping/JdbcDestinationHandler.java:95]: this is slightly different from the original redshift implementation - instead of doing a timestamp subtraction within redshift, we just query the raw timestamp and decrement it in java code. Timestamp math can be dialect-specific, so probably not a good idea to have it in a base Jdbc implementation.

**Review by jbfbell — APPROVED** [review]

File: airbyte-integrations/connectors/destination-snowflake/build.gradle [hunk 2]
```diff
@@ -4,9 +4,9 @@ plugins {
 }
 
 airbyteJavaConnector {
-    cdkVersionRequired = '0.9.0'
+    cdkVersionRequired = '0.10.0'
     features = ['db-destinations', 's3-destinations']
-    useLocalCdk = false
+    useLocalCdk = true
```
Comment (evantahler) [inline airbyte-integrations/connectors/destination-snowflake/build.gradle:9]: Don't forget to revert!

Comment (edgao) [reply airbyte-integrations/connectors/destination-snowflake/build.gradle:9]: I have a whole pile of commits with formatting/metadata/build.gradle stuff locally 😅 just waiting on the current CI run to finish before pushing to avoid cancelling+restarting the integration tests
image

(also... discussion on the [cdk publish flow doc](https://docs.google.com/document/d/1NYCbp1uShNzxXFogi5W2IdHyiEqiU6LmTPPQoVsl3TQ/edit) is mostly settled :D which would solve this once and for all)

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]
