### PR TITLE
Make schema field in source-snowflake mean a subset of the specified o…

### LINKED ISSUE #20018: Source Snowflake - connector Schema not used
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Snowflake source 0.1.24
- **Step where error happened**:Setup new connection

## Current Behavior
schema is one of the credentials while configuring snowflake source.
but it discovers all the tables from all the schema's in the current database.

## Expected Behavior
only tables in provided schema should get discovered.

## Steps to Reproduce
1. configure Snowflake source for particular schema for a database with multiple schemas
2. during discover_schema , we get streams/tables from all the schemas in that database

### PR DESCRIPTION
**Pull request by rodireich**
## What
the schema field in source-snowflake is not very useful today:
Regardless of what the user inputs in schema, all tables from all schemas are discovered and included in catalog.
This change changes its behavior to be more in line with other source connectors.
 
## How
If `schema` is specified, the catalog discovery will be limited to only tables included in this schema.
If field left open, all tables from all schema will be included in catalog - similarly to today's discovery.

## Recommended reading order
1. `spec,json`
2. `SnowflakeDataSourceUtils.java`

## 🚨 User Impact 🚨
This is going to have in impact, as source-snowflake connectors today have a mandatory schema field, but replication might include tables from outside the specified schema. 
These customers needs to be instructed to leave the schema field empty upon upgrade (field is mandatory today).
Existing connection that only sync tables from the specified schema should not have a problem.

 **>>>>>>>> We need to be carful in publishing this in order not to break existing connections**

## Do not merge until we have a go ahead from TCS!!

cc: @erica-airbyte

### CODE REVIEW

File: airbyte-integrations/bases/standard-source-test/src/main/java/io/airbyte/integrations/standardtest/source/AbstractSourceDatabaseTypeTest.java [hunk 1]
```diff
@@ -111,7 +111,10 @@ public void testDataTypes() throws Exception {
     final List<AirbyteMessage> allMessages = runRead(catalog);
     final UUID catalogId = runDiscover();
     final Map<String, AirbyteStream> streams = getLastPersistedCatalog().getStreams().stream()
-        .collect(Collectors.toMap(AirbyteStream::getName, s -> s));
+        .collect(Collectors.toMap(
+            s ->
+                "%s.%s".formatted(s.getNamespace(), s.getName()),
```
Comment (rodireich) [inline airbyte-integrations/bases/standard-source-test/src/main/java/io/airbyte/integrations/standardtest/source/AbstractSourceDatabaseTypeTest.java:116]: This change makes the test more robust in case previous runs left junk schemas.

File: airbyte-config/init/src/test/resources/connector_catalog.json [hunk 2]
```diff
@@ -12691,7 +12691,7 @@
           "$schema": "http://json-schema.org/draft-07/schema#",
```
Comment (rodireich) [inline airbyte-config/init/src/test/resources/connector_catalog.json:12691]: @grishick , @evantahler  Do we need to make changes to connector_catalog as well?

**Comment by rodireich** [comment]
Going over [metabase](https://airbyte.metabaseapp.com/question/509-cloud-connector-failures?connector_definition_id=e2d65910-8c8b-40a1-ae7d-ee2416b2bfa2&detail_date=past14days&is_initial_connector_sync=true&is_initial_connector_sync=false) I'm seeing the following active cloud source-snowflake connections:
1. [kipi](https://cloud.airbyte.io/workspaces/280ec316-f4f9-4e44-aad4-726e92ddac54/connections/0ba35da1-0370-4302-8bf9-40ea7f191a87/status#933274::0)
2. [Thrive Data](https://cloud.airbyte.io/workspaces/68c83ea2-2135-49da-ab1e-f98d09ae8820/connections/d313913b-7eb8-4095-a3c8-5588f84cedd0/status#957076::0)
3. [Caring LLC](https://cloud.airbyte.io/workspaces/e2451a90-c9a8-4c22-b825-bb7ff9e1eb34/connections/36513aac-5871-43e4-9a48-8cb1f1336d6d/status#964440::0)
4. [Caring LLC](https://cloud.airbyte.io/workspaces/e2451a90-c9a8-4c22-b825-bb7ff9e1eb34/connections/ddb16134-92a5-4a06-a006-1109283f47c7/status#964665::0)
5. [Joveo](https://cloud.airbyte.io/workspaces/0ba115ff-500d-41ce-81ba-7c9d422f9ef6/connections/91d775cc-5da9-4e45-b287-d845f68fa43c/status#964888::0)
6. [Act 2 Network](https://cloud.airbyte.io/workspaces/2293a3fe-8228-4a50-b522-7788abcbcc76/connections/ba3512f1-c16d-4483-9c0a-e34c23e109cf/status#966968::0)

**Comment by grishick** [comment]
> the schema field in source-postgres is not very useful today

did you mean source-snowflake?

File: airbyte-integrations/connectors/source-snowflake/src/main/java/io.airbyte.integrations.source.snowflake/SnowflakeDataSourceUtils.java [hunk 3]
```diff
@@ -37,8 +38,9 @@ public class SnowflakeDataSourceUtils {
   public static final String AIRBYTE_OSS = "airbyte_oss";
   public static final String AIRBYTE_CLOUD = "airbyte_cloud";
   private static final String JDBC_CONNECTION_STRING =
-      "role=%s&warehouse=%s&database=%s&schema=%s&JDBC_QUERY_RESULT_FORMAT=%s&CLIENT_SESSION_KEEP_ALIVE=%s&application=%s";
+      "role=%s&warehouse=%s&database=%s&JDBC_QUERY_RESULT_FORMAT=%s&CLIENT_SESSION_KEEP_ALIVE=%s&application=%s";
 
+  private static final String JDBC_SCHEMA_PARAM = "&schema=%s&CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true";
```
Comment (grishick) [inline airbyte-integrations/connectors/source-snowflake/src/main/java/io.airbyte.integrations.source.snowflake/SnowflakeDataSourceUtils.java:43]: is the problem with the current implementation that it does not set `CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX` to `true` and therefore connector ends up pulling all tables from all schemas?

Comment (rodireich) [reply airbyte-integrations/connectors/source-snowflake/src/main/java/io.airbyte.integrations.source.snowflake/SnowflakeDataSourceUtils.java:43]: Correct. 
So while UI is requiring a schema field, it doesn't affect the outcome catalog

**Comment by rodireich** [comment]
Input from Greg:
Source-snowflake is eligible to move to Beta, so when publishing this change we'll make it 1.0 and promote to Beta.

There are some 90 active OSS connection using source-snowflake. 
We should also reach the community with heads up on this potentially breaking change.
[Source1](https://airbyte.metabaseapp.com/dashboard/1-connector-metrics?%255Ball%255D_connector_definition_id=e2d65910-8c8b-40a1-ae7d-ee2416b2bfa2&%255Ball%255D_aggregation_type=day&%255Ball%255D_limit_num_of_versions_displayed=7&%255Bcustom%255D_deployment_type=cloud&%255Bcustom%255D_deployment_type=internal-cloud&%255Ball%255D_relative_focus_date=past4weeks~&%255Bcustom%255D_sample_power_user_data=true&%255Bcustom%255D_sample_power_user_data=false)
[source2](https://airbyte.metabaseapp.com/question/23-criteria-for-global-usage?connector_definition_id=e2d65910-8c8b-40a1-ae7d-ee2416b2bfa2)

cc: @jerri-airbyte

**Comment by rodireich** [comment]
@grishick, @jerri-airbyte 
Should I go ahead in merging this PR?

File: docs/integrations/sources/snowflake.md [hunk 4]
```diff
@@ -82,22 +82,22 @@ Your database user should now be ready for use with Airbyte.
...
 | [Database](https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl) | The database you created in Step 1 for Airbyte to sync data into. Example: `AIRBYTE_DATABASE`                                                                                                     |
-| [Schema](https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl) | The default schema used as the target schema for all statements issued from the connection that do not explicitly specify a schema name.                                                          |
+| [Schema](https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl) | The schema whose tables this replication is targeting. If no schema is specified, all tables with permission will be presentd regardless of their schema.                                         |
```
Comment (Amruta-Ranade) [inline docs/integrations/sources/snowflake.md:85]: nit: s/presentd/presented

File: docs/integrations/sources/snowflake.md [hunk 5]
```diff
@@ -82,22 +82,22 @@ Your database user should now be ready for use with Airbyte.
...
+| [Role](https://docs.snowflake.com/en/user-guide/security-access-control-overview.html#roles) | The role you created in Step 1 for Airbyte to access Snowflake. Example: `AIRBYTE_ROLE`                                                                                                           |
+| [Warehouse](https://docs.snowflake.com/en/user-guide/warehouses-overview.html#overview-of-warehouses) | The warehouse you created in Step 1 for Airbyte to sync data into. Example: `AIRBYTE_WAREHOUSE`                                                                                                   |
+| [Database](https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl) | The database you created in Step 1 for Airbyte to sync data into. Example: `AIRBYTE_DATABASE`                                                                                                     |
+| [Schema](https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl) | The schema whose tables this replication is targeting. If no schema is specified, all tables with permission will be presentd regardless of their schema.                                         |
```
Comment (Amruta-Ranade) [inline docs/integrations/sources/snowflake.md:98]: nit: s/presentd/presented

File: docs/integrations/sources/snowflake.md (hunk 4 above)
Comment (rodireich) [reply docs/integrations/sources/snowflake.md]: Nice catch!

**Review by subodh1810 — APPROVED** [review]

**Comment by sheshan-doye-konvergeai** [comment]
trying snowflake 1.28 source version,
it seems now nothing is discovered if schema is provided
response:
`{"catalog":{"streams":[]},"jobInfo":{"id":"c2af2abf-05c8-4525-aea2-ec10002a6832","configType":"discover_schema","configId":"Optional[e2d65910-8c8b-40a1-ae7d-ee2416b2bfa2]","createdAt":1677493097784,"endedAt":1677493103991,"succeeded":true`
