### PR TITLE
🪟🐛 Fix type number in schema

### LINKED ISSUE #20062: type: "number" properties in spec do not work in the UI
## Current Behavior
When using `type: "number"` in the spec, the UI returns a string for this field rendering the spec invalid.

This can be observed for example in the e2e destination connector: https://github.com/airbytehq/airbyte/blob/938436bcc9bd05efb02b1937dd1b5ce02f0e6052/airbyte-integrations/connectors/destination-e2e-test/src/main/resources/spec.json#L41

## Expected Behavior
Should work by parsing the user input into a number like it happens for `type: "integer"` 

## Steps to Reproduce
1. Create E2E Testing destination
2. Change the "N" config
3. Check connection (fails with weird error message)

### PR DESCRIPTION
**Pull request by flash1293**
## What
Fixes https://github.com/airbytehq/airbyte/issues/20062

by treating type `number` like treating `integer`

## How
Just adding another case to the switch/case handling different types of form fields

### CODE REVIEW

File: airbyte-webapp/src/core/jsonSchema/schemaToYup.ts [hunk 1]
```diff
@@ -68,6 +68,7 @@ export const buildYupFormForJsonSchema = (
       schema = yup.boolean();
       break;
     case "integer":
```
Comment (lmossman) [inline airbyte-webapp/src/core/jsonSchema/schemaToYup.ts:70]: Slightly tangential to this PR, but it looks like this code is not actually validating that the `"integer"` case is actually an integer. It seems to just treat it as a number, so non-integer values are actually allowed to be set (I just confirmed this by testing it out locally:
Screen Shot 2022-12-05 at 11 38 48 AM

So we should likely update that case to add a `yup.integer()` validation

**Review by lmossman — APPROVED** [review]
Changes LGTM, tested locally and it seems to have fixed the bug.

Added a comment about handling `"integer"` types more strictly, but that can also be addressed in a separate PR

File: airbyte-webapp/src/core/jsonSchema/schemaToYup.ts (hunk 1 above)
Comment (flash1293) [reply airbyte-webapp/src/core/jsonSchema/schemaToYup.ts:70]: I added it to this related issue I created - there are a bunch of these low-hanging fruits: https://github.com/airbytehq/airbyte/issues/20064
