### PR TITLE
MySQL CDC sync fails because starting binlog position not found in DB #6425

### LINKED ISSUE #6425: MySQL CDC sync fails because starting binlog position not found in DB
## Enviroment
Source: MySQL `0.4.4`
Destination: Snowflake `0.3.14`
EC2 Docker Airbyte instance `0.29.17-alpha`

## Current Behavior
context dump from #5870 

[logs-23-0.txt](https://github.com/airbytehq/airbyte/files/7157563/logs-23-0.txt)

looking back at these logs, they actually start with the error
```
The connector is trying to read binlog starting at binlog file 'mysql-bin-changelog.162732', pos=834769, skipping 2 events plus 1 rows, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
```
but the job continues ahead and appears to "succeed" whilst still causing a retry

Screen Shot 2021-09-14 at 11 16 30 am

attached sync timestamps

1. see sync frequency. it is manual, so i ran it once (full refresh) and then again 2 days later. i doubt the sync waited too long as that "successful but retried" sync took 8 minutes.
2. only one CDC source for one connection. (in a seperate airbyte instance i have the same CDC source, with the same account **but** that connection is disabled and this new instance, with full-refresh sync on 09/10 worked fine)

separately. on point 2. I do have multiple connections with the same CDC source to the same destination. **is this not allowed**? I run these two multiple connections at the same time and they _appeared_ to work as expected although I run into the "hanging" issue, where it doesnt actually COPY the data after reading it.

## Expected Behavior
Presumably we should either: 

1. Reset the whole database and start fresh on the binlog, or
2. Somehow find out which table updates we missed (or refresh only the relevant tables). IDK how this would work.

### PR DESCRIPTION
**Pull request by mkhokh-33**
## What
*Check required binlog for CDC sync on mysql server before data sync and add error description into log if it absent*

## How
*Before start CDC sync implementation will check required binary log on mysql server and if it's absent will add error description about it with corresponding explanation and as possible solution will as to make "reset data"*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/airbytehq/airbyte/9514)

### CODE REVIEW

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java [hunk 1]
```diff
@@ -180,8 +185,12 @@ private static boolean shouldUseCDC(final ConfiguredAirbyteCatalog catalog) {
           new AirbyteDebeziumHandler(sourceConfig, MySqlCdcTargetPosition.targetPosition(database), MySqlCdcProperties.getDebeziumProperties(),
               catalog, true);
 
-      return handler.getIncrementalIterators(new MySqlCdcSavedInfoFetcher(stateManager.getCdcStateManager().getCdcState()),
-          new MySqlCdcStateHandler(stateManager), new MySqlCdcConnectorMetadataInjector(), emittedAt);
+      CdcState cdcState = stateManager.getCdcStateManager().getCdcState();
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java:188]: Could `stateManager.getCdcStateManager()` return null?

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java [hunk 2]
```diff
@@ -180,8 +185,12 @@ private static boolean shouldUseCDC(final ConfiguredAirbyteCatalog catalog) {
...
+      MySqlCdcSavedInfoFetcher fetcher = new MySqlCdcSavedInfoFetcher(cdcState);
+      if (cdcState != null) {
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java:190]: Is possible to use `Optional` type here?

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java [hunk 3]
```diff
@@ -229,4 +238,42 @@ public static void main(final String[] args) throws Exception {
     };
   }
 
+  private void checkBinlog(JsonNode offset, JdbcDatabase database) {
+    String binlog = getBinlog(offset);
+    if (binlog != null && !binlog.isEmpty()) {
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java:243]: Is it possible to use Optional type here?

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java [hunk 4]
```diff
@@ -229,4 +238,42 @@ public static void main(final String[] args) throws Exception {
...
+      if (isBinlogAvailable(binlog, database)) {
+        LOGGER.info(String.format("Binlog %s is available", binlog));
+      } else {
+        String error =
+            String.format("Binlog %s is not available. This is a critical error, it means that requested binlog is not present on mysql server. " +
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java:248]: I believe, we can use Text block here instead of string concatenation https://openjdk.java.net/jeps/378, as we migrate to Java 17.

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java [hunk 5]
```diff
@@ -229,4 +238,42 @@ public static void main(final String[] args) throws Exception {
...
+  }
+
+  private String getBinlog(JsonNode offset) {
+    JsonNode node = offset.get(CDC_OFFSET);
+    Iterator<Map.Entry<String, JsonNode>> fields = node.fields();
+    while (fields.hasNext()) {
+      Map.Entry<String, JsonNode> jsonField = fields.next();
+      return Jsons.deserialize(jsonField.getValue().asText()).path("file").asText();
+    }
+    return null;
```
Comment (alexandertsukanov) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java:276]: Why do we return null here?

**Comment by alexandertsukanov** [comment]
Please, consider to move methods of Binlog to another class or util. (e.g. `BinlogManager.java` or something similar) to keep Single Responsibility principle in code. Thanks.

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java (hunk 1 above)
Comment (mkhokh-33) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java]: no, from what I can see from the code :
 public StateManager(final DbState serialized, final ConfiguredAirbyteCatalog catalog) {
    this.cdcStateManager = new CdcStateManager(serialized.getCdcState());
    this.isCdc = serialized.getCdc();
    if (serialized.getCdc() == null) {
      this.isCdc = false;
    }

**Comment by alexandertsukanov** [comment]
LGTM

**Review by alexandertsukanov — APPROVED** [review]

File: airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+        LOGGER.info("""
+                    Binlog %s is available""".formatted(binlog));
+      } else {
+        String error =
+            """
+            Binlog %s is not available. This is a critical error, it means that requested binlog is not present on mysql server. To fix data synchronization you need to reset your data. Please check binlog retention policy configurations."""
+                .formatted(binlog);
+        LOGGER.error(error);
+        throw new RuntimeException("""
+                                   Binlog %s is not available.""".formatted(binlog));
```
Comment (ChristopheDuong) [inline airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java:59]: Should this part of the code executed too if `binlogOptional.ifPresent` is not true?

Comment (mkhokh-33) [reply airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/helpers/CdcConfigurationHelper.java:59]: > Should this part of the code executed too if `binlogOptional.ifPresent` is not true?

- binlogOptional.ifPresent check that saved cdc_offset contain information about last sync binlog and returns binlog file name

- if (isBinlogAvailable(binlog, database)) - will check that required for sync binlog file is present on mysql-server

if binlog is not on mysql server anymore only then this part of code will executed.

**Review by ChristopheDuong — APPROVED** [review]
