### PR TITLE
Publish base-normalization

### LINKED ISSUE #7198: SSH Tunnel: allow using OPENSSH key format
## Enviroment
- **Airbyte version**:  Cloud
- **Source Connector and version**: postgres
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Create a Source

## Current Behavior
Airbyte uses BouncyCastle to validate the SSH key. Some users want to use the OPENSSH format and its not supported.

## Expected Behavior
I want to use OPENSSH keys when trying to connect using SSH tunnels.

## Logs
```
2021-10-19 21:56:09 INFO  2021-10-19 21:56:09 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - {} - Starting connection with method: SSH_KEY_AUTH
2021-10-19 21:56:17 ERROR Exception in thread "main" java.lang.RuntimeException: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:286)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.<init>(SshTunnel.java:134)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getInstance(SshTunnel.java:185)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:204)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:37)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.check(SpecModifyingSource.java:38)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.source.postgres.PostgresSourceStrictEncrypt.main(PostgresSourceStrictEncrypt.java:34)
2021-10-19 21:56:17 ERROR Caused by: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
2021-10-19 21:56:17 ERROR 	at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getPrivateKeyPair(SshTunnel.java:234)
2021-10-19 21:56:17 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:267)
2021-10-19 21:56:17 ERROR 	... 7 more
```
## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by rodireich**
## What
I missed doing the `/ publish` command on the [original PR](#15833).
This PR was created in order to publish.

### CODE REVIEW

File: airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java [hunk 1]
```diff
@@ -24,7 +24,6 @@
 import org.junit.jupiter.params.provider.ValueSource;
 
 class SshTunnelTest {
-
```
Comment (edgao) [inline airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java:27]: does this pass `SUB_BUILD=CONNECTORS_BASE ./gradlew format`?

**Review by edgao — APPROVED** [review]

File: airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java (hunk 1 above)
Comment (rodireich) [reply airbyte-integrations/bases/base-java/src/test/java/io/airbyte/integrations/base/ssh/SshTunnelTest.java:27]: it does
