### PR TITLE
Fix check connection

### LINKED ISSUE #325: When setting up a destination, it should be "Destination type" instead of "Source type"
See screenshot. This should be changed in both the onboarding and the Destination section.

Screen Shot 2020-09-17 at 12 14 30 PM

### LINKED ISSUE #340: Check connection always succeeds
## Expected Behavior
* When the connection is not successful, the user should receive a failure.

## Current Behavior
* It always succeeds

## Steps to Reproduce
1. Configure a postgres tap
1. Put in fake creds
Screen Shot 2020-09-18 at 9 36 11 AM copy

## Additional context
1. It looks like the UI is never calling check connection.

Screen Shot 2020-09-18 at 9 39 08 AM

### PR DESCRIPTION
**Pull request by jamakase**
## What
Check connection on create/update source and destination

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java [hunk 1]
```diff
@@ -65,17 +65,7 @@
...
-import io.airbyte.server.handlers.DestinationSpecificationsHandler;
-import io.airbyte.server.handlers.DestinationsHandler;
-import io.airbyte.server.handlers.JobHistoryHandler;
-import io.airbyte.server.handlers.SchedulerHandler;
-import io.airbyte.server.handlers.SourceImplementationsHandler;
-import io.airbyte.server.handlers.SourceSpecificationsHandler;
-import io.airbyte.server.handlers.SourcesHandler;
-import io.airbyte.server.handlers.WebBackendConnectionsHandler;
-import io.airbyte.server.handlers.WorkspacesHandler;
+import io.airbyte.server.handlers.*;
```
Comment (michel-tricot) [inline airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java:68]: can you configure you IJ to not star imports?

File: airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendDestinationImplementationHandler.java [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+                                                                                         DestinationImplementationCreate destinationImplementationCreate)
+      throws ConfigNotFoundException, IOException, JsonValidationException {
+    DestinationImplementationRead destinationImplementation =
+        destinationImplementationsHandler
+            .createDestinationImplementation(destinationImplementationCreate);
+
+    final DestinationImplementationIdRequestBody destinationImplementationIdRequestBody = new DestinationImplementationIdRequestBody()
+        .destinationImplementationId(destinationImplementation.getDestinationImplementationId());
+
+    CheckConnectionRead checkConnectionRead = null;
```
Comment (michel-tricot) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendDestinationImplementationHandler.java:56]:
```
   try {
      CheckConnectionRead checkConnectionRead = schedulerHandler
          .checkDestinationImplementationConnection(destinationImplementationIdRequestBody);
      if (checkConnectionRead.getStatus() == SUCCESS) {
         return destinationImplementation;
      }
    } catch (Exception e) {
        LOGGER.error("Error while checking connection", e);
    }

    destinationImplementationsHandler.deleteDestinationImplementation(destinationImplementationIdRequestBody);
    throw new KnownException(400, "Unable to connect to destination");
    
```

Comment (michel-tricot) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendDestinationImplementationHandler.java:56]: could be rewritten this way to make the flow a little bit more obvious

File: airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendSourceImplementationHandler.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+      throws ConfigNotFoundException, IOException, JsonValidationException {
+    SourceImplementationRead sourceImplementation = sourceImplementationsHandler
+        .createSourceImplementation(sourceImplementationCreate);
+
+    final SourceImplementationIdRequestBody sourceImplementationIdRequestBody = new SourceImplementationIdRequestBody()
+        .sourceImplementationId(sourceImplementation.getSourceImplementationId());
+
+    CheckConnectionRead checkConnectionRead = null;
+
+    boolean syncFailed;
```
Comment (michel-tricot) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendSourceImplementationHandler.java:60]: Same as `Destination`

**Review by michel-tricot — APPROVED** [review]

File: airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendDestinationImplementationHandler.java (hunk 2 above)
Comment (Jamakase) [reply airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendDestinationImplementationHandler.java]: Good point! Indeed here it will look simpler. Though the reason why I wrote it another way in the beginning, is that I prefer to exit from method earlier with errors and return the good result in the end. Someone may think, that 
```
   destinationImplementationsHandler.deleteDestinationImplementation(destinationImplementationIdRequestBody);
    throw new KnownException(400, "Unable to connect to destination");
``` is correct flow, and return in try section is unexpected exit.

I usually prefer to have 1 return for good case at the bottom of the function.
