### PR TITLE
:tada: Updated timestamp transformation with microseconds

### LINKED ISSUE #9915: In timestamp cursor fields, Seconds in cursor values are rounded to ceil and causing to sync rows whose cursor column values are smaller than cursor.
## Environment
- **Airbyte version**:  0.35.5-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: snowflake - 0.1.5
- **Destination Connector and version**: S3 - 0.2.5
- **Severity**:  Medium 
- **Step where error happened**: Sync job 

## Current Behavior
Even though there is no change in cursor value, incremental sync pulls up rows whose cursor columns values are smaller than cursor value. 
Cursor value(timestamp) is getting rounded to ceil when last (milliseconds) field is more than 500.
Ex: Snowflake timestamp value: 2022-01-28 10:30:33.614 which got round to 2022-01-28T10:30:34Z by airbyte.

## Expected Behavior
It should not sync rows whose value is smaller than cursor value.

## Logs
Please check them in sequence after reading steps to reproduce.
[logs-58-0.txt](https://github.com/airbytehq/airbyte/files/7970089/logs-58-0.txt)
[logs-59-0.txt](https://github.com/airbytehq/airbyte/files/7970090/logs-59-0.txt)
[logs-60-0.txt](https://github.com/airbytehq/airbyte/files/7970093/logs-60-0.txt)
[logs-61-0.txt](https://github.com/airbytehq/airbyte/files/7970094/logs-61-0.txt)
[logs-62-0.txt](https://github.com/airbytehq/airbyte/files/7970095/logs-62-0.txt)

## Steps to Reproduce
1. Create Snowflake -> Aws S3 incremental connection and manual frequency.
My snowflake table is 
`CREATE OR REPLACE TABLE test_timestamp (
  id int,
  request_timestamp_formatted  TIMESTAMP_NTZ
);`
Set request_timestamp_formatted as cursor field.
Screenshot 2022-01-28 at 4 50 44 PM

2. Add 132 rows to the table.
`insert into test_timestamp select * from (select seq2(0), current_timestamp() from table(generator(rowcount => 132))) order by seq2(0) limit 132;`
3. Run Sync. It should sync 132 records.
4. Add 100 records. 
`insert into test_timestamp select * from (select seq2(0), current_timestamp() from table(generator(rowcount => 132))) order by seq2(0) limit 100;`

5. It should sync 232 records as per the greater than equal to cursor value logic.
6. Add 3 more rows.  
`insert into test_timestamp select * from (select seq2(0), current_timestamp() from table(generator(rowcount => 132))) order by seq2(0) limit 3;`
7. Run Sync. It should sync 103 records: 100 repeated + 3 new.
8. On all subsequent syncs,  It pulls up 103 records every-time. 

Ideally it should sync only 3 records where cursor value is equal to newly added 3 records but it keeps on syncing old 100 records as well whose cursor column value is less than cursor value.

## Are you willing to submit a PR?
I am not fully verse with code base.

### LINKED ISSUE #9963: Postgres

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## Recommended reading order
1. `DataTypeUtils.java`
2. `AbstractJdbcCompatibleSourceOperations.java`
3. `DebeziumConverterUtils.java`
4. `JdbcSourceAcceptanceTest.java`

## 🚨 User Impact 🚨
Time-related fields that are used for incremental sync will have better precision.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by mkhokh-33 — APPROVED** [review]

File: airbyte-db/lib/src/main/java/io/airbyte/db/jdbc/AbstractJdbcCompatibleSourceOperations.java [hunk 1]
```diff
@@ -120,9 +125,9 @@ protected void putTime(final ObjectNode node, final String columnName, final Res
 
   protected void putTimestamp(final ObjectNode node, final String columnName, final ResultSet resultSet, final int index) throws SQLException {
     // https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jdbc/getstart/mapping.doc.html
-    final Timestamp t = resultSet.getTimestamp(index);
-    final java.util.Date d = new java.util.Date(t.getTime() + (t.getNanos() / 1000000));
-    node.put(columnName, DataTypeUtils.toISO8601String(d));
+    final Instant instant = resultSet.getTimestamp(index).toInstant();
+    var aa = DataTypeUtils.toISO8601StringWithMicroseconds(instant);
```
[the remark this answers is not in the document]
Comment (andriikorotkov) [reply airbyte-db/lib/src/main/java/io/airbyte/db/jdbc/AbstractJdbcCompatibleSourceOperations.java:129]: thanks for noticing. displayed the value in the logs when I tested it. did not rename the value back.)

**Review by alexandr-shegeda — APPROVED** [review]

File: airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java [hunk 2]
```diff
@@ -40,6 +44,12 @@
     }
   }
 
+  public static String toISO8601StringWithMicroseconds(Instant instant) {
+    var microSeconds = (instant.getNano() / 1000) % 1000;
+    String dateWithMilliseconds = DATE_FORMAT_WITH_MILLISECONDS.format(Date.from(instant));
+    return dateWithMilliseconds.substring(0, 23) + microSeconds + dateWithMilliseconds.substring(23);
```
Comment (edgao) [inline airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:50]: Can this use `DateTimeFormatter`? I believe that class supports microseconds natively, rather than needing this manual handling

File: airbyte-integrations/connectors/source-db2/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/Db2SourceDatatypeTest.java [hunk 3]
```diff
@@ -312,8 +312,9 @@ protected void initTests() {
             .createTablePatternSql(CREATE_TABLE_SQL)
             .sourceType("TIMESTAMP")
             .airbyteType(JsonSchemaType.STRING)
-            .addInsertValues("null", "'2018-03-22-12.00.00.123'", "'20180322125959'", "'20180101 12:00:59 PM'")
-            .addExpectedValues(null, "2018-03-22T12:00:00Z", "2018-03-22T12:59:59Z", "2018-01-01T12:00:59Z") // milliseconds values are erased
+            .addInsertValues("null", "'2018-03-22-12.00.00.123'", "'2018-03-22-12.00.00.123456'", "'20180322125959'", "'20180101 12:00:59 PM'")
+            .addExpectedValues(null, "2018-03-22T12:00:00.1230Z", "2018-03-22T12:00:00.123456Z", "2018-03-22T12:59:59.0000Z",
+                "2018-01-01T12:00:59.0000Z") // milliseconds values are erased
```
Comment (edgao) [inline airbyte-integrations/connectors/source-db2/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/Db2SourceDatatypeTest.java:317]: this comment is no longer true, right? I.e. millisecond values are now retained?

File: airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java [hunk 4]
```diff
@@ -115,6 +131,107 @@ void cleanUpTables() throws SQLException {
       conn.close();
   }
 
+  @Override
+  protected List<AirbyteMessage> getTestMessages() {
```
Comment (edgao) [inline airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java:135]: just curious: why do we need to override this method now

File: airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java [hunk 5]
```diff
@@ -115,6 +131,107 @@ void cleanUpTables() throws SQLException {
...
+            .withRecord(new AirbyteRecordMessage().withStream(streamName)
+                .withNamespace(getDefaultNamespace())
+                .withData(Jsons.jsonNode(ImmutableMap
+                    .of(COL_ID, ID_VALUE_3,
+                        COL_NAME, "vash",
+                        COL_UPDATED_AT, "2006-10-19T00:00:00.0000Z")))));
+  }
+
+  @Test
+  void testIncrementalTimestampCheckCursor() throws Exception {
```
Comment (edgao) [inline airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java:162]: does this override the method from `JdbcSourceAcceptanceTest`? and if yes, why can't the original JdbcSourceAcceptanceTest method be modified? (same question for `testReadOneTableIncrementallyTwice`)

**Review by edgao — CHANGES_REQUESTED** [review]

File: airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java (hunk 2 above)
Comment (andriikorotkov) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java:50]: I tried using `DateTimeFormatter` with microseconds - `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` but unfortunately it doesn't work correctly.

File: airbyte-integrations/connectors/source-db2/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/Db2SourceDatatypeTest.java (hunk 3 above)
Comment (andriikorotkov) [reply airbyte-integrations/connectors/source-db2/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/Db2SourceDatatypeTest.java:317]: Yes, this comment is no longer relevant. Deleted it.

File: airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java (hunk 4 above)
Comment (andriikorotkov) [reply airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java:135]: All methods in JdbcSourceAcceptanceTest work for all of our sources. I could change this in JdbcSourceAcceptanceTest, but then all tests for sources that don't use microseconds will not work correctly. Therefore, for some sources, I have redefined the methods you specified for the time being. When we update all our sources to work with microseconds, then we can update JdbcSourceAcceptanceTest and remove the overrides from the sources. While this is relevant only for oracle, other Jdbc sources successfully cope with the conversion.

File: airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java (hunk 5 above)
Comment (andriikorotkov) [reply airbyte-integrations/connectors/source-oracle/src/test/java/io/airbyte/integrations/source/oracle/OracleJdbcSourceAcceptanceTest.java:162]: Answered in the comment above

File: airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java (hunk 2 above)
Comment (edgao) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java]: what was the error you got? I was able to run this code:
```java
final DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'").withZone(ZoneOffset.UTC);
System.out.println(f.format(Instant.now()));
```

is the problem that we don't actually know what timezone to use?

**Review by edgao — APPROVED** [review]
:shipit:

added a question about the DateTimeFormatter thing, but feel free to merge regardless.

File: airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java (hunk 2 above)
Comment (andriikorotkov) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java]: Not certainly in that way. For a `DateTimeFormatter` of type `yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'`, a microsecond conversion error will occur. For example if your timestamp is like `2018-05-08T02:07:23.123456Z` - this DateTimeFormatter will convert it to `2018-05-08T02:07:23.000123Z`

Comment (andriikorotkov) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java]: Yes, you're right, that's really better. I added these changes to the pull request. Thank you.

Comment (andriikorotkov) [reply airbyte-db/lib/src/main/java/io/airbyte/db/DataTypeUtils.java]: @edgao I ran several tests. all the same, for some connectors, this DateTimeFormatter does not work correctly. this breaks hours and minutes and we get an incorrect result at the output. For example oracle and snowflake sources interpret this as minutes and seconds. Therefore, I will revert my changes.

**Comment by andriikorotkov** [comment]
/publish connector=connectors/source-cockroachdb-strict-encrypt

**Comment by andriikorotkov** [comment]
@tuliren thank you. This is my mistake.
