### PR TITLE
remove validation from source delete

### LINKED ISSUE #8244: Can't delete a connector which has a secret property containing a `pattern` in spec.json
## Current Behavior
I can't delete a stripe connector via the UI. I suspect it's because the spec for the connector describes the field: 

```
 "client_secret": {
        "type": "string",
        "pattern": "^(s|r)k_(live|test)_[a-zA-Z0-9]+$. ",
         "airbyte_secret": true
}
```

I suspect that because this field is **both** a secret and a pattern, when we go to delete it, the secret value is replaced with a secret mask `*******`. But this causes the pattern validation to fail. 

## Expected Behavior
I should be able to delete the connector. 

## Steps to Reproduce
1. Use Stripe connector version 0.1.23
2. Create a stripe connector in airbyte
3. try to delete it
4. fail

### PR DESCRIPTION
**Pull request by cgardens**
closes https://github.com/airbytehq/oncall/issues/33
closes https://github.com/airbytehq/airbyte/issues/8244

## What
* See context here: https://github.com/airbytehq/airbyte/issues/8244#issuecomment-991824798

### CODE REVIEW

File: airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java [hunk 1]
```diff
@@ -170,10 +170,7 @@ public void deleteSource(final SourceRead source)
     }
 
     final ConnectorSpecification spec = getSpecFromSourceId(source.getSourceId());
-    validateSource(spec, source.getConnectionConfiguration());
-
     final var fullConfig = configRepository.getSourceConnectionWithSecrets(source.getSourceId()).getConfiguration();
-    validateSource(spec, fullConfig);
```
Comment (cgardens) [inline airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java:176]: @jrhizor i think deleting both of these is the right thing to do, but curious if to hear if you think there's any value in keeping the second one.

**Review by jrhizor — APPROVED** [review]

**Review by benmoriceau — APPROVED** [review]
